SELECT   
'Rind '||D.RIND||':  '||  
NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA   AND D.NUM IN (2,3,4) THEN D.COL1 ELSE 0 END)) ||' < '||  
NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA-1 AND D.NUM IN (1,2,3) THEN D.COL1 ELSE 0 END))
   
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D
 

WHERE
   D.PERIOADA IN (:PERIOADA,:PERIOADA-1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (5)  AND
  D.CAPITOL IN (312)
  
 
GROUP BY D.RIND

HAVING

NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA   AND D.NUM IN (2,3,4) THEN D.COL1 ELSE 0 END))< 
NVAL(SUM(CASE WHEN D.PERIOADA=:PERIOADA-1 AND D.NUM IN (1,2,3) THEN D.COL1 ELSE 0 END))