SELECT   
D.RIND,  
  
SUM(D.COL1) AS COL1
   
 

FROM
  CIS2.VW_DATA_ALL D
 

WHERE
   D.PERIOADA IN (:PERIOADA-1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (5)  AND
  D.CAPITOL IN (312)
  AND  D.NUM IN (1,2,3)
  AND D.RIND NOT IN ('-')
 
GROUP BY D.RIND

