
SELECT 
L.RIND,
L.ID_MD,
L.DENUMIRE,
L.ORDINE,
SUM(R.COL1) AS COL1
 FROM 
(
 SELECT  D.RIND,
         D.ID_MD,
        D.DENUMIRE,
        D.ORDINE 
                
            FROM CIS2.MD_RIND D 
            
            WHERE 
            D.CAPITOL = 312
AND D.RIND_VERS = 1052
AND D.STATUT = '1'
AND D.RIND NOT IN ('-','999','002')

ORDER BY 
D.ORDINE 


) L LEFT JOIN (

SELECT   

D.RIND,
D.ID_MD,
MR.DENUMIRE,  
SUM(D.COL1) AS COL1
   
 

FROM

  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE  D
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD


WHERE
   D.PERIOADA IN (:PERIOADA) AND
  
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  

  
  
  D.FORM IN (5)  AND
  D.CAPITOL IN (312)
  AND  D.NUM IN (2,3,4)
 
 
GROUP BY 
D.RIND,
D.ID_MD,
MR.DENUMIRE
) R ON R.RIND = L.RIND


GROUP BY 
L.RIND,
L.DENUMIRE,
L.ORDINE,
L.ID_MD

ORDER BY
L.ORDINE 