SELECT
  
  'PP Rind'||D.RIND ||
' Col.16  = '||SUM(CASE WHEN (D.PERIOADA IN  (:PERIOADA - 1))   THEN  NVAL(COL16) ELSE  0  END)  ||' <> ' || 'Rind PA '||D.RIND ||' Col.1  =  '

|| SUM(CASE WHEN D.PERIOADA IN  (:PERIOADA)  THEN NVAL(COL1) ELSE  0  END) 
  AS REZULTAT

FROM
  VW_DATA_ALL_GC D

WHERE
  (D.PERIOADA IN  (:PERIOADA,:PERIOADA-1)          ) AND
  (D.NR_GOSP=:NR_GOSP  ) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  D.FORM IN (58) AND 
  
  D.CAPITOL IN (416)
  
   GROUP BY
   D.RIND
  
HAVING
SUM(CASE WHEN D.CAPITOL IN (416) AND  (D.PERIOADA IN  (:PERIOADA -1))  THEN NVAL(D.COL16)  ELSE 0  END) <> 

SUM(CASE WHEN D.CAPITOL IN (416) AND D.PERIOADA IN  (:PERIOADA)   THEN  NVAL(D.COL1) ELSE  0 END)


AND (
SELECT MAX(D.RIND) AS RIND 
            
             FROM VW_DATA_ALL_GC D

WHERE
  (D.PERIOADA IN  (:PERIOADA)) AND
  (D.NR_GOSP=:NR_GOSP  ) AND 
  D.FORM IN (58) AND  D.CAPITOL IN (416)  
 
) IS NOT NULL 