SELECT 
R.NR_GOSP,
  L.NR_GOSP,
'Eroare. Nu trebuie sa fie date in raport.' AS REZULTAT 
FROM 

(

SELECT
D.NR_GOSP, 
COUNT(D.COL1) AS CNUM
FROM VW_DATA_ALL_GC D
WHERE
   
   (D.PERIOADA=:PERIOADA          ) AND
  --(D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  

  D.FORM IN (58)  AND
  D.CAPITOL IN (419)
  AND D.RIND NOT IN ('CA','-','TIP2','TIP3','0')
  
  GROUP BY
  D.NR_GOSP 
  HAVING 
  COUNT(D.COL1) = 1
  
  ) L LEFT JOIN (
  
  SELECT
DISTINCT D.NR_GOSP,
D.CAPITOL,
D.RIND,
SUM(D.COL1) AS COL1

FROM VW_DATA_ALL_GC D
WHERE
   
   (D.PERIOADA=:PERIOADA          ) AND
 -- (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  

  D.FORM IN (58)  AND
  D.CAPITOL NOT IN (419)
  
  GROUP BY
  D.NR_GOSP,
  D.CAPITOL,
  D.RIND 

HAVING 
SUM(D.COL1) > 0

  )  R ON R.NR_GOSP = L.NR_GOSP
  
  
  
  GROUP BY 
  R.NR_GOSP,
  L.NR_GOSP
  
  HAVING 
  R.NR_GOSP IS NOT   NULL
  
  

