--DECLARE
--
--  CURSOR C IS
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4,
--    DF.COL5,
--    DF.COL6,
--    DF.COL7,
--    DF.COL8,
--    DF.COL9,
--    DF.COL10,
--    DF.COL11,
--    DF.COL12,
--    DF.COL13,
--    DF.COL14,
--    DF.COL15,
--    DF.COL16,
--    DF.COL17,
--    DF.COL18,
--    DF.COL19     
--FROM 
--(

    


    
SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS  NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,  
      RIND||'~'||ROWNUM AS NR_ROW,  
      ROWNUM AS ORDINE,
     '0000000000000000000' AS DECIMAL_POS,
     REPLACE(REPLACE(DENUMIRE, '<br>'),'</br>') AS NUME_ROW,
ROUND(COL1,0) COL1,     
ROUND(COL2,0) COL2, 
ROUND(COL3,0) COL3, 
ROUND(COL4,0) COL4,  
ROUND(COL5,0) COL5, 
ROUND(COL6,0) COL6, 
ROUND(COL7,0) COL7, 
ROUND(COL8,0) COL8, 
ROUND(COL9,0) COL9, 
ROUND(COL10,0) COL10,
ROUND(COL11,0) COL11,
ROUND(COL12,0) COL12,
ROUND(COL13,0) COL13,
ROUND(COL14,0) COL14,
ROUND(COL15,0) COL15,
ROUND(COL16,0) COL16,
ROUND(COL17,0) COL17,
ROUND(COL18,0) COL18,
ROUND(COL19,0) COL19



FROM
(

SELECT 
         MR.ORDINE,
         MR.RIND, 
         MR.DENUMIRE,
    
    SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL16 ELSE NULL  end ) AS COL1, 
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL17 ELSE NULL  end ) AS COL2,   
     
     SUM( CASE WHEN  D.PERIOADA IN (:pPERIOADA)    THEN   D.COL3 ELSE NULL  end ) AS COL3,    
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL4 ELSE NULL  end ) AS COL4,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL5 ELSE NULL  end ) AS COL5,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL6 ELSE NULL  end ) AS COL6,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL7 ELSE NULL  end ) AS COL7,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL8 ELSE NULL  end ) AS COL8,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL9 ELSE NULL  end ) AS COL9,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)   THEN   D.COL10 ELSE NULL  end ) AS COL10,
     
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL11 ELSE NULL  end ) AS COL11,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL12 ELSE NULL  end ) AS COL12,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL13 ELSE NULL  end ) AS COL13,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL14 ELSE NULL  end ) AS COL14, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL15 ELSE NULL  end ) AS COL15, 
     
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL16 ELSE NULL  end ) AS COL16,
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL17 ELSE NULL  end ) AS COL17,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL18 ELSE NULL  end ) AS COL18, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL19 ELSE NULL  end ) AS COL19         

        
FROM
  VW_DATA_ALL_GC  D
            
    INNER JOIN CIS2.MD_RIND MR  ON (MR.ID_MD =  D.ID_MD)

     
WHERE
 
 
             
   D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1 ) 
  
   
   
   AND 


  (D.FORM =:pFORM) AND
 (D.FORM_VERS =:pFORM_VERS) AND 
  --(:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  
  
  GROUP BY 
  MR.RIND,
  MR.ORDINE,
  MR.DENUMIRE
  
  
  
  
  UNION 
  
  
  SELECT 
      17.2 ORDINE,
     '043' RIND,
     'Ovine si Caprine - total' DENUMIRE,   
    
   SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL16 ELSE NULL  end ) AS COL1, 
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL17 ELSE NULL  end ) AS COL2,   
     
     SUM( CASE WHEN  D.PERIOADA IN (:pPERIOADA)    THEN   D.COL3 ELSE NULL  end ) AS COL3,    
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL4 ELSE NULL  end ) AS COL4,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL5 ELSE NULL  end ) AS COL5,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL6 ELSE NULL  end ) AS COL6,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL7 ELSE NULL  end ) AS COL7,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL8 ELSE NULL  end ) AS COL8,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL9 ELSE NULL  end ) AS COL9,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)   THEN   D.COL10 ELSE NULL  end ) AS COL10,
     
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL11 ELSE NULL  end ) AS COL11,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL12 ELSE NULL  end ) AS COL12,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL13 ELSE NULL  end ) AS COL13,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL14 ELSE NULL  end ) AS COL14, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL15 ELSE NULL  end ) AS COL15, 
     
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL16 ELSE NULL  end ) AS COL16,
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL17 ELSE NULL  end ) AS COL17,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL18 ELSE NULL  end ) AS COL18, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL19 ELSE NULL  end ) AS COL19     
        
FROM
  VW_DATA_ALL_GC  D
            
    INNER JOIN CIS2.MD_RIND MR  ON (MR.ID_MD =  D.ID_MD)

     
WHERE
 
 
             
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1 ) 
  
   
   
   AND 


  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
 -- (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
   AND MR.RIND IN ('030','040')
  
 

UNION 
  
  
  SELECT 
      27.2 ORDINE,
     '092' RIND,
     'Pasari - total' DENUMIRE,  
    
    SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL16 ELSE NULL  end ) AS COL1, 
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA-1) )  THEN   D.COL17 ELSE NULL  end ) AS COL2,   
     
     SUM( CASE WHEN  D.PERIOADA IN (:pPERIOADA)    THEN   D.COL3 ELSE NULL  end ) AS COL3,    
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL4 ELSE NULL  end ) AS COL4,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL5 ELSE NULL  end ) AS COL5,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL6 ELSE NULL  end ) AS COL6,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL7 ELSE NULL  end ) AS COL7,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL8 ELSE NULL  end ) AS COL8,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL9 ELSE NULL  end ) AS COL9,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)   THEN   D.COL10 ELSE NULL  end ) AS COL10,
     
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL11 ELSE NULL  end ) AS COL11,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL12 ELSE NULL  end ) AS COL12,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL13 ELSE NULL  end ) AS COL13,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL14 ELSE NULL  end ) AS COL14, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL15 ELSE NULL  end ) AS COL15, 
     
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL16 ELSE NULL  end ) AS COL16,
     SUM( CASE WHEN  (D.PERIOADA IN (:pPERIOADA)) THEN   D.COL17 ELSE NULL  end ) AS COL17,
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)    THEN   D.COL18 ELSE NULL  end ) AS COL18, 
     SUM( CASE WHEN D.PERIOADA IN (:pPERIOADA)     THEN   D.COL19 ELSE NULL  end ) AS COL19      
        
FROM
  VW_DATA_ALL_GC  D
            
    INNER JOIN CIS2.MD_RIND MR  ON (MR.ID_MD =  D.ID_MD)

     
WHERE
 
 
             
 D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1 ) 
  
   
   
   AND 


  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  --(:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (416)
  AND MR.RIND IN ('060','070','080','090')
  

    ORDER BY 
  ORDINE
  )
    



    


    



    

--  ) DF
--  
--  ;
--   
--    BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--   
--    INSERT INTO  CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14,
--      COL15, COL16, COL17, COL18, COL19
--       
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5, CR.COL6, CR.COL7, CR.COL8, CR.COL9, CR.COL10, CR.COL11, CR.COL12, CR.COL13, CR.COL14,
--      CR.COL15, CR.COL16, CR.COL17, CR.COL18, CR.COL19 
--    );
--  END LOOP;
--END;
--  
  