SELECT
DISTINCT D.NR_GOSP, 
SUM(NVAL(D.COL1)+NVAL(D.COL2) + NVAL(D.COL3) + NVAL(D.COL4) + NVAL(D.COL5) +NVAL(D.COL6) + NVAL(D.COL7)
+ NVAL(D.COL8) + NVAL(D.COL9) + NVAL(D.COL10) + NVAL(D.COL11)+NVAL(D.COL12) + NVAL(D.COL13) + NVAL(D.COL14) + NVAL(D.COL15) +NVAL(D.COL16) + NVAL(D.COL17)
+ NVAL(D.COL18) + NVAL(D.COL19)  ) AS COL1

FROM VW_DATA_ALL_GC D
WHERE
   
   (D.PERIOADA=:PERIOADA          ) AND
 -- (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (58)  AND
  D.CAPITOL  NOT IN (419)
 
  GROUP BY
  D.NR_GOSP

HAVING 
SUM(NVAL(D.COL1)+NVAL(D.COL2) + NVAL(D.COL3) + NVAL(D.COL4) + NVAL(D.COL5) +NVAL(D.COL6) + NVAL(D.COL7)
+ NVAL(D.COL8) + NVAL(D.COL9) + NVAL(D.COL10) + NVAL(D.COL11)+NVAL(D.COL12) + NVAL(D.COL13) + NVAL(D.COL14) + NVAL(D.COL15) +NVAL(D.COL16) + NVAL(D.COL17)
+ NVAL(D.COL18) + NVAL(D.COL19)) <>  0