SELECT 
   1 AS ORDINE, 
  'cod 11-col.2' AS RIND,
  COUNT(DISTINCT D.CUIIO) AS COL1,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  1200 AND 2200) THEN D.CUIIO END ) AS COL2,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  2200 AND 3200) THEN D.CUIIO END ) AS COL3,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  3200 AND 4200) THEN D.CUIIO END ) AS COL4,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  4200 AND 5200) THEN D.CUIIO END ) AS COL5,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  5200 AND 7000) THEN D.CUIIO END ) AS COL6,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  7000 AND 10000) THEN D.CUIIO END ) AS COL7
  FROM (
SELECT
DISTINCT 
  D.CUIIO,
  SUM(D.COL2) AS COL1
 FROM 
  CIS2.VW_DATA_ALL D
  WHERE
 D.PERIOADA IN (1051) AND
 D.FORM IN (26)AND   
 D.CAPITOL IN (367) AND
 D.RIND IN ('11')
GROUP BY
   D.CUIIO)  D

union all 

SELECT 
   2 AS ORDINE, 
  'cod 12-col.2' AS RIND,
  COUNT(DISTINCT D.CUIIO) AS COL1,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  1200 AND 2200) THEN D.CUIIO END ) AS COL2,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  2200 AND 3200) THEN D.CUIIO END ) AS COL3,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  3200 AND 4200) THEN D.CUIIO END ) AS COL4,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  4200 AND 5200) THEN D.CUIIO END ) AS COL5,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  5200 AND 7000) THEN D.CUIIO END ) AS COL6,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  7000 AND 10000) THEN D.CUIIO END ) AS COL7
  FROM (
SELECT
DISTINCT 
  D.CUIIO,
  SUM(D.COL2) AS COL1
 FROM 
  CIS2.VW_DATA_ALL D
  WHERE
 D.PERIOADA IN (1051) AND
 D.FORM IN (26)AND   
 D.CAPITOL IN (367) AND
 D.RIND IN ('12')
GROUP BY
   D.CUIIO)  D


UNION ALL 

SELECT 
   3 AS ORDINE, 
  'cod 27-col.2' AS RIND,
  COUNT(DISTINCT D.CUIIO) AS COL1,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  1200 AND 2200) THEN D.CUIIO END ) AS COL2,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  2200 AND 3200) THEN D.CUIIO END ) AS COL3,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  3200 AND 4200) THEN D.CUIIO END ) AS COL4,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  4200 AND 5200) THEN D.CUIIO END ) AS COL5,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  5200 AND 7000) THEN D.CUIIO END ) AS COL6,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  7000 AND 10000) THEN D.CUIIO END ) AS COL7
  FROM (
SELECT
DISTINCT 
  D.CUIIO,
  SUM(D.COL2) AS COL1
 FROM 
  CIS2.VW_DATA_ALL D
  WHERE
 D.PERIOADA IN (1051) AND
 D.FORM IN (26)AND   
 D.CAPITOL IN (367) AND
 D.RIND IN ('27')
GROUP BY
   D.CUIIO)  D

UNION ALL 
SELECT 
   4 AS ORDINE, 
  'cod 29-col.2' AS RIND,
  COUNT(DISTINCT D.CUIIO) AS COL1,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  1200 AND 2200) THEN D.CUIIO END ) AS COL2,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  2200 AND 3200) THEN D.CUIIO END ) AS COL3,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  3200 AND 4200) THEN D.CUIIO END ) AS COL4,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  4200 AND 5200) THEN D.CUIIO END ) AS COL5,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  5200 AND 7000) THEN D.CUIIO END ) AS COL6,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  7000 AND 10000) THEN D.CUIIO END ) AS COL7
  FROM (
SELECT
DISTINCT 
  D.CUIIO,
  SUM(D.COL2) AS COL1
 FROM 
  CIS2.VW_DATA_ALL D
  WHERE
 D.PERIOADA IN (1051) AND
 D.FORM IN (26)AND   
 D.CAPITOL IN (367) AND
 D.RIND IN ('29')
GROUP BY
   D.CUIIO)  D


UNION ALL 
SELECT 
   5 AS ORDINE, 
  'cod 30-col.2' AS RIND,
  COUNT(DISTINCT D.CUIIO) AS COL1,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  1200 AND 2200) THEN D.CUIIO END ) AS COL2,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  2200 AND 3200) THEN D.CUIIO END ) AS COL3,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  3200 AND 4200) THEN D.CUIIO END ) AS COL4,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  4200 AND 5200) THEN D.CUIIO END ) AS COL5,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  5200 AND 7000) THEN D.CUIIO END ) AS COL6,
  COUNT(DISTINCT CASE WHEN (NVAL(D.COL1) BETWEEN  7000 AND 10000) THEN D.CUIIO END ) AS COL7
  FROM (
SELECT
DISTINCT 
  D.CUIIO,
  SUM(D.COL2) AS COL1
 FROM 
  CIS2.VW_DATA_ALL D
  WHERE
 D.PERIOADA IN (1051) AND
 D.FORM IN (26)AND   
 D.CAPITOL IN (367) AND
 D.RIND IN ('30')
GROUP BY
   D.CUIIO)  D
