SELECT
  'RIND '||D.RIND||' - col.4 : '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1105) AND D.PERIOADA IN (:PERIOADA)   THEN  NVAL(D.COL1) ELSE NULL END)) ||' <> : col.5 - '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1105) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END))   
  AS REZULTAT
  
FROM VW_DATA_ALL_FR_TEMP D
--Anexa 2 col.3 anul curent= Anexa 2 col.4 anul precedent

WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ))   AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND 
  (D.CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               OR :FORM = -1) AND  
  (D.FORM_VERS=:FORM_VERS OR  D.FORM_VERS <>  :FORM_VERS) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (59)  AND
  D.CAPITOL IN (1105)   

  AND D.RIND NOT IN ('200', '210', '240')
 
 
GROUP BY 
D.RIND


HAVING
  NVAL(SUM(CASE WHEN D.CAPITOL IN (1105) AND D.PERIOADA IN (:PERIOADA)   THEN   NVAL(D.COL1) ELSE NULL END)) <> 
  NVAL(SUM(CASE WHEN D.CAPITOL IN (1105) AND D.PERIOADA IN (:PERIOADA-1)  THEN  NVAL(D.COL2) ELSE NULL END) )  

AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL_FR_TEMP D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN (59)
   
   
   
   ) IS NOT NULL

