--ASA - Daca este completat rd. 200  Cap. 2 trebuie sa fie  completat  obligatoriu rd.110 din Cap. 1 si invers

SELECT

'Rind 200 - '|| SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) ||' Rind 100 - ' 
||SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('100')  THEN D.COL1 ELSE 0 END) 
 
  
  AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   
   D.FORM IN (64)
   AND D.CUIIO = 34275
 HAVING  
  
( SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN D.COL1 ELSE 0 END) > 0 
 AND 
 SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('100')  THEN D.COL1 ELSE 0 END)  = 0 )

OR 


( SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN D.COL1 ELSE 0 END) = 0 
 AND 
 SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('100')  THEN D.COL1 ELSE 0 END)  > 0 )
 
  
  