--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2
--)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  TRIM(TO_CHAR(ROUND(COL1,1),'99999999999999999999999990.9'))||'~'||ORDINE AS NR_ROW,
  ORDINE,
  '11' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL2,1) AS COL1,
  ROUND(CIS2.NVAL(COL2)/CIS2.NOZERO(COL1)*100,1) AS COL2
FROM
(
SELECT
  R.ORDINE, 
  R.NUME_ROW,
  R.NR_ROW,
  SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN 
    CASE 
 WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (0) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (1) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN (CIS2.NVAL(D.COL1)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL6))/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (2) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (3) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (4) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (5) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (6) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (7) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (10) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (11) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (12) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (13) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (14) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (15) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (16) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (18) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (18.1) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (19) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN  CIS2.NVAL(D.COL1)/1000
           
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (22) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (24) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (25) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (26) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (27) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (28) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (29) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (30) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (32) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (33) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (34) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (35) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (36) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (37) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (38) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (39) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (40) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (41) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (42) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (43) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (44) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (45) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (46) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (47) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (48) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (49) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (50) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (51) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (52) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)
            END  END) AS COL1,
   SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN 
    CASE 
WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (0) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (1) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN (CIS2.NVAL(D.COL1)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL6))/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (2) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (3) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (4) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (5) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (6) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (7) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (10) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (11) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (12) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (13) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (14) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (15) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (16) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (18) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (18.1) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (19) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN  CIS2.NVAL(D.COL1)/1000
           
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (22) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (24) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (25) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (26) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (27) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (28) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (29) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (30) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000      
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (32) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (33) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (34) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (35) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (36) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (37) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (38) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (39) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (40) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)/1000
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (41) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (42) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (43) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (44) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (45) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (46) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (47) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN NULL
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (48) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL1)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (49) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL3)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (50) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL4)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (51) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL6)
      WHEN R.NR_ROW LIKE '%'|| D.RIND ||'%' AND R.ORDINE IN (52) AND R.CAPITOL LIKE '%'|| D.CAPITOL ||'%' THEN CIS2.NVAL(D.COL8)
            END  END) AS COL2
FROM 
  CIS2.VW_DATA_ALL D
  CROSS JOIN 
  (
    SELECT '-' AS NR_ROW, 'Total productia (cresterea) în greutate vie, mii chintale' AS NUME_ROW, 0 AS ORDINE , 379 AS CAPITOL FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'Animale - total' AS NUME_ROW, 1 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'bovine' AS NUME_ROW, 2 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'porcine' AS NUME_ROW, 3 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'ovine si caprine' AS NUME_ROW, 4 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'pasari' AS NUME_ROW, 5 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'alte animale' AS NUME_ROW, 6 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    --------------------------------------------------------------------------------
    SELECT '-' AS NR_ROW, 'Spor zilnic in greutate la crestere, ingrasare - grame' AS NUME_ROW, 7 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION       -- 8 si 9 in union 
    SELECT '-' AS NR_ROW, 'Greutatea animalelor sacrificate vândute (în carcasa) - total, mii chintale' AS NUME_ROW, 10 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'bovine' AS NUME_ROW, 11 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'porcine' AS NUME_ROW, 12 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'ovine si caprine' AS NUME_ROW, 13 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'pasari' AS NUME_ROW, 14 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION    
    SELECT '4' AS NR_ROW, 'alte animale' AS NUME_ROW, 15 AS ORDINE, 379 AS CAPITOL  FROM DUAL UNION
    --------------------------------------------------------------------------------
    SELECT '-' AS NR_ROW, 'Productia  laptelui' AS NUME_ROW, 16 AS ORDINE, 380 AS CAPITOL FROM DUAL UNION
    --17 in union    
    SELECT '7' AS NR_ROW, 'Productia  totala  a laptelui de vaca, mii chintale' AS NUME_ROW, 18 AS ORDINE, 380 AS CAPITOL  FROM DUAL  UNION    
    SELECT '8' AS NR_ROW, 'Produc?ia totala de lapte de oi, mii chintale' AS NUME_ROW, 18.1 AS ORDINE, 380 AS CAPITOL  FROM DUAL  UNION
    SELECT '9' AS NR_ROW, 'Produc?ia totala de lapte de capara, mii chintale' AS NUME_ROW, 19 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
  -- - 20 - UNION
    --------------------------------------------------------------------------------
    SELECT '-' AS NR_ROW, 'Productia  oualor' AS NUME_ROW, 22 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
    --23 union    
    SELECT '10' AS NR_ROW, 'din care: oua de gaina, mii bucati' AS NUME_ROW, 24 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
    SELECT '11' AS NR_ROW, 'Produc?ia de oua pentru incubare, buca?i' AS NUME_ROW, 25 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
    --26 union
    --------------------------------------------------------------------------------
    SELECT '-' AS NR_ROW, 'Productia lânii' AS NUME_ROW, 27 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
    SELECT '13' AS NR_ROW, 'Productia globala de lâna tunsa, chintale' AS NUME_ROW, 28 AS ORDINE, 380 AS CAPITOL  FROM DUAL UNION
    --------------------------------------------------------------------------------
    
    SELECT '-' AS NR_ROW, 'Efectivul de animale la 01.04.2025, mii capete' AS NUME_ROW, 29 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '1' AS NR_ROW, 'Bovine' AS NUME_ROW, 30 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '3' AS NR_ROW, 'din ele: vaci pentru lapte' AS NUME_ROW, 32 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION    
    SELECT '4' AS NR_ROW, 'alte vaci' AS NUME_ROW, 33 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '5' AS NR_ROW, 'Porcine' AS NUME_ROW, 34 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '7' AS NR_ROW, 'Ovine' AS NUME_ROW, 36 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '8' AS NR_ROW, 'Caprine' AS NUME_ROW, 37 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '9' AS NR_ROW, 'Cabaline' AS NUME_ROW, 38 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '10' AS NR_ROW, 'Pasari' AS NUME_ROW, 39 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    SELECT '11' AS NR_ROW, 'Iepuri' AS NUME_ROW, 40 AS ORDINE, 381 AS CAPITOL FROM DUAL UNION
    --------------------------------------------------------------------------------
    SELECT '-' AS NR_ROW, 'Greutatea produsilor obtinuti în viu, chintale' AS NUME_ROW, 41 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION
    SELECT '1' AS NR_ROW, 'Vitei' AS NUME_ROW, 42 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '3' AS NR_ROW, 'Purcei' AS NUME_ROW, 43 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '4' AS NR_ROW, 'Miei' AS NUME_ROW, 44 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '6' AS NR_ROW, 'Pui' AS NUME_ROW, 45 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '8' AS NR_ROW, 'Alte animale' AS NUME_ROW, 46 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '-' AS NR_ROW, 'Greutatea animalelor pierite, chintale' AS NUME_ROW, 47 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '4' AS NR_ROW, 'Bovine' AS NUME_ROW, 48 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '4' AS NR_ROW, 'Porcine' AS NUME_ROW, 49 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION 
    SELECT '4' AS NR_ROW, 'Ovine si caprine' AS NUME_ROW, 50 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'Pasari' AS NUME_ROW, 51 AS ORDINE, 379 AS CAPITOL FROM DUAL UNION
    SELECT '4' AS NR_ROW, 'Alte aniamale' AS NUME_ROW, 52 AS ORDINE, 379 AS CAPITOL FROM DUAL  
    
  ) R 
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)           
--  AND D.CUIIO IN (40234110)
GROUP BY
  R.ORDINE,
  R.NUME_ROW,
  R.NR_ROW
--------------------------------------------------------------------------------
UNION
SELECT
  8 AS ORDINE, 
  'bovine' AS NUME_ROW,
  '-' AS NR_ROW,  
 -- ((tab.1.1 rd. 2 col.1 )*100000 / tab.1.1 rd.3 col.1) AP
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL1 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL1 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL1 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL1 END)) AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('2','3') AND 
  D.CAPITOL IN (379)
--------------------------------------------------------------------------------
UNION
 SELECT
  9 AS ORDINE, 
  'porcine' AS NUME_ROW,
  '-' AS NR_ROW,  
 -- ((tab.1.1 rd. 2 col.3)*100000 / tab.1.1 rd.3 col.3) AP
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL3 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL3 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL3 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL3 END)) AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('2','3') AND 
  D.CAPITOL IN (379)
--------------------------------------------------------------------------------
UNION
SELECT
  17 AS ORDINE, 
  ' Productia totala a laptelui , mii chintale  ' AS NUME_ROW,
  '-' AS NR_ROW,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7','8','9') AND D.CAPITOL IN (380) THEN D.COL1 END))/1000 AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA)   AND D.RIND IN ('7','8','9') AND D.CAPITOL IN (380) THEN D.COL1 END))/1000 AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('7','8','9') AND 
  D.CAPITOL IN (380)
--------------------------------------------------------------------------------
UNION
SELECT
  20 AS ORDINE, 
  'Productia  medie de lapte pe o vaca, kg' AS NUME_ROW,
  '-' AS NR_ROW,
  
  --((tab.1.1 rd.7)/(tab.1.1 rd.20))*100AP
  ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END)/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('20') THEN D.COL1 END)))*100,0) AS COL1,
  ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') THEN D.COL1 END)/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('20') THEN D.COL1 END)))*100,0) AS COL2
  
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('7','20')AND 
  D.CAPITOL IN (380)
  
  --------------------------------------------------------------------------------
UNION
SELECT
  23 AS ORDINE, 
  'Oua alimentare ob?inute de la toate speciile de pasari, mii bucati' AS NUME_ROW,
  '-' AS NR_ROW,
  
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','12') AND D.CAPITOL IN (380) THEN D.COL1 END))*1000 AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA)   AND D.RIND IN ('10','12') AND D.CAPITOL IN (380) THEN D.COL1 END))*1000 AS COL2
  
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('10','12')AND 
  D.CAPITOL IN (380)

--------------------------------------------------------------------------------
UNION
SELECT
  26 AS ORDINE, 
  'Productia medie de oua pe o gaina-ouatoare, bucati' AS NUME_ROW,
  '-' AS NR_ROW,
 -- ((tab.1.1 rd.11)  / (tab.1.1 rd.21))*1000AP

  ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('11') THEN D.COL1 END)/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('21') THEN D.COL1 END)))*1000,0) AS COL1,
  ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11') THEN D.COL1 END)/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('21') THEN D.COL1 END)))*1000,0) AS COL2
  
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('11','21')AND 
  D.CAPITOL IN (380)
--------------------------------------------------------------------------------
UNION
SELECT
  31 AS ORDINE, 
  'din care vaci' AS NUME_ROW,
  '-' AS NR_ROW,
 -- (tab.1.2 (rd.3+ rd.4)/1000 AP
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('3','4') THEN D.COL1 END))/1000 AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA)   AND D.RIND IN ('3','4') THEN D.COL1 END))/1000 AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('3','4')AND 
  D.CAPITOL IN (381)
--------------------------------------------------------------------------------

UNION
SELECT
  35 AS ORDINE, 
  'Ovine si caprine' AS NUME_ROW,
  '-' AS NR_ROW,
 -- (tab.1.2 (rd.7+ rd.8)/1000 AP
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7','8') THEN D.COL1 END))/1000 AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA)   AND D.RIND IN ('7','8') THEN D.COL1 END))/1000 AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('7','8')AND 
  D.CAPITOL IN (381)
--------------------------------------------------------------------------------
)