SELECT DISTINCT 
D.CUIIO,
'RIND-'||D.RIND||'-'||DECODE(CC.NR_COLUMN, '1', 'COL1 ', '3', 'COL3 ', '4', 'COL4 ', '5', 'COL5 ', '6', 'COL6 ' , '8', 'COL8 ')||' PC '||
    CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND  D.RIND IN('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END))|| ' <=  PP ' ||
    CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.RIND IN ('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END))
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D,             
       (                                                                        
       SELECT '1' AS NR_COLUMN FROM DUAL UNION                                  
      -- SELECT '2' AS NR_COLUMN FROM DUAL UNION                                  
       SELECT '3' AS NR_COLUMN FROM DUAL UNION  
       SELECT '4' AS NR_COLUMN FROM DUAL UNION 
       SELECT '5' AS NR_COLUMN FROM DUAL UNION 
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
     --  SELECT '7' AS NR_COLUMN FROM DUAL UNION 
       SELECT '8' AS NR_COLUMN FROM DUAL                            
       ) CC  
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1 ) ) AND
 -- (D.CUIIO=:CUIIO        ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM       ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (33)  AND
  D.CAPITOL IN (379) AND
  D.RIND IN ('2')
GROUP BY
  CC.NR_COLUMN,
  D.RIND,
  D.CUIIO
HAVING
      CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND  D.RIND IN ('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END)) <
      CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND  D.RIND IN ('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END))


AND 
(CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND  D.RIND IN ('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END)) <> 0
AND 
CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND  D.RIND IN ('2') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END)) <> 0
)
