SELECT
  'Cap. SR: RIND.01  este bifat dar raportul nu  con?ine date' AS REZULTAT
FROM
  VW_DATA_ALL D
WHERE
  (D.PERIOADA = :PERIOADA) AND
  (D.CUIIO=:CUIIO ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL<>:CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (33) 
  
HAVING
  SUM(CASE WHEN D.CAPITOL=1201 AND D.RIND IN('01') THEN NVAL(D.COL1) ELSE 0 END) > 0 
  AND
 SUM(CASE WHEN D.CAPITOL NOT IN (1201) THEN NVAL(D.COL1)+NVAL(D.COL2)+ NVAL(D.COL3)+NVAL(D.COL4)+ NVAL(D.COL5)+NVAL(D.COL6)+NVAL(D.COL7)+NVAL(D.COL8) ELSE 0 END) = 0 