SELECT 
D.CUIIO,
RE.CUATM,
RE.DENUMIRE,
D.RIND,
SUM(D.COL1) AS COL1

 

FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
 
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
--  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)                 AND 
  D.CAPITOL IN (381) AND
  D.RIND IN ('250')
  
  GROUP BY 
  D.CUIIO,
  RE.CUATM,
RE.DENUMIRE,
D.RIND