SELECT
  CUIIO,       

   ROUND(COL5,0) AS COL4

FROM
(
SELECT 
  D.CUIIO,
  CF.ORDINE AS ORDINE_CFOJ,
--  D.CFOJ,
  CF.NR_ROW AS CODE_CFJO,
  CF.NUME_ROW AS NNAME_CFOJ,
      
      
  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('2')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL2 END END) AS COL5
      
  

--      CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL4 END END) AS COL7,
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('7')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL4 END END) AS COL8,
--  
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('8')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('106')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 END END) AS COL10,
--  
--  NVAL(SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL6 END END)) AS COL11,
--  NVAL(SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('10','13')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL6 END END)) AS COL12,
--  
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL8 END END) AS COL14,
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('15')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL8 END END) AS COL15,
--  
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('20')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN NVAL(D.COL1) ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('153')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN NVAL(D.COL1)+NVAL(D.COL2) END END) AS COL17,
--  SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('20')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN NVAL(D.COL1) ELSE
--  CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('153')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN NVAL(D.COL1)+NVAL(D.COL2) END END) AS COL18,
--  
--  SUM(CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('147')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 END) AS COL20,
--  SUM(CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('147')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 END) AS COL21,
--  
--  SUM(CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA-1) AND D.RIND IN ('118')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 END) AS COL23,
--  SUM(CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('118')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 END) AS COL24
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  CROSS JOIN
  (
--    SELECT '420+450+684+685+686' AS NR_ROW, 'Gospodariile taranesti (de fermier), care au la balanta animale' AS NUME_ROW, 4 AS ORDINE, '27' AS FORM FROM DUAL UNION
--    SELECT '880' AS NR_ROW, 'Gospodariile populatiei' AS NUME_ROW, 9 AS ORDINE, '30' AS FORM FROM DUAL UNION
--    SELECT '590+620+880' AS NR_ROW, 'Gospodariile auxiliare' AS NUME_ROW, 5 AS ORDINE, '27' AS FORM FROM DUAL UNION
--    SELECT '500+510+530+540+541+550+690+700+890+970' AS NR_ROW, 'Intreprinderile agricole' AS NUME_ROW, 7 AS ORDINE, '27' AS FORM FROM DUAL UNION
--    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+684+685+686' AS NR_ROW, 'Intreprinderile agricole si gospodariile taranesti (de fermier), care au balanta animale' AS NUME_ROW, 8 AS ORDINE, '27' AS FORM FROM DUAL UNION
--    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+684+685+686+880' AS NR_ROW, 'Gospodariile de toate categoriile' AS NUME_ROW, 6 AS ORDINE, '27,30' AS FORM FROM DUAL UNION
--    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+684+685+686+880+590+620' AS NR_ROW, 'Gospodariile de toate categoriile (gosp. auxiliare)' AS NUME_ROW, 1 AS ORDINE, '27,30' AS FORM FROM DUAL UNION
--    SELECT '500+510+530+540+541+550+690+700+890+970+590+620+880' AS NR_ROW, 'Intreprinderile agricole(gosp.auxiliare)' AS NUME_ROW, 3 AS ORDINE, '27' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+684+685+686+880+590+620' AS NR_ROW, 'Intreprinderile agricole (gosp. auxiliare) si gospodariile taranesti (de fermier), care au la balanta animale' AS NUME_ROW, 2 AS ORDINE, '27' AS FORM FROM DUAL
  ) CF
 

WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-1,:pPERIOADA+1) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (27,30)                 AND 
  D.CAPITOL IN (371,372,373,376)           
  
GROUP BY 
--  R.NR_ROW,
--  R.NUME_ROW,
  CF.NR_ROW,
  CF.NUME_ROW,
  CF.ORDINE,
  

   D.CUIIO
   
   
   HAVING 
   
     SUM(CASE WHEN D.FORM IN (30) AND D.PERIOADA IN (:pPERIOADA+1) AND D.RIND IN ('2')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (27) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('89')   AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'|| D.FORM ||'%' THEN D.COL2 END END) >  0   
--  
--  ORDER BY 
--   R.NR_ROW
  )
  
  