DECLARE -- ====================================================================

  CURSOR C IS
  SELECT
    :pCOD_CUATM AS pCOD_CUATM
  FROM
    DUAL;

BEGIN -- ======================================================================
  FOR CR IN C
  LOOP
   IF CR.pCOD_CUATM = '0000000' THEN
    INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14,COL15,COL16,COL17
)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  ORDINE_CFOJ AS NR_SECTIE,
  NNAME_CFOJ||'('||CODE_CFJO||')' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  TRIM(TO_CHAR(ROUND(COL1,0),'99999999999999999999999990.9'))||'~'||NR_ROW AS NR_ROW,
  ORDINE,
  '01001001000100010' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL2,0) AS COL1,
  ROUND((NVAL(COL2)/NOZERO(COL1))*100,1) AS COL2,
  ROUND(COL4,0) AS COL3,
  ROUND(COL5,0) AS COL4,
  ROUND((NVAL(COL5)/NOZERO(COL4))*100,1) AS COL5,
  ROUND(COL7,0) AS COL6,
  ROUND(COL8,0) AS COL7,
  ROUND((NVAL(COL8)/NOZERO(COL7))*100,1) AS COL8,
  ROUND(COL10,0) AS COL9,
  ROUND(COL11,0) AS COL10,
  ROUND(COL12,0) AS COL11,
  ROUND((NVAL(COL12)/NOZERO(COL11))*100,1) AS COL12,
  ROUND(COL14,0) AS COL13,
  ROUND(COL17,0) AS COL14,
  ROUND(COL15,0) AS COL15,
  
  ---ROUND((NVAL(COL16)/NOZERO(COL15))*100,1) AS COL16,
  
  ROUND(COL16,0) AS COL16,
  
  
    ROUND((NVAL(COL16)/NOZERO(COL15))*100,1) AS COL17
  
FROM
(
SELECT 
  R.NR_ROW,
  R.NUME_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
  CF.ORDINE AS ORDINE_CFOJ,
--  D.CFOJ,
  CF.NR_ROW AS CODE_CFJO,
  CF.NUME_ROW AS NNAME_CFOJ,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('230') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN NVAL(D.COL1) END END)) AS COL1,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('230') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN NVAL(D.COL1) END END)) AS COL2,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('240') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL4,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('240') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL5,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('250') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL7,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('250') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL8,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('251') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL10,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('260') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE 
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL11,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('260') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL12,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('261') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11','14') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL14,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('280') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END) AS COL15,
      
      
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 END END)  AS COL16,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('262') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND CF.NR_ROW LIKE '%'|| D.CFOJ ||'%' AND CF.FORM LIKE '%'||D.FORM||'%' THEN D.COL1 ELSE NULL  END)  AS COL17
 
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
  CROSS JOIN
   (
    SELECT '420+450+684+685+686' AS NR_ROW, 'Gospodariile taranesti (de fermier), care au la balanta animale' AS NUME_ROW, 5 AS ORDINE, '33' AS FORM FROM DUAL UNION
    SELECT '880' AS NR_ROW, 'Gospodariile populatiei' AS NUME_ROW, 8 AS ORDINE, '29' AS FORM FROM DUAL UNION
    SELECT '590+620+880' AS NR_ROW, 'Gospodariile auxiliare' AS NUME_ROW, 7 AS ORDINE, '33' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970' AS NR_ROW, 'Intreprinderile agricole' AS NUME_ROW, 6 AS ORDINE, '33' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+684+685+686' AS NR_ROW, 'Intreprinderile agricole si gospodariile taranesti (de fermier), care au balanta animale' AS NUME_ROW, 4 AS ORDINE, '33' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+880+590+620+684+685+686' AS NR_ROW, 'Gospodariile de toate categoriile' AS NUME_ROW, 1 AS ORDINE, '29,33' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970+590+620+880' AS NR_ROW, 'Intreprinderile agricole(gosp.auxiliare)' AS NUME_ROW, 3 AS ORDINE, '33' AS FORM FROM DUAL UNION
    SELECT '500+510+530+540+541+550+690+700+890+970+420+450+880+590+620+684+685+686' AS NR_ROW, 'Intreprinderile agricole (gosp. auxiliare) si gospodariile taranesti (de fermier), care au la balanta animale' AS NUME_ROW, 2 AS ORDINE, '33' AS FORM FROM DUAL
  ) CF
  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT
      DECODE(CS.CODUL, 
      '0000000','01','0100000','02','1111111','03','0300000','04',
      '1400000','05','3400000','06','3600000','07','4100000','08','4300000','09',
      '4500000','10','4800000','11','6200000','12','7100000','13','7400000','14',
      '7800000','15','2222222','16','1000000','17','2500000','18','3100000','19',
      '3800000','20','5300000','21','5500000','22','6000000','23','6400000','24',
      '6700000','25','8000000','26','8300000','27','8900000','28','9200000','29',
      '3333333','30','1200000','31','1700000','32','2100000','33','2700000','34',
      '2900000','35','5700000','36','8500000','37','8700000','38','9600000','39')
      AS NR_ROW,
      CS.DENUMIRE AS NUME_ROW,
      CS.CODUL AS CS_CUATM
    FROM
      VW_CL_CUATM CS
    WHERE
      CS.CODUL 
      IN(
         '0000000','0100000','1111111','0300000','1400000','3400000','3600000','4100000','4300000','4500000',
         '4800000','6200000','7100000','7400000','7800000','2222222','1000000','2500000','3100000','3800000',
         '5300000','5500000','6000000','6400000','6700000','8000000','8300000','8900000','9200000','3333333',
         '1200000','1700000','2100000','2700000','2900000','5700000','8500000','8700000','9600000'
        )
  ) R 
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (29,33)                 AND 
  D.CAPITOL IN (381,375)
  AND D.CFOJ IS NOT NULL
  
GROUP BY 
  R.NR_ROW,
  R.NUME_ROW,
  CF.NR_ROW,
  CF.NUME_ROW,
  CF.ORDINE
);
   ELSE
     INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14,COL15,COL16, COL17
)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  ROUND(COL1,0)||'~'||NR_ROW AS NR_ROW,
  ORDINE,
  '01001001000100000' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL2,0) AS COL1,
  ROUND((NVAL(COL2)/NOZERO(COL1))*100,1) AS COL2,
  ROUND(COL4,0) AS COL3,
  ROUND(COL5,0) AS COL4,
  ROUND((NVAL(COL5)/NOZERO(COL4))*100,1) AS COL5,
  ROUND(COL7,0) AS COL6,
  ROUND(COL8,0) AS COL7,
  ROUND((NVAL(COL8)/NOZERO(COL7))*100,1) AS COL8,
  ROUND(COL10,0) AS COL9,
  ROUND(COL11,0) AS COL10,
  ROUND(COL12,0) AS COL11,
  ROUND((NVAL(COL12)/NOZERO(COL11))*100,1) AS COL12,
  ROUND(COL14,0) AS COL13,
  NULL COL14, 
  ROUND(COL15,0) AS COL15,
  ROUND(COL16,0) AS COL16,

  ROUND((NVAL(COL16)/NOZERO(COL15))*100,1)  AS COL17
  
FROM
(
SELECT 
  RE.CUIIO AS NR_ROW,
  MAX(RE.DENUMIRE) AS NUME_ROW,
  TO_NUMBER(RE.CUIIO) AS ORDINE,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL1,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL2,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('240') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL4,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('240') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL5,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('250') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL7,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('250') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL8,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('251') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') THEN D.COL1 END END) AS COL10,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('260') THEN D.COL1 ELSE 
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL11,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('260') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL12,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('261') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11','14') THEN D.COL1 END END) AS COL14,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15') THEN D.COL1 END END) AS COL15,
      
      
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL16,
      
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL17
  
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)                 AND 
  D.CAPITOL IN (381)
  AND D.CFOJ IS NOT NULL
  
GROUP BY 
  RE.CUIIO
--  RE.DENUMIRE
UNION
SELECT 
  0 AS NR_ROW,
  'TOTAL' AS NUME_ROW,
  0 AS ORDINE,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL1,
  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL2,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('240') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL4,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('240') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL5,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('250') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL7,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('250') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL8,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('251') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') THEN D.COL1 END END) AS COL10,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('260') THEN D.COL1 ELSE 
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL11,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('260') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL12,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('261') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11','14') THEN D.COL1 END END) AS COL14,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15') THEN D.COL1 END END) AS COL15,
      
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL16,
      
       SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL17
      
   
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)                 AND 
  D.CAPITOL IN (381)
  AND D.CFOJ IS NOT NULL
);
   END IF;
  END LOOP;
END; -- =======================================================================