SELECT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
--         
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
 -- ROUND(COL1,0)||'~'||NR_ROW AS NR_ROW,
  ORDINE,
  '01001001000100000' AS DECIMAL_POS,
  NUME_ROW,
--  ROUND(COL2,0) AS COL1,
--  ROUND((NVAL(COL2)/NOZERO(COL1))*100,1) AS COL2,
--  ROUND(COL4,0) AS COL3,
--  ROUND(COL5,0) AS COL4,
--  ROUND((NVAL(COL5)/NOZERO(COL4))*100,1) AS COL5,
--  ROUND(COL7,0) AS COL6,
--  ROUND(COL8,0) AS COL7,
--  ROUND((NVAL(COL8)/NOZERO(COL7))*100,1) AS COL8,
--  ROUND(COL10,0) AS COL9,
  ROUND(COL11,0) AS COL10,
  ROUND(COL12,0) AS COL11,
  ROUND((NVAL(COL12)/NOZERO(COL11))*100,1) AS COL12
--  ROUND(COL14,0) AS COL13,
--  NULL COL14, 
--  ROUND(COL15,0) AS COL15,
--  ROUND(COL16,0) AS COL16,
--
--  ROUND((NVAL(COL16)/NOZERO(COL15))*100,1)  AS COL17
--  
FROM
(
SELECT 
  RE.CUIIO AS NR_ROW,
  MAX(RE.DENUMIRE) AS NUME_ROW,
  TO_NUMBER(RE.CUIIO) AS ORDINE,
--  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
--           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL1,
--  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
--           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL2,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('240') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL4,
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('240') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL5,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('250') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL7,
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('250') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL8,
--  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('251') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') THEN D.COL1 END END) AS COL10,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('260') THEN D.COL1 ELSE 
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL11,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('260') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL12
  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('261') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11','14') THEN D.COL1 END END) AS COL14,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15') THEN D.COL1 END END) AS COL15,
--      
--      
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL16,
--      
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL17
  
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)                 AND 
  D.CAPITOL IN (381)
  AND D.CFOJ IS NOT NULL
  
GROUP BY 
  RE.CUIIO
--  RE.DENUMIRE
UNION
SELECT 
  0 AS NR_ROW,
  'TOTAL' AS NUME_ROW,
  0 AS ORDINE,
--  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
--           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL1,
--  NVAL(SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('230') THEN NVAL(D.COL1) ELSE
--           CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('1') THEN NVAL(D.COL1) END END)) AS COL2,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('240') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL4,
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('240') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') THEN D.COL1 END END) AS COL5,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('250') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL7,
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('250') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('7') THEN D.COL1 END END) AS COL8,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('251') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('8') THEN D.COL1 END END) AS COL10,
  
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('260') THEN D.COL1 ELSE 
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL11,
  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('260') THEN D.COL1 ELSE
      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('10','13') THEN D.COL1 END END) AS COL12
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('261') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('11','14') THEN D.COL1 END END) AS COL14,
--  
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('15') THEN D.COL1 END END) AS COL15,
--      
--  SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL16,
--      
--       SUM(CASE WHEN D.FORM IN (33) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('280') THEN D.COL1 ELSE
--      CASE WHEN D.FORM IN (29) AND D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('15') THEN D.COL1 END END)  AS COL17
      
   
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33)                 AND 
  D.CAPITOL IN (381)
  AND D.CFOJ IS NOT NULL )