SELECT ----
    'Rind '||DD.RIND||' '||
  NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END))||' &lt;&gt;  '||
  NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 THEN  D.COL2 ELSE 0 END)) AS REZULTAT
FROM
  CIS.VW_DATA_ALL D 
  INNER JOIN USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD ON (D.CUIIO=DD.CUIIO AND DD.ID_SCHEMA IN (1) AND D.FORM=DD.FORM AND D.RIND=DD.RIND AND D.CAPITOL=DD.CAPITOL)
   
   WHERE 
  (D.PERIOADA IN(:PERIOADA-1)) AND
  (DD.PERIOADA IN(:PERIOADA)) AND
  (D.CUIIO=:CUIIO              ) AND
  (:CUIIO_VERS=:CUIIO_VERS      AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL           ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS ) AND
  (D.ID_MD=:ID_MD               ) AND
   D.FORM = 1 AND
   D.CAPITOL = 1 
   AND DD.RIND NOT IN  ('2100','2200','2600','2000'))
   GROUP BY 
   DD.RIND
   
   HAVING
  ((NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END)) <
   (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 AND D.NUM IN (1,2,3) THEN  D.COL2 ELSE 0 END))*0.9) 
    
  OR  
  
   NVAL(SUM(CASE WHEN DD.PERIOADA IN :PERIOADA  AND DD.NUM IN (2,3,4) THEN DD.COL1 ELSE 0 END)) >
  (NVAL(SUM(CASE WHEN D.PERIOADA IN :PERIOADA-1 AND D.NUM IN (1,2,3)  THEN  D.COL2 ELSE 0 END))*1.1) ))
  
   AND
  (
  SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO ) AND
   D.FORM  IN(1) 
   AND
   D.CAPITOL IN (0)   
  AND D.RIND  IN  ('01','05')   
   ) IS NOT NULL 
    