MERGE INTO USER_BANCU.RENIM_24 T
USING (
    SELECT 
        B.CUIIO AS STRING_CUIIO, 
        A.IDNO AS SUBSTRING_IDNO
    FROM 
        USER_BANCU.RENIM_24 A
    JOIN 
        USER_BANCU.RENIM_24 B
    ON 
        A.CUIIO <> B.CUIIO
        AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%'
) S
ON (T.CUIIO = S.STRING_CUIIO)
WHEN MATCHED THEN 
    UPDATE SET T.IDNO = S.SUBSTRING_IDNO;
