SELECT 
    B.CUIIO AS STRING_CUIIO, 
    A.IDNO AS SUBSTRING_IDNO
FROM 
    USER_BANCU.RENIM_24 A
JOIN 
    USER_BANCU.RENIM_24 B
ON 
    A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%';