SELECT *
FROM USER_BANCU.RENIM_24
WHERE CUIIO IN (
    SELECT DISTINCT A.CUIIO
    FROM USER_BANCU.RENIM_24 A
    JOIN USER_BANCU.RENIM_24 B
    ON A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%'
    UNION
    SELECT DISTINCT B.CUIIO
    FROM USER_BANCU.RENIM_24 A
    JOIN USER_BANCU.RENIM_24 B
    ON A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%'
)
ORDER BY SUBSTR(CUIIO, 1, 10), LENGTH(CUIIO);
