SELECT 
    B.CUIIO AS STRING_CUIIO, 
    A.IDNO  AS SUBSTRING_IDNO,
    B.IDNO  AS  STRING_IDNO,
    A.DENUMIRE AS SUBSTRING_DENUMIRE,
    B.DENUMIRE AS STRING_DENUMIRE 
FROM 
    USER_BANCU.RENIM_24 A
JOIN 
    USER_BANCU.RENIM_24 B
ON 
    A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%';