SELECT 
    A.*, 
    B.*,
    A.CUIIO AS SUBSTRING_CUIIO,
    B.CUIIO AS CONTAINING_CUIIO
FROM 
    USER_BANCU.RENIM_24 A
JOIN 
    USER_BANCU.RENIM_24 B
ON 
    A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%'
ORDER BY 
    A.CUIIO, B.CUIIO;
