SELECT 
 CUIIO,
 REZULTAT
 
 FROM 

(

SELECT
D.CUIIO,
   'Rind '||D.RIND||' '||SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL14) ELSE 0 END)||' <> '||
   
   (SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL1) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL3) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL4) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL5) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL6) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL7) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL8) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL10) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL11) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL12) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL13) ELSE 0 END))  AS REZULTAT
  
FROM
  CIS2.VW_DATA_ALL D
  
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
 -- (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (40)  AND
  D.CAPITOL IN (1023) AND
  D.RIND BETWEEN '01' AND '30'
  
GROUP BY D.RIND,
D.CUIIO

HAVING
  SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL14) ELSE 0 END) <>
   
   (SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL1) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL3) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL4) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL5) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL6) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL7) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL8) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL9) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL10) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL11) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL12) ELSE 0 END)+
    SUM(CASE WHEN D.CAPITOL IN 1023 THEN CIS2.NVAL(D.COL13) ELSE 0 END))
    
    )
    
    
    WHERE 
    
    REZULTAT LIKE '%Rind 30%'
    
--    
--    Daca NTII = 40 atunci rind 20,21,30 COL14 = 0  