SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
D.CAPITOL,
CA.DEN_SHORT,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10,
SUM(D.COL11) AS COL11,
SUM(D.COL12) AS COL12,
SUM(D.COL13) AS COL13,
SUM(D.COL14) AS COL14
    
    
    
      
    

FROM   
    ---CIS2.VW_DATA_ALL_COEF D    
     
     
     CIS2.VW_DATA_ALL D   
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
                    INNER JOIN CIS2.MD_CAPITOL CA ON CA.CAPITOL = D.CAPITOL AND CA.CAPITOL_VERS = D.CAPITOL_VERS 
WHERE
  D.FORM IN (40)             AND 
     
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  
  AND D.CAPITOL IN (1022)  AND D.RIND IN ('19') 
 -- D.CAPITOL IN (1127,1129) 
  
  
  

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
D.CAPITOL,
CA.DEN_SHORT,
D.RIND


HAVING 

SUM (CASE WHEN  D.CAPITOL IN (1022)  AND D.RIND IN ('19') THEN D.COL14 ELSE  0  END ) >   0 
ORDER BY 
D.CUIIO,
D.CAPITOL,
D.RIND