--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
   NR_SECTIE,
   NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,
   ORDINE,
  '00000000000000' AS DECIMAL_POS,
   NUME_ROW,
   COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14
   
FROM (

SELECT
  C.FULL_CODE NR_SECTIE,
  C.DENUMIRE AS NUME_SECTIE,
  J.DENUMIRE AS NUME_ROW,
  J.RIND AS NR_ROW,
  J.ORDINE,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL1 ELSE NULL  END) AS COL1,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL3 ELSE NULL END) AS COL3,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL4 ELSE NULL END) AS COL4,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL5 ELSE NULL END) AS COL5,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL6 ELSE NULL END) AS COL6,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL7 ELSE NULL END) AS COL7,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL8 ELSE NULL END) AS COL8,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL9 ELSE NULL END) AS COL9,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL10 ELSE NULL END) AS COL10,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL11 ELSE NULL END) AS COL11,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL12 ELSE NULL END) AS COL12,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL13 ELSE NULL END) AS COL13,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL14 ELSE NULL END) AS COL14

FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_CL_CUATM B ON (D.CUATM=B.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')
  CROSS JOIN (

  SELECT
    DENUMIRE,
    RIND,
    ORDINE
  
  FROM 
    CIS2.MD_RIND

  WHERE
    FORM = 40 AND
    CAPITOL = 1022 ) J
    
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1022 AND
   C.PRGS IN 2
   
GROUP BY
  C.FULL_CODE,
  C.DENUMIRE,
  J.DENUMIRE,
  J.RIND,
  J.ORDINE
  
  
UNION


SELECT
  '0000000;9810000;' AS FULL_CODE,
  C.DENUMIRE,
  J.DENUMIRE,
  J.RIND,
  J.ORDINE,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL1 ELSE NULL END) AS COL1,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL2 ELSE NULL END) AS COL2,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL3 ELSE NULL END) AS COL3,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL4 ELSE NULL END) AS COL4,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL5 ELSE NULL END) AS COL5,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL6 ELSE NULL END) AS COL6,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL7 ELSE NULL END) AS COL7,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL8 ELSE NULL END) AS COL8,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL9 ELSE NULL END) AS COL9,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL10 ELSE NULL END) AS COL10,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL11 ELSE NULL END) AS COL11,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL12 ELSE NULL END) AS COL12,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL13 ELSE NULL END) AS COL13,
  SUM(CASE WHEN J.RIND LIKE '%'|| D.RIND ||'%' THEN D.COL14 ELSE NULL END) AS COL14

FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_CL_CUATM B ON (D.CUATM=B.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM C ON (B.FULL_CODE LIKE '%'||C.CODUL||';%')
  CROSS JOIN (

  SELECT
    DENUMIRE,
    RIND,
    ORDINE
  
  FROM 
    CIS2.MD_RIND

  WHERE
    FORM = 40 AND
    CAPITOL = 1022 ) J
    
WHERE
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND
   D.CAPITOL = 1022 AND
   C.CODUL IN 0501000
   
GROUP BY
  C.FULL_CODE,
  C.DENUMIRE,
  J.DENUMIRE,
  J.RIND,
  J.ORDINE
  
ORDER BY
  NR_SECTIE,
  ORDINE
  
)