INSERT INTO  CIS2.TABLE_OUT
    (
      PERIOADA,
      FORM,
      FORM_VERS,
      ID_MDTABLE,
      COD_CUATM,
      NR_SECTIE,
      NUME_SECTIE,
      NR_SECTIE1,
      NUME_SECTIE1,
      NR_SECTIE2,
      NUME_SECTIE2,
      NR_ROW,
      ORDINE,
      DECIMAL_POS,
      NUME_ROW,
       
      COL1, COL2, COL3
    )
SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
   '0' AS  NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
    A.COL1||'~'||ROWNUM AS NR_ROW,
    ROWNUM AS ORDINE,
    '001' AS DECIMAL_POS,
    A.DENUMIRE AS NUME_ROW,
    A.COL2 COL1,
    A.COL3 COL2,
    A.COL4 COL3
   

FROM
(
SELECT 
 CC.DENUMIRE,CC.CODUL, CC.FULL_CODE, 0 AS ORDINE, CC.PRGS,

    COUNT(DISTINCT CASE WHEN MR.RIND IN ('0')  THEN D.UNIT_CODE  ELSE NULL END) AS COL1,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP3')  THEN D.UNIT_CODE  ELSE NULL END) AS COL2,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP2')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL3,
    COUNT(DISTINCT CASE WHEN MR.RIND NOT IN ('TIP2', 'TIP3','0')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL4
FROM
  VW_DATA_ALL_GC  D
  INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)

 INNER JOIN CIS2.VW_CL_CUATM CC ON ((C.CODUL=CC.CODUL AND CC.PRGS IN (8,3,5)) OR (CC.PRGS NOT IN (8,3,5) AND C.FULL_CODE LIKE '%'||CC.CODUL||'%'))
   
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  D.FORM IN (61)  AND
  D.CAPITOL IN (1114)
  AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
  



GROUP BY CC.DENUMIRE,
  CC.CODUL, CC.FULL_CODE,CC.PRGS
    
    

    
    
    ORDER BY 
    FULL_CODE
    ) A