SELECT 
L.DEN_SHORT,
L.CUIIO,
L.CUATM,
L.DENUMIRE,
L.PACHET,
L.DATA_PRIMIRII,
L.DATA_PROCESARII,
L.CAPITOL_DEN,
L.CAPITOL,
L.RIND


FROM

(
SELECT
DISTINCT
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
NULL  AS DATA_PRIMIRII,
MAX(C.DATA_REG) AS DATA_PROCESARII,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10,
SUM(D.COL11) AS COL11,
SUM(D.COL12) AS COL12,
SUM(D.COL13) AS COL13,
SUM(D.COL14) AS COL14,
SUM(D.COL15) AS COL15,
SUM(D.COL16) AS COL16,
SUM(D.COL17) AS COL17,
SUM(D.COL18) AS COL18,
SUM(D.COL19) AS COL19,
SUM(D.COL20) AS COL20,
SUM(D.COL21) AS COL21,
SUM(D.COL22) AS COL22

FROM
CIS.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST
INNER JOIN CIS.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
INNER JOIN CIS.MD_FORM F ON (D.FORM=F.FORM AND D.FORM_VERS=F.FORM_VERS)
--INNER JOIN USER_EREPORTING.VW_DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (1)
INNER JOIN CIS.CONTROL C ON (D.PERIOADA=C.PERIOADA AND D.CUIIO=C.CUIIO AND D.CUIIO_VERS=C.CUIIO_VERS)
WHERE
D.PERIOADA = :pPERIOADA_TRIM AND
D.CUATM LIKE '01%' AND
D.FORM IN (6)

--AND D.CUIIO = 65063
GROUP BY
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND


) l

--ORDER BY
--DEN_SHORT,
--CUIIO,
--CAPITOL,
--RIND
