SELECT
L.DEN_SHORT,
L.CUIIO,
L.CUATM,
L.DENUMIRE,
L.PACHET,
L.DATA_PRIMIRII,
L.DATA_PROCESARII,
R.CNT VALORILOR_NUMERICE 
FROM
(
SELECT
DEN_SHORT,
CUIIO,
CUATM,
DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII
FROM
(


SELECT
DISTINCT
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
MAX(PR.DATA_REG) AS DATA_PRIMIRII,
MAX(C.DATA_REG) AS DATA_PROCESARII
FROM
CIS2.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST
INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
INNER JOIN CIS2.MD_FORM F ON (D.FORM=F.FORM AND D.FORM_VERS=F.FORM_VERS)
INNER JOIN USER_EREPORTING.DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (1)
INNER JOIN CIS2.CONTROL C ON (D.PERIOADA=C.PERIOADA AND D.CUIIO=C.CUIIO AND D.CUIIO_VERS=C.CUIIO_VERS)
WHERE
D.PERIOADA = :pPERIOADA_LUNARA AND
D.CUATM LIKE '01%' AND
D.FORM IN (3,4)
GROUP BY
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE




)
ORDER BY
DEN_SHORT,
CUIIO
) L  LEFT JOIN (

SELECT 
DEN_SHORT,
CUIIO,
SUM(CNT) AS CNT

FROM
(
SELECT
RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11,
CASE WHEN  COL1 > 0 AND  COL1 IS NOT NULL THEN 1 ELSE 0  END 
+ CASE WHEN  COL2 > 0 AND  COL2 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL3 > 0 AND  COL3 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL4 > 0 AND  COL4 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL5 > 0 AND  COL5 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL6 > 0 AND  COL6 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL7 > 0 AND  COL7 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL8 > 0 AND  COL8 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL9 > 0 AND  COL9 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL10 > 0 AND  COL10 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL11 > 0 AND  COL11 IS NOT NULL THEN 1 ELSE 0  END
 CNT
FROM

(
SELECT
ROWNUM RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11
 
FROM
(


SELECT
DISTINCT
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
MAX(PR.DATA_REG) AS DATA_PRIMIRII,
MAX(C.DATA_REG) AS DATA_PROCESARII,
PR.CAPITOL_DEN,
PR.CAPITOL,
PR.RIND,
SUM(PR.COL1) AS COL1,
SUM(PR.COL2) AS COL2,
SUM(PR.COL3) AS COL3,
SUM(PR.COL4) AS COL4,
SUM(PR.COL5) AS COL5,
SUM(PR.COL6) AS COL6,
SUM(PR.COL7) AS COL7,
SUM(PR.COL8) AS COL8,
SUM(PR.COL9) AS COL9,
SUM(PR.COL10) AS COL10,
SUM(PR.COL11) AS COL11

FROM
CIS2.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST
INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
INNER JOIN CIS2.MD_FORM F ON (D.FORM=F.FORM AND D.FORM_VERS=F.FORM_VERS)
INNER JOIN USER_EREPORTING.VW_DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (1)
INNER JOIN CIS2.CONTROL C ON (D.PERIOADA=C.PERIOADA AND D.CUIIO=C.CUIIO AND D.CUIIO_VERS=C.CUIIO_VERS)
WHERE
D.PERIOADA = :pPERIOADA_LUNARA AND
D.CUATM LIKE '01%' AND
D.FORM IN (:pFORM)

--AND D.CUIIO = 65063
GROUP BY
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
PR.CAPITOL_DEN,
PR.CAPITOL,
PR.RIND

ORDER BY
DEN_SHORT,
CUIIO,
CAPITOL,
RIND

)

)
)

GROUP BY 
DEN_SHORT,
CUIIO
) R ON R.CUIIO = L.CUIIO 