SELECT 
L.DEN_SHORT,
L.CUIIO,
L.CUATM,
L.DENUMIRE,
L.PACHET,
R.DATA_PRIMIRII,
L.DATA_PROCESARII


FROM

(
SELECT
DISTINCT
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
NULL  AS DATA_PRIMIRII,
MAX(C.DATA_REG) AS DATA_PROCESARII



FROM
CIS.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST
INNER JOIN CIS.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
INNER JOIN CIS.MD_FORM F ON (D.FORM=F.FORM AND D.FORM_VERS=F.FORM_VERS)
--INNER JOIN USER_EREPORTING.VW_DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (1)
INNER JOIN CIS.CONTROL C ON (D.PERIOADA=C.PERIOADA AND D.CUIIO=C.CUIIO AND D.CUIIO_VERS=C.CUIIO_VERS)
WHERE
D.PERIOADA = :pPERIOADA_TRIM AND
D.CUATM LIKE '01%' AND
D.FORM IN (:pFORM)

--AND D.CUIIO = 65063
GROUP BY
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE

) L LEFT join (

SELECT
DISTINCT
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
MAX(PR.DATA_REG) AS DATA_PRIMIRII,
MAX(C.DATA_REG) AS DATA_PROCESARII



FROM
CIS.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST
INNER JOIN CIS.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
INNER JOIN CIS.MD_FORM F ON (D.FORM=F.FORM AND D.FORM_VERS=F.FORM_VERS)
INNER JOIN USER_EREPORTING.VW_DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (1)
INNER JOIN CIS.CONTROL C ON (D.PERIOADA=C.PERIOADA AND D.CUIIO=C.CUIIO AND D.CUIIO_VERS=C.CUIIO_VERS)
WHERE
D.PERIOADA = :pPERIOADA_TRIM AND
D.CUATM LIKE '01%' AND
D.FORM IN (:pFORM)
--AND D.CUIIO = 65063
GROUP BY
F.DEN_SHORT,
D.CUIIO,
D.CUATM,
R.DENUMIRE


ORDER BY
DEN_SHORT,
CUIIO

) R ON R.CUIIO = L.CUIIO

ORDER BY
DEN_SHORT,
CUIIO
