SELECT
  NVAL(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1630') THEN nval(D.COL1) ELSE 0 END)) ||' < '||
 (SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1631') THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1501','1502') THEN NVAL(D.COL2) ELSE 0 END)+ 
  SUM(CASE WHEN D.CAPITOL IN (401) AND D.RIND IN ('2100','2110','2120','2200','2300') THEN NVAL(D.COL1) ELSE 0 END))
  
  
  AS REZULTAT
  
FROM
  CIS2.VW_DATA_ALL D
  
WHERE
  (D.PERIOADA IN (:PERIOADA)          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERSM <> CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (45)  AND
  D.CAPITOL IN (399,401)
  
  
HAVING
  NVAL(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1630') THEN nval(D.COL1) ELSE 0 END)) <
 (SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1631') THEN NVAL(D.COL1) ELSE 0 END)+
  SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('1501','1502') THEN NVAL(D.COL2) ELSE 0 END)+ 
  SUM(CASE WHEN D.CAPITOL IN (401) AND D.RIND IN ('2100','2110','2120','2200','2300') THEN NVAL(D.COL1) ELSE 0 END))

