--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   COL1||'~'||ROWNUM AS NR_ROW,
   ROWNUM AS ORDINE,
  '00' AS DECIMAL_POS,
   NUME_ROW,
   
   COL2 AS COL1,
   ROUND(COL3,2) AS COL2
FROM
(

SELECT DISTINCT
  CC.FULL_CODE,
  CC.DENUMIRE AS NUME_ROW,
  CC.CODUL AS NR_ROW,
  SUM(CASE WHEN D.RIND IN '20' AND D.PERIOADA IN (:pPERIOADA-4) THEN COL1 ELSE 0 END) AS COL1,
  SUM(CASE WHEN D.RIND IN '20' AND D.PERIOADA IN (:pPERIOADA) THEN COL1 ELSE 0 END) AS COL2,
 CIS2.NVAL(SUM(CASE WHEN D.RIND IN '20' AND D.PERIOADA IN (:pPERIOADA) THEN COL1 END)/
  SUM(CASE WHEN D.RIND IN '20' AND D.PERIOADA IN (:pPERIOADA-4) THEN COL1 END))*100 AS COL3
  
FROM
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.VW_CL_CUATM C ON (CIS2.D.CUATM=CIS2.C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (CIS2.C.FULL_CODE LIKE '%'||CIS2.CC.CODUL ||';%' )

WHERE
  D.PERIOADA IN (:pPERIOADA,:pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  FORM = 29 AND
  CAPITOL = 375 AND
  CC.PRGS IN 2
GROUP BY 
  CC.FULL_CODE,
  CC.DENUMIRE,
  CC.CODUL


ORDER BY CC.FULL_CODE
)