SELECT 
    DISTINCT D.CUIIO,D.CUIIO_VERS, D.CUATM,
 MAX( CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
    D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ,
    SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL0 ,  
    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL4,
    SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)  AS CD,
    (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS  
FROM   
    CIS2.VW_DATA_ALL D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
 
  D.CAPITOL IN  (100,1123,1127,1129) 
  AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','400','CD','8')
  AND  D.CUIIO=41175467
 GROUP BY D.CUIIO,D.CUIIO_VERS, D.CUATM,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ
 
-- HAVING
-- 
--  SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END) >0