--NEW VERS--
INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28
)
----------------------------
--------------------------------
--------------------------------


SELECT 
 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
 '0' AS  NR_SECTIE,
 '0' AS  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW,
ROWNUM AS ORDINE,--||'~'||ORDINE
'0000000000000000000000000000' AS DECIMAL_POS,
NUME_ROW,
COL1, COL2, COL3,COL4,COL5,COL6,ROUND(COL7,1) AS COL7,COL8,COL9,ROUND(COL10,1) AS COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, ROUND(COL21,1) AS COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28
     FROM (

SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
  NR_SECTIE,
  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW||'~'|| NR_SECTIE||COL1||'1' AS NR_ROW,
 1||ORDINE AS ORDINE,
'0000000000000000000000000000' AS DECIMAL_POS,
NUME_ROW,
COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28
FROM
(
SELECT 
    NR_ROW AS NR_SECTIE ,         
    NUME_ROW AS NUME_SECTIE,  
    DENUMIRE AS NUME_ROW,
    CODUL AS NR_ROW,    
    ORDINE,
    COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28
   
   FROM(

SELECT 
   RR.NR_ROW ,         
   RR.NUME_ROW ,
   CC.FULL_CODE,
   CASE WHEN  CC.CODUL like '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
   CASE WHEN  Substr(CC.CODUL,1,1)||'0000' IS NOT NULL THEN Substr(CC.CODUL,1,1)||'0000' END AS codul, 
   RR.NR_ROW||'~'||CC.FULL_CODE AS ORDINE,
   
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN  DD.CUIIO END) AS COL1, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 0 AND 3   THEN DD.CUIIO  END) END) AS COL2, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 3 AND 6   THEN DD.CUIIO  END) END) AS COL3, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 6 AND 9   THEN DD.CUIIO  END) END) AS COL4, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 9 AND 12  THEN DD.CUIIO  END) END) AS COL5,
   
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('300') THEN  DR.COL1 END) AS COL6,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('300') THEN  DR.COL2 END) AS COL7,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('310') THEN  DR.COL1 END) AS COL8,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('310') THEN  DR.COL2 END) AS COL9,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('320') THEN  DR.COL1 END) AS COL10,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('320') THEN  DR.COL2 END) AS COL11,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('330') THEN  DR.COL1 END) AS COL12,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('330') THEN  DR.COL2 END) AS COL13,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('340') THEN  DR.COL1 END) AS COL14,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('340') THEN  DR.COL2 END) AS COL15,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('350') THEN  DR.COL1 END) AS COL16,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('350') THEN  DR.COL2 END) AS COL17,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('360') THEN  DR.COL1 END) AS COL18,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('360') THEN  DR.COL2 END) AS COL19,
   
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL3 END) AS COL20,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL4 END) AS COL21,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL5 END) AS COL22,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL8 END) AS COL23,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL9 END) AS COL24,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL10 END) AS COL25,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL8 END) AS COL26,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL9 END) AS COL27,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL10 END) AS COL28
                
    FROM
    
    
    CIS2.VW_DATA_ALL DR INNER JOIN
    
 (
-------------------------------------------------------------------------------     
  SELECT 
    DISTINCT D.CUIIO,D.CUIIO_VERS, D.CUATM,D.CAEM2,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ,
    SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL0 ,  
    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL4 
FROM   
    CIS2.VW_DATA_ALL D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1123,1124,1125,1126,1127,1128)
-- AND  D.CUIIO=40075114
 GROUP BY D.CUIIO,D.CUIIO_VERS, D.CUATM,D.CAEM2,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ

) DD ON DR.CUIIO=DD.CUIIO AND DR.CUIIO_VERS=DD.CUIIO_VERS

 INNER JOIN CIS2.VW_CL_CAEM2 C ON C.CODUL = DD.CAEM2                  
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 
  CROSS JOIN
  ( 
      SELECT 'Intreprinderile cu numarul de salariati 0-249 persoane'            AS NUME_ROW, '03' AS NR_ROW, 0 AS PERS_FROM, 249 AS PERS_TO FROM DUAL      
    
  ) RR  
         
 WHERE 
  (DR.FORM=:pFORM) AND
  (DR.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DR.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DR.PERIOADA IN (:pPERIOADA) 
 -- AND  C.CODUL LIKE '%00'
 
   GROUP BY
    CC.FULL_CODE,
   CC.DENUMIRE,
    CC.CODUL,
    RR.NR_ROW,       
    RR.NUME_ROW
     
    ORDER BY 
     RR.NR_ROW,CC.CODUL)
     
     WHERE DENUMIRE IS NOT NULL)
     
     UNION
     
SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
  NR_SECTIE,
  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW||'~'|| NR_SECTIE||COL1||'2' AS NR_ROW,
2||ORDINE AS ORDINE,
'0000000000000000000000000000' AS DECIMAL_POS,
NUME_ROW,
COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28
FROM
(
 SELECT
D.NR_ROW AS NR_SECTIE,         
D.NUME_ROW AS NUME_SECTIE,
D.CODUL AS NR_ROW,
ORDINE,
D.DENUMIRE AS NUME_ROW,
COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19,
    COL20, COL21, COL22,COL23,COL24,COL25,COL26,COL27,COL28

FROM(
SELECT 
   RR.NR_ROW ,         
   RR.NUME_ROW ,
   CC.FULL_CODE,
   CC.DENUMIRE,
   CC.CODUL,
   RR.NR_ROW||'~'||CC.FULL_CODE AS ORDINE,
   
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN  DD.CUIIO END) AS COL1, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 0 AND 3   THEN DD.CUIIO  END) END) AS COL2, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 3 AND 6   THEN DD.CUIIO  END) END) AS COL3, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 6 AND 9   THEN DD.CUIIO  END) END) AS COL4, 
   COUNT(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO THEN ROUND(CASE  WHEN DD.COL0 BETWEEN 9 AND 12  THEN DD.CUIIO  END) END) AS COL5,
  
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('300') THEN  DR.COL1 END) AS COL6,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('300') THEN  DR.COL2 END) AS COL7,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('310') THEN  DR.COL1 END) AS COL8,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('310') THEN  DR.COL2 END) AS COL9,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('320') THEN  DR.COL1 END) AS COL10,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('320') THEN  DR.COL2 END) AS COL11,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('330') THEN  DR.COL1 END) AS COL12,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('330') THEN  DR.COL2 END) AS COL13,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('340') THEN  DR.COL1 END) AS COL14,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('340') THEN  DR.COL2 END) AS COL15,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('350') THEN  DR.COL1 END) AS COL16,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('350') THEN  DR.COL2 END) AS COL17,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('360') THEN  DR.COL1 END) AS COL18,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('360') THEN  DR.COL2 END) AS COL19,
   
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL3 END) AS COL20,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL4 END) AS COL21,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('400') THEN  DR.COL5 END) AS COL22,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL8 END) AS COL23,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL9 END) AS COL24,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('500') THEN  DR.COL10 END) AS COL25,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL8 END) AS COL26,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL9 END) AS COL27,
   SUM(DISTINCT CASE WHEN DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO AND DR.RIND IN ('510') THEN  DR.COL10 END) AS COL28
              
    FROM
    
    
    CIS2.VW_DATA_ALL DR INNER JOIN
    
     (
-------------------------------------------------------------------------------     
  SELECT 
    DISTINCT D.CUIIO,D.CUIIO_VERS, D.CUATM,D.CAEM2,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ,
    SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL0 ,  
    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL4 
FROM   
    CIS2.VW_DATA_ALL D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1123,1124,1125,1126,1127,1128) 
-- AND  D.CUIIO=40075114
 GROUP BY D.CUIIO,D.CUIIO_VERS, D.CUATM,D.CAEM2,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ

) DD ON DR.CUIIO=DD.CUIIO AND DR.CUIIO_VERS=DD.CUIIO_VERS
-------------------------------------------------------------------------------    

 INNER JOIN CIS2.VW_CL_CAEM2 C ON C.CODUL = DD.CAEM2                  
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 
  CROSS JOIN
  ( 
     SELECT 'Intreprinderile cu numarul de salariati 0-249 persoane'            AS NUME_ROW, '03' AS NR_ROW, 0 AS PERS_FROM, 249 AS PERS_TO FROM DUAL        
    
  ) RR  
         
 WHERE 
  (DR.FORM=:pFORM) AND
  (DR.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DR.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DR.PERIOADA IN (:pPERIOADA) 
 -- AND  C.CODUL LIKE '%0'
 
   GROUP BY
    CC.FULL_CODE,
    CC.DENUMIRE,
    CC.CODUL,
    RR.NR_ROW,       
    RR.NUME_ROW
    
    ORDER BY 
     RR.NR_ROW,CC.CODUL
     ) D
     
     
      WHERE
         
         D.COL1+D.COL2+ D.COL3+D.COL4+D.COL5>0 )
     ORDER BY ORDINE ) ORDER BY ORDINE