MERGE INTO CIS2.RENIM R
USING USER_BANCU.LIV_2 L
ON (R.CUIIO = L.CUIIO AND R.CUIIO_VERS = L.CUIIO_VERS)
WHEN MATCHED THEN
  UPDATE SET
    R.DENUMIRE = L.DENUMIRE,
    R.CUATM = L.CUATM,
    R.CFP = L.CFP,
    R.CFOJ = L.CFOJ;