SELECT
 
 SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2100-1')    THEN CIS2.NVAL(D.COL1)  ELSE 0 END) ||' <> '  || SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200','240')    THEN CIS2.NVAL(D.COL1)  ELSE 0 END)
 AS REZULTAT
  

FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  ( :CAPITOL = :CAPITOL           OR :CAPITOL <>  :CAPITOL) AND
  ( :CAPITOL_VERS=:CAPITOL_VERS   OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  

  D.CAPITOL IN (1200,1125)
  
  
  HAVING 
  
  SUM(CASE WHEN D.CAPITOL IN (1200) AND D.RIND IN ('2100-1')    THEN CIS2.NVAL(D.COL1)  ELSE 0 END)  <> 
   SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200','240')    THEN CIS2.NVAL(D.COL1)  ELSE 0 END)
  
  

  

 