SELECT 
 
  TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') -
  TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  ||' zile'
 --
  --TO_CHAR(LAST_DAY(TO_DATE( '01-FEB-'|| EXTRACT(YEAR FROM TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')), 'DD-MON-YYYY')), 'DD'),
 
  AS REZULTAT
  
FROM
 CIS2.VW_DATA_ALL_FR D  
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (59)  AND
  D.RIND IN ('2') AND CAPITOL IN (1109)
  
  HAVING 
  
 (TO_CHAR(LAST_DAY(TO_DATE( '01-FEB-'|| EXTRACT(YEAR FROM TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')), 
 'DD-MON-YYYY')), 'DD') =28 AND
  
 (TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') -
  TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  >=365) )
 
 OR  
 
 (TO_CHAR(LAST_DAY(TO_DATE( '01-FEB-'|| EXTRACT(YEAR FROM TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY')), 'DD-MON-YYYY')), 'DD') =29 AND
  
 (TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL2 ELSE NULL END),'DD.MM.YYYY') -
  TO_DATE(MAX(CASE WHEN D.RIND IN ('2') AND CAPITOL IN (1109) THEN D.COL1 ELSE NULL END),'DD.MM.YYYY')  >=366) )
 
