SELECT 
    CC.CODUL,
    CC.DENUMIRE DENUMIRE_CUATM,
    CC.FULL_CODE,
    
    CII.ITEM_CODE,
    CII.SHOW_ORDER,  
    CII.NAME,
    SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA) AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
    SUM(CASE WHEN D.PERIOADA IN(:pPERIOADA-1) AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL2
     
  FROM    
     CIS2.VW_DATA_ALL D \
     
      INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
      INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2') AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
      
      INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL) 
      INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )

  WHERE 
  (D.PERIOADA IN(:pPERIOADA,:pPERIOADA-1)) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)   AND
  D.CAPITOL IN (405)
  AND CII.ITEM_CODE = '00.00.00' 
  AND D.CUIIO = 20282377
  
  GROUP BY 
    CII.ITEM_CODE,
    CII.SHOW_ORDER,  
    CII.NAME,
    
    CC.CODUL,
    CC.DENUMIRE,
    CC.FULL_CODE
    
    ORDER BY 
    CII.SHOW_ORDER
 
  
  