--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16
--)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  'B+C+D+E' AS NR_ROW,
  (N.ORDINE - 0.5)  AS ORDINE,
  '1111111111111111' AS DECIMAL_POS,
  'Industrie:(B+C+D+E)' AS NUME_ROW,
  ROUND(SUM(R.COL1),1) AS COL1,
  ROUND(SUM(R.COL2),1) AS COL2,
  ROUND(SUM(R.COL3),1) AS COL3,
  ROUND(SUM(R.COL4),1) AS COL4,
  ROUND(SUM(R.COL5),1) AS COL5,
  ROUND(SUM(R.COL6),1) AS COL6,
  ROUND(SUM(R.COL7),1) AS COL7,
  ROUND(SUM(R.COL8),1) AS COL8,
  ROUND(SUM(R.COL9),1) AS COL9,
  ROUND(SUM(R.COL10),1) AS COL10, 
  ROUND(SUM(R.COL2)/CIS2.NOZERO(SUM(R.COL1))*1000/12,1) AS COL11,
  ROUND(MAX(TT.COL11),1) AS COL12,
  ROUND(SUM(R.COL2)/CIS2.NOZERO(SUM(R.COL1))*1000/12/MAX(TT.COL11)*100,1) AS COL13,
  ROUND(((CIS2.NVAL(SUM(R.COL3))+ CIS2.NVAL(SUM(R.COL5)) + CIS2.NVAL(SUM(R.COL6)))- CIS2.NVAL(SUM(R.COL8)) - CIS2.NVAL(SUM(R.COL9)))/CIS2.NOZERO(SUM(T1.COL2))*1000/12,1) AS COL14,  
  ROUND(MAX(TT.COL14),1) AS COL15,  
  ROUND(((CIS2.NVAL(SUM(R.COL3))+ CIS2.NVAL(SUM(R.COL5)) + CIS2.NVAL(SUM(R.COL6)))- CIS2.NVAL(SUM(R.COL8)) - CIS2.NVAL(SUM(R.COL9)))/CIS2.NOZERO(SUM(T1.COL2))*1000/12/CIS2.NOZERO(MAX(TT.COL14))* 100,1) AS COL16 
   

FROM CIS2.TABLE_OUT R
  LEFT JOIN
   (SELECT NR_ROW, COL11, COL14, ID_MDTABLE FROM CIS2.TABLE_OUT  
  
  WHERE  
    ID_MDTABLE=(CASE WHEN :pPERIOADA>2010 THEN 11635 ELSE 5684 END) AND 
    PERIOADA = :pPERIOADA-1  AND
    FORM IN (3)              AND 
    FORM_VERS = :PFORM_VERS  AND    
    COD_CUATM IN (:pCOD_CUATM) AND
    NR_ROW IN ('B+C+D+E')) TT ON (1=1)
    
    LEFT JOIN (
  SELECT NR_ROW, COL2, ID_MDTABLE FROM  CIS2.TABLE_OUT  
  
  WHERE  ID_MDTABLE =(11521) AND
    FORM IN (3)              AND 
    FORM_VERS = :PFORM_VERS  AND    
    COD_CUATM IN (:pCOD_CUATM) AND
    PERIOADA = :pPERIOADA     
    ) T1
     
  ON (R.NR_ROW=T1.NR_ROW)
  
  ,
   ( SELECT MIN(ORDINE) AS ORDINE
   FROM CIS2.TABLE_OUT 
   WHERE  COD_CUATM IN (:pCOD_CUATM) AND 
   PERIOADA IN (:pPERIOADA) AND 
   ID_MDTABLE IN (:pID_MDTABLE) AND
   FORM IN (:pFORM) AND
   SUBSTR(NR_ROW,1,5) IN ('B0000','C0000','D0000','E0000')) N

WHERE
  R.COD_CUATM IN (:pCOD_CUATM) AND 
  R.PERIOADA IN (:pPERIOADA) AND 
  R.ID_MDTABLE IN (:pID_MDTABLE) AND
  R.FORM IN (:pFORM) AND
  SUBSTR(R.NR_ROW,1,5) IN ('B0000','C0000','D0000','E0000')
GROUP BY
  N.ORDINE