CREATE OR REPLACE FORCE VIEW  VVW_KATALOG_PRODMOLD_2023
(
CUIIO,
PRDOMOLD_R10
)

AS

select 
D.CUIIO,
SUM(CASE WHEN D.CAPITOL = 97 AND D.RIND IN '10' THEN D.COL1 ELSE NULL END) AS PRDOMOLD_R10
    from CIS.VW_DATA_ALL D 
where 
D.FORM = 10

AND D.PERIOADA IN (2012)
--AND D.CUIIO = 411016
GROUP by
D.CUIIO


