select 
D.CUIIO,
SUM(CASE WHEN D.CAPITOL = 301 AND D.RIND IN '00-T' THEN D.COL3 ELSE NULL END) AS M3_00_T_COL2
    from CIS2.VW_DATA_ALL D 
where 
D.FORM = 3

AND D.PERIOADA IN (2012)
AND D.CUIIO = 9202
GROUP by
D.CUIIO


