SELECT
  D.RIND,
  C.DENUMIRE,
  C.FULL_CODE,
  CIS2.NVAL(COUNT (DISTINCT(CASE WHEN D.RIND NOT IN '0000000' AND D.CAPITOL IN (1035) AND  CIS2.NVAL(D.COL9)>0 THEN D.RIND END))) AS COL1 

  

   
  FROM
      CIS2.VW_DATA_ALL D        
     INNER JOIN CIS2.VW_CL_CUATM C ON (D.RIND=C.CODUL) 

WHERE  D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 47 AND
       D.CAPITOL IN (1035,1037) AND
       C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'
      
GROUP BY
D.RIND,
C.DENUMIRE,
C.FULL_CODE

HAVING 

CIS2.NVAL(COUNT (DISTINCT(CASE WHEN D.RIND NOT IN '0000000' AND D.CAPITOL IN (1035) AND  CIS2.NVAL(D.COL9)>0 THEN D.RIND END))) > 0

ORDER BY
C.FULL_CODE 