--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--   
--  COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9
--)

  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CD.CODE AS NR_ROW,  
   CD.CODE AS ORDINE,
  '11111111111' AS DECIMAL_POS,
   CD.DEN_CUATM AS NUME_ROW,               

   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) AS COL1, 
   SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) AS COL2,
   SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) AS COL3,  
   SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) AS COL4,
   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) AS COL5,
   SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) AS COL6,
   SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) AS COL7,
   SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) AS COL8,
   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL4 END) AS COL9 
   
  
  FROM
              VW_DATA_ALL D
                INNER JOIN RENIM R ON (R.CUIIO= D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
                INNER JOIN VW_CL_CUATM VC ON (VC.CODUL = R.CUATM)
                
                CROSS JOIN 

(

SELECT  V.CODUL AS CODE, V.PRGS AS PRGS, V.DENUMIRE 
AS DEN_CUATM
FROM VW_CL_CUATM V
WHERE V.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'


--AND  PRGS NOT IN ('2','3','4','5')
) CD

WHERE  D.PERIOADA = :pPERIOADA AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS 
     -- AND       VC.PRGS NOT IN ('2','3','4','5')
GROUP BY  CD.CODE , CD.DEN_CUATM

HAVING

  
   
  
   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) > 0 OR 
   SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) > 0 OR 
   SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) > 0 OR   
   SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL1 END) > 0 OR 
   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) > 0 OR 
   SUM(CASE WHEN D.RIND='07'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) > 0 OR 
   SUM(CASE WHEN D.RIND='08'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) > 0 OR 
   SUM(CASE WHEN D.RIND='09'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL2 END) > 0 OR 
   SUM(CASE WHEN D.RIND='01'  AND VC.FULL_CODE LIKE '%'||CD.CODE||';%' THEN  D.COL4 END) > 0 
   

ORDER BY  CD.CODE