WITH CALCULATION AS (
  SELECT 
    D.CUIIO,
    D.PERIOADA,
    SUM(D.COL4) AS COL4,
    CR.COL1
  FROM 
    CIS2.DATA_ALL D
  CROSS JOIN (
    SELECT
      D.PERIOADA,
      SUM(D.COL1) AS COL1
    FROM 
      DATA_ALL D
    WHERE
      D.PERIOADA IN (:pPERIOADA, :pPERIOADA-1) AND
      D.ID_MD = 44519
    GROUP BY 
      D.PERIOADA
  ) CR
  WHERE 
    (D.PERIOADA = :pPERIOADA OR D.PERIOADA = :pPERIOADA-1) AND
    D.FORM = 44 AND
    D.FORM IN (44) AND
    D.CUIIO = 19206
  GROUP BY 
    D.CUIIO,
    D.PERIOADA,
    CR.COL1
)
SELECT 
  CUIIO,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2
FROM
(
  SELECT 
    CUIIO,
    PERIOADA,
    COL4 - CASE WHEN PERIOADA = 1056 THEN 1688 ELSE 9806 END AS COL1,
    COL4 / COL1 - CASE WHEN PERIOADA = 1056 THEN 1688 / 18.8453 ELSE 9806 / 19.456 END AS COL2
  FROM CALCULATION
)
GROUP BY CUIIO;