SELECT D.CUIIO,   
D.CUATM,
D.RIND,
SUM(D.COL1) AS COL1 

FROM CIS2.VW_DATA_ALL D 

        

WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (27)                 AND 
  D.CAPITOL IN (370) 
  AND D.RIND IN ('32')
  
  GROUP BY 
  D.CUIIO,
  D.CUATM,
  D.RIND