SELECT 
    D.CUIIO,
    SUM(D.COL1) COL1,
    SUM(D.COL2) COL2,
    SUM(D.COL3) COL3,
    SUM(D.COL4) COL4,
    SUM(D.COL5) COL5
    
     FROM VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) AND
  D.RIND IN ('1220')
  
  GROUP BY
  D.CUIIO