SELECT DISTINCT 
  'Col.'||C.COL||': '|| 
  SUM(CASE WHEN D.RIND     IN( '0100') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) ||' <> '||
  SUM(CASE WHEN D.RIND     IN ('0101','0102','0103') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D,
  (
    SELECT 1 AS COL FROM DUAL
  ) C

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (1)  AND
  D.CAPITOL in (2)
 
GROUP BY
  C.COL
  
HAVING
  SUM(CASE WHEN D.RIND     IN('0100') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END) <> 
  SUM(CASE WHEN D.RIND    IN ('0101','0102','0103') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2) ELSE 0 END)