INSERT INTO CIS.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3
)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   D.CODUL||'~'||D.ORDINE AS NR_ROW,
   D.CODUL AS ORDINE,
  '000' AS DECIMAL_POS,
   D.DENUMIRE AS NUME_ROW,
   ROUND(D.COL1,1) AS COL1,
   ROUND(D.COL2,1) AS COL2,
   ROUND(D.COL3,1) AS COL3
FROM
(
  
SELECT
  DENUMIRE, 
  CODUL,
  FULL_CODE,
  ORDINE,
  PRGS,
  COL1,COL2,COL3
FROM
(

SELECT
  CC.DENUMIRE,CC.CODUL, CC.FULL_CODE, 0 AS ORDINE, CC.PRGS,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' THEN COL1 ELSE 0 END)) AS COL1,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' THEN COL2 ELSE 0 END)) AS COL2,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' THEN COL3 ELSE 0 END)) AS COL3
  
FROM
  CIS.VW_DATA_ALL D
 INNER JOIN (
 -----------------------------------------
 SELECT
D.ITEM_CODE CODUL,
D.A01 AS PRGS,
D.NAME DEN_CUATM,
D.ITEM_PATH FULL_CODE
 
 FROM CIS2.VW_CLS_CLASS_ITEM D INNER JOIN (
 
 SELECT 
ITEM_CODE,
MAX(ITEM_CODE_VERS) ITEM_CODE_VERS


FROM CIS2.VW_CLS_CLASS_ITEM


WHERE 
CLASS_CODE IN ('CUATM') 

GROUP BY 
ITEM_CODE

 ) DD ON D.ITEM_CODE = DD.ITEM_CODE AND D.ITEM_CODE_VERS = DD.ITEM_CODE_VERS  AND D.CLASS_CODE IN ('CUATM')
 
 ------------------------------------------
 
 ) C ON (D.RIND=C.CODUL )
  INNER JOIN CIS.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||'%')
  
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 6 AND
  -- D.CUIIO=1123 AND 
 
   D.CAPITOL IN (32) AND CC.PRGS NOT IN '4'  AND C.PRGS IN ('6','8','9') AND 
   C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'
   
GROUP BY CC.DENUMIRE,
  CC.CODUL, CC.FULL_CODE,CC.PRGS
)
WHERE
  PRGS IN ('2','6','8','9')
ORDER BY
  FULL_CODE,
  ORDINE  
   )  D
 
  
  