--SELECT
--  DENUMIRE, 
--  CODUL,
--  FULL_CODE,
--  ORDINE,
--  PRGS,
--  COL1,COL2,COL3,COL4,COL5,COL6
--FROM
--(
SELECT
  CC.DENUMIRE,CC.CODUL, CC.FULL_CODE, 
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) THEN COL2 ELSE 0 END)) AS COL1,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND  C.PRGS IN (2,3,4,5) THEN COL2 ELSE 0 END)) AS COL2,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND  C.PRGS IN (6,8,9)   THEN COL2 ELSE 0 END)) AS COL3,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND  D.CFP IN (15) THEN COL2 ELSE 0 END)) AS COL4,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND  D.CFP IN (15) AND  C.PRGS IN (2,3,4,5) THEN COL2 ELSE 0 END)) AS COL5,
  CIS.NVAL(SUM(CASE WHEN CAPITOL IN (32) AND D.RIND NOT IN '0000000' AND (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) AND  D.CFP IN (15) AND  C.PRGS IN (6,8,9)   THEN COL2 ELSE 0 END)) AS COL6
  
FROM
  CIS.VW_DATA_ALL D
 INNER JOIN CIS.VW_CL_CUATM C ON (D.RIND=C.CODUL )
  INNER JOIN CIS.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||'%')
  
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 6 AND
 
   D.CAPITOL IN (32) AND CC.PRGS NOT IN '4'  AND
   C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'
   
GROUP BY CC.DENUMIRE,
  CC.CODUL, CC.FULL_CODE
  
  ORDER BY
  CC.FULL_CODE
--)
--WHERE
--  PRGS IN (2)
--ORDER BY
--  FULL_CODE