SELECT   
 D.RIND

   
 AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D  
 

WHERE
  (CIS2.D.PERIOADA=:PERIOADA          ) AND
  (CIS2.D.CUIIO=:CUIIO                ) AND
  (CIS2.D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (CIS2.D.FORM = :FORM               ) AND
  (CIS2.D.FORM_VERS=:FORM_VERS ) AND
  (CIS2.D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (CIS2.D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (CIS2.D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  CIS2.D.FORM IN (19)  AND
  CIS2.D.CAPITOL IN (1017) 
  
  AND  D.RIND NOT IN 
  (
  SELECT 
    CODUL
  FROM 
    CIS2.CL_TARI 
  )
 

GROUP BY 
  D.RIND, 
  D.COL1
