CREATE TABLE USER_BANCU.FORM_CUIIO_ASC
(
  CUIIO       NUMBER,
  
  CUIIO_VERS  NUMBER,
  
  STATUT      VARCHAR2(1024 BYTE),
  FORM        VARCHAR2(1024 BYTE)

)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;