--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3,COL4,COL5, COL6, COL7, COL8, COL9, COL10, COL11
--)

SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
 NR_SECTIE,
 NR_SECTIE ||' - '||NUME_SECTIE AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW||'~'||NR_SECTIE||'.'||ROWNUM  AS NR_ROW,
NR_ROW||'.'||ROWNUM   AS ORDINE,
'01111111111' AS DECIMAL_POS,
NUME_ROW,

CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN 100  ELSE COL1 END AS COL1, --COL2, COL3,COL4,COL5, COL6, COL7, COL8, COL9, COL10, COL11
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL2 END AS COL2, 
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL3 END AS COL3,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL4 END AS COL4,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL5 END AS COL5,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL6 END AS COL6,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL7 END AS COL7,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL8 END AS COL8,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL9 END AS COL9,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL10 END AS COL10,
CASE WHEN NR_ROW IN ('02','04','06','08','10') THEN NULL ELSE COL11 END AS COL11
FROM
(

SELECT 
    NR_ROW ,         
    NUME_ROW,  
    DENUMIRE AS NUME_SECTIE,
    CODUL AS NR_SECTIE, --NR_ROW,    
    ORDINE,
    COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11
   
   FROM(

SELECT 
   RR.NR_ROW,
   RR.NUME_ROW,
   CC.FULL_CODE,
  -- CC.DENUMIRE,
   CASE WHEN  CC.CODUL like '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
   CASE WHEN  Substr(CC.CODUL,1,1)||'0000' IS NOT NULL THEN Substr(CC.CODUL,1,1)||'0000' END AS CODUL, 
 --  CC.CODUL,
   CC.FULL_CODE AS ORDINE,
   
  
   
 SUM ( CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN ROUND (DECODE(RR.NR_ROW, 
         '01', (DD.COL0),
         '02', '100',
         '03',(DD.COL1),
         '04', '100',
         '05',(DD.COL2),
         '06', '100' ,
         '07',(DD.COL3),
         '08','100' ,
         '09',(DD.COL4),
         '10', '100' ),1) END)AS COL1,
 
 
  SUM( CASE WHEN DD.COL1 BETWEEN 0 AND 9 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN  (DECODE(RR.NR_ROW, 
         '01',( DD.COL0),
         '02',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL2,
  
  SUM( CASE WHEN DD.COL1 BETWEEN 10 AND 19 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',(DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL3,
  
   SUM( CASE WHEN DD.COL1 BETWEEN 20 AND 49 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',( DD.COL0 ),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL4,
         
  SUM( CASE WHEN DD.COL1 BETWEEN 0 AND 49 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',(DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL5,
  
  SUM( CASE WHEN DD.COL1 BETWEEN 50 AND 99 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',( DD.COL0 ),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL6,
 
   SUM( CASE WHEN DD.COL1 BETWEEN 100 AND 249 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',(DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL7,
         
   SUM( CASE WHEN DD.COL1 BETWEEN 50 AND 249 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',(DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL8,
         
   SUM( CASE WHEN DD.COL1 BETWEEN 250 AND 9999999 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',(DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL9,
         
            
   SUM( CASE WHEN DD.COL1 BETWEEN 250 AND 499 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',( DD.COL0),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL10,
   
            
   SUM( CASE WHEN DD.COL1 BETWEEN 500 AND 99999999 AND   C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN (DECODE(RR.NR_ROW, 
         '01',( DD.COL0 ),
         '02',(CASE WHEN  C.FULL_CODE LIKE '%'||CC.CODUL||';%'      THEN DD.CUIIO END),
         '03',(DD.COL1),
         '04',(CASE WHEN DD.COL1 IS NOT NULL      THEN DD.COL1 END),
         '05',(DD.COL2),
         '06',(CASE WHEN DD.COL2 IS NOT NULL      THEN DD.COL2 END),
         '07',(DD.COL3),
         '08',(CASE WHEN DD.COL3 IS NOT NULL      THEN DD.COL3 END),
         '09',(DD.COL4),
         '10',(CASE WHEN DD.COL4 IS NOT NULL      THEN DD.COL4 END))) END)AS COL11
-- 

    FROM 
  (
-------------------------------------------------------------------------------
SELECT 
 
 DISTINCT D.CUIIO, D.CAEM2, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,
 CIS2.NVAL(COUNT(DISTINCT CASE WHEN D.CAPITOL IN (1123,1124,1125,1126,1127,1128) THEN  D.CUIIO END))  AS COL0,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4) END))  AS COL1,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))  AS COL2,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))  AS COL3,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN CIS2.NVAL(D.COL1) END))    AS COL4 
 
FROM   
    CIS2.VW_DATA_ALL D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1123,1124,1125,1126,1127,1128) 

 GROUP BY D.CUIIO, D.CAEM2, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA
 
 HAVING
  
--  NVAL(SUM(COL1))+ NVAL(SUM(COL2))+ NVAL(SUM(COL3))+ NVAL(SUM(COL4))>0
  
  
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4) END))
 + 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))
 
 + 
 
 (
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))
 )
 
 + 
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN CIS2.NVAL(D.COL1) END))  
 
 
 >0
 
 
 )DD

-------------------------------------------------------------------------------

 INNER JOIN CIS2.VW_CL_CAEM2 C ON C.CODUL = DD.CAEM2                  
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON  (C.FULL_CODE LIKE '%'||CC.CODUL||';%') --AND C.GRUPA LIKE '%0000'-- (CC.FULL_CODE IN(SUBSTR(C.FULL_CODE,1,5)))--
--,SUBSTR(DC.FULL_CODE,1,18),SUBSTR(DC.FULL_CODE,1,9)))
 
  CROSS JOIN
  ( 
    SELECT 'Nr. de intreprinderi pe economie'  AS NUME_ROW, '01' AS NR_ROW, 'Col0' AS COL FROM DUAL UNION     
    SELECT 'Structura (%)'                     AS NUME_ROW, '02' AS NR_ROW, 'Col0' AS COL FROM DUAL UNION
    SELECT 'Numarul mediu de salariati'        AS NUME_ROW, '03' AS NR_ROW, 'Col1' AS COL FROM DUAL UNION 
    SELECT 'Structura (%)'                     AS NUME_ROW, '04' AS NR_ROW, 'Col1' AS COL FROM DUAL UNION 
    SELECT 'Venituri din vinzarie'             AS NUME_ROW, '05' AS NR_ROW, 'Col2' AS COL FROM DUAL UNION 
    SELECT 'Structura (%)'                     AS NUME_ROW, '06' AS NR_ROW, 'Col2' AS COL FROM DUAL UNION   
    SELECT 'Valoarea productiei'               AS NUME_ROW, '07' AS NR_ROW, 'Col3' AS COL FROM DUAL UNION 
    SELECT 'Structura (%)'                     AS NUME_ROW, '08' AS NR_ROW, 'Col3' AS COL FROM DUAL UNION 
    SELECT 'Valoarea adaugata bruta la costul factorilor'   AS NUME_ROW, '09' AS NR_ROW, 'Col4' AS COL FROM DUAL UNION   
    SELECT 'Structura (%)'                     AS NUME_ROW, '10' AS NR_ROW, 'Col4' AS COL FROM DUAL     

  ) RR 

         
 WHERE 
  (DD.FORM=:pFORM) AND
  (DD.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) 
 -- AND  C.CODUL LIKE '%0'
 
   GROUP BY
   CC.FULL_CODE,
    CC.DENUMIRE,
   CC.CODUL,
 --   Substr(CC.CODUL,1,1),
    RR.NR_ROW,       
    RR.NUME_ROW
    
    ORDER BY 
  --  Substr(CC.CODUL,1,1),
    CC.CODUL,RR.NR_ROW)
    WHERE DENUMIRE IS NOT NULL)