INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3,COL4,COL5, COL6, COL7
)


SELECT 
 
:PPERIOADA AS PERIOADA,
:PFORM AS FORM,
:PFORM_VERS AS FORM_VERS,
:PID_MDTABLE AS ID_MDTABLE,
:PCOD_CUATM AS COD_CUATM,    
'0' AS  NR_SECTIE,
'0' AS  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
CODUL||'~'||COL1||'1' AS NR_ROW,
ROWNUM AS ORDINE,--||'~'||ORDINE
'1111111' AS DECIMAL_POS,
 DENUMIRE AS NUME_ROW,
COL1, COL2, COL3,COL4,COL5, COL6, COL7
 FROM (

SELECT 
   CASE WHEN  CC.CODUL LIKE '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
   CASE WHEN  SUBSTR(CC.CODUL,1,1)||'0000' IS NOT NULL THEN SUBSTR(CC.CODUL,1,1)||'0000' END AS CODUL, 
   CC.FULL_CODE AS ORDINE,
   CIS2.NVAL(SUM(ROUND(D.CD,1)))    AS COL1,
   CIS2.NVAL(SUM(ROUND(D.COL2,1)))  AS COL2,
   CIS2.NVAL(SUM(ROUND(D.COL3,1)))  AS COL3,
   CIS2.NVAL(SUM(CASE WHEN D.R400_C BETWEEN 1 AND 5  THEN ROUND(D.R400_D,1) END ))  AS COL4,
   CIS2.NVAL(SUM(CASE WHEN D.R400_C BETWEEN 1 AND 20 THEN ROUND(D.R400_D,1) END ))  AS COL5,
   CIS2.NVAL(SUM(CASE WHEN D.R150_C BETWEEN 1 AND 5  THEN ROUND(D.R150_D,1) END ))  AS COL6,
   CIS2.NVAL(SUM(CASE WHEN D.R150_C BETWEEN 1 AND 20 THEN ROUND(D.R150_D,1) END ))  AS COL7
   FROM(   

SELECT 
   DISTINCT DD.CUIIO,   
   CASE WHEN  SUBSTR(C.CODUL,1,1)||'0000' IS NOT NULL THEN SUBSTR(C.CODUL,1,1)||'0000' END AS CODUL,      
   DD.PERIOADA,DD.CUATM_FULL,DD.FORM_VERS,DD.FORM,DD.CD,   COL3, COL2,
  
   ROW_NUMBER() OVER (PARTITION BY SUBSTR(C.CODUL,1,1) ORDER BY DD.R150_D  DESC NULLS LAST ) AS R150_C, DD.R150_D,
   ROW_NUMBER() OVER (PARTITION BY SUBSTR(C.CODUL,1,1) ORDER BY DD.R400_D  DESC NULLS LAST ) AS R400_C, DD.R400_D  
   
FROM(
   SELECT DISTINCT D.CUIIO, D.CUIIO_VERS,D.COL3, D.COL2,D.FORM, D.FORM_VERS, D.CUATM_FULL, D.PERIOADA,
   CASE WHEN D.CAEM2_ACTUALIZAT IS NULL THEN D.CAEM2 ELSE D.CAEM2_ACTUALIZAT END AS CAEM2, D.PERS, D.R150_D, D.R400_D,D.CD
       
   FROM(
SELECT  
 DISTINCT D.CUIIO, D.CUIIO_VERS, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,
 MAX(CASE WHEN D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4)) AS CAEM2, 
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4)  ELSE 0 END))  AS COL2,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))  AS COL3,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) AS CD,
 (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)
   
   ) AS PERS,
   
    (SELECT  CASE WHEN DD.COL1 IS NOT NULL THEN DD.COL1 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (58742) AND
   DD.CUIIO IN (D.CUIIO)) AS R150_D,
   
    (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (58791) AND
   DD.CUIIO IN (D.CUIIO)) AS R400_D
FROM   
    CIS2.VW_DATA_ALL_COEF D  
      
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:PPERIOADA     AND
  D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1124,1127,1129) -- and d.cuiio in (40381696)
  
 GROUP BY D.CUIIO,D.CUIIO_VERS, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA
 
 HAVING   
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) >0 
 )D) DD INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR(C.CODUL,2,4)  = DD.CAEM2
         
 WHERE 
  (DD.FORM=:pFORM) AND
  (DD.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) 
 
 )D
 INNER JOIN CIS2.VW_CL_CAEM2 C ON C.CODUL  = D.CODUL
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON  (C.FULL_CODE LIKE '%'||CC.CODUL||';%') 
   GROUP BY
   CC.FULL_CODE,
   CC.DENUMIRE,
   CC.CODUL
    
   ORDER BY 
   CC.CODUL

   
     ) ORDER BY ORDINE