--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3,COL4,COL5
--)

     
SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
CFP AS NR_SECTIE,
CFP ||'-'||CFP_DEN AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW AS NR_ROW,
ROWNUM AS ORDINE,
'00000' AS DECIMAL_POS,
NUME_ROW,
COL1, COL2, COL3,COL4,COL5
FROM
(
SELECT 
   CFF.CODUL AS CFP,
   CFF.DENUMIRE AS CFP_DEN,
   CC.FULL_CODE,
   CC.DENUMIRE AS NUME_ROW,
   CC.CODUL AS NR_ROW,
   CC.FULL_CODE AS ORDINE,

    
 ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERS BETWEEN 0 AND 49 OR D.PERS IS NULL  THEN D.CD END )),2)  AS COL1, 
 
 ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERS BETWEEN 0 AND 49 OR D.PERS IS NULL THEN D.COL2 END)),2)  AS COL2,
 ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERS BETWEEN 0 AND 49 OR D.PERS IS NULL THEN D.COL3 END)),3)  AS COL3,
 ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERS BETWEEN 0 AND 49 OR D.PERS IS NULL THEN D.COL4 END)),1)  AS COL4,
 ROUND(CIS2.NVAL(SUM(CASE WHEN D.PERS BETWEEN 0 AND 49 OR D.PERS IS NULL THEN D.COL5 END)),1)  AS COL5  
FROM   
   (
    
   
SELECT  
 DISTINCT D.CUIIO, D.CFP, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,
 MAX( CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,

 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4)  ELSE 0 END))  AS COL2,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))  AS COL3,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))  AS COL4,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN CIS2.NVAL(D.COL1) END))   AS COL5, 
 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) AS CD,
 (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS
 
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
 

 GROUP BY D.CUIIO,  D.CFP,D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA 
  
 HAVING 
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)>0
-- AND  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL4) END))BETWEEN 0 AND 249
 
 )  D
-------------------------------------------------------------------------------    


 INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR(C.CODUL,2,4)  = CASE WHEN D.CAEM2_ACTUALIZAT IS NULL THEN D.CAEM2 ELSE D.CAEM2_ACTUALIZAT END                   
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 
 INNER JOIN CIS2.VW_CL_CFP CF ON CF.CODUL = D.CFP                 
 INNER JOIN CIS2.VW_CL_CFP CFF ON (CF.FULL_CODE LIKE '%'||CFF.CODUL||';%')
   
 WHERE 
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  D.PERIOADA IN (:pPERIOADA) AND
  SUBSTR(C.CODUL,1,1) ='C' AND 
  CFF.CODUL IN ('00','11','14','20','22','28')
 
   GROUP BY
    CC.FULL_CODE,
    CC.DENUMIRE,
    CC.CODUL,
    CFF.CODUL,
    CFF.DENUMIRE
    
  
ORDER BY  
CFF.CODUL,CC.CODUL)
WHERE NR_ROW LIKE 'C%'