--
--BEGIN
--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3,COL4,COL5
--)

SELECT 
 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
 '0' AS  NR_SECTIE,
 '0' AS  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW,
ROWNUM AS ORDINE,--||'~'||ORDINE
'22222' AS DECIMAL_POS,

NUME_ROW,
ROUND(COL1,2) AS COL1, 
ROUND(COL2,2) AS COL2,
ROUND(COL3,2) AS COL3,
ROUND(COL4,2) AS COL4,
ROUND(COL5,2) AS COL5
     FROM (

--SELECT 
--:pPERIOADA AS PERIOADA,
--:pFORM AS FORM,
--:pFORM_VERS AS FORM_VERS,
--:pID_MDTABLE AS ID_MDTABLE,
--:pCOD_CUATM AS COD_CUATM,    
--  NR_SECTIE,
--  NUME_SECTIE,
--'0' AS NR_SECTIE1,
--'0' AS NUME_SECTIE1,
--'0' AS NR_SECTIE2,
--'0' AS NUME_SECTIE2, 
--NR_ROW||'~'|| NR_SECTIE||'1' AS NR_ROW,
-- 1||ORDINE AS ORDINE,
--'22222' AS DECIMAL_POS,
--NUME_ROW,
--ROUND(COL15,2) AS COL1, 
--ROUND(COL30,2) AS COL2,
--ROUND(COL31,2) AS COL3,
--ROUND(COL46,2) AS COL4,
--ROUND(COL5,2) AS COL5
--FROM
--(
--SELECT 
--    NR_ROW AS NR_SECTIE ,         
--    NUME_ROW AS NUME_SECTIE,  
--    DENUMIRE AS NUME_ROW,
--    CODUL AS NR_ROW,    
--    ORDINE,
--ROUND(COL15,2) AS COL15, 
--ROUND(COL30,2) AS COL30,
--ROUND(COL31,2) AS COL31,
--ROUND(COL46,2) AS COL46,
--ROUND(COL5,2) AS COL5
--   
--   FROM(
--
--SELECT 
--   '05' AS NR_ROW,
--   'Intreprinderile cu numarul de salariati 0-249 persoane' AS NUME_ROW,
--   CC.FULL_CODE,
--   CASE WHEN  CC.CODUL like '%0000' THEN CC.DENUMIRE END AS DENUMIRE,   
--   CASE WHEN  Substr(CC.CODUL,1,1)||'0000' IS NOT NULL THEN Substr(CC.CODUL,1,1)||'0000' END AS codul, 
--   '05'||'~'||CC.FULL_CODE AS ORDINE,
--   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('150') THEN  DR.COL1 END) AS COL15,
--   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('270') THEN  DR.COL1 END) AS COL30,
--   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('280') THEN  DR.COL1 END) AS COL31,
--   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('295') THEN  DR.COL1 END) AS COL46,
-- (CIS2.NVAL(SUM(CASE WHEN  DR.RIND IN ('340') THEN CIS2.NVAL(DR.COL2) END))-
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('340') THEN CIS2.NVAL(DR.COL1) END)))-
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('220') THEN CIS2.NVAL(DR.COL1) END))-
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('240') THEN CIS2.NVAL(DR.COL1) END))-
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('290') THEN CIS2.NVAL(DR.COL1) END))+
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('294') THEN CIS2.NVAL(DR.COL1) END))+
-- CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('180') THEN CIS2.NVAL(DR.COL1) END))  AS COL5
-- FROM
--    CIS2.VW_DATA_ALL_COEF DR INNER JOIN
--    
--    (
---------------------------------------------------------------------------------     
--         SELECT 
--    DISTINCT D.CUIIO,D.CUIIO_VERS, D.CUATM,
--    MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
--    MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
--    CASE WHEN MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) IS NULL THEN  MAX(SUBSTR(D.CAEM2,2,4)) 
--    ELSE MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) END  CAEM2_MOD,
--    
--    D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ,
--    SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL0 ,  
--    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL4,
--    SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)  AS CD,
--    (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
-- FROM
--   CIS2.DATA_ALL DD
-- WHERE
--   DD.PERIOADA IN (D.PERIOADA) AND
--   DD.FORM=D.FORM AND
--   DD.ID_MD IN (69986) AND
--   DD.CUIIO IN (D.CUIIO)) AS PERS  
--FROM   
--    CIS2.VW_DATA_ALL_COEF D       
--WHERE
--  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
--  D.PERIOADA =:pPERIOADA AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
--  D.CAPITOL IN (100,1123,1127,1129) 
--  AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','400','CD','8')
-- --AND  D.CUIIO=40075114
-- GROUP BY D.CUIIO,D.CUIIO_VERS, D.CUATM,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ
-- 
-- HAVING
--  SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)>0
--
--) DD ON DR.CUIIO=DD.CUIIO AND DR.CUIIO_VERS=DD.CUIIO_VERS
--
---- INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR(C.CODUL,2,4)  = CASE WHEN DD.CAEM2_ACTUALIZAT IS NULL THEN DD.CAEM2 ELSE DD.CAEM2_ACTUALIZAT END                 
-- 
-- INNER JOIN (
-- SELECT
--CODUL, 
--DENUMIRE, 
--GRUPA, 
--ORDINE, 
--FULL_CODE, 
--NUM_CODE, 
--PRIM                
--                FROM  CIS2.VW_CL_CAEM2
--                
--               
--                
--                WHERE 
--                CODUL LIKE 'C%'
--                OR CODUL LIKE 'B%'
--                OR CODUL LIKE 'D%'
--                OR CODUL LIKE 'E%'
--                OR CODUL LIKE 'F%'
--                OR CODUL LIKE 'G%'
--                OR CODUL LIKE 'H%'
--                OR CODUL LIKE 'I%'
--                OR CODUL LIKE 'J%'
--                OR CODUL LIKE 'L%'
--                OR CODUL LIKE 'M%'
--                OR CODUL LIKE 'N%'
--                OR CODUL LIKE 'S%'
-- ) C ON SUBSTR(C.CODUL,2,4)  = DD.CAEM2_MOD 
-- INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
-- 
--
--         
-- WHERE 
--  (DR.FORM=:pFORM) AND
--  (DR.FORM_VERS=:pFORM_VERS) AND
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  (DR.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
--  DR.PERIOADA IN (:pPERIOADA) 
-- -- AND  C.CODUL LIKE '%00'
-- 
-- AND ( SUBSTR(CC.CODUL,1,3)
--IN (
--'B00','B06','B08','B09',
--'C00','C10','C11','C12','C13','C14','C15','C16','C17','C18','C19','C20','C21','C22','C23','C24','C25','C26','C27','C28','C29','C30','C31','C32','C33',
--'D00','D35',
--'E00','E36','E37','E38','E39',
--'F00','F41','F42','F43',
--'G00','G45','G46','G47','G48',
--'H00','H49','H50','H51','H52','H53',
--'I00','I55','I56',
--'J00','J58','J59','J60','J61','J62','J63',
--'M00','M69','M70','M71','M72','M73','M74','M75',
--'N00','N77','N78','N79','N80','N81','N82',
--'S00','S94','S95','S96',
--'L00','L68'
--) )
--
--AND CC.CODUL LIKE '%00'
-- -- AND DR.CUIIO = 1129894
--   GROUP BY
--    CC.FULL_CODE,
--   CC.DENUMIRE,
--    CC.CODUL
----    RR.NR_ROW,       
----    RR.NUME_ROW
--     
--    ORDER BY 
----     RR.NR_ROW,
--     CC.CODUL)
--     
--     WHERE DENUMIRE IS NOT NULL)
     
     
     --UNION 
     
     SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
  NR_SECTIE,
  NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
NR_ROW||'~'|| NR_SECTIE||'2' AS NR_ROW,
2||ORDINE AS ORDINE,
'22222' AS DECIMAL_POS,
NUME_ROW,
ROUND(COL15,2) AS COL1, 
ROUND(COL30,2) AS COL2,
ROUND(COL31,2) AS COL3,
ROUND(COL46,2) AS COL4,
ROUND(COL5,2) AS COL5
FROM
(
 SELECT
D.NR_ROW AS NR_SECTIE,         
D.NUME_ROW AS NUME_SECTIE,
D.CODUL AS NR_ROW,
ORDINE,
D.DENUMIRE AS NUME_ROW,
ROUND(COL15,2) AS COL15, 
ROUND(COL30,2) AS COL30,
ROUND(COL31,2) AS COL31,
ROUND(COL46,2) AS COL46,
ROUND(COL5,2) AS COL5

FROM(
SELECT 
   '05' AS NR_ROW,
   'Intreprinderile cu numarul de salariati 0-249 persoane' AS NUME_ROW,
   CC.FULL_CODE,
   CC.DENUMIRE,
   CC.CODUL,
   '05'||'~'||CC.FULL_CODE AS ORDINE,
   


   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('150') THEN  DR.COL1 END) AS COL15,
   
   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('270') THEN  DR.COL1 END) AS COL30,
   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('280') THEN  DR.COL1 END) AS COL31,
 
   SUM(CASE WHEN (DD.PERS BETWEEN 0 AND 249 OR DD.PERS IS NULL ) AND  DR.RIND IN ('295') THEN  DR.COL1 END) AS COL46,
 (CIS2.NVAL(SUM(CASE WHEN  DR.RIND IN ('340') THEN CIS2.NVAL(DR.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('340') THEN CIS2.NVAL(DR.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('220') THEN CIS2.NVAL(DR.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('240') THEN CIS2.NVAL(DR.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('290') THEN CIS2.NVAL(DR.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('294') THEN CIS2.NVAL(DR.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN   DR.RIND IN ('180') THEN CIS2.NVAL(DR.COL1) END))  AS COL5
                                                                                                                                                                          
                
    FROM
    
    
    CIS2.VW_DATA_ALL_COEF DR INNER JOIN
    
    (
-------------------------------------------------------------------------------     
  SELECT 
    DISTINCT D.CUIIO,D.CUIIO_VERS, 
    --D.CUATM,
    --MAX( CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  AS CAEM2_ACTUALIZAT,
 --MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
     CASE WHEN MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) IS NULL THEN  MAX(SUBSTR(D.CAEM2,2,4)) 
    ELSE MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) END  CAEM2_MOD,
    D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ,
    SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL0 ,  
    SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL4,
    SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)  AS CD,
    (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS  
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN  (100,1123,1127,1129) 
  AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','400','CD','8')
-- AND  D.CUIIO=40075114
 GROUP BY D.CUIIO,D.CUIIO_VERS, D.CUATM,D.PERIOADA,D.FORM_VERS,D.FORM,CUATM_FULL,D.CFOJ
 
 HAVING
 
  SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END) >0

) DD ON DR.CUIIO=DD.CUIIO AND DR.CUIIO_VERS=DD.CUIIO_VERS
-------------------------------------------------------------------------------    

-- INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR( C.CODUL,2,4)  = CASE WHEN DD.CAEM2_ACTUALIZAT IS NULL THEN DD.CAEM2 ELSE DD.CAEM2_ACTUALIZAT END     
 INNER JOIN (
 SELECT
CODUL, 
DENUMIRE, 
GRUPA, 
ORDINE, 
FULL_CODE, 
NUM_CODE, 
PRIM                
                FROM  CIS2.VW_CL_CAEM2
                
               
                
                WHERE 
                CODUL LIKE 'C%'
                OR CODUL LIKE 'B%'
                OR CODUL LIKE 'D%'
                OR CODUL LIKE 'E%'
                OR CODUL LIKE 'F%'
                OR CODUL LIKE 'G%'
                OR CODUL LIKE 'H%'
                OR CODUL LIKE 'I%'
                OR CODUL LIKE 'J%'
                OR CODUL LIKE 'L%'
                OR CODUL LIKE 'M%'
                OR CODUL LIKE 'N%'
                OR CODUL LIKE 'S%'
 ) C ON SUBSTR(C.CODUL,2,4)  = DD.CAEM2_MOD               
 INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 

         
 WHERE 
  (DR.FORM=:pFORM) AND
  (DR.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DR.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DR.PERIOADA IN (:pPERIOADA) AND 
--  AND  C.CODUL LIKE '%B00'
( SUBSTR(CC.CODUL,1,3)
IN (
'B00','B06','B08','B09',
'C00','C10','C11','C12','C13','C14','C15','C16','C17','C18','C19','C20','C21','C22','C23','C24','C25','C26','C27','C28','C29','C30','C31','C32','C33',
'D00','D35',
'E00','E36','E37','E38','E39',
'F00','F41','F42','F43',
'G00','G45','G46','G47','G48',
'H00','H49','H50','H51','H52','H53',
'I00','I55','I56',
'J00','J58','J59','J60','J61','J62','J63',
'M00','M69','M70','M71','M72','M73','M74','M75',
'N00','N77','N78','N79','N80','N81','N82',
'S00','S94','S95','S96',
'L00','L68'
) )

AND CC.CODUL LIKE '%00'
  AND DR.CUIIO = 1129894
   GROUP BY
    CC.FULL_CODE,
    CC.DENUMIRE,
    CC.CODUL
--    RR.NR_ROW,       
--    RR.NUME_ROW
    
    ORDER BY 
--     RR.NR_ROW,
     CC.CODUL
     ) D
     
      WHERE
        1=1 
        
        
        )
     ORDER BY ORDINE)
     ; END; 