


SELECT *
FROM USER_BANCU.TRIM_4_29_AGRO;

        UPDATE  USER_BANCU.TRIM_4_29_AGRO
        SET
         CUATM = CASE WHEN (LENGTH(CUATM) = 6 AND (SUBSTR(CUATM,1,1) = 1  OR SUBSTR(CUATM,1,1) = 3 )) THEN '0'||CUATM ELSE CUATM END