SELECT
  D.CUIIO,
  MAX(D.PACHET) PACHET,
  CI.ITEM_CODE SERV_CODUL,
  CI.NAME||' - '||MAX(R.DENUMIRE) DENUMIRE,
  CI.A01 SERV_CODUL_OLD,
  SUM(CASE WHEN D.PERIOADA IN (1052,1053,1054) AND  MR.CAPITOL IN (405) AND MR.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  
  (SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050) AND MR.CAPITOL IN (405) AND MR.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050) AND MR.CAPITOL IN (406) AND MR.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.DATA_ALL D 
        INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
        INNER JOIN CIS2.VW_CL_CUATM C ON R.CUATM = C.CODUL
        INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
        INNER  JOIN MD_CAPITOL MC ON MR.CAPITOL = MC.CAPITOL AND MR.CAPITOL_VERS = MC.CAPITOL_VERS
  

  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (1048,1049,1050)  THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (1048,1049,1050) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 

 ((D.PERIOADA IN  (1052,1053,1054)) OR (D.PERIOADA IN (1048,1049,1050)))  AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  --(D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   (C.FULL_CODE LIKE '%'||:pCOD_CUATM||';%') AND
  
  MR.FORM IN (44)
  AND  MR.CAPITOL IN (405,406) 
  
 --  AND D.CUIIO = 20282383 
  


GROUP BY
  D.CUIIO, 
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
  
  
HAVING

SUM(CASE WHEN D.PERIOADA IN (1052,1053,1054)   AND  MR.CAPITOL IN (405) AND MR.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) <> 0