--DECLARE
--
--  CURSOR C IS
--
--SELECT 
--    DF.PERIOADA,
--    DF.FORM,
--    DF.FORM_VERS,
--    DF.ID_MDTABLE,
--    DF.COD_CUATM,
--    DF.NR_SECTIE,
--    DF.NUME_SECTIE,
--    DF.NR_SECTIE1,
--    DF.NUME_SECTIE1,
--    DF.NR_SECTIE2,
--    DF.NUME_SECTIE2,
--    DF.NR_ROW NR_ROW,
--    DF.ORDINE,
--    DF.DECIMAL_POS,
--    DF.NUME_ROW,
--    DF.COL1,
--    DF.COL2,
--    DF.COL3,
--    DF.COL4
--   
--   
--   FROM 
--(





SELECT 
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
   '0' AS  NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     CUIIO||'-'||SERV_CODUL||'-'||SERV_CODUL_OLD||'~'||ROWNUM NR_ROW,
     ROWNUM  AS ORDINE,
     '00000' AS DECIMAL_POS,
     CUIIO||'-'||DENUMIRE NUME_ROW,
   --  PACHET     COL1,
     REPLACE(SERV_CODUL,'.','')   COL1,
   
    
     COL1 COL2,
     COL2 COL3,
     COL3 COL4
     FROM

(

SELECT 
1 ORDINE,
CUIIO,
PACHET,
'9999999' SERV_CODUL,
SERV_CODUL_OLD,
NULL DENUMIRE,
     SUM(COL1)  COL1,
     COL2 COL2,
      NVAL(SUM(COL1)) - NVAL(COL2) AS COL3
    
     FROM 
     (
SELECT
  D.CUIIO,
  MAX(D.PACHET) PACHET,
  CI.ITEM_CODE SERV_CODUL,
  CI.NAME||' - '||MAX(R.DENUMIRE) DENUMIRE,
  CI.A01 SERV_CODUL_OLD,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  --(D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND    
 ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
   AND D.CUIIO = 20282383 
  


GROUP BY
  D.CUIIO, 
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
  
  
HAVING

SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA  AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) <> 0

UNION
SELECT DISTINCT
  CUIIO,
  MAX(PACHET) PACHET,
  MAX(ITEM_CODE) SERV_CODUL,
  MAX(NAME) DENUMIRE,
  A01 SERV_CODUL_OLD,
  SUM(COL1) AS COL1,
  COL2 
FROM
(SELECT
  D.CUIIO,
   MAX(D.PACHET) PACHET,
  CI.ITEM_CODE,
   CI.NAME||' - '||MAX(R.DENUMIRE)  NAME,
  CI.A01,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
   INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  --(D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND
   ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
   AND D.CUIIO = 20282383 
  



GROUP BY
  CI.ITEM_CODE,
  D.CUIIO,
  CI.NAME,
  CI.A01

ORDER BY
  D.CUIIO,
  CI.A01,
  CI.ITEM_CODE
)
GROUP BY
  CUIIO,
  A01,
  COL2
HAVING
  SUM(COL1) = 0

  

  
   ORDER BY

    CUIIO,
    SERV_CODUL
    
   )



GROUP BY 
CUIIO,
PACHET,

SERV_CODUL_OLD,
COL2

HAVING 
(
NVAL(SUM(COL1)) - NVAL(COL2) > 500000
OR 
NVAL(COL2) - NVAL(SUM(COL1)) > 500000
 )





UNION 

SELECT 
2 ORDINE,
CUIIO,
PACHET,
SERV_CODUL,
SERV_CODUL_OLD,
DENUMIRE,    
     COL1 COL1,
     COL2 COL2,
     NVAL(COL1) - NVAL(COL2) AS COL3
     
     FROM 
     (
SELECT
  D.CUIIO,
  
  MAX(D.PACHET) PACHET,
  CI.ITEM_CODE SERV_CODUL,
  CI.NAME||' - '||MAX(R.DENUMIRE) DENUMIRE,
  CI.A01 SERV_CODUL_OLD,
  SUM(CASE WHEN  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
 -- (D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND
 
  ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
 AND D.CUIIO = 20282383 

  
GROUP BY
  D.CUIIO, 
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
  
  
HAVING

SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) <> 0

UNION
SELECT DISTINCT
  CUIIO,
  MAX(PACHET) PACHET,
  MAX(ITEM_CODE) SERV_CODUL,
  MAX(NAME) DENUMIRE,
  A01 SERV_CODUL_OLD,
  SUM(COL1) AS COL1,
  COL2 
FROM
(SELECT
  D.CUIIO,
   MAX(D.PACHET) PACHET,
  CI.ITEM_CODE,
   CI.NAME||' - '||MAX(R.DENUMIRE)  NAME,
  CI.A01,
  SUM(CASE WHEN D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA  AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4 AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
   INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (:pPERIOADA-4) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
 -- (D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND    
  ((D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA) OR (D.PERIOADA BETWEEN (FLOOR(:pPERIOADA/4)*4)-4 AND :pPERIOADA-4))  AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
   AND D.CUIIO = 20282383 
  

 
GROUP BY
  CI.ITEM_CODE,
  D.CUIIO,
  CI.NAME,
  CI.A01

ORDER BY
  D.CUIIO,
  CI.A01,
  CI.ITEM_CODE
)
GROUP BY
  CUIIO,
  A01,
  COL2
HAVING
  SUM(COL1) = 0
  
  
   ORDER BY

    CUIIO,
    SERV_CODUL
    
   )
   
   
   GROUP BY 
CUIIO,
PACHET,
SERV_CODUL,
SERV_CODUL_OLD,
DENUMIRE,    
     COL1,
     COL2
   HAVING
   
   NVAL(COL1) - NVAL(COL2) > 500000
   
   OR 
   
   NVAL(COL2) - NVAL(COL1) > 500000




ORDER BY 
CUIIO,
ORDINE,
SERV_CODUL,
SERV_CODUL_OLD

)




--) DF
--
--;
--   
--    BEGIN
--
--  FOR CR IN C
--  
--  LOOP
--    INSERT INTO  --USER_BANCU.TABLE_OUT_TEST 
--    
--     CIS2.TABLE_OUT
--    (
--      PERIOADA,
--      FORM,
--      FORM_VERS,
--
--      ID_MDTABLE,
--      COD_CUATM,
--      NR_SECTIE,
--      NUME_SECTIE,
--      NR_SECTIE1,
--      NUME_SECTIE1,
--      NR_SECTIE2,
--      NUME_SECTIE2,
--      NR_ROW,
--      ORDINE,
--      DECIMAL_POS,
--      NUME_ROW,
--       
--      COL1, COL2, COL3,  COL4
--    )
--    VALUES
--    (
--      CR.PERIOADA,
--      CR.FORM,
--      CR.FORM_VERS,
--      CR.ID_MDTABLE,
--      CR.COD_CUATM,
--      CR.NR_SECTIE,
--      CR.NUME_SECTIE,
--      CR.NR_SECTIE1,
--      CR.NUME_SECTIE1,
--      CR.NR_SECTIE2,
--      CR.NUME_SECTIE2,
--      CR.NR_ROW,
--      CR.ORDINE,
--      CR.DECIMAL_POS,
--      CR.NUME_ROW,
--       
--      CR.COL1, CR.COL2, CR.COL3, CR.COL4
--    );
--  END LOOP;
--END;