

SELECT B.* 
FROM
(
SELECT
   CCF.CODUL NR_ROW,
   CCF.DENUMIRE NUME_ROW,
   CASE WHEN ltrim(TO_NUMBER(CC.codul),'0') IS NULL THEN '0' ELSE ltrim(TO_NUMBER(CC.codul),'0')  END   CODUL,
   CC.DENUMIRE,

  
   CC.ORDINE,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL1) ELSE 0 END ) COL1,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL2) ELSE 0 END ) COL2,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL2) END)  COL3,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL3) END)  COL4,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL3) ELSE 0 END ) COL5,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL7) ELSE 0 END ) COL6,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL8) ELSE 0 END ) COL7,
   SUM (CASE WHEN 1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8) END) COL8,
   SUM (CASE WHEN 1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL9) END) COL9,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL9) ELSE 0 END ) COL10,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL10) ELSE 0 END ) COL11,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL11) ELSE 0 END ) COL12,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL11) END) COL13,
   SUM (CASE WHEN 1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL12) END)  COL14,
   SUM (CASE WHEN  1=1 AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN CIS2.NVAL(D.COL12) ELSE 0 END ) COL15

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','070')
     
       )   
       
       ORDER BY 
       MR.ORDINE
 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
     INNER JOIN  (SELECT  
        
        RINDOUT CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13915) C  ON  (ltrim(TO_NUMBER(C.codul),'0') =  DD.RIND_MOD) 
     
    CROSS JOIN   (SELECT  
        
        TRIM(RINDOUT) CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13915)   CC 



 INNER JOIN CIS2.VW_CL_CFP CF ON (CF.CODUL = D.CFP)
    INNER JOIN CIS2.VW_CL_CFP CCF ON (CF.FULL_CODE LIKE '%'||CCF.CODUL||';%') 
  
    
 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) 

 AND  CCF.CODUL IN ('00','11','14')

  GROUP BY 


  CCF.CODUL,
  CCF.DENUMIRE,
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  CC.ORDINE
   
  
  
  ORDER BY
  CC.ORDINE
  
   ) B
  
  
  
  

