SELECT
   CC.ITEM_CODE CODUL,
   CC.NAME DENUMIRE,
   CC.ITEM_PATH FULL_CODE,
   CC.ITEM_PARENT,
   SUM (CIS2.NVAL(D.COL1)) COL1,
   SUM (CIS2.NVAL(D.COL2)) COL2,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL2) END)  COL3,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL3) END)  COL4,
   SUM (CIS2.NVAL(D.COL3)) COL5,
   SUM (CIS2.NVAL(D.COL7)) COL6,
   SUM (CIS2.NVAL(D.COL8)) COL7,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8) END) COL8,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL9) END) COL9,
   SUM (CIS2.NVAL(D.COL9)) COL10,
   SUM (CIS2.NVAL(D.COL10)) COL11,
   SUM (CIS2.NVAL(D.COL11)) COL12,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL11) END) COL13,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL12) END)  COL14,
   SUM (CIS2.NVAL(D.COL12)) COL15

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,

CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0')
  ELSE TO_CHAR(SUBSTR(D.RIND, 2))
END AS RIND_MOD,

    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
    
  
FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','070')
     
       )   
       
       
       
       ORDER BY 
       MR.ORDINE
 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
 
 INNER JOIN  CIS2.VW_CLS_CLASS_ITEM C  ON  (C.ITEM_CODE =  DD.RIND_MOD AND  C.CLASS_CODE = 'SPEC_2EDU' ) 
     
 INNER JOIN  CIS2.VW_CLS_CLASS_ITEM   CC ON (C.ITEM_PATH LIKE '%'||CC.ITEM_CODE||';%'  AND  CC.CLASS_CODE = 'SPEC_2EDU'  )




    
 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) 
--  

 

 
  
  GROUP BY 


  CC.ITEM_CODE,
  CC.NAME,
  CC.ITEM_PATH,
  CC.SHOW_ORDER,
  CC.ITEM_PARENT 
  
  
  
  UNION 
  
  SELECT
   CC.ITEM_CODE CODUL,
   CC.NAME DENUMIRE,
   CC.ITEM_PATH FULL_CODE,
   CC.ITEM_PARENT,
   SUM (CIS2.NVAL(D.COL1)) COL1,
   SUM (CIS2.NVAL(D.COL2)) COL2,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL2) END)  COL3,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL1)-CIS2.NVAL(D.COL3) END)  COL4,
   SUM (CIS2.NVAL(D.COL3)) COL5,
   SUM (CIS2.NVAL(D.COL7)) COL6,
   SUM (CIS2.NVAL(D.COL8)) COL7,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL8) END) COL8,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL7)-CIS2.NVAL(D.COL9) END) COL9,
   SUM (CIS2.NVAL(D.COL9)) COL10,
   SUM (CIS2.NVAL(D.COL10)) COL11,
   SUM (CIS2.NVAL(D.COL11)) COL12,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL11) END) COL13,
   SUM (CASE WHEN 1=1 THEN CIS2.NVAL(D.COL10)-CIS2.NVAL(D.COL12) END)  COL14,
   SUM (CIS2.NVAL(D.COL12)) COL15

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,

CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0')
  ELSE TO_CHAR(SUBSTR(D.RIND, 2))
END AS RIND_MOD,

    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
    
  
FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','070')
     
       )   
       
       
       
       ORDER BY 
       MR.ORDINE
 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
 
 INNER JOIN  CIS2.VW_CLS_CLASS_ITEM C  ON  (C.ITEM_CODE =  DD.RIND_MOD AND  C.CLASS_CODE = 'SPEC_2EDU' ) 
     
 INNER JOIN  CIS2.VW_CLS_CLASS_ITEM   CC ON (C.ITEM_PATH LIKE '%'||CC.ITEM_CODE||';%'  AND  CC.CLASS_CODE = 'SPEC_2EDU'  )




    
 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) 
--  
  AND CC.ITEM_CODE = '2111.102111.5'  
 

 
  
  GROUP BY 


  CC.ITEM_CODE,
  CC.NAME,
  CC.ITEM_PATH,
  CC.SHOW_ORDER,
  CC.ITEM_PARENT 
  

  


  
  ORDER BY 
  FULL_CODE
  

