SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
MAX(CASE WHEN D.CAPITOL IN (1129)  AND D.RIND IN ('8') THEN  D.COL31 ELSE NULL END ) CAEM_ACT,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('320') THEN  D.COL1 ELSE NULL END ) RIND_320_COL1,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('320') THEN  D.COL2 ELSE NULL END ) RIND_320_COL2, 
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('330') THEN  D.COL1 ELSE NULL END ) RIND_330_COL1,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('330') THEN  D.COL2 ELSE NULL END ) RIND_330_COL2, 
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('340') THEN  D.COL1 ELSE NULL END ) RIND_340_COL1,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('340') THEN  D.COL2 ELSE NULL END ) RIND_340_COL2, 
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('350') THEN  D.COL1 ELSE NULL END ) RIND_350_COL1,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('350') THEN  D.COL2 ELSE NULL END ) RIND_350_COL2 



FROM   
    CIS2.VW_DATA_ALL D    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1126,1129) 
--  AND D.CUIIO = 68179

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2