SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
MAX(CASE WHEN D.CAPITOL IN (1129)  AND D.RIND IN ('8') THEN  D.COL31 ELSE NULL END ) CAEM_ACT,
SUM(CASE WHEN D.CAPITOL IN (1178)  AND D.RIND IN ('600') THEN  D.COL1 ELSE NULL END ) RIND_600,
SUM(CASE WHEN D.CAPITOL IN (1178)  AND D.RIND IN ('610') THEN  D.COL1 ELSE NULL END ) RIND_610,
SUM(CASE WHEN D.CAPITOL IN (1178)  AND D.RIND IN ('620') THEN  D.COL1 ELSE NULL END ) RIND_620,
SUM(CASE WHEN D.CAPITOL IN (1178)  AND D.RIND IN ('630') THEN  D.COL1 ELSE NULL END ) RIND_630,
SUM(CASE WHEN D.CAPITOL IN (1178)  AND D.RIND IN ('640') THEN  D.COL1 ELSE NULL END ) RIND_640



FROM   
    CIS2.VW_DATA_ALL_COEF D    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1178,1129) 
--  AND D.CUIIO = 68179

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2

ORDER BY
D.CUIIO