SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
MAX(CASE WHEN D.CAPITOL IN (1129)  AND D.RIND IN ('8') THEN  D.COL31 ELSE NULL END ) CAEM_ACT,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('700') THEN  D.COL1 ELSE NULL END ) RIND_700,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('710') THEN  D.COL1 ELSE NULL END ) RIND_710,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('720') THEN  D.COL1 ELSE NULL END ) RIND_720,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('721') THEN  D.COL1 ELSE NULL END ) RIND_721,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('730') THEN  D.COL1 ELSE NULL END ) RIND_730,

SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('731') THEN  D.COL1 ELSE NULL END ) RIND_731,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('732') THEN  D.COL1 ELSE NULL END ) RIND_732,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('733') THEN  D.COL1 ELSE NULL END ) RIND_733,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('740') THEN  D.COL1 ELSE NULL END ) RIND_740,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('750') THEN  D.COL1 ELSE NULL END ) RIND_750,

SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('760') THEN  D.COL1 ELSE NULL END ) RIND_760,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('770') THEN  D.COL1 ELSE NULL END ) RIND_770,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('771') THEN  D.COL1 ELSE NULL END ) RIND_771,
SUM(CASE WHEN D.CAPITOL IN (1179)  AND D.RIND IN ('772') THEN  D.COL1 ELSE NULL END ) RIND_772


FROM   
    CIS2.VW_DATA_ALL D    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1179,1129) 
--  AND D.CUIIO = 68179

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2

ORDER BY
D.CUIIO