SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
MAX(CASE WHEN D.CAPITOL IN (1129)  AND D.RIND IN ('8') THEN  D.COL31 ELSE NULL END ) CAEM_ACT,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('100') THEN  D.COL1 ELSE NULL END ) RIND_100,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('110') THEN  D.COL1 ELSE NULL END ) RIND_110,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('111') THEN  D.COL1 ELSE NULL END ) RIND_111,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('112') THEN  D.COL1 ELSE NULL END ) RIND_112,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('120') THEN  D.COL1 ELSE NULL END ) RIND_120,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('121') THEN  D.COL1 ELSE NULL END ) RIND_121,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('122') THEN  D.COL1 ELSE NULL END ) RIND_122,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('130') THEN  D.COL1 ELSE NULL END ) RIND_130,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('140') THEN  D.COL1 ELSE NULL END ) RIND_140,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('150') THEN  D.COL1 ELSE NULL END ) RIND_150,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('151') THEN  D.COL1 ELSE NULL END ) RIND_151,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('160') THEN  D.COL1 ELSE NULL END ) RIND_160,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('170') THEN  D.COL1 ELSE NULL END ) RIND_170,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('180') THEN  D.COL1 ELSE NULL END ) RIND_180


FROM   
    CIS2.VW_DATA_ALL_COEF D    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1124,1129) 
  AND D.CUIIO = 38877935



GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2

ORDER BY
D.CUIIO