
SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
CASE WHEN     MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END) CAEM_ACT, END)) END AS CAEM_ACT
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN D.COL8 ELSE NULL END) RIND_500_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN D.COL9 ELSE NULL END) RIND_500_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN D.COL10 ELSE NULL END) RIND_500_COL3, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('510') THEN D.COL33 ELSE NULL END) RIND_510_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('510') THEN D.COL37 ELSE NULL END) RIND_510_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('510') THEN D.COL8 ELSE NULL END)  RIND_510_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('510') THEN D.COL9 ELSE NULL END)  RIND_510_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('510') THEN D.COL10 ELSE NULL END) RIND_510_COL3, END)) END AS
    
CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('511') THEN D.COL33 ELSE NULL END) RIND_511_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('511') THEN D.COL37 ELSE NULL END) RIND_511_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('511') THEN D.COL8 ELSE NULL END)  RIND_511_COL1,------------------------------ END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('511') THEN D.COL9 ELSE NULL END)  RIND_511_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('511') THEN D.COL10 ELSE NULL END) RIND_511_COL3, END)) END AS
    
    
CASE WHEN             SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('512') THEN D.COL33 ELSE NULL END) RIND_512_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('512') THEN D.COL37 ELSE NULL END) RIND_512_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('512') THEN D.COL8 ELSE NULL END)  RIND_512_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('512') THEN D.COL9 ELSE NULL END)  RIND_512_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('512') THEN D.COL10 ELSE NULL END) RIND_512_COL3, END)) END AS
    
    
CASE WHEN                 SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('513') THEN D.COL33 ELSE NULL END) RIND_513_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('513') THEN D.COL37 ELSE NULL END) RIND_513_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('513') THEN D.COL8 ELSE NULL END)  RIND_513_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('513') THEN D.COL9 ELSE NULL END)  RIND_513_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('513') THEN D.COL10 ELSE NULL END) RIND_513_COL3, END)) END AS
    
CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('514') THEN D.COL33 ELSE NULL END) RIND_514_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('514') THEN D.COL37 ELSE NULL END) RIND_514_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('514') THEN D.COL8 ELSE NULL END)  RIND_514_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('514') THEN D.COL9 ELSE NULL END)  RIND_514_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('514') THEN D.COL10 ELSE NULL END) RIND_514_COL3, END)) END AS
    
    
CASE WHEN          SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('515') THEN D.COL33 ELSE NULL END) RIND_515_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('515') THEN D.COL37 ELSE NULL END) RIND_515_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('515') THEN D.COL8 ELSE NULL END)  RIND_515_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('515') THEN D.COL9 ELSE NULL END)  RIND_515_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('515') THEN D.COL10 ELSE NULL END) RIND_515_COL3, END)) END AS
    
    
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('516') THEN D.COL33 ELSE NULL END) RIND_516_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('516') THEN D.COL37 ELSE NULL END) RIND_516_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('516') THEN D.COL8 ELSE NULL END)  RIND_516_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('516') THEN D.COL9 ELSE NULL END)  RIND_516_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('516') THEN D.COL10 ELSE NULL END) RIND_516_COL3, END)) END AS
    
    
        
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('517') THEN D.COL33 ELSE NULL END) RIND_517_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('517') THEN D.COL37 ELSE NULL END) RIND_517_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('517') THEN D.COL8 ELSE NULL END)  RIND_517_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('517') THEN D.COL9 ELSE NULL END)  RIND_517_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('517') THEN D.COL10 ELSE NULL END) RIND_517_COL3, END)) END AS
    
    
            
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('518') THEN D.COL33 ELSE NULL END) RIND_518_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('518') THEN D.COL37 ELSE NULL END) RIND_518_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('518') THEN D.COL8 ELSE NULL END)  RIND_518_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('518') THEN D.COL9 ELSE NULL END)  RIND_518_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('518') THEN D.COL10 ELSE NULL END) RIND_518_COL3, END)) END AS
    
    
                
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('519') THEN D.COL33 ELSE NULL END) RIND_519_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('519') THEN D.COL37 ELSE NULL END) RIND_519_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('519') THEN D.COL8 ELSE NULL END)  RIND_519_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('519') THEN D.COL9 ELSE NULL END)  RIND_519_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('519') THEN D.COL10 ELSE NULL END) RIND_519_COL3, END)) END AS
    
    
CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('520') THEN D.COL33 ELSE NULL END) RIND_520_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('520') THEN D.COL37 ELSE NULL END) RIND_520_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('520') THEN D.COL8 ELSE NULL END)  RIND_520_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('520') THEN D.COL9 ELSE NULL END)  RIND_520_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('520') THEN D.COL10 ELSE NULL END) RIND_520_COL3, END)) END AS
    

CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('521') THEN D.COL33 ELSE NULL END) RIND_521_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('521') THEN D.COL37 ELSE NULL END) RIND_521_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('521') THEN D.COL8 ELSE NULL END)  RIND_521_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('521') THEN D.COL9 ELSE NULL END)  RIND_521_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('521') THEN D.COL10 ELSE NULL END) RIND_521_COL3, END)) END AS



CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('522') THEN D.COL33 ELSE NULL END) RIND_522_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('522') THEN D.COL37 ELSE NULL END) RIND_522_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('522') THEN D.COL8 ELSE NULL END)  RIND_522_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('522') THEN D.COL9 ELSE NULL END)  RIND_522_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('522') THEN D.COL10 ELSE NULL END) RIND_522_COL3, END)) END AS


CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('523') THEN D.COL33 ELSE NULL END) RIND_523_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('523') THEN D.COL37 ELSE NULL END) RIND_523_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('523') THEN D.COL8 ELSE NULL END)  RIND_523_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('523') THEN D.COL9 ELSE NULL END)  RIND_523_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('523') THEN D.COL10 ELSE NULL END) RIND_523_COL3, END)) END AS
    
    
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('524') THEN D.COL33 ELSE NULL END) RIND_524_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('524') THEN D.COL37 ELSE NULL END) RIND_524_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('524') THEN D.COL8 ELSE NULL END)  RIND_524_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('524') THEN D.COL9 ELSE NULL END)  RIND_524_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('524') THEN D.COL10 ELSE NULL END) RIND_524_COL3, END)) END AS



CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('525') THEN D.COL33 ELSE NULL END) RIND_525_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('525') THEN D.COL37 ELSE NULL END) RIND_525_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('525') THEN D.COL8 ELSE NULL END)  RIND_525_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('525') THEN D.COL9 ELSE NULL END)  RIND_525_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('525') THEN D.COL10 ELSE NULL END) RIND_525_COL3, END)) END AS
    
    
CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('526') THEN D.COL33 ELSE NULL END) RIND_526_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('526') THEN D.COL37 ELSE NULL END) RIND_526_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('526') THEN D.COL8 ELSE NULL END)  RIND_526_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('526') THEN D.COL9 ELSE NULL END)  RIND_526_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('526') THEN D.COL10 ELSE NULL END) RIND_526_COL3, END)) END AS



    
CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('527') THEN D.COL33 ELSE NULL END) RIND_527_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('527') THEN D.COL37 ELSE NULL END) RIND_527_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('527') THEN D.COL8 ELSE NULL END)  RIND_527_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('527') THEN D.COL9 ELSE NULL END)  RIND_527_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('527') THEN D.COL10 ELSE NULL END) RIND_527_COL3, END)) END AS



    
CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('528') THEN D.COL33 ELSE NULL END) RIND_528_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('528') THEN D.COL37 ELSE NULL END) RIND_528_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('528') THEN D.COL8 ELSE NULL END)  RIND_528_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('528') THEN D.COL9 ELSE NULL END)  RIND_528_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('528') THEN D.COL10 ELSE NULL END) RIND_528_COL3, END)) END AS



CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('529') THEN D.COL33 ELSE NULL END) RIND_529_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('529') THEN D.COL37 ELSE NULL END) RIND_529_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('529') THEN D.COL8 ELSE NULL END)  RIND_529_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('529') THEN D.COL9 ELSE NULL END)  RIND_529_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('529') THEN D.COL10 ELSE NULL END) RIND_529_COL3, END)) END AS



CASE WHEN         SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL33 ELSE NULL END) RIND_530_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL37 ELSE NULL END) RIND_530_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL8 ELSE NULL END)  RIND_530_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL9 ELSE NULL END)  RIND_530_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL10 ELSE NULL END) RIND_530_COL3, END)) END AS
    
    
CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL33 ELSE NULL END) RIND_530_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL37 ELSE NULL END) RIND_530_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL8 ELSE NULL END)  RIND_530_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL9 ELSE NULL END)  RIND_530_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('530') THEN D.COL10 ELSE NULL END) RIND_530_COL3, END)) END AS
    
CASE WHEN      SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('531') THEN D.COL33 ELSE NULL END) RIND_531_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('531') THEN D.COL37 ELSE NULL END) RIND_531_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('531') THEN D.COL8 ELSE NULL END)  RIND_531_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('531') THEN D.COL9 ELSE NULL END)  RIND_531_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('531') THEN D.COL10 ELSE NULL END) RIND_531_COL3, END)) END AS
    
CASE WHEN          SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('532') THEN D.COL33 ELSE NULL END) RIND_532_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('532') THEN D.COL37 ELSE NULL END) RIND_532_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('532') THEN D.COL8 ELSE NULL END)  RIND_532_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('532') THEN D.COL9 ELSE NULL END)  RIND_532_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('532') THEN D.COL10 ELSE NULL END) RIND_532_COL3, END)) END AS
    
CASE WHEN              SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('533') THEN D.COL33 ELSE NULL END) RIND_533_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('533') THEN D.COL37 ELSE NULL END) RIND_533_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('533') THEN D.COL8 ELSE NULL END)  RIND_533_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('533') THEN D.COL9 ELSE NULL END)  RIND_533_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('533') THEN D.COL10 ELSE NULL END) RIND_533_COL3, END)) END AS


CASE WHEN              SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('534') THEN D.COL33 ELSE NULL END) RIND_534_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('534') THEN D.COL37 ELSE NULL END) RIND_534_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('534') THEN D.COL8 ELSE NULL END)  RIND_534_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('534') THEN D.COL9 ELSE NULL END)  RIND_534_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('534') THEN D.COL10 ELSE NULL END) RIND_534_COL3, END)) END AS
    
CASE WHEN                  SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('535') THEN D.COL33 ELSE NULL END) RIND_535_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('535') THEN D.COL37 ELSE NULL END) RIND_535_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('535') THEN D.COL8 ELSE NULL END)  RIND_535_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('535') THEN D.COL9 ELSE NULL END)  RIND_535_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('535') THEN D.COL10 ELSE NULL END) RIND_535_COL3, END)) END AS



CASE WHEN           SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('536') THEN D.COL33 ELSE NULL END) RIND_536_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('536') THEN D.COL37 ELSE NULL END) RIND_536_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('536') THEN D.COL8 ELSE NULL END)  RIND_536_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('536') THEN D.COL9 ELSE NULL END)  RIND_536_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('536') THEN D.COL10 ELSE NULL END) RIND_536_COL3, END)) END AS


CASE WHEN   SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('537') THEN D.COL33 ELSE NULL END) RIND_537_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('537') THEN D.COL37 ELSE NULL END) RIND_537_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('537') THEN D.COL8 ELSE NULL END)  RIND_537_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('537') THEN D.COL9 ELSE NULL END)  RIND_537_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('537') THEN D.COL10 ELSE NULL END) RIND_537_COL3, END)) END AS


CASE WHEN   SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('538') THEN D.COL33 ELSE NULL END) RIND_538_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('538') THEN D.COL37 ELSE NULL END) RIND_538_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('538') THEN D.COL8 ELSE NULL END)  RIND_538_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('538') THEN D.COL9 ELSE NULL END)  RIND_538_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('538') THEN D.COL10 ELSE NULL END) RIND_538_COL3, END)) END AS
    
    
CASE WHEN       SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('539') THEN D.COL33 ELSE NULL END) RIND_539_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('539') THEN D.COL37 ELSE NULL END) RIND_539_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('539') THEN D.COL8 ELSE NULL END)  RIND_539_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('539') THEN D.COL9 ELSE NULL END)  RIND_539_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('539') THEN D.COL10 ELSE NULL END) RIND_539_COL3, END)) END AS
    
    
CASE WHEN           SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('540') THEN D.COL33 ELSE NULL END) RIND_540_CUATM, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('540') THEN D.COL37 ELSE NULL END) RIND_540_CAEM2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('540') THEN D.COL8 ELSE NULL END)  RIND_540_COL1, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('540') THEN D.COL9 ELSE NULL END)  RIND_540_COL2, END)) END AS
CASE WHEN     SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('540') THEN D.COL10 ELSE NULL END) RIND_540_COL3 END)) END AS





    
    



   


    
     
FROM   

    CIS2.VW_DATA_ALL_COEF D    
     
     
    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
     
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1128,1129) 
  

 

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2

ORDER BY
D.CUIIO