SELECT
    D.CUIIO,
    D.CUATM,
    D.RIND,
    MAX(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND  NVAL(D.COL1) = 1 THEN D.RIND ELSE NULL END ) AS COL1
FROM
     CIS2.VW_DATA_ALL D
WHERE  
    D.FORM IN (64)
    AND D.PERIOADA IN  (:pPERIOADA)
    AND D.CAPITOL IN (100)
    AND D.RIND IN ('1','2','3','4','5','6','7')
   -- AND D.CUIIO = 819906
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND
