
SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2,
    CASE WHEN MAX(CASE WHEN D.CAPITOL IN (1129) = 0 THEN NULL ELSE MAX(CASE WHEN D.CAPITOL IN (1129) END AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END) CAEM_ACT,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1128) = 0 THEN NULL ELSE SUM(CASE WHEN D.CAPITOL IN (1128) END AND D.RIND IN ('500') THEN D.COL8 ELSE NULL END) RIND_500_COL1,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1128) = 0 THEN NULL ELSE SUM(CASE WHEN D.CAPITOL IN (1128) END AND D.RIND IN ('500') THEN D.COL9 ELSE NULL END) RIND_500_COL2,
    CASE WHEN SUM(CASE WHEN D.CAPITOL IN (1128) = 0 THEN NULL ELSE SUM(CASE WHEN D.CAPITOL IN (1128) END AND D.RIND IN ('500') THEN D.COL10 ELSE NULL END) RIND_500_COL3
FROM   
    CIS2.VW_DATA_ALL_COEF D    
    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64) AND 
  D.PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.CAPITOL IN (1128,1129) 
GROUP BY 
  D.ANUL,
  D.CUIIO,
  R.IDNO,
  R.DENUMIRE,
  R.CUATM,
  R.CFP,
  R.CFOJ,
  R.CAEM2
ORDER BY
  D.CUIIO