SELECT
    D.CUIIO,
    D.RIND,
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) AS COL1,
    0 COL2
FROM
     CIS2.VW_DATA_ALL_FR D
WHERE  
    D.FORM IN (57)
    AND D.PERIOADA IN  (:pPERIOADA)
    AND D.CAPITOL IN (1092)
    AND D.RIND IN ('010')
   -- AND D.CUIIO = 2743946
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND 
    
    HAVING 
    
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) > 0 
    
    
   