SELECT 
L.CUIIO,
L.CUATM,
L.RIND_2024,
L.RIND_2023,
R.COL1 RSF1,
R.COL2 RSF1Prescurtat

FROM 
(
SELECT 
L.CUIIO,
L.CUATM,
L.RIND RIND_2024,
R.RIND RIND_2023


FROM
(
SELECT
    D.CUIIO,
    D.CUATM,
    D.RIND,
    MAX(CASE WHEN D.PERIOADA IN  (:pPERIOADA) AND  NVAL(D.COL1) = 1 THEN D.RIND ELSE NULL END ) AS COL1
FROM
     CIS2.VW_DATA_ALL D
WHERE  
    D.FORM IN (64)
    AND D.PERIOADA IN  (:pPERIOADA)
    AND D.CAPITOL IN (100)
    AND D.RIND IN ('1','2','3','4','5','6','7')
   -- AND D.CUIIO = 819906
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND 
    
    
    ) L LEFT JOIN (
    
    SELECT
    D.CUIIO,
    D.CUATM,
    D.RIND,
    MAX(CASE WHEN D.PERIOADA IN  (:pPERIOADA-1) AND  NVAL(D.COL1) = 1 THEN D.RIND ELSE NULL END ) AS COL1
FROM
     CIS2.VW_DATA_ALL D
WHERE  
    D.FORM IN (64)
    AND D.PERIOADA IN  (:pPERIOADA-1)
    AND D.CAPITOL IN (100)
    AND D.RIND IN ('1','2','3','4','5','6','7')
   -- AND D.CUIIO = 819906
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND 
    
    ) R ON R.CUIIO = L.CUIIO 


ORDER BY
L.CUIIO

) L LEFT JOIN (
SELECT
    D.CUIIO,
    D.RIND,
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) AS COL1,
    0 COL2
FROM
     CIS2.VW_DATA_ALL_FR D
WHERE  
    D.FORM IN (57)
    AND D.PERIOADA IN  (:pPERIOADA)
    AND D.CAPITOL IN (1092)
    AND D.RIND IN ('010')
   -- AND D.CUIIO = 2743946
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND 
    
    HAVING 
    
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) > 0 


UNION ALL 

SELECT
    D.CUIIO,
    D.RIND,
    0 COL1,
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) AS COL2
FROM
     CIS2.VW_DATA_ALL_FR D
WHERE  
    D.FORM IN (63)
    AND D.PERIOADA IN  (:pPERIOADA)
    AND D.CAPITOL IN (1121)
    AND D.RIND IN ('010')
  --  AND D.CUIIO = 5523
GROUP BY
    D.CUIIO,
    D.CUATM,
    D.RIND 
    
    HAVING 
    SUM(CASE WHEN  1 = 1 THEN NVAL(D.COL2) ELSE 0 END ) > 0 
   

    
   ) R ON R.CUIIO = L.CUIIO 