SELECT DISTINCT
  'Este bifat  rd.681, 682, 683, 684' AS REZULTAT
FROM
VW_DATA_ALL  D                                  
WHERE
  (D.PERIOADA=:PERIOADA) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  D.FORM = 71
  AND D.CAPITOL IN (1186)

HAVING
 SUM(CASE WHEN D.RIND IN ('670') THEN NVAL(D.COL1) ELSE 0 END) =  0 
 
 AND 
 

( 
SUM(CASE WHEN D.RIND IN ('681') THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) >  0 
OR 
SUM(CASE WHEN D.RIND IN ('682') THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) >  0
OR 
SUM(CASE WHEN D.RIND IN ('683') THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) >  0
OR 
SUM(CASE WHEN D.RIND IN ('684') THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) >  0


)
  
  

  
  
  