SELECT
  TR.ORDINE||'. '||
  CASE 
    WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('0') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa aiba bifa in una din coloane'
   WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL1) ELSE 0 END) = MAX(TR.RESULT2) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL2) ELSE 0 END) = MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' trebuie sa aiba bifa in una din coloane'
   WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<=') AND MAX(TR.BOTH_COL) IN ('0') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat DA atunci Rindul.'||MAX(TR.RIND2)||' trebuie sa fie > 0'
   WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>=') AND MAX(TR.BOTH_COL) IN ('0') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci Rindul.'||MAX(TR.RIND2)||' trebuie sa fie = 0'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat DA dar nu ati bifat unul din rindurile '||MAX(TR.RIND2)||' cu DA'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat DA atunci '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' = 0 (trebuie sa fie > 0)'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >= MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat DA atunci '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' = '||SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END)||' (trebuie sa fie < 100)'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2) ||
            CASE WHEN MAX(TR.ORDINE) IN (85) THEN ' trebuie sa fie NU' 
            ELSE ' = '||SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END)||' (trebuie sa fie = '||MAX(TR.RESULT2)||'%)' END
   WHEN
      (MAX(TR.CONDITIE1) IN ('<=') AND MAX(TR.CONDITIE2) IN ('COMPARE') AND MAX(TR.BOTH_COL) IS NULL AND
      (
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END)))
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie <= '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)
    WHEN
      
    (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
    SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
    SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' = '||MAX(TR.RESULT1)||' dar '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||'trebuie sa fie 0'
    WHEN
     (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT1))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie > 0'
   WHEN
     (MAX(TR.CONDITIE1) IN ('<') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >= MAX(TR.RESULT1))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie < 600'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('1') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL1) ELSE 0 END) = MAX(TR.RESULT2) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL2) ELSE 0 END) = MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati bifat atunci,'||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' trebuie sa aiba bifa in una din coloane'
   WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
      SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2)
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci Rindul.'||MAX(TR.RIND2)||' trebuie sa fie = 0'
   
  END
  AS REZULTAT
FROM 
 (
 SELECT
  D.CUIIO,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.RIND,
  D.CAEM2,
  D.COL1,D.COL2
FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA IN (:PERIOADA) ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL<>:CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (71) AND
  D.CAPITOL IN (1181,1182,1183,1184,1185,1186,1187,1195,1206) AND
  (SELECT
      
     DISTINCT    D.RIND
      
    FROM
      VW_DATA_ALL D
    WHERE
      D.PERIOADA IN (:PERIOADA) AND  
      D.FORM IN (71) AND
      D.CAPITOL IN (1195) AND
      D.CUIIO=:CUIIO) IN (1)
 )D
CROSS JOIN
 (
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '130' AS RIND2, 1 AS ORDINE, '1' AS NR_COLUMN1, '2' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '140' AS RIND2, 2 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION

SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '192' AS RIND2, 2.1 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '193' AS RIND2, 2.2 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '194' AS RIND2, 2.3 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '195' AS RIND2, 2.4 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '150' AS RIND2, 3 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '150' AS RIND1, '170' AS RIND2, 4 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '170' AS RIND1, '180' AS RIND2, 5 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '190' AS RIND1, '191' AS RIND2, 6 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '140' AS RIND1, '141' AS RIND2, 7 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '150' AS RIND1, '161,162,163,164,165' AS RIND2, 8 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1182 AS CAPITOL2, '130' AS RIND1, '210' AS RIND2, 9 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1182 AS CAPITOL2, '130' AS RIND1, '221' AS RIND2, 10 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1182 AS CAPITOL2, '130' AS RIND1, '222' AS RIND2, 11 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1182 AS CAPITOL2, '130' AS RIND1, '223' AS RIND2, 12 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1182 AS CAPITOL2, '130' AS RIND1, '224' AS RIND2, 13 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1183 AS CAPITOL2, '130' AS RIND1, '310' AS RIND2, 14 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '321' AS RIND2, 15 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '322' AS RIND2, 16 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '323' AS RIND2, 17 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '324' AS RIND2, 18 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '325' AS RIND2, 19 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '326' AS RIND2, 20 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '327' AS RIND2, 21 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '328' AS RIND2, 22 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '329' AS RIND2, 23 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '330' AS RIND2, 24 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '411' AS RIND2, 25 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '412' AS RIND2, 26 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '413' AS RIND2, 27 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '414' AS RIND2, 28 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '415' AS RIND2, 29 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '416' AS RIND2, 30 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '417' AS RIND2, 31 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '418' AS RIND2, 32 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '419' AS RIND2, 33 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '420' AS RIND2, 34 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '430' AS RIND2, 35 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '421' AS RIND2, 36 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '422' AS RIND2, 37 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1184 AS CAPITOL2, '130' AS RIND1, '423' AS RIND2, 38 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '511' AS RIND2, 39 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '512' AS RIND2, 40 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '513' AS RIND2, 41 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '514' AS RIND2, 42 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '515' AS RIND2, 43 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1186 AS CAPITOL2, '130' AS RIND1, '611' AS RIND2, 44 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1186 AS CAPITOL2, '130' AS RIND1, '612' AS RIND2, 45 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '620' AS RIND2, 46 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '620' AS RIND2, 47 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '631' AS RIND2, 48 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '631' AS RIND2, 49 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '632' AS RIND2, 50 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '632' AS RIND2, 51 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1181 AS CAPITOL1, 1186 AS CAPITOL2, '130' AS RIND1, '633' AS RIND2, 52 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N,S' AS CAEM2 FROM DUAL UNION
--SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '643' AS RIND2, 53 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '643' AS RIND2, 54 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '633' AS RIND2, 52 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '643' AS RIND2, 53 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '633' AS RIND2, 52.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '643' AS RIND2, 53.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '642' AS RIND2, 55 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '642' AS RIND2, 56 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL  UNION
--SELECT 1181 AS CAPITOL1, 1186 AS CAPITOL2, '130' AS RIND1, '643' AS RIND2, 57 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '100' AS RESULT2, '0' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N,S' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '651,652,653,654' AS RIND2, 58 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '651,652,653,654' AS RIND2, 59 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '670' AS RIND2, 60 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '681,682,683,684' AS RIND2, 61 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1187 AS CAPITOL2, '130' AS RIND1, '710' AS RIND2, 62 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1187 AS CAPITOL2, '130' AS RIND1, '721' AS RIND2, 63 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1187 AS CAPITOL2, '130' AS RIND1, '722' AS RIND2, 64 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '141' AS RIND1, '120' AS RIND2, 65 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '<=' AS CONDITIE1, 'COMPARE' AS CONDITIE2, NULL AS RESULT1, NULL AS RESULT2, NULL AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '181' AS RIND1, '120' AS RIND2, 66 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '<=' AS CONDITIE1, 'COMPARE' AS CONDITIE2, NULL AS RESULT1, NULL AS RESULT2, NULL AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '112,113' AS RIND1, '181' AS RIND2, 67 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '181' AS RIND1, '141' AS RIND2, 68 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '<=' AS CONDITIE1, 'COMPARE' AS CONDITIE2, NULL AS RESULT1, NULL AS RESULT2, NULL AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1186 AS CAPITOL2, '130' AS RIND1, '660' AS RIND2, 69 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '651' AS RIND2, 70 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '652' AS RIND2, 71 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '653' AS RIND2, 72 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '654' AS RIND2, 73 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '651' AS RIND2, 74 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '652' AS RIND2, 75 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '653' AS RIND2, 76 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '654' AS RIND2, 77 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '681' AS RIND2, 78 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '682' AS RIND2, 79 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '683' AS RIND2, 80 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '660' AS RIND1, '684' AS RIND2, 81 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1185 AS CAPITOL2, '130' AS RIND1, '520' AS RIND2, 82 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, 'C,D,E,F,G,H,I,J,L,M,N' AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611' AS RIND1, '631' AS RIND2, 83 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '612' AS RIND1, '632' AS RIND2, 84 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '140' AS RIND1, '180' AS RIND2, 85 AS ORDINE, '2' AS NR_COLUMN1, '2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1206 AS CAPITOL1, NULL AS CAPITOL2, '900' AS RIND1, NULL AS RIND2, 86 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '>' AS CONDITIE1, NULL AS CONDITIE2, '0' AS RESULT1, '' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
--SELECT 1187 AS CAPITOL1, NULL AS CAPITOL2, '900' AS RIND1, NULL AS RIND2, 87 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '<' AS CONDITIE1, NULL AS CONDITIE2, '600' AS RESULT1, '' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1195 AS CAPITOL1, 1181 AS CAPITOL2, '1' AS RIND1, '130' AS RIND2, 88 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '170' AS RIND1, '181' AS RIND2, 89 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '180' AS RIND1, '181' AS RIND2, 90 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, '0' AS BOTH_COL, NULL AS CAEM2 FROM DUAL UNION
SELECT 1186 AS CAPITOL1, 1186 AS CAPITOL2, '611,612' AS RIND1, '620' AS RIND2, 91 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>=' AS CONDITIE2, '2' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, NULL AS CAEM2 FROM DUAL

) TR
GROUP BY
  TR.ORDINE,
  SUBSTR(D.CAEM2,1,1)
  
HAVING
   -------------- Daca 1 '=' si 2 '<='
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('1') AND MAX(TR.CAEM2) IS NULL AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL1) ELSE 0 END) = MAX(TR.RESULT2) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL2) ELSE 0 END) = MAX(TR.RESULT2))   OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('1') AND MAX(TR.CAEM2) IS NOT NULL AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL1) ELSE 0 END) = MAX(TR.RESULT2) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL2) ELSE 0 END) = MAX(TR.RESULT2) AND
  CASE WHEN MAX(TR.CAEM2) IS NOT NULL THEN MAX(TR.CAEM2) END LIKE ('%'||SUBSTR(D.CAEM2,1,1)||'%'))   OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<=') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>=') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('0') AND MAX(TR.CAEM2) IS NULL AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('0') AND MAX(TR.CAEM2) IS NOT NULL AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2) AND
  CASE WHEN MAX(TR.CAEM2) IS NOT NULL THEN MAX(TR.CAEM2) END LIKE ('%'||SUBSTR(D.CAEM2,1,1)||'%')) OR
  (MAX(TR.CONDITIE1) IN ('<=') AND MAX(TR.CONDITIE2) IN ('COMPARE') AND MAX(TR.BOTH_COL) IS NULL AND
  (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END))) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2)) OR
   (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT1)) OR
   (MAX(TR.CONDITIE1) IN ('<') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >= MAX(TR.RESULT1)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL1) ELSE 0 END) = MAX(TR.RESULT2) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(D.COL2) ELSE 0 END) = MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
  SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2))