SELECT
  TR.ORDINE||'. '||
  CASE 
    WHEN
      (MAX(TR.CONDITIE1) IN ('<=') AND MAX(TR.CONDITIE2) IN ('COMPARE>0') AND MAX(TR.BOTH_COL) IS NULL AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > 0 AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END)))
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie <= '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)
    WHEN
      (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > 0 AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = 0)
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' > 0 dar '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' = 0 (trebuie sa fie > 0)'
   WHEN
     (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT1))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie > 0'
   WHEN
     (MAX(TR.CONDITIE1) IN ('<') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >= MAX(TR.RESULT1))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' trebuie sa fie < 600'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat DA dar nu ati bifat '||CASE WHEN MAX(TR.ORDINE) IN (11) THEN 'DA' END||' unul din rindurile '||MAX(TR.RIND2)
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS12') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindurile.'||MAX(TR.RIND1)||' = 0 atunci Rindurile.'||MAX(TR.RIND2)||' = '||MAX(TR.RESULT2)
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('0') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci '||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' = '||SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END)||' (trebuie sa fie '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||')'
   WHEN
     (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
     SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))
   THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND1)||' ati selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci unul din'||
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) THEN D.CAPITOL_DEN END)||' Rindul.'||MAX(TR.RIND2)||' trebuie sa fie DA)'
   
  END
  AS REZULTAT
FROM 
 (
 SELECT
  D.CUIIO,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.RIND,
  D.COL1,D.COL2
FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA IN (:PERIOADA) ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL<>:CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (71) AND
  D.CAPITOL IN (1181,1183,1187) AND
  (SELECT
     DISTINCT   D.RIND
    FROM
      VW_DATA_ALL D
    WHERE
      D.PERIOADA IN (:PERIOADA) AND  
      D.FORM IN (71) AND
      D.CAPITOL IN (1195) AND
      D.CUIIO=:CUIIO) IN (1)
  
 )D
CROSS JOIN
 (
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '110' AS RIND1, '111' AS RIND2, 1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '<=' AS CONDITIE1, 'COMPARE>0' AS CONDITIE2, NULL AS RESULT1, NULL AS RESULT2, NULL AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '110' AS RIND1, '112' AS RIND2, 2 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '<=' AS CONDITIE1, 'COMPARE>0' AS CONDITIE2, NULL AS RESULT1, NULL AS RESULT2, NULL AS BOTH_COL FROM DUAL UNION
--SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '111,112' AS RIND1, '141' AS RIND2, 3 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '>' AS CONDITIE1, '=' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL FROM DUAL UNION
--SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '112,113' AS RIND1, '181' AS RIND2, 4 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '>' AS CONDITIE1, '=' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL FROM DUAL UNION
--SELECT 1187 AS CAPITOL1, NULL AS CAPITOL2, '900' AS RIND1, NULL AS RIND2, 5 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '>' AS CONDITIE1, NULL AS CONDITIE2, '0' AS RESULT1, '' AS RESULT2, '0' AS BOTH_COL FROM DUAL UNION
--SELECT 1187 AS CAPITOL1, NULL AS CAPITOL2, '900' AS RIND1, NULL AS RIND2, 6 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '<' AS CONDITIE1, NULL AS CONDITIE2, '600' AS RESULT1, '' AS RESULT2, '0' AS BOTH_COL FROM DUAL UNION
SELECT 1183 AS CAPITOL1, 1183 AS CAPITOL2, '310' AS RIND1, '320,321,322,323,324,325,326,327,328,329,330' AS RIND2, 7 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '110,111,112,113' AS RIND1, '120,141,181' AS RIND2, 8 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS12' AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '111,112' AS RIND1, '120' AS RIND2, 9 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '>' AS CONDITIE1, '=' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL FROM DUAL UNION

SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '112,113' AS RIND1, '191' AS RIND2, 9.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '>' AS CONDITIE1, '=' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '140' AS RIND1, '170' AS RIND2, 10 AS ORDINE, '2' AS NR_COLUMN1, '2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '0' AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '150,170' AS RIND2, 11 AS ORDINE, '1' AS NR_COLUMN1, '2' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL FROM DUAL UNION
SELECT 1181 AS CAPITOL1, 1181 AS CAPITOL2, '130' AS RIND1, '111,112' AS RIND2, 11.1 AS ORDINE, '1' AS NR_COLUMN1, '2' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS2' AS BOTH_COL FROM DUAL UNION
SELECT 1187 AS CAPITOL1, NULL AS CAPITOL2, '900' AS RIND1, NULL AS RIND2, 12 AS ORDINE, '1' AS NR_COLUMN1, NULL AS NR_COLUMN2, '<' AS CONDITIE1, NULL AS CONDITIE2, '600' AS RESULT1, '' AS RESULT2, '0' AS BOTH_COL FROM DUAL

) TR
GROUP BY
  TR.ORDINE
  
HAVING
   -------------- Daca 1 '=' si 2 '<='
  (MAX(TR.CONDITIE1) IN ('<=') AND MAX(TR.CONDITIE2) IN ('COMPARE>0') AND MAX(TR.BOTH_COL) IS NULL AND
  (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > 0 AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END))) OR
  (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > 0 AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = 0) OR
   (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <= MAX(TR.RESULT1)) OR
   (MAX(TR.CONDITIE1) IN ('<') AND MAX(TR.CONDITIE2) IS NULL AND MAX(TR.BOTH_COL) IN ('0') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) >= MAX(TR.RESULT1)) OR
   (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) OR
   (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS12') AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
   SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2)) OR
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('0') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2))