SELECT DISTINCT
  'Nu satisface conditia' AS REZULTAT
FROM
VW_DATA_ALL  D                                  
WHERE
  (D.PERIOADA=:PERIOADA) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL             OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS   OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  D.FORM = 71
  AND D.CAPITOL IN (1181,1182)
HAVING
(SUM(CASE WHEN D.CAPITOL IN (1181) AND RIND IN ('130')   THEN  D.COL1 ELSE NULL END ) IS  NULL )
AND  
(SUM(CASE WHEN  D.CAPITOL IN (1182) AND RIND  IN ('210','220','221','111','222','223','224','230')   THEN  NVAL(D.COL1) + NVAL(D.COL2) ELSE NULL END )   IS NOT NULL  )
 