
--Tab.2.18 Cap.III rind 0000000 COL2 (2101028) <>   (2078634) Tab.1 Cap.III Rind 081 COL 2 



SELECT 
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
  
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
  
  NR_ROW||'~'||ORDINE AS NR_ROW,
  ORDINE,
  '0000000000000000' AS DECIMAL_POS,
  NUME_ROW AS NUME_ROW,
    ROUND(CASE WHEN COL1 = 0 THEN NULL ELSE COL1 END,0) AS COL1,
  ROUND(CASE WHEN COL2 = 0 THEN NULL ELSE COL2 END,0) AS COL2,
  ROUND(CASE WHEN COL3 = 0 THEN NULL ELSE COL3 END,0) AS COL3,
  ROUND(CASE WHEN COL4 = 0 THEN NULL ELSE COL4 END,0) AS COL4,
  ROUND(CASE WHEN COL5 = 0 THEN NULL ELSE COL5 END,0) AS COL5,
  ROUND(CASE WHEN COL6 = 0 THEN NULL ELSE COL6 END,0) AS COL6,
  ROUND(CASE WHEN COL7 = 0 THEN NULL ELSE COL7 END,0) AS COL7,
  ROUND(CASE WHEN COL8 = 0 THEN NULL ELSE COL8 END,0) AS COL8,
  ROUND(CASE WHEN COL9 = 0 THEN NULL ELSE COL9 END,0) AS COL9,
  ROUND(CASE WHEN COL10 = 0 THEN NULL ELSE COL10 END,0) AS COL10,
  ROUND(CASE WHEN COL11 = 0 THEN NULL ELSE COL11 END,0) AS COL11,
  ROUND(CASE WHEN COL12 = 0 THEN NULL ELSE COL12 END,0) AS COL12,
  ROUND(CASE WHEN COL13 = 0 THEN NULL ELSE COL13 END,0) AS COL13,
  ROUND(CASE WHEN COL14 = 0 THEN NULL ELSE COL14 END,0) AS COL14,
  ROUND(CASE WHEN COL15 = 0 THEN NULL ELSE COL15 END,0) AS COL15,
  ROUND(CASE WHEN COL16 = 0 THEN NULL ELSE COL16 END,0) AS COL16
FROM 
(
SELECT 
  R.CUATM AS NR_ROW,
  R.NR_ROW AS ORDINE,
  R.NUME_ROW AS NUME_ROW,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL1 ELSE 0 END)) AS COL1,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL2 ELSE 0 END)) AS COL2,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL3 ELSE 0 END)) AS COL3,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL4 ELSE 0 END)) AS COL4,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL5 ELSE 0 END)) AS COL5,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL6 ELSE 0 END)) AS COL6,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL7 ELSE 0 END)) AS COL7,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL8 ELSE 0 END)) AS COL8,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL9 ELSE 0 END)) AS COL9,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL10 ELSE 0 END)) AS COL10,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL11 ELSE 0 END)) AS COL11,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL12 ELSE 0 END)) AS COL12,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL13 ELSE 0 END)) AS COL13,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL14 ELSE 0 END)) AS COL14,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL15 ELSE 0 END)) AS COL15,
  NVAL(SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CUATM||'%' THEN D.COL16 ELSE 0 END)) AS COL16
FROM 
  VW_DATA_ALL D
--  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS) 
  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT 'TOTAL' AS NUME_ROW,                                   '01' AS NR_ROW, '0000000' AS CUATM FROM DUAL UNION
    SELECT 'Mun. CHISINAU' AS NUME_ROW,                           '02' AS NR_ROW, '0100000' AS CUATM FROM DUAL UNION  
    SELECT 'NORD' AS NUME_ROW,                                    '03' AS NR_ROW, '1111111' AS CUATM FROM DUAL UNION 
    SELECT 'Mun. Balti' AS NUME_ROW,                              '04' AS NR_ROW, '0300000' AS CUATM FROM DUAL UNION 
    SELECT 'r-l Briceni' AS NUME_ROW,                             '05' AS NR_ROW, '1400000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Donduseni' AS NUME_ROW,                           '06' AS NR_ROW, '3400000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Drochia' AS NUME_ROW,                             '07' AS NR_ROW, '3600000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Edinet' AS NUME_ROW,                              '08' AS NR_ROW, '4100000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Falesti' AS NUME_ROW,                             '09' AS NR_ROW, '4300000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Floresti' AS NUME_ROW,                            '10' AS NR_ROW, '4500000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Glodeni' AS NUME_ROW,                             '11' AS NR_ROW, '4800000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Ocnita' AS NUME_ROW,                              '12' AS NR_ROW, '6200000' AS CUATM FROM DUAL UNION     
    SELECT 'r-l Riscani' AS NUME_ROW,                             '13' AS NR_ROW, '7100000' AS CUATM FROM DUAL UNION 
    SELECT 'r-l Singerei' AS NUME_ROW,                            '14' AS NR_ROW, '7400000' AS CUATM FROM DUAL UNION     
    SELECT 'r-l Soroca' AS NUME_ROW,                              '15' AS NR_ROW, '7800000' AS CUATM FROM DUAL UNION  
    SELECT 'CENTRU' AS NUME_ROW,                                  '16' AS NR_ROW, '2222222' AS CUATM FROM DUAL UNION 
    SELECT 'r-l Anenii Noi' AS NUME_ROW,                          '17' AS NR_ROW, '1000000' AS CUATM FROM DUAL UNION        
    SELECT 'r-l Calaras' AS NUME_ROW,                             '18' AS NR_ROW, '2500000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Criuleni' AS NUME_ROW,                            '19' AS NR_ROW, '3100000' AS CUATM FROM DUAL UNION   
    SELECT 'Dubasari' AS NUME_ROW,                                '20' AS NR_ROW, '3800000' AS CUATM FROM DUAL UNION
    SELECT 'r-l Hincesti' AS NUME_ROW,                            '21' AS NR_ROW, '5300000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Ialoveni' AS NUME_ROW,                            '22' AS NR_ROW, '5500000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Nisporeni' AS NUME_ROW,                           '23' AS NR_ROW, '6000000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Orhei' AS NUME_ROW,                               '24' AS NR_ROW, '6400000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Rezina' AS NUME_ROW,                              '25' AS NR_ROW, '6700000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Straseni' AS NUME_ROW,                            '26' AS NR_ROW, '8000000' AS CUATM FROM DUAL UNION     
    SELECT 'r-l Soldanesti' AS NUME_ROW,                          '28' AS NR_ROW, '8300000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Telenesti' AS NUME_ROW,                           '29' AS NR_ROW, '8900000' AS CUATM FROM DUAL UNION 
    SELECT 'r-l Ungheni' AS NUME_ROW,                             '30' AS NR_ROW, '9200000' AS CUATM FROM DUAL UNION 
    SELECT 'SUD' AS NUME_ROW,                                     '31' AS NR_ROW, '3333333' AS CUATM FROM DUAL UNION 
    SELECT 'r-l Basarabeasca' AS NUME_ROW,                        '32' AS NR_ROW, '1200000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Cahul' AS NUME_ROW,                               '34' AS NR_ROW, '1700000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Cantemir' AS NUME_ROW,                            '35' AS NR_ROW, '2100000' AS CUATM FROM DUAL UNION     
    SELECT 'r-l Causeni' AS NUME_ROW,                             '36' AS NR_ROW, '2700000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Cimislia' AS NUME_ROW,                            '37' AS NR_ROW, '2900000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Leovo' AS NUME_ROW,                               '38' AS NR_ROW, '5700000' AS CUATM FROM DUAL UNION    
    SELECT 'r-l Stefan Voda' AS NUME_ROW,                         '39' AS NR_ROW, '8500000' AS CUATM FROM DUAL UNION   
    SELECT 'r-l Taraclia' AS NUME_ROW,                            '40' AS NR_ROW, '8700000' AS CUATM FROM DUAL UNION   
    SELECT 'UTA Gagauzia' AS NUME_ROW,                            '41' AS NR_ROW, '9600000' AS CUATM FROM DUAL    
  ) R 
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (36)                 AND 
  D.CAPITOL IN (387) AND
  D.RIND IN ('081') 
GROUP BY
  R.NR_ROW,
  R.NUME_ROW,
  R.CUATM )
  
  
  ORDER BY
  ORDINE