SELECT
    TRIM(TO_CHAR(1+TO_NUMBER(R.RIND), '00')) AS RIND,
    R.DENUMIRE AS DENUMIRE,
    1+TO_NUMBER(R.RIND) AS ORDINE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2
  FROM
    CIS2.VW_DATA_ALL D INNER JOIN
    CIS2.MD_RIND R ON(D.ID_MD=R.ID_MD)
  WHERE
    D.FORM = 15 AND
    D.CAPITOL = 1000 AND
    D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
    AND (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
    
  GROUP BY
    R.RIND,
    R.DENUMIRE