
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  L.RIND AS NR_ROW,
  L.ORDINE AS ORDINE,
  '0111' AS DECIMAL_POS,
  L.DENUMIRE AS NUME_ROW,
  R.COL1 AS COL1,
  R.COL2 AS COL2,
  NULL AS COL3,
  NULL AS COL4
FROM 
(
SELECT
RIND,
DENUMIRE,
RIND_VERS,
ORDINE 

FROM CIS2.MD_RIND 
WHERE
CAPITOL IN (1000)
AND CAPITOL_VERS = 1060

UNION 

SELECT
'00'RIND,
  'Autorizatii de construire eliberate pentru cladiri rezidentiale - total (r.03+r.04+r.05)' AS DENUMIRE,
   
1060  RIND_VERS,
 0 AS ORDINE


FROM DUAL 

ORDER BY
ORDINE  



) L LEFT JOIN (

SELECT
   -- TRIM(TO_CHAR(1+TO_NUMBER(R.RIND), '00')) AS RIND,
    R.RIND,
    R.DENUMIRE AS DENUMIRE,
    --1+TO_NUMBER(R.RIND) AS ORDINE,
    R.ORDINE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2
  FROM
    CIS2.VW_DATA_ALL D INNER JOIN
    CIS2.MD_RIND R ON(D.ID_MD=R.ID_MD)
  WHERE
    D.FORM = 15 AND
    D.CAPITOL = 1000 AND
  --  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
    D.PERIOADA IN (:pPERIOADA)
    AND (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
    
    AND D.CUIIO = 4496728
    
  GROUP BY
    R.RIND,
    R.DENUMIRE,
    R.ORDINE
    
    
    
    UNION 
    
    SELECT
    '00' AS RIND,
    'Autorizatii de construire eliberate pentru cladiri rezidentiale - total (r.03+r.04+r.05)' AS DENUMIRE,
    0 AS ORDINE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2
  FROM
    CIS2.VW_DATA_ALL D
  WHERE
    D.FORM = 15 AND
    D.CAPITOL = 1000 AND
    D.RIND IN('03', '04', '05')
   -- AND D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
    
    AND  D.PERIOADA IN (:pPERIOADA)
    AND (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
    
    
    AND D.CUIIO = 4496728
    
    
    ORDER BY
    ORDINE
    

)  R  ON TO_CHAR(R.RIND) = TO_CHAR(L.RIND)


ORDER BY
L.ORDINE 