SELECT
  
    R.RIND,
    R.DENUMIRE AS DENUMIRE,
    R.ORDINE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2
  FROM
    CIS2.VW_DATA_ALL D INNER JOIN
    CIS2.MD_RIND R ON(D.ID_MD=R.ID_MD)
    INNER JOIN CIS2.RENIM RR ON (D.CUIIO = RR.CUIIO AND D.CUIIO_VERS = RR.CUIIO_VERS)
  WHERE
    D.FORM = 15 AND
    D.CAPITOL = 1000 AND
     RR.TIP_LOCAL = '2' AND
    D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
   -- D.PERIOADA IN (:pPERIOADA)
    AND (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
    
  --  AND D.CUIIO = 4496728
    
  GROUP BY
    R.RIND,
    R.DENUMIRE,
    R.ORDINE
    
    
    
    UNION 
    
    SELECT
    '00' AS RIND,
    'Autorizatii de construire eliberate pentru cladiri rezidentiale - total (r.01 + r.05)' AS DENUMIRE,
    0 AS ORDINE,
    SUM(D.COL1) AS COL1,
    SUM(D.COL2) AS COL2
  FROM
    CIS2.VW_DATA_ALL D
     INNER JOIN CIS2.RENIM RR ON (D.CUIIO = RR.CUIIO AND D.CUIIO_VERS = RR.CUIIO_VERS)
  WHERE
    RR.TIP_LOCAL = '2' AND
    D.FORM = 15 AND
    D.CAPITOL = 1000 AND
    D.RIND IN('01', '05')
    AND D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
    
   -- AND  D.PERIOADA IN (:pPERIOADA)
    AND (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
    
    
  --  AND D.CUIIO = 4496728
    
    
    ORDER BY
    ORDINE