SELECT   
D.CUIIO,
'Rind.0000000: '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 :', '5', 'COL5 :', '6', 'COL6 :', '7', 'COL7 :', '8', 'COL8 :', '9', 'COL9 :')||
  SUM(CASE WHEN D.RIND     IN ('0000000') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9)) ELSE 0 END) ||' <> '||
  SUM(CASE WHEN D.RIND NOT IN ('0000000') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9)) ELSE 0 END)
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL UNION
       SELECT '9' AS NR_COLUMN FROM DUAL                                  
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
--  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (25)  AND
  D.CAPITOL in (365)
  --AND D.CUIIO = 41100914
GROUP BY CC.NR_COLUMN,
D.CUIIO

HAVING

  SUM(CASE WHEN D.RIND     IN ('0000000') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9)) ELSE 0 END) <>
  SUM(CASE WHEN D.RIND NOT IN ('0000000') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9)) ELSE 0 END)