
CREATE TABLE USER_BANCU.ASA_FR
(
  CUIIO       NUMBER,
 
  CUIIO_VERS  NUMBER,
  DENUMIRE    VARCHAR2(1024 BYTE),
  CUATM       VARCHAR2(1024 BYTE),
  CFP         VARCHAR2(1024 BYTE),
  CFOJ        VARCHAR2(1024 BYTE),
  FORMA       VARCHAR2(1024 BYTE),
  CAEM_FIN       VARCHAR2(1024 BYTE),
  S10_F2       VARCHAR2(1024 BYTE),
  IDNO        VARCHAR2(1024 BYTE),
  S4_CALC        VARCHAR2(1024 BYTE)
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
