SELECT


  DENUMIRE,
  CODUL,
  FULL_CODE,
  ORDINE,
  PRGS,
  COL1,COL2,COL3,COL4
FROM
(
SELECT 
'Localitati urbane' AS DENUMIRE,
  CC.CODUL, CC.FULL_CODE, 1 AS ORDINE, CC.PRGS,

    COUNT(DISTINCT CASE WHEN MR.RIND IN ('0')  THEN D.UNIT_CODE  ELSE NULL END) AS COL1,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP3')  THEN D.UNIT_CODE  ELSE NULL END) AS COL2,
    COUNT(DISTINCT CASE WHEN MR.RIND IN ('TIP2')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL3,
    COUNT(DISTINCT CASE WHEN MR.RIND NOT IN ('TIP2', 'TIP3','0')  THEN   D.UNIT_CODE  ELSE NULL END) AS COL4
FROM
  VW_DATA_ALL_GC  D
    INNER JOIN MD_RIND MR ON D.ID_MD = MR.ID_MD
  INNER JOIN VW_CL_CUATM C ON(D.CUATM = C.CODUL)

 INNER JOIN CIS2.VW_CL_CUATM CC ON ((C.CODUL=CC.CODUL AND CC.PRGS IN (3)) OR (CC.PRGS NOT IN (3) AND C.FULL_CODE LIKE '%'||CC.CODUL||'%'))



   
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
  D.FORM IN (58)  AND
  D.CAPITOL IN (419)
  AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
  
 AND   C.PRGS IN (2,3,4,5) 

  



GROUP BY CC.DENUMIRE,
  CC.CODUL, CC.FULL_CODE, CC.PRGS
ORDER BY CC.FULL_CODE
)
WHERE
  PRGS IN (2)
    
    

    
    
 