SELECT
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  SUM(CASE WHEN D.RIND IN ('1.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_1_1_C_1,
  SUM(CASE WHEN D.RIND IN ('1.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_1_2_C_1,
  SUM(CASE WHEN D.RIND IN ('1.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_1_3_C_1,
  
  SUM(CASE WHEN D.RIND IN ('2.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_2_1_C_1,
  SUM(CASE WHEN D.RIND IN ('2.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_2_2_C_1,
  SUM(CASE WHEN D.RIND IN ('2.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_2_3_C_1,
  
  SUM(CASE WHEN D.RIND IN ('3.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_3_1_C_1,
  SUM(CASE WHEN D.RIND IN ('3.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_3_2_C_1,
  SUM(CASE WHEN D.RIND IN ('3.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_3_3_C_1,
  
  SUM(CASE WHEN D.RIND IN ('4.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_4_1_C_1,
  SUM(CASE WHEN D.RIND IN ('4.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_4_2_C_1,
  SUM(CASE WHEN D.RIND IN ('4.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_4_3_C_1,
  
  SUM(CASE WHEN D.RIND IN ('5.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_5_1_C_1,
  SUM(CASE WHEN D.RIND IN ('5.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_5_2_C_1,
  SUM(CASE WHEN D.RIND IN ('5.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_5_3_C_1,
  
  
  SUM(CASE WHEN D.RIND IN ('6.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_6_1_C_1,
  SUM(CASE WHEN D.RIND IN ('6.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_6_2_C_1,
  SUM(CASE WHEN D.RIND IN ('6.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_6_3_C_1, 


  SUM(CASE WHEN D.RIND IN ('7.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_7_1_C_1,
  SUM(CASE WHEN D.RIND IN ('7.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_7_2_C_1,
  SUM(CASE WHEN D.RIND IN ('7.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_7_3_C_1, 
  
  
  SUM(CASE WHEN D.RIND IN ('8.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_8_1_C_1,
  SUM(CASE WHEN D.RIND IN ('8.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_8_2_C_1,
  SUM(CASE WHEN D.RIND IN ('8.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_8_3_C_1, 
  
   SUM(CASE WHEN D.RIND IN ('9') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_C_1,
   SUM(CASE WHEN D.RIND IN ('9') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_9_C_2,
   
   SUM(CASE WHEN D.RIND IN ('9.01') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_01_C_1,
   SUM(CASE WHEN D.RIND IN ('9.02') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_02_C_1,
   SUM(CASE WHEN D.RIND IN ('9.03') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_03_C_1,
   SUM(CASE WHEN D.RIND IN ('9.04') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_04_C_1,
   SUM(CASE WHEN D.RIND IN ('9.05') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_05_C_1,
   SUM(CASE WHEN D.RIND IN ('9.06') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_06_C_1,
   SUM(CASE WHEN D.RIND IN ('9.07') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_07_C_1,
   SUM(CASE WHEN D.RIND IN ('9.08') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_9_08_C_1,

   
   SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_10_C_1,
   SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_10_C_2,
   
   SUM(CASE WHEN D.RIND IN ('11.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_11_1_C_1,
   SUM(CASE WHEN D.RIND IN ('11.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_11_2_C_1,
   SUM(CASE WHEN D.RIND IN ('11.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_11_3_C_1,
   SUM(CASE WHEN D.RIND IN ('11.4') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_11_4_C_1,
   
   SUM(CASE WHEN D.RIND IN ('12.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_12_1_C_1,
   SUM(CASE WHEN D.RIND IN ('12.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_12_2_C_1,
   SUM(CASE WHEN D.RIND IN ('12.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_12_3_C_1,
   SUM(CASE WHEN D.RIND IN ('12.4') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_12_4_C_1,
   
   
   SUM(CASE WHEN D.RIND IN ('13.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_13_1_C_1,
   SUM(CASE WHEN D.RIND IN ('13.1') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_13_1_C_2,
   
   SUM(CASE WHEN D.RIND IN ('13.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_13_2_C_1,
   SUM(CASE WHEN D.RIND IN ('13.2') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_13_2_C_2,
   
   SUM(CASE WHEN D.RIND IN ('13.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_13_3_C_1,
   SUM(CASE WHEN D.RIND IN ('13.3') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_13_3_C_2,
   
   SUM(CASE WHEN D.RIND IN ('13.4') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_13_4_C_1,
   SUM(CASE WHEN D.RIND IN ('13.4') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_13_4_C_2,
  
   SUM(CASE WHEN D.RIND IN ('13.5') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_13_5_C_1,
   SUM(CASE WHEN D.RIND IN ('13.5') THEN NVAL(D.COL2) ELSE NULL END)  AS RIND_13_5_C_2,
   
   SUM(CASE WHEN D.RIND IN ('14.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_14_1_C_1,
   SUM(CASE WHEN D.RIND IN ('14.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_14_2_C_1,
   SUM(CASE WHEN D.RIND IN ('14.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_14_3_C_1,
   SUM(CASE WHEN D.RIND IN ('14.4') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_14_4_C_1,
   
   SUM(CASE WHEN D.RIND IN ('15.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_15_1_C_1,
   SUM(CASE WHEN D.RIND IN ('15.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_15_2_C_1,
   SUM(CASE WHEN D.RIND IN ('15.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_15_3_C_1,
   SUM(CASE WHEN D.RIND IN ('15.4') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_15_4_C_1,
   
   SUM(CASE WHEN D.RIND IN ('16.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_16_1_C_1,
   SUM(CASE WHEN D.RIND IN ('16.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_16_2_C_1,
   SUM(CASE WHEN D.RIND IN ('16.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_16_3_C_1,
   
   SUM(CASE WHEN D.RIND IN ('17.1') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_17_1_C_1,
   SUM(CASE WHEN D.RIND IN ('17.2') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_17_2_C_1,
   SUM(CASE WHEN D.RIND IN ('17.3') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_17_3_C_1,
   
   SUM(CASE WHEN D.RIND IN ('18') THEN NVAL(D.COL1) ELSE NULL END)  AS RIND_18_C_1
  
 FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (1061) AND
  D.FORM IN (74) AND 
  D.CAPITOL IN (1197)
 -- AND D.CUIIO = 458963
  
  GROUP BY
  D.CUIIO,
  D.CUATM,
  D.CAEM2
--  D.RIND
 
ORDER BY
  D.CUIIO
  
 