SELECT
  A.NR_TABLE, 
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  TO_CHAR(ROWNUM) AS ORDINE,
  TO_CHAR(ROWNUM) AS RIND,
  A.COL1,
  A.COL2,
  A.COL3
FROM
(SELECT
  1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE,
  'CAEM '|| A.CAEM2 AS RIND_DENUMIRE,
  CC.FULL_CODE AS ORDINE,
  A.CAEM2 AS RIND,
  COUNT(CASE WHEN A.RIND IN ('1.1') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.CUIIO END) AS COL1,
  COUNT(CASE WHEN A.RIND IN ('1.2') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.CUIIO END) AS COL2,
  COUNT(CASE WHEN A.RIND IN ('1.3') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.CUIIO END) AS COL3
FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('1.1','1.2','1.3')--AND D.CUIIO=40988116
) A
  
  INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR( C.CODUL,2,4)  = SUBSTR( A.CAEM2,2,4)                  
  INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 
WHERE 
CC.FULL_CODE ='00000;'

AND A.CAEM2 NOT LIKE 'A%' 


 GROUP BY
 CC.FULL_CODE,
 A.CAEM2

 ORDER BY CC.FULL_CODE) A