SELECT

  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.RIND,
  CASE WHEN SUM(D.COL1) = 0 THEN NULL ELSE  SUM(D.COL1) END  AS COL1, 
  CASE WHEN SUM(D.COL2) = 0 THEN NULL ELSE  SUM(D.COL2) END  AS COL2 
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (1061) AND
  D.FORM IN (74) AND 
  D.CAPITOL IN (1197)
  
  
  GROUP BY
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.RIND
 
ORDER BY
  D.CUIIO,
  D.RIND
 