SELECT

A.CUIIO,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.1')  THEN A.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.2')  THEN A.CUIIO END) AS COL2,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.3')  THEN A.CUIIO END) AS COL3
FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('1.1','1.2','1.3')
) A

  
  WHERE 
  A.CAEM2 NOT LIKE 'A%' 
  
  GROUP BY
  A.CUIIO
  HAVING 
  COUNT(DISTINCT CASE WHEN A.RIND IN ('1.2')  THEN A.CUIIO END) > 0 
  

 