SELECT L.CUIIO
FROM USER_BANCU.VW_DATA_ALL_1061 L LEFT JOIN USER_BANCU.VW_DATA_SONDAJ_1061 R ON R.CUIIO = L.CUIIO

WHERE
R.CUIIO IS NULL;



SELECT R.CUIIO
FROM USER_BANCU.VW_DATA_ALL_3_3 L RIGHT JOIN USER_BANCU.VW_DATA_SONDAJ_3_3 R ON R.CUIIO = L.CUIIO

WHERE
L.CUIIO IS NULL;