--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8
--)

SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
NR_TABLE AS NR_SECTIE,
TABLE_DENUMIRE AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
ORDINE  NR_ROW,
ORDINE AS ORDINE,
'111111111' AS DECIMAL_POS, 
RIND_DENUMIRE AS NUME_ROW,
COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8,COL9

FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL1,1) AS COL1,
  ROUND(A.COL2,1) AS COL2,
  ROUND(A.COL3,1) AS COL3,
  ROUND(A.COL4,1) AS COL4,
  ROUND(A.COL5,1) AS COL5,
  ROUND(A.COL6,1) AS COL6,
  ROUND(A.COL7,1) AS COL7,
  ROUND(A.COL8,1) AS COL8,
    ROUND(A.COL1,2)+
  ROUND(A.COL2,2)+
  ROUND(A.COL3,2)+
  ROUND(A.COL4,2)+
  ROUND(A.COL5,2)+
  ROUND(A.COL6,2)+
  ROUND(A.COL7,2)+
  ROUND(A.COL8,2)AS COL9
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
--  SUBSTR(A.CAEM2,1,1),
   SUM(CASE WHEN A.RIND IN ('9.01') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL1,
  SUM(CASE WHEN A.RIND IN ('9.02') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL2,
  SUM(CASE WHEN A.RIND IN ('9.03') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL3,
  SUM(CASE WHEN A.RIND IN ('9.04') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL4,
  SUM(CASE WHEN A.RIND IN ('9.05') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL5,
  SUM(CASE WHEN A.RIND IN ('9.06') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL6,

SUM(CASE WHEN A.RIND IN ('9.07') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL7,
  SUM(CASE WHEN A.RIND IN ('9.08') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL8,
  SUM(CASE WHEN A.RIND IN ('9.09') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL9


FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL_COEF D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('9.01','9.02','9.03','9.04','9.05','9.06','9.07','9.08')--AND D.CUIIO=40988116
) A LEFT JOIN
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2025)
  CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+F+G+H+I+J+L+M+N+R+S' AS RIND, 'Total activitati' AS RIND_DENUMIRE, '0.1' AS ORDINE FROM DUAL UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E' AS RIND, 'Industrie (B+C+D+E)' AS RIND_DENUMIRE, '0.2' AS ORDINE FROM DUAL UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'F' AS RIND, 'Conctruc?ie (F)' AS RIND_DENUMIRE, '129.1' AS ORDINE FROM DUAL UNION
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'G+H+I+J+L+M+N+R+S' AS RIND, 'Servicii (G+H+I+J+L+M+N+R+S)' AS RIND_DENUMIRE, '141.1' AS ORDINE FROM DUAL 

  ) TR
  
    
   WHERE 
  A.CAEM2 NOT LIKE 'A%' 
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND
--  A.CAEM2
--ORDER BY
--  TR.NR_TABLE,
--  TR.ORDINE
UNION

  
  SELECT
  A.NR_TABLE, 
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  TO_CHAR(ROWNUM) AS ORDINE,
  TO_CHAR(ROWNUM) AS RIND,
  A.COL1,
  A.COL2,
  A.COL3,
  A.COL4,
  A.COL5,
  A.COL6,
  A.COL7,
  A.COL8,
  A.COL9
FROM
(SELECT
  1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE,
  'CAEM '|| A.CAEM2 AS RIND_DENUMIRE,
  CC.FULL_CODE AS ORDINE,
  A.CAEM2 AS RIND,
    SUM(CASE WHEN A.RIND IN ('9.01') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL1,
  SUM(CASE WHEN A.RIND IN ('9.02') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL2,
  SUM(CASE WHEN A.RIND IN ('9.03') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL3,
    SUM(CASE WHEN A.RIND IN ('9.04') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL4,
  SUM(CASE WHEN A.RIND IN ('9.05') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL5,
  SUM(CASE WHEN A.RIND IN ('9.06') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL6,
    SUM(CASE WHEN A.RIND IN ('9.07') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL7,
  SUM(CASE WHEN A.RIND IN ('9.08') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL8,
  SUM(CASE WHEN A.RIND IN ('9.09') AND C.FULL_CODE LIKE '%'||CC.CODUL||';%' THEN A.COL1 END) AS COL9

FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5,
  D.COL6,
  D.COL7,
  D.COL8,
  D.COL9
FROM 
  CIS2.VW_DATA_ALL_COEF D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('9.01','9.02','9.03','9.04','9.05','9.06','9.07','9.08')--AND D.CUIIO=40988116
) A
  
  INNER JOIN CIS2.VW_CL_CAEM2 C ON SUBSTR( C.CODUL,2,4)  = SUBSTR( A.CAEM2,2,4)                  
  INNER JOIN CIS2.VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
 
WHERE CC.FULL_CODE ='00000;'
AND A.CAEM2 NOT LIKE 'A%' 
 GROUP BY
 CC.FULL_CODE,
 A.CAEM2

 ORDER BY CC.FULL_CODE) A
) A


WHERE 
A.ORDINE IN (0.1)

ORDER BY
  A.NR_TABLE,
  A.ORDINE
) 