SELECT
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  
  R.IDNO,
  R.DENUMIRE DENUMIRE_CUIIO,
  R.CFP, 
  D.RIND,
  NULL AS COL1,
  NULL AS COL2,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL2 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL3 ELSE 0 END),1) AS COL5,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL4 ELSE 0 END),1) AS COL6,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL5 ELSE 0 END),1) AS COL7,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL6 ELSE 0 END),1) AS COL8,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL7 ELSE 0 END),1) AS COL9,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL8 ELSE 0 END),1) AS COL10,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL9 ELSE 0 END),1) AS COL11,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL10 ELSE 0 END),1) AS COL12,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL11 ELSE 0 END),1) AS COL13,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1035) THEN D.COL12 ELSE 0 END),1) AS COL14
         
 
  

    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (1035)
    AND D.RIND IN ('0000000')
--     AND
--   D.CUIIO= 38923807 
   
    
GROUP BY 
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO