SELECT DISTINCT

'Rind.' ||D.RIND||': '||
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL  IN(1142) THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END))||'<>'||
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA -1 ) AND D.CAPITOL  IN(1142) THEN NVAL(D.COL7) + NVAL(D.COL8) ELSE 0 END)) 

 
AS REZULTAT
FROM
CIS2.VW_DATA_ALL D
                        
WHERE
    (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)          ) AND
    (D.CUIIO=:CUIIO ) AND
    (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS <>  :CUIIO_VERS ) AND
    (D.FORM=:FORM ) AND
    (D.FORM_VERS=:FORM_VERS ) AND
    (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
    (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND          
    D.FORM     IN(67) AND
    D.CAPITOL  IN(1142) 
    AND D.RIND IN ('700','760')    
  GROUP BY D.RIND
    

  HAVING
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL  IN(1142) THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE NULL END)) <>
NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA -1 ) AND D.CAPITOL  IN(1142) THEN NVAL(D.COL7) + NVAL(D.COL8) ELSE NULL END)) 

AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO  ) AND
   D.FORM  IN(67)) IS NOT NULL
   
   AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO  ) AND
   D.FORM  IN(67)) IS NOT NULL

