SELECT DISTINCT

'Rind.' ||D.RIND||': '||
SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL  IN(1141) THEN D.COL1 ELSE 0 END)||'<>'||
SUM(CASE WHEN D.PERIOADA IN (:PERIOADA -1 ) AND D.CAPITOL  IN(1141) THEN D.COL5 ELSE 0 END) 

 
AS REZULTAT
FROM
CIS2.VW_DATA_ALL D
                        
WHERE
    (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)          ) AND
    (D.CUIIO=:CUIIO ) AND
    (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS <>  :CUIIO_VERS ) AND
    (D.FORM=:FORM ) AND
    (D.FORM_VERS=:FORM_VERS ) AND
    (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
    (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND          
    D.FORM     IN(67) AND
    D.CAPITOL  IN(1141) 
    AND D.RIND IN ('500','560')    
  GROUP BY D.RIND
    

  HAVING
SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CAPITOL  IN(1141) THEN D.COL1 ELSE NULL END) <>
SUM(CASE WHEN D.PERIOADA IN (:PERIOADA -1 ) AND D.CAPITOL  IN(1141) THEN D.COL5 ELSE NULL END) 

