SELECT DISTINCT

 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1139) AND D.RIND  IN('070') THEN D.COL7 ELSE 0 END)) ||'<>'||
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1141) AND D.RIND  IN('541') THEN D.COL5 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1141) AND D.RIND  IN('551') THEN D.COL5 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('741') THEN D.COL7 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('751') THEN D.COL7 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('741') THEN D.COL8 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('751') THEN D.COL8 ELSE 0 END)))

AS REZULTAT

FROM
CIS2.VW_DATA_ALL_TEMP D                                    
WHERE
    (D.PERIOADA=:PERIOADA          ) AND
    (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
    (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
    (D.FORM=:FORM                 OR :FORM = -1) AND
    (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
    (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
    (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND          
    D.FORM     IN(67) AND
    D.CAPITOL  IN(1139,1141,1142) 
    
  HAVING
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1139) AND D.RIND  IN('070') THEN D.COL7 ELSE 0 END)) <>
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1141) AND D.RIND  IN('541') THEN D.COL5 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1141) AND D.RIND  IN('551') THEN D.COL5 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('741') THEN D.COL7 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('751') THEN D.COL7 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('741') THEN D.COL8 ELSE 0 END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL  IN(1142) AND D.RIND  IN('751') THEN D.COL8 ELSE 0 END)))

AND  
   
 ( 
 
 
 SELECT
  DISTINCT
  D.CUIIO
 FROM
  CIS2.VW_DATA_ALL_TEMP D
 WHERE
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
   D.FORM  IN(67)AND D.CAPITOL IN (1139)
   
    GROUP BY
      D.CUIIO
      
      HAVING 
      
      SUM (CASE WHEN D.CAPITOL IN (1139) THEN (CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7))ELSE 0 END)  <> 0
 
   
   ) IS NOT NULL
   
   
   
   
   
--   AND      
--   
-- ( SELECT
--  
--  
--  SUM (CASE WHEN D.CAPITOL IN (1139) THEN (CIS2.NVAL(D.COL2)+CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL5)+CIS2.NVAL(D.COL6)+CIS2.NVAL(D.COL7))ELSE 0 END) 
--  
--  AS REZULTAT
-- FROM
--  CIS2.VW_DATA_ALL_TEMP D
-- WHERE
--  (D.PERIOADA IN (:PERIOADA)) AND
--  (D.CUIIO=:CUIIO OR :CUIIO = -1) AND
--   D.FORM IN(67) AND D.CAPITOL IN (1139))<>0) 