SELECT 
    D.ANUL,
    D.CUIIO,
    R.DENUMIRE,
    R.GEN_INSTITUTIE,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL4 ELSE NULL END ) AS COL2,
    SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN D.COL5 ELSE NULL END ) AS COL3,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL1 = 1 THEN D.CUIIO ELSE NULL  END  ) AS COL4,   
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL1 = 2 THEN D.CUIIO ELSE NULL  END  ) AS COL5,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL1 = 3 THEN D.CUIIO ELSE NULL  END  ) AS COL6,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL2 = 1 THEN D.CUIIO ELSE NULL  END  ) AS COL7,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL2 = 2 THEN D.CUIIO ELSE NULL  END  ) AS COL8,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL3 = 1 THEN D.CUIIO ELSE NULL  END  ) AS COL9,
    COUNT (DISTINCT CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) AND  D.COL3 = 2 THEN D.CUIIO ELSE NULL  END  ) AS COL10,
    ROUND(SUM(CASE WHEN D.RIND IN ('100') AND D.CAPITOL IN (1079) THEN  D.COL6 ELSE NULL END ),1) AS COL11
   
   
   FROM   CIS2.VW_DATA_ALL D 
 
               INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS --AND R.GEN_INSTITUTIE IN ('2')
               )
                
               
                 WHERE 
  --(D.PERIOADA =:pPERIOADA) AND
  D.ANUL IN (2023,2022,2021,2020,2019,2018,2017,2016) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1079)
  
  GROUP BY
     D.CUIIO,
     R.DENUMIRE,
    R.GEN_INSTITUTIE,
    D.ANUL
    
    
    ORDER BY
    D.ANUL,
    R.GEN_INSTITUTIE,
    D.CUIIO