  SELECT 
    D.ANUL,
    D.CUIIO,
    R.DENUMIRE,
    R.GEN_INSTITUTIE,
    SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE NULL END )  AS COL1,
    SUM(CASE WHEN D.RIND IN ('20') THEN D.COL2 ELSE NULL END )  AS COL2,
    SUM(CASE WHEN D.RIND IN ('30') THEN D.COL2 ELSE NULL END )  AS COL3,
    SUM(CASE WHEN D.RIND IN ('40') THEN D.COL2 ELSE NULL END )  AS COL4,
    SUM(CASE WHEN D.RIND IN ('50') THEN D.COL2 ELSE NULL END )  AS COL5,
    SUM(CASE WHEN D.RIND IN ('60') THEN D.COL2 ELSE NULL END )  AS COL6
    
   
   FROM   CIS2.VW_DATA_ALL D 

                 INNER JOIN CIS2.RENIM R ON (R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS)
                
               
                 WHERE 
     D.ANUL IN (2023,2022,2021,2020,2019,2018,2017,2016) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
  D.FORM = 55  AND D.CAPITOL IN (1078)
  
  
   GROUP BY
     D.CUIIO,
     R.DENUMIRE,
    R.GEN_INSTITUTIE,
    D.ANUL
    
    
    ORDER BY
    D.ANUL,
    R.GEN_INSTITUTIE,
    D.CUIIO
  
 