DECLARE

  CURSOR C IS

SELECT 
    DF.PERIOADA,
    DF.FORM,
    DF.FORM_VERS,
    DF.ID_MDTABLE,
    DF.COD_CUATM,
    DF.NR_SECTIE,
    DF.NUME_SECTIE,
    DF.NR_SECTIE1,
    DF.NUME_SECTIE1,
    DF.NR_SECTIE2,
    DF.NUME_SECTIE2,
    DF.NR_ROW  NR_ROW,
    DF.ORDINE,
    DF.DECIMAL_POS,
    DF.NUME_ROW,
    DF.COL1,
    DF.COL2,
    DF.COL3,
    DF.COL4,
    DF.COL5, DF.COL6, DF.COL7,DF. COL8, DF.COL9, DF.COL10, DF.COL11
   
    
    
FROM 
(



SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  MR.RIND AS NR_ROW,
  MR.ORDINE AS ORDINE,
  '00200200200' AS DECIMAL_POS, 
  REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'<br>'),'nbsp'),'&;') AS NUME_ROW,
    
     SUM(CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL5)) AS COL1,
     SUM(CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)) AS COL2,
     
     ROUND(SUM(CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL5))),2) AS COL3,
       
     
    SUM(D.COL3)  AS COL4,
    SUM(D.COL4)  AS COL5, 
    
    ROUND(SUM( CIS2.NVAL(D.COL4)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL3))),2) AS COL6, 
    SUM(CIS2.NVAL(D.COL5))  AS COL7,
    SUM(CIS2.NVAL(D.COL6))  AS COL8, 
    ROUND(SUM(CIS2.NVAL(D.COL6)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL5))),2) AS COL9, 
    SUM( CIS2.NVAL(D.COL7)) AS COL10, 
    SUM(CIS2.NVAL(D.COL8) )  AS COL11 
FROM 
  VW_DATA_ALL D
  RIGHT JOIN MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (54)                 AND 
  MR.CAPITOL IN (1075)  AND 
  MR.RIND_VERS = 2008
   AND MR.RIND  IN ('10','11','12','13','14','15','16','17','18','19','140','141','20','70','80','81','100','110','111','112','115','113','150','130','131') 
  
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE

   
)DF;
   
   
   
    
  BEGIN

  FOR CR IN C
  
  LOOP
    INSERT INTO 
              
           --   TABLE_OUT_TEST
    CIS2.TABLE_OUT
    (
      
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11
  
    )
    VALUES
    (
  CR.PERIOADA,
  CR.FORM,
  CR.FORM_VERS,
  CR.ID_MDTABLE,
  CR.COD_CUATM,
  CR.NR_SECTIE,
  CR.NUME_SECTIE,
  CR.NR_SECTIE1,
  CR.NUME_SECTIE1,
  CR.NR_SECTIE2,
  CR.NUME_SECTIE2,
  CR.NR_ROW,
  CR.ORDINE,
  CR.DECIMAL_POS,
  CR.NUME_ROW,  
  CR.COL1, CR.COL2, CR.COL3, CR.COL4, CR.COL5, CR.COL6, CR.COL7, CR.COL8, CR.COL9, CR.COL10, CR.COL11
  
    );
  END LOOP;
END;
  