

SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  MR.RIND AS NR_ROW,
  MR.ORDINE AS ORDINE,
  '00200200200' AS DECIMAL_POS, 
  REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'<br>'),'nbsp'),'&;') AS NUME_ROW,
    
     SUM(CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL5)) AS COL1,
     SUM(CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)) AS COL2,
     
     ROUND(SUM(CIS2.NVAL(D.COL4)+CIS2.NVAL(D.COL6)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL3)+CIS2.NVAL(D.COL5))),2) AS COL3,
       
     
    SUM(D.COL3)  AS COL4,
    SUM(D.COL4)  AS COL5, 
    
    ROUND(SUM( CIS2.NVAL(D.COL4)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL3))),2) AS COL6, 
    SUM(CIS2.NVAL(D.COL5))  AS COL7,
    SUM(CIS2.NVAL(D.COL6))  AS COL8, 
    ROUND(SUM(CIS2.NVAL(D.COL6)) / CIS2.NOZERO(SUM(CIS2.NVAL(D.COL5))),2) AS COL9, 
    SUM( CIS2.NVAL(D.COL7)) AS COL10, 
    SUM(CIS2.NVAL(D.COL8) )  AS COL11 
FROM 
  VW_DATA_ALL D
  RIGHT JOIN (
  SELECT 
      D.*
            FROM CIS2.MD_RIND D  INNER JOIN (
            
            SELECT 
  RIND,
  MAX(RIND_VERS) RIND_VERS

FROM CIS2.MD_RIND

WHERE 
capitol=1075 AND capitol_vers=2000

GROUP BY 
RIND

            )DD ON DD.RIND = D.RIND AND DD.RIND_VERS = D.RIND_VERS
            
            
            
            WHERE 
            
            D.capitol=1075 AND D.capitol_vers=2000
            
            AND D.STATUT = '1'
            AND D.RIND NOT IN ('-','--')
            
            ORDER BY 
            D.ORDINE
            
  ) MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')

  
WHERE
  MR.FORM IN (54)                 AND 
  MR.CAPITOL IN (1075)  

   
  
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE


ORDER BY
MR.ORDINE
   
