  SELECT
  L.COD_SPEC,
  L.COD_SPEC_MOD,
  L.DENUMIRE,
  L.GROUP_SPEC,  
  L.STATUT,
  L.ORDINE,
  L.NIVEL   

FROM

(
SELECT
  S1.COD_SPEC,
  REPLACE(S1.COD_SPEC, '.', '') AS COD_SPEC_MOD,
  S1.DENUMIRE,
  S1.GROUP_SPEC,  
  S1.STATUT,
  S1.ORDINE,
  S1.NIVEL     

FROM USER_BANCU.CL_SPEC_2EDU_24 S1 )L  LEFT JOIN (

SELECT 
    CODUL,
    CASE WHEN LTRIM(TRIM(CODUL), '0') IS NULL THEN '0' ELSE LTRIM(TRIM(CODUL), '0') END AS CODUL_MOD,  
    DENUMIRE, 
    GRUPA, 
    FULL_CODE, 
    ORDINE
FROM VW_CL_SPEC_2EDU_24
) R ON L.COD_SPEC_MOD = R.CODUL_MOD

WHERE

R.CODUL_MOD IS NULL