INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3,COL4,COL5,COL6,COL7,COL8, COL9,COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17
)

SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
   R.NFI AS NR_SECTIE,
   NF.DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  MR.RIND AS NR_ROW,
  MR.ORDINE AS ORDINE,
  '00000000000000000' AS DECIMAL_POS,
  MR.DENUMIRE AS NUME_ROW,
  SUM(D.COL1) AS COL1,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  SUM(D.COL5) AS COL5,
  SUM(D.COL6) AS COL6,
  SUM(D.COL7) AS COL7,
  SUM(D.COL8) AS COL8,
  SUM(D.COL9) AS COL9,
  SUM(D.COL10) AS COL10,
  SUM(D.COL11) AS COL11,
  SUM(D.COL12) AS COL12, 
  SUM(D.COL13) AS COL13,
  SUM(D.COL14) AS COL14,
  SUM(D.COL15) AS COL15,
  SUM(D.COL16) AS COL16,
  SUM(D.COL17) AS COL17
  
FROM 
  CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.MD_RIND MR ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL) 
  INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
  INNER JOIN CIS2.CL_NFI NF ON R.NFI=NF.CODUL
 
 WHERE 
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  MR.FORM IN (50) AND 
  MR.CAPITOL IN (1058) AND
  D.RIND NOT IN ('090','100','110','120') AND
  (D.RIND LIKE ('0%') OR 
  
   (D.RIND LIKE ('0%') OR MR.ORDINE >= 7000)
  
  )
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE,
  R.NFI,
  NF.DENUMIRE
  
  ORDER BY  R.NFI,MR.RIND