SELECT 
    CODUL,
    CASE WHEN LTRIM(TRIM(CODUL), '0') IS NULL THEN '0' ELSE LTRIM(TRIM(CODUL), '0') END AS CODUL_MOD,  
    DENUMIRE, 
    GRUPA, 
    FULL_CODE, 
    ORDINE
FROM VW_CL_SPEC_2EDU_24;
