SELECT
D.CUIIO|| ' - Raportul nu este completat pentru anul 2024 '
 
  AS REZULTAT

FROM
 USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE D 
WHERE
   D.PERIOADA IN (:PERIOADA) AND  
  (D.CUIIO=:CUIIO ) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR  :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
    
  D.FORM IN (48)  AND
  D.ID_SCHEMA IN (2)
 
GROUP BY 
D.CUIIO

HAVING
:PERIOADA  < 2013