SELECT
  --'Nu ati completat Rind. 3.1.1 - 3.1.3' AS REZULTAT
  
   SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  AND D.COL31 IS NULL THEN 1 ELSE 0 END) AS REZ_1,
   
    MAX(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  THEN D.COL31   ELSE NULL   END)  AS REZ_2,
    
    
    MAX(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  THEN LENGTH(D.COL31)      END)  AS REZ_3,
    
    MAX(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  THEN LENGTHB (D.COL31)      END)  AS REZ_4,
    
    MAX(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  THEN LENGTHC  (D.COL31)      END)  AS REZ_5

FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL = :CAPITOL           OR :CAPITOL <>  :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (48)  

--HAVING
--
--
--SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1048.9.2')  AND D.COL31 IS NULL THEN 1 ELSE 0 END) = 1 
  
  
