
SELECT
--  NR_SECTIE AS NR_ROW,
--  NR_SECTIE AS ORDINE,
--  '000000000' AS DECIMAL_POS,
--  NUME_SECTIE AS NUME_ROW,
  SUM(COL9) AS COL1,
  SUM(COL7) AS COL2
--  SUM(COL1) AS COL2,
--  SUM(COL2) AS COL3, 
--  SUM(COL3) AS COL4, 
--  SUM(COL4) AS COL5, 
--  SUM(COL5) AS COL6, 
--  SUM(COL6) AS COL7,
--  SUM(COL7) AS COL8,
--  SUM(COL8) AS COL9  


   
FROM
(

SELECT
  DISTINCT D.CUIIO,
  CIS2.NVAL(COUNT( DISTINCT CASE WHEN   (D.CAPITOL IN (100)  AND D.RIND  IN ('02','03','04','05','06','07')) THEN D.CUIIO  END )) AS COL9,
  CIS2.NVAL(COUNT( DISTINCT CASE WHEN    D.CAPITOL||'.'||D.RIND IN ('100.02','100.03','100.04','100.05','100.06','100.07')THEN D.CUIIO END )) AS COL7
  
  FROM 
  CIS2.VW_DATA_ALL D  
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND  

  D.FORM IN (48)  
--  AND  (D.CAPITOL IN (100)  AND D.RIND  IN ('02','03','04','05','06''07'))
  
GROUP BY  

  
  D.CUIIO
  
  
--  HAVING 
--  CIS2.NVAL(COUNT( DISTINCT CASE WHEN   (D.CAPITOL IN (100)  AND D.RIND  IN ('02','03','04','05','06''07')) THEN D.CUIIO  END )) > 0

  
  )

  
