SELECT
D.CUIIO,

COUNT (D.RIND) AS CNT 
  
   
  FROM 
  CIS2.VW_DATA_ALL D  
   
  INNER JOIN CIS2.VW_CL_CUATM CC ON (D.CUATM=CC.CODUL)
    
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND  

  D.FORM IN (48)
  AND 
D.CAPITOL||'.'||D.RIND IN ('100.01','100.02','100.03','100.04','100.05','100.06','100.07')

GROUP BY 

    D.CUIIO


HAVING 
COUNT (D.RIND) = 1
    
    ORDER BY 
    D.CUIIO