--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1,COL2, COL3
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' as NR_SECTIE2,
  '0' as NUME_SECTIE2,
  NR_ROW AS NR_ROW,
  ORDINE AS ORDINE,
  '000' AS DECIMAL_POS,
  NUME_ROW AS NUME_ROW ,
  SUM(COL1) AS COL1, 
  SUM(COL2) AS COL2, 
  SUM(COL3) AS COL3

--     
FROM
(
SELECT
  D.RIND AS NR_ROW,
  R.DENUMIRE AS NUME_ROW,
  D.CUIIO,
  R.ORDINE,
    
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL1 ELSE NULL END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL2 ELSE NULL END)) AS COL2,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL3 ELSE NULL END)) AS COL3

  
  FROM 
  CIS2.VW_DATA_ALL D  
  INNER JOIN CIS2.MD_RIND R ON D.RIND=R.RIND AND R.FORM=D.FORM AND R.CAPITOL=D.CAPITOL

  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND  
  D.FORM IN (48)  AND D.CAPITOL IN (1045)
  AND D.RIND NOT IN ('6.1.1')

  
GROUP BY  
  D.RIND,
  R.DENUMIRE,
  D.CUIIO,
  R.ORDINE
  )
  
  
  GROUP BY
  NR_ROW,
  NUME_ROW,
  ORDINE
  
   
   UNION
   
   SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' as NR_SECTIE2,
  '0' as NUME_SECTIE2,
  NR_ROW AS NR_ROW,
  ORDINE AS ORDINE,
  '000' AS DECIMAL_POS,
  NUME_ROW AS NUME_ROW ,
  SUM(COL1) AS COL1, 
  SUM(COL2) AS COL2, 
  SUM(COL3) AS COL3

--     
FROM
(
SELECT
  '1' AS NR_ROW,
  'Total' AS NUME_ROW,  
  1 as ORDINE,
    
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL1 ELSE NULL END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL2 ELSE NULL END)) AS COL2,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1045') AND D.COL1=1  THEN D.COL3 ELSE NULL END)) AS COL3

  
  FROM 
  CIS2.VW_DATA_ALL D  
  INNER JOIN CIS2.MD_RIND R ON D.RIND=R.RIND AND R.FORM=D.FORM AND R.CAPITOL=D.CAPITOL

  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND   
  D.FORM= :pFORM     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND  
  D.FORM IN (48)  AND D.CAPITOL IN (1045)
  AND D.RIND NOT IN ('6.1.1')


  )
  
  
  GROUP BY
  NR_ROW,
  NUME_ROW,
  ORDINE
  
  ORDER BY 
   NR_ROW