--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   ORDINE ||'~'|| DENUMIRE AS NR_ROW,
   ORDINE AS ORDINE,
  '11' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW,
  COL1,
  NULL AS COL2
   
FROM
(
SELECT
    TR.DENUMIRE,
    TR.ORDINE,
    ROUND(SUM(
    CASE 
        WHEN 
            TR.CONDITIE IN ('BETWEEN') AND TR.CAEM2 LIKE '%'|| SUBSTR(D.CAEM2,0,1) ||'%' AND  D.PERS_IT BETWEEN (SUBSTR(TR.RESULT,0,INSTR(RESULT,'-')-1)) AND (SUBSTR(TR.RESULT,INSTR(TR.RESULT,'-')+1,LENGTH(TR.RESULT))) 
        THEN D.COL1_1/100000 END),1) AS COL1

FROM 
  (
    SELECT DISTINCT
      D.CUIIO,
      D.CAEM2,
      BS.PERS_IT,
      CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.3.3','1041.2.3.4')   THEN D.COL1 *BS.CIF_IT ELSE NULL END)) AS COL1_1
    FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN
      CIS2.X_BAZA_SONDAJ BS ON D.CUIIO=BS.CUIIO AND D.ANUL=BS.ANUL
    WHERE
      D.PERIOADA IN (:pPERIOADA) AND 
      D.FORM_VERS = :pFORM_VERS     AND   
      D.FORM= :pFORM     AND    
      (:pID_MDTABLE=:pID_MDTABLE) AND
      D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  AND 
      D.FORM IN (48)
    GROUP BY
      D.CUIIO,
      D.CAEM2,
      BS.PERS_IT
  ) D
CROSS JOIN
 (
SELECT 'Total' AS DENUMIRE, 1 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E+G46+H+J+K+M71+M72+M73' AS CAEM2, '0-99999999999' AS RESULT FROM DUAL UNION 
SELECT '10-49 salariati' AS DENUMIRE, 2 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E+G46+H+J+K+M71+M72+M73' AS CAEM2, '0-49' AS RESULT FROM DUAL UNION 
SELECT '50-249 salariati' AS DENUMIRE, 3 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E+G46+H+J+K+M71+M72+M73' AS CAEM2, '50-249' AS RESULT FROM DUAL UNION 
SELECT '250 si peste salariati' AS DENUMIRE, 4 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E+G46+H+J+K+M71+M72+M73' AS CAEM2, '250-99999999999' AS RESULT FROM DUAL UNION
SELECT 'Industrie - total' AS DENUMIRE, 5 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E' AS CAEM2, '0-99999999999' AS RESULT FROM DUAL UNION 
SELECT '10-49 salariati' AS DENUMIRE, 6 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E' AS CAEM2, '0-49' AS RESULT FROM DUAL UNION 
SELECT '50-249 salariati' AS DENUMIRE, 7 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E' AS CAEM2, '50-249' AS RESULT FROM DUAL UNION 
SELECT '250 si peste salariati' AS DENUMIRE, 8 AS ORDINE, 'BETWEEN' AS CONDITIE, 'B+C+D+E' AS CAEM2, '250-99999999999' AS RESULT FROM DUAL UNION
SELECT 'Servicii - total' AS DENUMIRE, 9 AS ORDINE, 'BETWEEN' AS CONDITIE, 'G46+H+J+K+M71+M72+M73' AS CAEM2, '0-99999999999' AS RESULT FROM DUAL UNION 
SELECT '10-49 salariati' AS DENUMIRE, 10 AS ORDINE, 'BETWEEN' AS CONDITIE, 'G46+H+J+K+M71+M72+M73' AS CAEM2, '0-49' AS RESULT FROM DUAL UNION 
SELECT '50-249 salariati' AS DENUMIRE, 11 AS ORDINE, 'BETWEEN' AS CONDITIE, 'G46+H+J+K+M71+M72+M73' AS CAEM2, '50-249' AS RESULT FROM DUAL UNION 
SELECT '250 si peste salariati' AS DENUMIRE, 12 AS ORDINE, 'BETWEEN' AS CONDITIE, 'G46+H+J+K+M71+M72+M73' AS CAEM2, '250-99999999999' AS RESULT FROM DUAL
) TR
GROUP BY
  TR.DENUMIRE,
  TR.ORDINE)
  
  ORDER BY
  ORDINE