--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1,COL2,COL3
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,    
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   ORDINE ||'~'|| DENUMIRE AS NR_ROW,
   ORDINE AS ORDINE,
  '111' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW, 
  COL1, 
  COL2,
  COL3
  
FROM
(
SELECT
    TR.DENUMIRE,
    TR.ORDINE, 
    ROUND(SUM(CASE WHEN TR.CONDITIE IN ('LIKE') AND TR.RESULT LIKE '%'|| SUBSTR(D.CAEM2,0,1) ||'%' THEN D.COL1_1/100000 END),1) AS COL1,
    ROUND(SUM(CASE WHEN TR.CONDITIE IN ('LIKE') AND TR.RESULT LIKE '%'|| SUBSTR(D.CAEM2,0,1) ||'%' THEN D.COL2_1/100000 END),1) AS COL2,
    ROUND(SUM(CASE WHEN TR.CONDITIE IN ('LIKE') AND TR.RESULT LIKE '%'|| SUBSTR(D.CAEM2,0,1) ||'%' THEN D.COL3_1/100000 END),1) AS COL3
FROM 
  (
    SELECT DISTINCT
      D.CUIIO,
      D.CAEM2,
      CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.3.3','1041.2.3.4')   THEN D.COL1 *BS.CIF_IT ELSE NULL END)) AS COL1_1,
      CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.3.3')             THEN D.COL1*BS.CIF_IT  ELSE NULL END)) AS COL2_1,
      CIS2.NVAL(SUM(CASE WHEN D.CAPITOL||'.'||D.RIND IN ('1041.2.3.4')            THEN D.COL1*BS.CIF_IT ELSE NULL END)) AS COL3_1
    FROM
      CIS2.VW_DATA_ALL D  
        INNER JOIN
        CIS2.X_BAZA_SONDAJ BS ON D.CUIIO=BS.CUIIO AND D.ANUL = BS.ANUL
    WHERE
      D.PERIOADA IN (:pPERIOADA) AND 
      D.FORM_VERS = :pFORM_VERS     AND   
      D.FORM= :pFORM     AND    
      (:pID_MDTABLE=:pID_MDTABLE) AND
      D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  AND 
      D.FORM IN (48)
    GROUP BY
      D.CUIIO,
      D.CAEM2
  ) D

CROSS JOIN
 (
SELECT 'Total' AS DENUMIRE, 1 AS ORDINE, 'LIKE' AS CONDITIE, 'B+C+D+E+G46+H+J+K+M71+M72+M73' AS RESULT FROM DUAL UNION 
SELECT 'Industrie - total' AS DENUMIRE, 2 AS ORDINE, 'LIKE' AS CONDITIE, 'B+C+D+E' AS RESULT FROM DUAL UNION 
SELECT 'Industrie extractiva' AS DENUMIRE, 3 AS ORDINE, 'LIKE' AS CONDITIE, 'B' AS RESULT FROM DUAL UNION 
SELECT 'Industrie prelucratoare' AS DENUMIRE, 4 AS ORDINE, 'LIKE' AS CONDITIE, 'C' AS RESULT FROM DUAL UNION
SELECT 'Productia si furnizarea de energie electrica si termica, gaze, apa calda si aer conditionat' AS DENUMIRE, 5 AS ORDINE, 'LIKE' AS CONDITIE, 'D' AS RESULT FROM DUAL UNION
SELECT 'Distributia apei; salubritate, gestionarea deseurilor, activitati de decontaminare ' AS DENUMIRE, 6 AS ORDINE, 'LIKE' AS CONDITIE, 'E' AS RESULT FROM DUAL UNION
SELECT 'Servicii - total ' AS DENUMIRE, 7 AS ORDINE, 'LIKE' AS CONDITIE, 'G46+H+K+J+M71+M72+M73' AS RESULT FROM DUAL UNION
SELECT 'Comert cu ridicata ' AS DENUMIRE, 8 AS ORDINE, 'LIKE' AS CONDITIE, 'G46' AS RESULT FROM DUAL UNION
SELECT 'Transport si depozitare ' AS DENUMIRE, 9 AS ORDINE, 'LIKE' AS CONDITIE, 'H' AS RESULT FROM DUAL UNION
SELECT 'Informatii si comunicatii ' AS DENUMIRE, 10 AS ORDINE, 'LIKE' AS CONDITIE, 'J' AS RESULT FROM DUAL UNION
SELECT 'Activitati  financiare si asigurari  ' AS DENUMIRE, 11 AS ORDINE, 'LIKE' AS CONDITIE, 'K' AS RESULT FROM DUAL UNION
SELECT 'Activitati profesionale, stiintifice si tehnice ' AS DENUMIRE, 12 AS ORDINE, 'LIKE' AS CONDITIE, 'M71+M72+M73' AS RESULT FROM DUAL 
) TR
GROUP BY
  TR.DENUMIRE,
  TR.ORDINE
)

ORDER BY 
ORDINE 
  
  