SELECT

  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '002' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   COL1,
   COL2,
   COL3

FROM
( 
SELECT
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE,
SUM(L.COL2) AS COL1,
SUM(L.COL1) AS COL2,
ROUND(SUM(L.COL2) / SUM(L.COL1),2) AS COL3 
FROM
(
SELECT
L.CUIIO,
L.CUIIO_VERS,
L.CUATM,
SUM(L.COL1) COL1,
SUM(R.COL1) COL2
FROM 

(
SELECT
D.CUIIO,
D.CUIIO_VERS,
D.CUATM,
COUNT(DISTINCT CASE WHEN D.CAPITOL = 1195 AND D.RIND IN ('1') AND  NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END ) AS COL1

    FROM
      CIS2.VW_DATA_ALL D     
                   
            
       WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  

       D.FORM = 71 AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
       AND D.CAPITOL = 1195 AND D.RIND IN ('1') AND  NVAL(D.COL1) = 1

        GROUP BY 
        D.CUIIO,
        D.CUATM,
        D.CUIIO_VERS ) L LEFT JOIN (
        
        SELECT
D.CUIIO,
D.CUIIO_VERS,
D.CUATM,
SUM(CASE WHEN D.CAPITOL = 1206 AND D.RIND IN ('900') THEN NVAL(D.COL1) ELSE 0 END ) AS COL1

    FROM
      CIS2.VW_DATA_ALL D     
                   
            
       WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  

       D.FORM = 71 AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
       AND D.CAPITOL = 1206 AND D.RIND IN ('900') 
       AND NVAL(D.COL1) > 0
   

        GROUP BY 
        D.CUIIO,
        D.CUATM,
        D.CUIIO_VERS
        ) R  ON R.CUIIO = L.CUIIO AND R.CUIIO_VERS = L.CUIIO_VERS
        
        
       WHERE 
       R.CUIIO IS NOT NULL  
       GROUP BY
       L.CUIIO,
       L.CUIIO_VERS,
       L.CUATM ) L  
       
       INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = L.CUATM
       INNER JOIN CIS2.VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||';%' 
       
       WHERE
       CC.PRGS IN ('2')
       
       GROUP BY 
       CC.CODUL,
       CC.DENUMIRE,
       CC.FULL_CODE
       
       ORDER BY
       CC.FULL_CODE
       ) 
       