SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM  AS ORDINE,
  '002' AS DECIMAL_POS,
   DENUMIRE NUME_ROW,
COL1,
COL2,
ROUND(COL1/COL2,2) AS COL3
FROM
(
SELECT
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE,

SUM(DD.COL2) AS COL1,
COUNT(DISTINCT CASE WHEN D.CAPITOL = 1195 AND D.RIND IN ('1') AND  NVAL(D.COL1) = 1 THEN D.CUIIO ELSE 0 END ) AS COL2

    FROM
      CIS2.VW_DATA_ALL D     
                   
                   INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
                   
                   INNER JOIN (
                   
                   SELECT
DISTINCT 
D.CUIIO,
D.CUIIO_VERS,
SUM(CASE WHEN D.CAPITOL = 1206 AND D.RIND IN ('900') THEN D.COL1 ELSE 0 END ) AS COL2
  FROM
      CIS2.VW_DATA_ALL D     
                   
       WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1206)  AND D.RIND IN ('900')
       
GROUP BY  
D.CUIIO,
D.CUIIO_VERS

                   ) DD ON D.CUIIO = DD.CUIIO AND D.CUIIO_VERS = DD.CUIIO_VERS 
                   
                   
                   INNER JOIN CIS2.VW_CL_CUATM C  ON  C.CODUL = D.CUATM 
                   INNER JOIN CIS2.VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||';%'

       
    WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
--       D.CAPITOL IN (1206) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
  
      AND CC.PRGS IN ('2')
      
   AND D.CAPITOL = 1195 AND D.RIND IN ('1') AND  NVAL(D.COL1) = 1
    --  AND D.CUIIO = 227548


GROUP BY  
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE

ORDER BY
CC.FULL_CODE
)