SELECT
 -- A.CUIIO,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('10') AND NVAL(A.COL1) IN (1)  THEN A.CUIIO END) AS COL1,
  COUNT(DISTINCT CASE WHEN A.RIND IN ('10') AND NVAL(A.COL2) IN (1)  THEN A.CUIIO END) AS COL2
FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('10')
) A
  INNER JOIN CIS2.VW_CL_CUATM C ON(A.CUATM = C.CODUL)
     WHERE 
  A.CAEM2 NOT LIKE 'A%' 

GROUP BY
A.CUIIO