SELECT
   D.CUIIO, 
  'Cap.1rind 050 (col.7 + col.10) - '|| SUM(CASE WHEN D.CAPITOL IN (1049) AND RIND IN ('050') THEN CIS2.NVAL(D.COL7) +  CIS2.NVAL(D.COL10) ELSE 0 END) ||' - Cap.8 COL  2 ? 1  -'||
  SUM(CASE WHEN D.CAPITOL IN (1056) AND RIND IN ('01') THEN  CIS2.NVAL(D.COL2) ELSE 0 END) 
   AS REZULTAT


FROM CIS2.VW_DATA_ALL D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <>  :CAPITOL ) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (49)  
  AND
  D.CAPITOL IN (1049,1056)
  
GROUP BY
D.CUIIO

HAVING 
SUM(CASE WHEN D.CAPITOL IN (1049)  AND RIND IN ('050') THEN CIS2.NVAL(D.COL7) + CIS2.NVAL(D.COL10)  ELSE 0 END) > 0   
  
AND 
(
SUM(CASE WHEN D.CAPITOL IN (1056) AND RIND IN ('01') THEN  CIS2.NVAL(D.COL2) ELSE 0 END) = 0
OR 
SUM(CASE WHEN D.CAPITOL IN (1056) AND RIND IN ('01') THEN  CIS2.NVAL(D.COL2) ELSE 0 END) = 1
)
 