--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1, COL2, COL3
--)
SELECT DISTINCT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
   B.ORDINE AS NR_SECTIE,
   B.NUME_ROW AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   D.NR_ROW||'~'||D.ORDINE AS NR_ROW,
   D.ORDINE,
  '00000' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' THEN COL1 ELSE NULL END) AS COL1,
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' AND TIP_LOCAL IN (1) THEN COL1 ELSE NULL END) AS COL2, 
   SUM(CASE WHEN B.NR_ROW LIKE '%'|| D.NTII ||'%' AND TIP_LOCAL IN (2) THEN COL1 ELSE NULL END) AS COL3
FROM
(
SELECT
  
  TR.DENUMIRE AS DENUMIRE,
  TR.ORDINE,
--  D.CUIIO,
  R.NTII,
  R.TIP_LOCAL,
  NR_ROW,
  
  CASE 
  --01
    WHEN TR.ORDINE IN (1) THEN 
     COUNT(DISTINCT(CASE WHEN D.RIND IN ('020') AND NVAL(D.COL1) > 0 THEN D.CUIIO END))     
  --02  
    WHEN TR.ORDINE IN (2) THEN
     COUNT(DISTINCT(CASE WHEN D.RIND IN ('020') AND NVAL(D.COL3) > 0   THEN D.CUIIO END))
--   --03 
--    
     WHEN TR.ORDINE IN (3) THEN
     SUM(CASE WHEN D.RIND IN ('020') THEN D.COL1 END)
--  --04
--    
     WHEN TR.ORDINE IN (4) THEN
     SUM(CASE WHEN D.RIND IN ('020') THEN D.COL3 END)
  END AS COL1
  
FROM CIS2.VW_DATA_ALL D
  INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS
  CROSS JOIN 
  (
SELECT 'Numarul de institutii de invatamint echipate cu calculatoare utilizate in scopuri educationale'  AS DENUMIRE, '1'  AS NR_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT ' inclusiv conectate la Internet'                               AS DENUMIRE, '2'  AS NR_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT 'Numarul de calculatoare utilizate in scopuri educationale '      AS DENUMIRE, '3'  AS NR_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT ' inclusiv conectate la Internet'                               AS DENUMIRE, '4'  AS NR_ROW, 4 AS ORDINE FROM DUAL 
  ) TR
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40 AND  
   D.CAPITOL IN (1032) --AND
  -- R.NFI = 1
GROUP BY
  R.NTII,
--  D.CUIIO,
  TR.DENUMIRE,
  TR.ORDINE,
  NR_ROW,
  R.TIP_LOCAL
ORDER BY
  TR.ORDINE
  
  
  
) D
CROSS JOIN
(
SELECT '10+20+21+30+31+40+50' AS NR_ROW,'Total' AS NUME_ROW, 2 AS LENGTH_ROW, 0 AS ORDINE FROM DUAL UNION
SELECT '10' AS NR_ROW,'Scolile primare' AS NUME_ROW, 2 AS LENGTH_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '20+21' AS NR_ROW, 'Gimnazii' AS NUME_ROW, 2 AS LENGTH_ROW, 2 AS ORDINE FROM DUAL UNION 
SELECT '30+31' AS NR_ROW, 'Licee' AS NUME_ROW, 2 AS LENGTH_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '40' AS NR_ROW, 'Scolile pentru copii cu deficiente in dezvoltarea intelectuala sau fizica' AS NUME_ROW, 2 AS LENGTH_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '50' AS NR_ROW, 'Scolile serale' AS NUME_ROW, 2 AS LENGTH_ROW, 5 AS ORDINE FROM DUAL


) B

GROUP BY
  B.NR_ROW,
   B.NUME_ROW,
   D.NR_ROW,

   D.ORDINE,
   DENUMIRE,
   B.ORDINE
  
  
  
  
ORDER BY
  ORDINE