
CREATE TABLE USER_BANCU.CL_SPEC_3EDU_24
(
  COD_SPEC    VARCHAR2(20 BYTE),
  DENUMIREA   VARCHAR2(255 BYTE),
  GRUPA_SPEC  VARCHAR2(255 BYTE),
  STATUT      VARCHAR2(1 BYTE),
  ORDINE      NUMBER,
  NIVEL       NUMBER
)
TABLESPACE TBS_DTI_USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
