SELECT 
DISTINCT D.CUIIO,
SUM(CASE WHEN D.CAPITOL IN (1032) AND D.RIND IN ('020')  THEN NVAL(D.COL1) ELSE 0 END) AS COL1,
SUM(CASE WHEN D.CAPITOL IN (1032) AND D.RIND IN ('020')  THEN NVAL(D.COL3) ELSE 0 END) AS COL3

FROM CIS2.VW_DATA_ALL D 

WHERE 
  (D.PERIOADA =:pPERIOADA) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE)  AND 
  (D.CUATM_FULL LIKE '%' ||:pCOD_CUATM||';%') AND
   D.FORM = 40  
--   D.CAPITOL IN (1032) 

GROUP BY 
D.CUIIO 


--HAVING 
--SUM(CASE WHEN D.CAPITOL IN (1032) AND D.RIND IN ('020')  THEN NVAL(D.COL1) ELSE 0 END) = 0 
--
--
--AND 
--
--SUM(CASE WHEN D.CAPITOL IN (1032) AND D.RIND IN ('020')  THEN NVAL(D.COL3) ELSE 0 END) = 0  
