SELECT DISTINCT
  'Nu satisface conditia' AS REZULTAT
FROM
VW_DATA_ALL  D                                  
WHERE
  (D.PERIOADA=:PERIOADA) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL             OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS   OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
 
  D.FORM = 71
  AND D.CAPITOL IN (1181,1205)
HAVING


(SUM(CASE WHEN D.CAPITOL IN (1181) AND RIND IN ('130')   THEN  D.COL1 ELSE NULL END ) IS  NOT NULL 
AND  
SUM(CASE WHEN  D.CAPITOL IN (1205) AND RIND  IN ('910')   THEN  NVAL(D.COL1) + NVAL(D.COL2) ELSE 0  END )   <>  1)


OR


(
 
  
SUM(CASE WHEN  D.CAPITOL IN (1205) AND RIND  IN ('910')   THEN  NVAL(D.COL1)  ELSE 0  END )   =  1

AND  
SUM(CASE WHEN  D.CAPITOL IN (1205) AND RIND  IN ('921','922','923','924','925','926','927','931','932','933','941','951','961','971')   THEN  NVAL(D.COL1) + NVAL(D.COL2) ELSE 0  END )   <>  14
)



