SELECT 
D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,-------------------------
R.CAEM2,
SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('1') THEN  D.COL1 ELSE NULL END ) CAP_SR_RIND1,
SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('150') THEN  D.COL1 ELSE  NULL END ) RIND_150,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('210') THEN  D.COL1 ELSE NULL END ) RIND_210,
SUM(CASE WHEN D.CAPITOL IN (1127)  AND D.RIND IN ('400') THEN  NVAL(D.COL1) ELSE NULL END ) RIND_400,
SUM(CASE WHEN D.CAPITOL IN (1128)  AND D.RIND IN ('500') THEN  NVAL(D.COL1) ELSE NULL END ) RIND_500
-------------------------------------------------------

FROM   
    CIS2.VW_DATA_ALL D    
     
     
   --  CIS2.VW_DATA_ALL D    
    
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS  
WHERE
  D.FORM IN (64)             AND 
--  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA 
 -- D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  
  --D.CAPITOL IN (1124,1129) 
  
  
  
HAVING 

SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('1') THEN  D.COL1 ELSE NULL END ) = 1

AND 

(

SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('150') THEN  NVAL(D.COL1) ELSE 0 END ) = 0
OR   
--
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('210') THEN  NVAL(D.COL1) ELSE 0 END ) = 0
--
OR  
SUM(CASE WHEN D.CAPITOL IN (1127)  AND D.RIND IN ('400') THEN  NVAL(D.COL1) ELSE 0 END ) = 0 
OR  
SUM(CASE WHEN D.CAPITOL IN (1128)  AND D.RIND IN ('500') THEN  NVAL(D.COL1) ELSE 0 END ) = 0 

) 

GROUP BY 

D.ANUL,
D.CUIIO,
R.IDNO,
R.DENUMIRE,
R.CUATM,
R.CFP,
R.CFOJ,
R.CAEM2

ORDER BY
D.CUIIO