


INSERT INTO RENIM (
CUIIO, CUIIO_VERS, DENUMIRE, EDIT_USER, STATUT, 
 CUATM, CFP, CFOJ, COCM, CAEM, 
 BUGET, TIP, PROD, FOR_CUB, GENMUZEE, 
 TIPMUZEE, TIP_LOCAL, TIP_INST, CAEM2, N85_NTL, 
 N85_NTIIP, N85_NDIIP, N85_NPDS, N85_NRIIP, N85_NSIIP, 
 GENMUZEE2, NFI, NTII, NPDS, ORGANE, 
 TIP_INV, RENIM_PERS, ORGANE_COND, GEN_INSTITUTIE, IDNO

)





                SELECT 
                CUIIO, 
                1058 CUIIO_VERS, DENUMIRE, EDIT_USER, STATUT, 
 CUATM, CFP, CFOJ, COCM, CAEM, 
 BUGET, TIP, PROD, FOR_CUB, GENMUZEE, 
 TIPMUZEE, TIP_LOCAL, TIP_INST, CAEM2, N85_NTL, 
 N85_NTIIP, N85_NDIIP, N85_NPDS, N85_NRIIP, N85_NSIIP, 
 GENMUZEE2, NFI, NTII, NPDS, ORGANE, 
 TIP_INV, RENIM_PERS, ORGANE_COND, GEN_INSTITUTIE, IDNO
                 
                 FROM USER_BANCU.VW_MAX_RENIM_TRIM_CIS2
                 
                 WHERE
                 CUIIO  IN (

38944755,
38956824,
40244054,
40676552,
41477659


) 

AND CUIIO_VERS <> 1058