SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0'AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  ROUND(NVAL(COL1)-NVAL(COL1_1),0)||'~'||ORDINE AS NR_ROW,
  ORDINE,
  '0000000000' AS DECIMAL_POS,
  DENUMIRE||'('||ORDINE||')' AS NUME_ROW,
  ROUND(NVAL(COL2)-NVAL(COL2_1),0) AS COL1,
  ROUND(NVAL(COL3)-NVAL(COL3_1),0) AS COL2,
  ROUND(NVAL(COL4)-NVAL(COL4_1),0) AS COL3,
  ROUND(ROUND(NVAL(COL3)-NVAL(COL3_1),1)/NOZERO(ROUND(NVAL(COL2)-NVAL(COL2_1),1)),1) AS COL4,
  ROUND((NVAL(COL4)-NVAL(COL4_1))/NOZERO(NVAL(COL2)-NVAL(COL2_1)),1) AS COL5,
  ROUND(NVAL(COL5),0) AS COL6,
  ROUND(((NVAL(COL3)+NVAL(COL5)) - NVAL(COL3_1)),0) AS COL7,
  ROUND(((NVAL(COL4)+NVAL(COL5)) - NVAL(COL4_1)),0) AS COL8
FROM
(
SELECT
  R.DENUMIRE,
  TO_NUMBER(R.CUIIO) AS ORDINE,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL1 END)) AS COL1_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL2 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL2 END)) AS COL2_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL3 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL3 END)) AS COL3_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL4 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL4 END)) AS COL4_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL4 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL4 END)) AS COL5_1
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) AND
  D.RIND IN ('1190','1191')
GROUP BY
  R.DENUMIRE,
  R.CUIIO
UNION
SELECT
  'TOTAL' AS DENUMIRE,
  0 AS ORDINE,
 NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL1 END)) AS COL1_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL2 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL2 END)) AS COL2_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL3 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL3 END)) AS COL3_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL4 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL4 END)) AS COL4_1,
  NVAL(SUM(CASE WHEN D.RIND IN ('1190') THEN D.COL4 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('1191') THEN D.COL4 END)) AS COL5_1
 
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) AND
  D.RIND IN ('1190','1191')
);