SELECT 
'Nu satisface conditia' AS REZULTAT

FROM CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (:CAPITOL = :CAPITOL           OR :CAPITOL <> :CAPITOL ) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
   D.FORM = 5


HAVING


  (SUM(CASE WHEN D.CAPITOL IN (2) AND  D.RIND  IN('01') AND  NVAL(D.COL1) = 1  THEN NVAL(D.COL1)  ELSE 0 END)   =  1
  AND 
  SUM(CASE WHEN D.CAPITOL NOT IN (2)  AND  NVAL(D.COL1) + NVAL(D.COL2) > 0  THEN NVAL(D.COL1) + NVAL(D.COL2)  ELSE 0 END)   =  0 ) 
  
  OR 
   (SUM(CASE WHEN D.CAPITOL IN (2) AND  D.RIND  IN('01') AND  NVAL(D.COL1) = 1  THEN NVAL(D.COL1)  ELSE 0 END)   =  0
  AND 
  SUM(CASE WHEN D.CAPITOL NOT IN (2)  AND  NVAL(D.COL1) + NVAL(D.COL2) > 0  THEN NVAL(D.COL1) + NVAL(D.COL2)  ELSE 0 END)   >  0 ) 