SELECT DISTINCT

D.CUIIO 
--  NVAL(SUM(CASE WHEN D.RIND IN ('001') THEN D.COL1 END)) ||' <> '||
--  NVAL(SUM(CASE WHEN D.RIND NOT IN ('001') THEN D.COL1 END))
--  AS REZULTAT

FROM
  VW_DATA_ALL D
  INNER JOIN MD_PERIOADA P ON (D.PERIOADA=P.PERIOADA)
WHERE
  (D.PERIOADA IN (:PERIOADA)          ) AND
 -- (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (43)  AND
  D.CAPITOL IN (397) AND
  D.RIND IN ('001','007','013','014','020','047')
  
  GROUP BY
  D.CUIIO
  
  
HAVING
  NVAL(SUM(CASE WHEN D.RIND IN ('001') THEN D.COL1 END)) = 
  NVAL(SUM(CASE WHEN D.RIND NOT IN ('001') THEN D.COL1 END))