--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14,COL15,COL16,COL17,COL18,COL19,COL20,COL21,COL22,COL23,COL24,COL25,COL26,COL27,COL28,COL29,COL30,
-- COL31,COL32,COL33,COL34,COL35,COL36,COL37,COL38,COL39,COL40,COL41,COL42,COL43,COL44,COL45,COL46,COL47,COL48
--)
----------------------------------------------------------------------------------
  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  ORDINE_CFOJ AS NR_SECTIE,
  CFOJ_DENUMIRE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  ROUND(COL1,0)||'~'||ORDINE AS NR_ROW,
  ORDINE,
  '100000000000000000000001010010000000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL2,1) AS COL1,
  ROUND(COL3,0) AS COL2,
  ROUND(COL4,0) AS COL3,
  ROUND(COL5,0) AS COL4,
  ROUND(COL6,0) AS COL5,
  ROUND(COL7,0) AS COL6,
  ROUND(COL8,0) AS COL7,
  ROUND(COL9,0) AS COL8,
  ROUND(COL10,0) AS COL9,
  ROUND(COL11,0) AS COL10,
  ROUND(COL12,0) AS COL11,
  ROUND(COL13,0) AS COL12,
  ROUND(COL14,0) AS COL13,
  ROUND(COL15,0) AS COL14,
  ROUND(COL16,0) AS COL15,
  ROUND(COL17,0) AS COL16,
  ROUND(COL18,0) AS COL17,
  ROUND(COL19,0) AS COL18,
  ROUND(COL20,0) AS COL19,
  ROUND(COL21,0) AS COL20,
  ROUND(COL22,0) AS COL21,
  ROUND(COL23,0) AS COL22,
  ROUND(COL24,0) AS COL23,
  ROUND(COL25,1) AS COL24,
  ROUND(COL26,0) AS COL25,
  ROUND(COL27,1) AS COL26,
  ROUND(COL28,0) AS COL27,
  ROUND(COL29,0) AS COL28,
  ROUND(COL30,1) AS COL29,
  ROUND(COL31,0) AS COL30,
  ROUND(COL32,0) AS COL31,
  ROUND(COL33,0) AS COL32,
  ROUND(COL34,0) AS COL33,
  ROUND(COL35,0) AS COL34,
  ROUND(COL36,0) AS COL35,
  ROUND(COL37,0) AS COL36,
  ROUND(COL38,0) AS COL37,
  ROUND(COL39,0) AS COL38,
  ROUND(COL40,0) AS COL39,
  ROUND(COL41,0) AS COL40,
  ROUND(COL42,0) AS COL41,
  ROUND(COL43,0) AS COL42,
  ROUND(COL44,0) AS COL43,
  ROUND(COL45,0) AS COL44,
  ROUND(COL46,0) AS COL45,
  ROUND(COL47,0) AS COL46,
  ROUND(COL48,0) AS COL47,
  ROUND(COL49,0) AS COL48
FROM
(
SELECT
  TR.CFOJ_DENUMIRE||' ('||TR.CFOJ||')' AS CFOJ_DENUMIRE,
  TR.ORDINE AS ORDINE_CFOJ,
  R.NUME_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END) AS COL1,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL2,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('038') THEN D.COL1 END) AS COL3,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('038') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL4,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('015') THEN D.COL1 END) AS COL5,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('015') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL6,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('015') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('038') THEN D.COL1 END))*100 AS COL7,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('024') THEN D.COL1 END) AS COL8,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('024') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL9,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('024') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('038') THEN D.COL1 END))*100 AS COL10,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('036') THEN D.COL1 END) AS COL11,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('036') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL12,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('036') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('038') THEN D.COL1 END))*100 AS COL13,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('039') THEN D.COL1 END) AS COL14,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('039') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL15,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('041') THEN D.COL1 END) AS COL16,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('041') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL17,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('041') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('039') THEN D.COL1 END))*100 AS COL18,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('040') THEN D.COL1 END) AS COL19,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('040') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL20,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('040') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('039') THEN D.COL1 END))*100 AS COL21,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('051') THEN D.COL1 END) AS COL22,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('051') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL23,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('051') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('039') THEN D.COL1 END))*100 AS COL24,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('062') THEN D.COL1 END) AS COL25,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('062') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL26,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('063') THEN D.COL1 END) AS COL27,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('063') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL28,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('063') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('062') THEN D.COL1 END))*100 AS COL29,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('066') THEN D.COL1 END) AS COL30,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('066') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL31,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('066') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('062') THEN D.COL1 END))*100 AS COL32,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END) AS COL33,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL34,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('094') THEN D.COL1 END) AS COL35,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('094') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL36,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('094') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END))*100 AS COL37,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('102') THEN D.COL1 END) AS COL38,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('102') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL39,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('102') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END))*100 AS COL40,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('103') THEN D.COL1 END) AS COL41,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('103') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL42,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('103') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END))*100 AS COL43,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('109') THEN D.COL1 END) AS COL44,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('109') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL45,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('109') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END))*100 AS COL46,
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('141') THEN D.COL1 END) AS COL47,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('141') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('150') THEN D.COL1 END))*100 AS COL48,
  (SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('141') THEN D.COL1 END)/
  SUM(CASE WHEN TR.CFOJ LIKE '%'|| D.CFOJ ||'%' AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND D.RIND IN ('093') THEN D.COL1 END))*100 AS COL49
FROM 
  VW_DATA_ALL D
  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT
      DECODE(CS.CODUL, 
      '0000000','01','0100000','02','1111111','03','0300000','04',
      '1400000','05','3400000','06','3600000','07','4100000','08','4300000','09',
      '4500000','10','4800000','11','6200000','12','7100000','13','7400000','14',
      '7800000','15','2222222','16','1000000','17','2500000','18','3100000','19',
      '3800000','20','5300000','21','5500000','22','6000000','23','6400000','24',
      '6700000','25','8000000','26','8300000','27','8900000','28','9200000','29',
      '3333333','30','1200000','31','1700000','32','2100000','33','2700000','34',
      '2900000','35','5700000','36','8500000','37','8700000','38','9600000','39')
      AS NR_ROW,
      CS.DENUMIRE AS NUME_ROW,
      CS.CODUL AS CS_CUATM
    FROM
      VW_CL_CUATM CS
    WHERE
      CS.CODUL 
      IN(
         '0000000','0100000','1111111','0300000','1400000','3400000','3600000','4100000','4300000','4500000',
         '4800000','6200000','7100000','7400000','7800000','2222222','1000000','2500000','3100000','3800000',
         '5300000','5500000','6000000','6400000','6700000','8000000','8300000','8900000','9200000','3333333',
         '1200000','1700000','2100000','2700000','2900000','5700000','8500000','8700000','9600000'
        )
  ) R 
  CROSS JOIN 
  (
SELECT '500+530+540+541+550+590+690+880+890+684+685' AS CFOJ, 'Intreprinderi agricole si GT (de fermier) cu teremiro agricole de 10 ha si peste' AS CFOJ_DENUMIRE, 1 AS ORDINE FROM DUAL UNION
SELECT '500+530+540+541+550+590+690+880+890' AS CFOJ, 'Intreprinderi agricole - total' AS CFOJ_DENUMIRE, 2 AS ORDINE FROM DUAL UNION
SELECT '684+685' AS CFOJ, 'Gospodariile taranesti (de fermier) inregistrate cu suprafata terenurilor de 10 ha si peste' AS CFOJ_DENUMIRE, 3 AS ORDINE FROM DUAL
  ) TR
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (43)AND   
  D.CAPITOL IN (397) 
GROUP BY
  TR.CFOJ,
  TR.CFOJ_DENUMIRE,
  TR.ORDINE,
  R.NUME_ROW,
  R.NR_ROW
ORDER BY
  TR.ORDINE,
  R.NR_ROW
)