CREATE OR REPLACE FORCE VIEW  VW_DATA_ALL_ASA_2023
(

CUIIO,
CUIIO_VERS,
    CUATM,
    FULL_CODE,
    CAEM2,
    caem_calc,
    CAP_SR_1,
    CAP_SR_2,
    CAP_SR_3,
    CAP_SR_4,
    CAP_SR_5,
    CAP_SR_6,
    CAP_SR_7,
    RIND_400_COL2,
    RIND_150_COL1,
    RIND_160,
    RIND_200,
    RIND_210,
    RIND_220,
    RIND_240,
    RIND_260,
    RIND_270,
    RIND_280,
    RIND_290,
    RIND_296,
    RIND_320_COL1
 
 )
AS 
SELECT 
DISTINCT D.CUIIO,
D.CUIIO_VERS,
D.CUATM,
C.FULL_CODE,
D.CAEM2,
 max(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL END) caem_calc,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('1') THEN D.COL1 ELSE NULL END) CAP_SR_1,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('2') THEN D.COL1 ELSE NULL END) CAP_SR_2,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('3') THEN D.COL1 ELSE NULL END) CAP_SR_3,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('4') THEN D.COL1 ELSE NULL END) CAP_SR_4,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('5') THEN D.COL1 ELSE NULL END) CAP_SR_5,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('6') THEN D.COL1 ELSE NULL END) CAP_SR_6,
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('7') THEN D.COL1 ELSE NULL END) CAP_SR_7,
 SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN D.COL4 ELSE NULL END) RIND_400_COL2,
 SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('150') THEN  D.COL1 ELSE NULL END ) RIND_150_COL1,
 SUM(CASE WHEN D.CAPITOL IN (1124)  AND D.RIND IN ('160') THEN  D.COL1 ELSE NULL END ) RIND_160,
 SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('200') THEN  D.COL1 ELSE NULL END ) RIND_200,
 ----------------------------------------------------------------------------------------------
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('210') THEN  D.COL1 ELSE NULL END ) RIND_210,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('220') THEN  D.COL1 ELSE NULL END ) RIND_220,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('240') THEN  D.COL1 ELSE NULL END ) RIND_240,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('260') THEN  D.COL1 ELSE NULL END ) RIND_260,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('270') THEN  D.COL1 ELSE NULL END ) RIND_270,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('280') THEN  D.COL1 ELSE NULL END ) RIND_280,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('290') THEN  D.COL1 ELSE NULL END ) RIND_290,
SUM(CASE WHEN D.CAPITOL IN (1125)  AND D.RIND IN ('296') THEN  D.COL1 ELSE NULL END ) RIND_296,
SUM(CASE WHEN D.CAPITOL IN (1126)  AND D.RIND IN ('320') THEN  D.COL1 ELSE NULL END ) RIND_320_COL1
-------------------------------------------------------------------------------------------------


 


FROM   

    CIS2.VW_DATA_ALL D 
                    INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
    
                      
WHERE
  D.FORM IN (64) AND 
  D.PERIOADA = 2012 
  -- AND D.CUIIO = 135094
  
  
  GROUP BY 
  D.CUIIO,
  D.CUIIO_VERS,
  D.CUATM,
  C.FULL_CODE,
  D.CAEM2
 
  
  ORDER BY 
  C.FULL_CODE

  
  