SELECT   
'Filial '||D.FILIAL||', Rind '||D.COL1||':  '|| 
DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ', '9', 'COL9 : ', '10', 'COL10 : ', '11', 'COL11 : ', '12', 'COL12 : ', '13', 'COL13 : ', '14', 'COL14 : ', '15', 'COL15 : ')|| 
SUM(CASE WHEN D.CAPITOL IN (341) THEN DECODE(CC.NR_COLUMN, '1', NVAL(D.COL2), '2', NVAL(D.COL3), '3', NVAL(D.COL4), '4', NVAL(D.COL5), '5', NVAL(D.COL6), '6', NVAL(D.COL7), '7', NVAL(D.COL8), '8', NVAL(D.COL9), '9', NVAL(D.COL10), '10', NVAL(D.COL11), '11', NVAL(D.COL12), '12', NVAL(D.COL13), '13', NVAL(D.COL14), '14', NVAL(D.COL15), '15', NVAL(D.COL16)) ELSE 0 END) ||' > '||  
SUM(CASE WHEN D.CAPITOL IN (340) THEN DECODE(CC.NR_COLUMN, '1', NVAL(D.COL2), '2', NVAL(D.COL3), '3', NVAL(D.COL4), '4', NVAL(D.COL5), '5', NVAL(D.COL6), '6', NVAL(D.COL7), '7', NVAL(D.COL8), '8', NVAL(D.COL9), '9', NVAL(D.COL10), '10', NVAL(D.COL11), '11', NVAL(D.COL12), '12', NVAL(D.COL13), '13', NVAL(D.COL14), '14', NVAL(D.COL15), '15', NVAL(D.COL16)) ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION 
       SELECT '5' AS NR_COLUMN FROM DUAL UNION 
       SELECT '6' AS NR_COLUMN FROM DUAL UNION
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL UNION
       SELECT '9' AS NR_COLUMN FROM DUAL UNION
       SELECT '10' AS NR_COLUMN FROM DUAL UNION 
       SELECT '11' AS NR_COLUMN FROM DUAL UNION   
       SELECT '12' AS NR_COLUMN FROM DUAL UNION  
       SELECT '13' AS NR_COLUMN FROM DUAL UNION
       SELECT '14' AS NR_COLUMN FROM DUAL UNION   
       SELECT '15' AS NR_COLUMN FROM DUAL                                       
       ) CC
 
WHERE
  (D.PERIOADA =:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (14)  AND
  D.CAPITOL IN (340,341) AND
  D.RIND NOT IN ('100','101','102','150','151','152')
 
GROUP BY 
  D.COL1,
  CC.NR_COLUMN, D.FILIAL
--  D.CAPITOL,
--  D.COL1,
--  D.COL2,
--  D.COL3,
--  D.COL4,
--  D.COL5,
--  D.COL6,
--  D.COL7,
--  D.COL8,
--  D.COL9,
--  D.COL10,
--  D.COL11,
--  D.COL12,
--  D.COL13,
--  D.COL14,
--  D.COL15

HAVING

SUM(CASE WHEN D.CAPITOL IN (341) THEN DECODE(CC.NR_COLUMN, '1', NVAL(D.COL2), '2', NVAL(D.COL3), '3', NVAL(D.COL4), '4', NVAL(D.COL5), '5', NVAL(D.COL6), '6', NVAL(D.COL7), '7', NVAL(D.COL8), '8', NVAL(D.COL9), '9', NVAL(D.COL10), '10', NVAL(D.COL11), '11', NVAL(D.COL12), '12', NVAL(D.COL13), '13', NVAL(D.COL14), '14', NVAL(D.COL15), '15', NVAL(D.COL16)) ELSE 0 END) >  
SUM(CASE WHEN D.CAPITOL IN (340) THEN DECODE(CC.NR_COLUMN, '1', NVAL(D.COL2), '2', NVAL(D.COL3), '3', NVAL(D.COL4), '4', NVAL(D.COL5), '5', NVAL(D.COL6), '6', NVAL(D.COL7), '7', NVAL(D.COL8), '8', NVAL(D.COL9), '9', NVAL(D.COL10), '10', NVAL(D.COL11), '11', NVAL(D.COL12), '12', NVAL(D.COL13), '13', NVAL(D.COL14), '14', NVAL(D.COL15), '15', NVAL(D.COL16)) ELSE 0 END)