SELECT   
D.CAPITOL,
D.FILIAL,
D.COL1,

SUM(D.COL11) 
  AS REZULTAT

FROM
  VW_DATA_ALL D            
      
WHERE
  (D.PERIOADA =:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (14)  AND
  D.CAPITOL IN (340,341) AND
  D.RIND NOT IN ('100','101','102','150','151','152')
  AND D.COL1 IN ('32101')

GROUP BY 
  D.COL1,
  D.FILIAL,
  D.CAPITOL


