SELECT
'RIND '||D.RIND ||
  ' Cap. SR: SUM(RIND.01-07) trebuie sa fie = 1 iar aici  = ' || MAX(CASE WHEN D.CAPITOL = 100 AND D.RIND IN('01','02','03','04','05','06','07') THEN NVAL(D.COL1) ELSE 0 END)
  AS REZULTAT

FROM
  VW_DATA_ALL_TEMP D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND 
  
  D.CAPITOL IN (100)
  
  GROUP BY
  D.RIND 
  
  
HAVING
  MAX(CASE WHEN D.CAPITOL = 100 AND D.RIND IN('01','02','03','04','05','06','07') THEN NVAL(D.COL1) ELSE 0 END) <> 1