SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW  AS NR_ROW,
  ORDINE1,
  ORDINE2,
  NULL AS ORDINE3,
  '......'||NUME_ROW AS NUME_ROW,
  NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15
FROM
(
SELECT 
 MAX (CASE WHEN RTRIM (D.CUIIO,'0')  IN (5913188,1309538,4607265,82066,820602,2500868,37716555, 39060745,5689710,2245711,400018) THEN  
RTRIM (D.CUIIO,'0')||'~'||CC.CODUL  ELSE  D.CUIIO ||'~'||CC.CODUL END) AS NR_ROW,  
CN.CODUL AS ORDINE1,
  TO_NUMBER(RTRIM (D.CUIIO,'0'))   AS ORDINE2,
  
  CC.CODUL  AS NR_SECTIE,
  CC.DENUMIRE AS NUME_SECTIE,
  R.DENUMIRE AS NUME_ROW,  
 
  NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15
  

FROM 

   CIS2.VW_CL_SPEC_3EDU ED
  LEFT  JOIN CIS2.VW_CL_SPEC_3EDU EDD ON (EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%')
  LEFT  JOIN 
  (
    SELECT D.* FROM CIS2.VW_DATA_ALL D
    WHERE D.PERIOADA IN (:PPERIOADA)
      AND D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%'
      AND D.FORM       IN(50)
      AND D.CAPITOL    IN(1058)    
  ) D ON (TO_CHAR(SUBSTR(D.RIND,2,10),'0000000')= EDD.CODUL)  
  
  INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII 
  INNER JOIN CIS2.VW_CL_COCM C ON (D.COCM=C.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  
    WHERE
  
  PERIOADA IN (:PPERIOADA) AND 
  D.FORM_VERS = :PFORM_VERS     AND    
  (:PID_MDTABLE=:PID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%' AND
  D.FORM IN (50) 
  AND  CC.CODUL NOT IN '0000'   
  AND ID_MD NOT BETWEEN 36895 AND 37083  AND
  D.RIND NOT IN ('010','020','030','040','050','060','090','100','110','120')
 GROUP BY 
  CN.CODUL, 
  CC.CODUL,
  CC.DENUMIRE,  
  RTRIM (D.CUIIO,'0'), 
  R.DENUMIRE
  )