SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW
  AS NR_ROW,
  ORDINE AS ORDINE1,
  NULL AS ORDINE2,
  NULL AS ORDINE3,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT

  
  CCO.CODUL  AS NR_SECTIE,
  CCO.DENUMIRE AS NUME_SECTIE,
  CN.CODUL  AS NR_ROW, 
  CN.CODUL  AS ORDINE,
  '......'||CN.DENUMIRE AS NUME_ROW, 
    NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15--, NULL AS COL16

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','090','-','100','110','120')
     
       )   

 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
     


INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
 INNER JOIN CIS2.VW_CL_COCM CO ON (D.COCM=CO.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CCO ON (CO.FULL_CODE LIKE '%'||CCO.CODUL||';%')
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII

 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) 
  --AND D.CUIIO = 400001

   AND  CCO.CODUL NOT IN '0000'

  GROUP BY 



 CN.CODUL, 
 CN.DENUMIRE,
 CCO.CODUL,
 CCO.DENUMIRE
   
  
  
 ORDER BY  
  CN.CODUL
  
  )