SELECT
         
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW AS NR_ROW,
  TO_CHAR(NTII) AS ORDINE1,
  CUIIO_TEST AS ORDINE2,
  ORDINE AS ORDINE3,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  NR_ROW AS NR_ROW,
  NTII,
  TO_NUMBER(CUIIO_TEST) AS CUIIO_TEST,
  ROWNUM AS ORDINE,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT 
  
 MAX( CASE WHEN RTRIM (D.CUIIO,'0')  IN (5913188,1309538,4607265,82066,820602,2500868,37716555, 39060745,5689710,2245711,400018) THEN  
  RTRIM (D.CUIIO,'0')||'~'||CC.CODUL  ELSE  D.CUIIO||'~'||CC.CODUL END)  AS CUIIO,
  CC.CODUL  AS NR_SECTIE,
  CC.DENUMIRE AS NUME_SECTIE,
  TO_NUMBER(ED.CODUL) ||'~'||R.NTII||CC.CODUL||RTRIM (D.CUIIO,'0')AS NR_ROW, 
  ED.FULL_CODE AS ORDINE,
  ED.DENUMIRE AS NUME_ROW, 
  R.NTII,  
  RTRIM (D.CUIIO,'0') AS CUIIO_TEST,
  
   CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL12 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL13 END)) AS COL2,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL12 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL13 END)) AS COL3,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL12 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL14 END)) AS COL4,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' THEN D.COL14 END)) AS COL5,
   
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL12 END)) AS COL6,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL13 END)) AS COL7,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL12 END))- 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL13 END)) AS COL8,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL14 END)) AS COL9,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND ED.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (1) THEN D.COL14 END)) AS COL10,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL12 END)) AS COL11,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL13 END)) AS COL12,
  
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL13 END)) AS COL13,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL14 END)) AS COL14,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%' AND R.NFI IN (25) THEN D.COL14 END)) AS COL15
  
---
FROM 

   CIS2.VW_CL_SPEC_3EDU ED
  LEFT  JOIN CIS2.VW_CL_SPEC_3EDU EDD ON (EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%')
  LEFT  JOIN 
  (
    SELECT D.* FROM CIS2.VW_DATA_ALL D
    WHERE D.PERIOADA IN (:PPERIOADA)
      AND D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%'
      AND D.FORM       IN(50)
      AND D.CAPITOL    IN(1058)    
  ) D ON (TO_CHAR(SUBSTR(D.RIND,2,10),'0000000')= EDD.CODUL)  
  INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
  INNER JOIN CIS2.VW_CL_COCM C ON (D.COCM=C.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII
  
    WHERE
  
  PERIOADA IN (:PPERIOADA) AND 
  D.FORM_VERS = :PFORM_VERS     AND    
  (:PID_MDTABLE=:PID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:PCOD_CUATM||';%' AND
  D.FORM IN (50) 
  AND  CC.CODUL NOT IN '0000'
  AND ID_MD NOT BETWEEN 36895 AND 37083 AND
  D.RIND NOT IN ('010','020','030','040','050','060','090','100','110','120')
  
 GROUP BY 
   ED.CODUL,
   ED.FULL_CODE,
   ED.DENUMIRE,
   CC.CODUL,
   CC.DENUMIRE,
   RTRIM (D.CUIIO,'0'),
   R.NTII
   
 ORDER BY  
   R.NTII,
   CC.CODUL,
   RTRIM (D.CUIIO,'0'),
   ED.FULL_CODE
   ))
WHERE COL1+COL2+COL3+COL4+COL5+COL6+COL7+COL8+COL9+COL10>0