INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
)
SELECT
  :PPERIOADA AS PERIOADA,
  :PFORM AS FORM,
  :PFORM_VERS AS FORM_VERS,
  :PID_MDTABLE AS ID_MDTABLE,
  :PCOD_CUATM AS COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW||'~'||ROWNUM  NR_ROW,
  ROWNUM AS ORDINE,
  '00000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT
  :PPERIOADA AS PERIOADA,
  :PFORM AS FORM,
  :PFORM_VERS AS FORM_VERS,
  :PID_MDTABLE AS ID_MDTABLE,
  :PCOD_CUATM AS COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  '00000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT 
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE1,
  ORDINE2,
  ORDINE3,
  NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM (

-----RIND-SPECIALITATI-----

SELECT
         
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW AS NR_ROW,
  TO_CHAR(NTII) AS ORDINE1,
  CUIIO_TEST AS ORDINE2,
  ORDINE AS ORDINE3,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(

SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  NR_ROW AS NR_ROW,
  NTII,
  TO_NUMBER(CUIIO_TEST) AS CUIIO_TEST,
  ROWNUM AS ORDINE,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(

SELECT
   D.CUIIO||'~'||CCO.CODUL AS CUIIO,
   CCO.CODUL  AS NR_SECTIE,
  CCO.DENUMIRE AS NUME_SECTIE,
   CASE WHEN ltrim(TO_NUMBER(CC.codul),'0') IS NULL THEN '0' ELSE ltrim(TO_NUMBER(CC.codul),'0')||'~'||R.NTII||CCO.CODUL||RTRIM (D.CUIIO,'0')   END   NR_ROW,
    CC.ORDINE,
   CC.DENUMIRE NUME_ROW,
     R.NTII,  
  RTRIM (D.CUIIO,'0') AS CUIIO_TEST,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1058)  THEN D.COL1 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL2 END)) AS COL2,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL1 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL2 END)) AS COL3,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL1 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL3 END)) AS COL4,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  THEN D.COL3 END)) AS COL5,
     
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL15 END)) AS COL6,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL16 END)) AS COL7,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL15 END))- 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL16 END)) AS COL8,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL15 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (1) THEN D.COL17 END)) AS COL9,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (1) THEN D.COL17 END)) AS COL10,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL15 END)) AS COL11,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL16 END)) AS COL12,
      
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058  AND R.NFI IN (25)  THEN D.COL15 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL16 END)) AS COL13,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL15 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL17 END)) AS COL14,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058   AND R.NFI IN (25) THEN D.COL17 END)) AS COL15

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','090','-','100','110','120')
     
       )   

 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
     INNER JOIN  (SELECT  
        
        RINDOUT CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13834) C  ON  (ltrim(TO_NUMBER(C.codul),'0') =  DD.RIND_MOD) 
     
    INNER  JOIN   (SELECT  
        
        TRIM(RINDOUT) CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13834)  CC ON   C.FULL_CODE LIKE '%'||CC.CODUL||';%'


INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
 INNER JOIN CIS2.VW_CL_COCM CO ON (D.COCM=CO.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CCO ON (CO.FULL_CODE LIKE '%'||CCO.CODUL||';%')
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII

 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) 
  --AND D.CUIIO = 400001

   AND  CCO.CODUL NOT IN '0000'

  GROUP BY 



  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  CC.ORDINE,
  CCO.CODUL,
  CCO.DENUMIRE,
  D.CUIIO,
  R.NTII

   
  
  
  ORDER BY
  R.NTII,
  CCO.CODUL,
  RTRIM (D.CUIIO,'0'),
  CC.ORDINE 
  
  
  
  
  ) )
  
  WHERE NVAL(COL1)+NVAL(COL2)+NVAL(COL3)+NVAL(COL4)+NVAL(COL5)+NVAL(COL6)+NVAL(COL7)+NVAL(COL8)+NVAL(COL9)+NVAL(COL10)>0
   ---NTII----
UNION

   
   SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW
  AS NR_ROW,
  ORDINE AS ORDINE1,
  NULL AS ORDINE2,
  NULL AS ORDINE3,
  NUME_ROW AS NUME_ROW,
  COL1,COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15--, COL16
FROM
(
SELECT

  
  CCO.CODUL  AS NR_SECTIE,
  CCO.DENUMIRE AS NUME_SECTIE,
  CN.CODUL  AS NR_ROW, 
  CN.CODUL  AS ORDINE,
  '......'||CN.DENUMIRE AS NUME_ROW, 
    NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15--, NULL AS COL16

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','090','-','100','110','120')
     
       )   

 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
     


INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
 INNER JOIN CIS2.VW_CL_COCM CO ON (D.COCM=CO.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CCO ON (CO.FULL_CODE LIKE '%'||CCO.CODUL||';%')
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII

 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) 
  --AND D.CUIIO = 400001

   AND  CCO.CODUL NOT IN '0000'

  GROUP BY 



 CN.CODUL, 
 CN.DENUMIRE,
 CCO.CODUL,
 CCO.DENUMIRE
   
  
  
 ORDER BY  
  CN.CODUL
  
  )
   
   UNION

  ----------CUIIO----
  SELECT
  NR_SECTIE AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW  AS NR_ROW,
  ORDINE1,
  ORDINE2,
  NULL AS ORDINE3,
  '......'||NUME_ROW AS NUME_ROW,
  NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15
FROM
(

SELECT

  D.CUIIO||'~'||CCO.CODUL    NR_ROW, 
  CN.CODUL AS ORDINE1,
  TO_NUMBER(RTRIM (D.CUIIO,'0'))   AS ORDINE2,
  CCO.CODUL  AS NR_SECTIE,
  CCO.DENUMIRE AS NUME_SECTIE,

  R.DENUMIRE AS NUME_ROW, 
    NULL AS COL1,
  NULL AS COL2,NULL AS COL3, NULL AS COL4, NULL AS COL5, NULL AS COL6,NULL AS COL7, NULL AS COL8, NULL AS COL9,
  NULL AS COL10,NULL AS COL11, NULL AS COL12, NULL AS COL13, NULL AS COL14,NULL AS COL15--, NULL AS COL16

FROM 
  CIS2.VW_DATA_ALL D

INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) AND     
    
  (
  
  D.RIND NOT IN 
       
       (
       
        SELECT 
        CODUL
        
        FROM CIS2.CL_TARI_CS
        
       )
        
     AND 
     
     D.RIND NOT IN ('010','020','030','035','040','050','060','090','-','100','110','120')
     
       )   

 
  
   ) DD ON   (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
 
 
     


INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
 INNER JOIN CIS2.VW_CL_COCM CO ON (D.COCM=CO.CODUL)
  INNER JOIN CIS2.VW_CL_COCM CCO ON (CO.FULL_CODE LIKE '%'||CCO.CODUL||';%')
  INNER JOIN CIS2.CL_NTII CN ON CN.CODUL=R.NTII

 
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (50)                 AND 
  D.CAPITOL IN (1058) 
  --AND D.CUIIO = 400001

   AND  CCO.CODUL NOT IN '0000'

  GROUP BY 



 CN.CODUL, 
 CN.DENUMIRE,
 CCO.CODUL,
 CCO.DENUMIRE,
 D.CUIIO,
 R.DENUMIRE
   
  
  
 ORDER BY  
  CN.CODUL
  
  )
  )
  ORDER BY NR_SECTIE,ORDINE1, ORDINE2, ORDINE3
)
--WHERE COL1+COL2+COL3+COL4+COL5+COL6+COL7+COL8+COL9+COL10>0
ORDER BY
  NR_SECTIE, ORDINE1, CASE WHEN ORDINE2 IS NULL THEN 0.1 ELSE ORDINE2 END, CASE WHEN ORDINE3 IS NULL THEN 0.2 ELSE ORDINE3 END
)