SELECT 
 TO_NUMBER(ED.CODUL)  AS NR_ROW,

  ED.FULL_CODE AS ORDINE,
  ED.DENUMIRE AS NUME_ROW, 

 
  
  --COUNT(DISTINCT (CASE WHEN SUBSTR(D.RIND,2,10)>0  AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN RTRIM (D.CUIIO,'0') END )) AS COL1,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL12 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL13 END)) AS COL2,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL12 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL13 END)) AS COL3,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL12 END)) -
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL14 END)) AS COL4,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' THEN D.COL14 END)) AS COL5,
     
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL12 END)) AS COL6,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL13 END)) AS COL7,
 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL12 END))- 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL13 END)) AS COL8,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL14 END)) AS COL9,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND ED.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (1) THEN D.COL14 END)) AS COL10,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL12 END)) AS COL11,
    
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL13 END)) AS COL12,
      
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25)  THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL13 END)) AS COL13,
  
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL12 END))-
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL14 END)) AS COL14,
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN 1058 AND SUBSTR(D.RIND,2,10)>0 AND EDD.FULL_CODE LIKE  '%'||ED.CODUL||'%' AND R.NFI IN (25) THEN D.COL14 END)) AS COL15
  
---
FROM 

   CIS2.VW_CL_SPEC_3EDU ED
  LEFT  JOIN CIS2.VW_CL_SPEC_3EDU EDD ON ( EDD.FULL_CODE LIKE  '%'||ED.CODUL||';%')
--  LEFT  JOIN 
--  (
--    SELECT D.* FROM CIS2.VW_DATA_ALL D
--    WHERE D.PERIOADA IN (:pPERIOADA)
--      AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
--      AND D.FORM       IN(50)
--      AND D.CAPITOL    IN(1058)
--      --AND D.CUIIO =400001
--    
--  ) D ON (TO_CHAR(SUBSTR(D.RIND,2,10),'0000000')= EDD.CODUL)    
  INNER JOIN CIS2.RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
  
  WHERE 
  ID_MD NOT BETWEEN 36895 AND 37083 AND
  D.RIND NOT IN ('010','020','030','040','050','060','090','100','110','120')
  
    
 GROUP BY 
   ED.CODUL,
   ED.FULL_CODE,
   ED.DENUMIRE
   
 ORDER BY  
   ED.FULL_CODE