SELECT 
      CII.SHOW_ORDER   AS ORDINE, 
      CII.ITEM_CODE, 
      CII.NAME NUME_ROW,
      
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_TOTAL,

    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'0100000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_01,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'0300000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_03,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'1400000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_14,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'3400000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_34,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'3600000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_36,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'4100000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_41,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'4300000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_43,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'4500000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_45,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'4800000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_48,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'6200000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_62,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'7100000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_71,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'7400000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_74,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'7800000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_78,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'1000000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_10,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'2500000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_25,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'3100000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_31,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'3800000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_38,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'5300000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_53,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND C.FULL_CODE LIKE '%'||'5500000'||'%' AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_55

FROM VW_DATA_ALL D
       
           INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
           INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
           AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
           INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  
WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  D.FORM IN (44)
  AND D.CAPITOL IN (405) 
  
GROUP BY 
  CII.ITEM_CODE,
  CII.SHOW_ORDER,  
  CII.NAME
  
ORDER BY
  CII.SHOW_ORDER
