SELECT 
      CII.SHOW_ORDER   AS ORDINE, 
      CII.ITEM_CODE, 
      CII.NAME NUME_ROW,
     COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL_TOTAL,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '660' THEN D.CUIIO END) AS COL_660,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '388' THEN D.CUIIO END) AS COL_388,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '070' THEN D.CUIIO END) AS COL_070,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '208' THEN D.CUIIO END) AS COL_208,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '043' THEN D.CUIIO END) AS COL_043,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '330' THEN D.CUIIO END) AS COL_330,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '446' THEN D.CUIIO END) AS COL_446,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '459' THEN D.CUIIO END) AS COL_459,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '632' THEN D.CUIIO END) AS COL_632,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '528' THEN D.CUIIO END) AS COL_528,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '077' THEN D.CUIIO END) AS COL_077,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '474' THEN D.CUIIO END) AS COL_474,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '800' THEN D.CUIIO END) AS COL_800,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '038' THEN D.CUIIO END) AS COL_038,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '078' THEN D.CUIIO END) AS COL_078,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '453' THEN D.CUIIO END) AS COL_453,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '640' THEN D.CUIIO END) AS COL_640,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '666' THEN D.CUIIO END) AS COL_666,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '469' THEN D.CUIIO END) AS COL_469,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '073' THEN D.CUIIO END) AS COL_073,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '017' THEN D.CUIIO END) AS COL_017,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '421' THEN D.CUIIO END) AS COL_421,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '284' THEN D.CUIIO END) AS COL_284,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '413' THEN D.CUIIO END) AS COL_413,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '516' THEN D.CUIIO END) AS COL_516,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '477' THEN D.CUIIO END) AS COL_477,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '093' THEN D.CUIIO END) AS COL_093,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '391' THEN D.CUIIO END) AS COL_391,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '892' THEN D.CUIIO END) AS COL_892,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '508' THEN D.CUIIO END) AS COL_508,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '703' THEN D.CUIIO END) AS COL_703,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '068' THEN D.CUIIO END) AS COL_068,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '236' THEN D.CUIIO END) AS COL_236,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '328' THEN D.CUIIO END) AS COL_328,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '675' THEN D.CUIIO END) AS COL_675,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '247' THEN D.CUIIO END) AS COL_247,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '696' THEN D.CUIIO END) AS COL_696,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '302' THEN D.CUIIO END) AS COL_302,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '404' THEN D.CUIIO END) AS COL_404,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '463' THEN D.CUIIO END) AS COL_463,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '061' THEN D.CUIIO END) AS COL_061,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '021' THEN D.CUIIO END) AS COL_021,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '512' THEN D.CUIIO END) AS COL_512,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '720' THEN D.CUIIO END) AS COL_720,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '834' THEN D.CUIIO END) AS COL_834,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '244' THEN D.CUIIO END) AS COL_244,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '600' THEN D.CUIIO END) AS COL_600,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '833' THEN D.CUIIO END) AS COL_833,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '480' THEN D.CUIIO END) AS COL_480,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '375' THEN D.CUIIO END) AS COL_375,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '318' THEN D.CUIIO END) AS COL_318,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '837' THEN D.CUIIO END) AS COL_837,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '724' THEN D.CUIIO END) AS COL_724,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '728' THEN D.CUIIO END) AS COL_728,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '436' THEN D.CUIIO END) AS COL_436,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '272' THEN D.CUIIO END) AS COL_272,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '092' THEN D.CUIIO END) AS COL_092,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '448' THEN D.CUIIO END) AS COL_448,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '475' THEN D.CUIIO END) AS COL_475,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '008' THEN D.CUIIO END) AS COL_008,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '338' THEN D.CUIIO END) AS COL_338,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '460' THEN D.CUIIO END) AS COL_460,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '500' THEN D.CUIIO END) AS COL_500,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '220' THEN D.CUIIO END) AS COL_220,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '039' THEN D.CUIIO END) AS COL_039,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '647' THEN D.CUIIO END) AS COL_647,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '336' THEN D.CUIIO END) AS COL_336,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '053' THEN D.CUIIO END) AS COL_053,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '393' THEN D.CUIIO END) AS COL_393,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '334' THEN D.CUIIO END) AS COL_334,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '529' THEN D.CUIIO END) AS COL_529,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '075' THEN D.CUIIO END) AS COL_075,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '041' THEN D.CUIIO END) AS COL_041,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '815' THEN D.CUIIO END) AS COL_815,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '708' THEN D.CUIIO END) AS COL_708,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '032' THEN D.CUIIO END) AS COL_032,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '001' THEN D.CUIIO END) AS COL_001,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '314' THEN D.CUIIO END) AS COL_314,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '252' THEN D.CUIIO END) AS COL_252,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '076' THEN D.CUIIO END) AS COL_076,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '893' THEN D.CUIIO END) AS COL_893,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '004' THEN D.CUIIO END) AS COL_004,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '276' THEN D.CUIIO END) AS COL_276,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '044' THEN D.CUIIO END) AS COL_044,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '009' THEN D.CUIIO END) AS COL_009,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '473' THEN D.CUIIO END) AS COL_473,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '406' THEN D.CUIIO END) AS COL_406,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '831' THEN D.CUIIO END) AS COL_831,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '416' THEN D.CUIIO END) AS COL_416,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '260' THEN D.CUIIO END) AS COL_260,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '257' THEN D.CUIIO END) AS COL_257,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '310' THEN D.CUIIO END) AS COL_310,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '488' THEN D.CUIIO END) AS COL_488,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '452' THEN D.CUIIO END) AS COL_452,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '835' THEN D.CUIIO END) AS COL_835,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '424' THEN D.CUIIO END) AS COL_424,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '740' THEN D.CUIIO END) AS COL_740,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '664' THEN D.CUIIO END) AS COL_664,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '700' THEN D.CUIIO END) AS COL_700,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '628' THEN D.CUIIO END) AS COL_628,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '612' THEN D.CUIIO END) AS COL_612,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '616' THEN D.CUIIO END) AS COL_616,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '007' THEN D.CUIIO END) AS COL_007,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '024' THEN D.CUIIO END) AS COL_024,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '624' THEN D.CUIIO END) AS COL_624,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '005' THEN D.CUIIO END) AS COL_005,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '464' THEN D.CUIIO END) AS COL_464,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '732' THEN D.CUIIO END) AS COL_732,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '083' THEN D.CUIIO END) AS COL_083,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '079' THEN D.CUIIO END) AS COL_079,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '346' THEN D.CUIIO END) AS COL_346,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '812' THEN D.CUIIO END) AS COL_812,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '095' THEN D.CUIIO END) AS COL_095,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '636' THEN D.CUIIO END) AS COL_636,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '684' THEN D.CUIIO END) AS COL_684,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '395' THEN D.CUIIO END) AS COL_395,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '054' THEN D.CUIIO END) AS COL_054,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '604' THEN D.CUIIO END) AS COL_604,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '268' THEN D.CUIIO END) AS COL_268,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '216' THEN D.CUIIO END) AS COL_216,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '037' THEN D.CUIIO END) AS COL_037,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '055' THEN D.CUIIO END) AS COL_055,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '018' THEN D.CUIIO END) AS COL_018,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '743' THEN D.CUIIO END) AS COL_743,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '096' THEN D.CUIIO END) AS COL_096,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '370' THEN D.CUIIO END) AS COL_370,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '386' THEN D.CUIIO END) AS COL_386,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '701' THEN D.CUIIO END) AS COL_701,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '667' THEN D.CUIIO END) AS COL_667,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '232' THEN D.CUIIO END) AS COL_232,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '046' THEN D.CUIIO END) AS COL_046,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '820' THEN D.CUIIO END) AS COL_820,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '204' THEN D.CUIIO END) AS COL_204,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '824' THEN D.CUIIO END) AS COL_824,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '228' THEN D.CUIIO END) AS COL_228,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '373' THEN D.CUIIO END) AS COL_373,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '377' THEN D.CUIIO END) AS COL_377,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '023' THEN D.CUIIO END) AS COL_023,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '412' THEN D.CUIIO END) AS COL_412,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '823' THEN D.CUIIO END) AS COL_823,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '716' THEN D.CUIIO END) AS COL_716,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '470' THEN D.CUIIO END) AS COL_470,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '366' THEN D.CUIIO END) AS COL_366,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '097' THEN D.CUIIO END) AS COL_097,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '676' THEN D.CUIIO END) AS COL_676,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '389' THEN D.CUIIO END) AS COL_389,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '803' THEN D.CUIIO END) AS COL_803,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '672' THEN D.CUIIO END) AS COL_672,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '432' THEN D.CUIIO END) AS COL_432,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '240' THEN D.CUIIO END) AS COL_240,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '288' THEN D.CUIIO END) AS COL_288,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '838' THEN D.CUIIO END) AS COL_838,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '836' THEN D.CUIIO END) AS COL_836,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '028' THEN D.CUIIO END) AS COL_028,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '809' THEN D.CUIIO END) AS COL_809,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '804' THEN D.CUIIO END) AS COL_804,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '003' THEN D.CUIIO END) AS COL_003,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '649' THEN D.CUIIO END) AS COL_649,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '662' THEN D.CUIIO END) AS COL_662,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '825' THEN D.CUIIO END) AS COL_825,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '625' THEN D.CUIIO END) AS COL_625,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '442' THEN D.CUIIO END) AS COL_442,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '801' THEN D.CUIIO END) AS COL_801,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '520' THEN D.CUIIO END) AS COL_520,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '504' THEN D.CUIIO END) AS COL_504,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '813' THEN D.CUIIO END) AS COL_813,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '822' THEN D.CUIIO END) AS COL_822,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '060' THEN D.CUIIO END) AS COL_060,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '010' THEN D.CUIIO END) AS COL_010,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '644' THEN D.CUIIO END) AS COL_644,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '006' THEN D.CUIIO END) AS COL_006,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '608' THEN D.CUIIO END) AS COL_608,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '306' THEN D.CUIIO END) AS COL_306,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '322' THEN D.CUIIO END) AS COL_322,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '456' THEN D.CUIIO END) AS COL_456,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '352' THEN D.CUIIO END) AS COL_352,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '066' THEN D.CUIIO END) AS COL_066,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '324' THEN D.CUIIO END) AS COL_324,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '229' THEN D.CUIIO END) AS COL_229,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '652' THEN D.CUIIO END) AS COL_652,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '449' THEN D.CUIIO END) AS COL_449,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '465' THEN D.CUIIO END) AS COL_465,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '479' THEN D.CUIIO END) AS COL_479,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '408' THEN D.CUIIO END) AS COL_408,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '467' THEN D.CUIIO END) AS COL_467,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '428' THEN D.CUIIO END) AS COL_428,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '830' THEN D.CUIIO END) AS COL_830,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '819' THEN D.CUIIO END) AS COL_819,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '047' THEN D.CUIIO END) AS COL_047,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '311' THEN D.CUIIO END) AS COL_311,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '248' THEN D.CUIIO END) AS COL_248,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '098' THEN D.CUIIO END) AS COL_098,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '355' THEN D.CUIIO END) AS COL_355,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '329' THEN D.CUIIO END) AS COL_329,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '045' THEN D.CUIIO END) AS COL_045,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '264' THEN D.CUIIO END) AS COL_264,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '706' THEN D.CUIIO END) AS COL_706,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '063' THEN D.CUIIO END) AS COL_063,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '091' THEN D.CUIIO END) AS COL_091,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '806' THEN D.CUIIO END) AS COL_806,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '342' THEN D.CUIIO END) AS COL_342,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '011' THEN D.CUIIO END) AS COL_011,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '669' THEN D.CUIIO END) AS COL_669,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '400' THEN D.CUIIO END) AS COL_400,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '224' THEN D.CUIIO END) AS COL_224,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '225' THEN D.CUIIO END) AS COL_225,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '030' THEN D.CUIIO END) AS COL_030,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '492' THEN D.CUIIO END) AS COL_492,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '082' THEN D.CUIIO END) AS COL_082,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '736' THEN D.CUIIO END) AS COL_736,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '894' THEN D.CUIIO END) AS COL_894,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '357' THEN D.CUIIO END) AS COL_357,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '680' THEN D.CUIIO END) AS COL_680,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '626' THEN D.CUIIO END) AS COL_626,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '280' THEN D.CUIIO END) AS COL_280,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '839' THEN D.CUIIO END) AS COL_839,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '817' THEN D.CUIIO END) AS COL_817,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '472' THEN D.CUIIO END) AS COL_472,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '212' THEN D.CUIIO END) AS COL_212,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '052' THEN D.CUIIO END) AS COL_052,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '080' THEN D.CUIIO END) AS COL_080,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '454' THEN D.CUIIO END) AS COL_454,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '807' THEN D.CUIIO END) AS COL_807,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '072' THEN D.CUIIO END) AS COL_072,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '350' THEN D.CUIIO END) AS COL_350,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '064' THEN D.CUIIO END) AS COL_064,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '524' THEN D.CUIIO END) AS COL_524,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '081' THEN D.CUIIO END) AS COL_081,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '816' THEN D.CUIIO END) AS COL_816,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '484' THEN D.CUIIO END) AS COL_484,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '690' THEN D.CUIIO END) AS COL_690,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '468' THEN D.CUIIO END) AS COL_468,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '457' THEN D.CUIIO END) AS COL_457,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '811' THEN D.CUIIO END) AS COL_811,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '653' THEN D.CUIIO END) AS COL_653,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '378' THEN D.CUIIO END) AS COL_378,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '382' THEN D.CUIIO END) AS COL_382










    
     FROM VW_DATA_ALL D
       
           INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
           INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
           AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
         --  INNER JOIN   CIS2.VW_CL_TARI TT  ON (TT.CODUL=D.COL33)
  
         
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  --(:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND D.CAPITOL IN (405) 
  
  GROUP BY 
  CII.ITEM_CODE,
  CII.SHOW_ORDER,  
  CII.NAME
  
  

ORDER BY
CII.SHOW_ORDER


  

  




  
