SELECT 
      CII.SHOW_ORDER   AS ORDINE, 
      CII.ITEM_CODE, 
      CII.NAME NUME_ROW,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL1,
    COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL2

    
     FROM VW_DATA_ALL D
       
           INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
           INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
           AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
         --  INNER JOIN   CIS2.VW_CL_TARI TT  ON (TT.CODUL=D.COL33)
  
         
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  --(:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND D.CAPITOL IN (405) 
  
  GROUP BY 
  CII.ITEM_CODE,
  CII.SHOW_ORDER,  
  CII.NAME
  
  

ORDER BY
CII.SHOW_ORDER


  

  




  
