SELECT 
      CII.SHOW_ORDER   AS ORDINE, 
      CII.ITEM_CODE, 
      CII.NAME NUME_ROW,
     COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 THEN D.CUIIO END) AS COL1,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '660' THEN D.CUIIO END) AS COL2,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '388' THEN D.CUIIO END) AS COL3,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '070' THEN D.CUIIO END) AS COL4,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '208' THEN D.CUIIO END) AS COL5,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '043' THEN D.CUIIO END) AS COL6,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '330' THEN D.CUIIO END) AS COL7,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '446' THEN D.CUIIO END) AS COL8,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '459' THEN D.CUIIO END) AS COL9,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '632' THEN D.CUIIO END) AS COL10,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '528' THEN D.CUIIO END) AS COL11,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '077' THEN D.CUIIO END) AS COL12,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '474' THEN D.CUIIO END) AS COL13,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '800' THEN D.CUIIO END) AS COL14,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '038' THEN D.CUIIO END) AS COL15,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '078' THEN D.CUIIO END) AS COL16,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '453' THEN D.CUIIO END) AS COL17,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '640' THEN D.CUIIO END) AS COL18,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '666' THEN D.CUIIO END) AS COL19,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '469' THEN D.CUIIO END) AS COL20,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '073' THEN D.CUIIO END) AS COL21,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '017' THEN D.CUIIO END) AS COL22,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '421' THEN D.CUIIO END) AS COL23,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '284' THEN D.CUIIO END) AS COL24,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '413' THEN D.CUIIO END) AS COL25,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '516' THEN D.CUIIO END) AS COL26,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '477' THEN D.CUIIO END) AS COL27,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '093' THEN D.CUIIO END) AS COL28,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '391' THEN D.CUIIO END) AS COL29,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '892' THEN D.CUIIO END) AS COL30,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '508' THEN D.CUIIO END) AS COL31,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '703' THEN D.CUIIO END) AS COL32,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '068' THEN D.CUIIO END) AS COL33,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '236' THEN D.CUIIO END) AS COL34,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '328' THEN D.CUIIO END) AS COL35,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '675' THEN D.CUIIO END) AS COL36,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '247' THEN D.CUIIO END) AS COL37,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '696' THEN D.CUIIO END) AS COL38,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '302' THEN D.CUIIO END) AS COL39,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '404' THEN D.CUIIO END) AS COL40,
COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '463' THEN D.CUIIO END) AS COL41,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '061' THEN D.CUIIO END) AS COL42,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '021' THEN D.CUIIO END) AS COL43,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '512' THEN D.CUIIO END) AS COL44,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '720' THEN D.CUIIO END) AS COL45,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '834' THEN D.CUIIO END) AS COL46,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '244' THEN D.CUIIO END) AS COL47,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '600' THEN D.CUIIO END) AS COL48,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '833' THEN D.CUIIO END) AS COL49,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '480' THEN D.CUIIO END) AS COL50,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '375' THEN D.CUIIO END) AS COL51,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '318' THEN D.CUIIO END) AS COL52,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '837' THEN D.CUIIO END) AS COL53,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '724' THEN D.CUIIO END) AS COL54,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '728' THEN D.CUIIO END) AS COL55,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '436' THEN D.CUIIO END) AS COL56,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '272' THEN D.CUIIO END) AS COL57,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '092' THEN D.CUIIO END) AS COL58,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '448' THEN D.CUIIO END) AS COL59,

COUNT(DISTINCT CASE WHEN D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-') AND CIS2.NVAL(D.COL4) > 0 AND D.COL33 = '475' THEN D.CUIIO END) AS COL60


    
     FROM VW_DATA_ALL D
       
           INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))
           INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
           AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
         --  INNER JOIN   CIS2.VW_CL_TARI TT  ON (TT.CODUL=D.COL33)
  
         
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  --(:pID_MDTABLE =:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND D.CAPITOL IN (405) 
  
  GROUP BY 
  CII.ITEM_CODE,
  CII.SHOW_ORDER,  
  CII.NAME
  
  

ORDER BY
CII.SHOW_ORDER


  

  




  
