SELECT

'Completa?i sau  "Numarul mediu al salariatilor în perioada de gestiune" sau confirmati lipsa salariatilor '
 
--  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('6') THEN  D.COL1 ELSE NULL END))||' ,  '||
--  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('5') THEN  D.COL1 ELSE NULL END))
 
  AS REZULTAT


FROM VW_DATA_ALL_FR_TEMP D

WHERE   
  (D.PERIOADA IN (:PERIOADA)) AND
  (D.CUIIO=:CUIIO                ) AND
 -- (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR  D.CUIIO_VERS <>  :CUIIO_VERS) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (57)  AND
  D.CAPITOL IN (1091) AND D.RIND  IN ('6','5') 
 
HAVING
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('6') THEN  D.COL1 ELSE NULL END)) >0 AND 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('5') THEN  D.COL1 ELSE NULL END)) >0)
 
 OR

(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('6') THEN  D.COL1 ELSE NULL END)) =0 AND 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1091) AND D.RIND IN ('5') THEN  D.COL1 ELSE NULL END)) =0) 
