SELECT 
--CC.CODUL,
--CC.DENUMIRE DENUMIRE_CUATM,
--CC.FULL_CODE,
D.CUIIO,  
R.DENUMIRE,
C.FULL_CODE,
  SUM(CASE WHEN D.RIND IN ('1') THEN D.COL1 ELSE NULL END) AS COL1,
  SUM(CASE WHEN D.RIND IN ('7') THEN D.COL1 ELSE NULL END) AS COL2,
  SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 ELSE NULL END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('13') THEN D.COL1 ELSE NULL END) AS COL4
  
  
  
  
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
  INNER JOIN VW_CL_CUATM C ON C.CODUL = D.CUATM
 -- INNER JOIN VW_CL_CUATM CC ON  C.FULL_CODE LIKE '%'||CC.CODUL||';%'

 
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)           
  
GROUP BY
D.CUIIO,
R.DENUMIRE,
C.FULL_CODE
--CC.CODUL,
--CC.DENUMIRE,
--CC.FULL_CODE
 


ORDER BY 
C.FULL_CODE

