SELECT 
  CCC.CODUL,
  CCC.DENUMIRE NUME_ROW,
  CCC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('A')  THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('B')  THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1')  THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('2')  THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('3')  THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('4')  THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('5')  THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('6')  THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('7')  THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('8')  THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('9')  THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13')  THEN D.COL1 END)) AS COL12,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14')  THEN D.COL1 END)) AS COL13,
  NVAL(SUM(CASE WHEN D.RIND IN ('10')  THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.RIND IN ('11')  THEN D.COL1 END)) AS COL15,
  NVAL(SUM(CASE WHEN D.RIND IN ('12')  THEN D.COL1 END)) AS COL16,
  NVAL(SUM(CASE WHEN D.RIND IN ('13')  THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.RIND IN ('14')  THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.RIND IN ('15')  THEN D.COL1 END)) AS COL19,
  NVAL(SUM(CASE WHEN D.RIND IN ('16') THEN D.COL1 END)) AS COL20,
  NVAL(SUM(CASE WHEN D.RIND IN ('17')  THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.RIND IN ('18')  THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.RIND IN ('19')  THEN D.COL1 END)) AS COL23,
  NVAL(SUM(CASE WHEN D.RIND IN ('20')  THEN D.COL1 END)) AS COL24,
  NVAL(SUM(CASE WHEN D.RIND IN ('21')  THEN D.COL1 END)) AS COL25,
  NVAL(SUM(CASE WHEN D.RIND IN ('22') THEN D.COL1 END)) AS COL26,
  NVAL(SUM(CASE WHEN D.RIND IN ('23')  THEN D.COL1 END)) AS COL27,
  NVAL(SUM(CASE WHEN D.RIND IN ('24')  THEN D.COL1 END)) AS COL28,
  NVAL(SUM(CASE WHEN D.RIND IN ('25')  THEN D.COL1 END)) AS COL29,
  NVAL(SUM(CASE WHEN D.RIND IN ('26')  THEN D.COL1 END)) AS COL30,
  NVAL(SUM(CASE WHEN D.RIND IN ('27')  THEN D.COL1 END)) AS COL31,
  NVAL(SUM(CASE WHEN D.RIND IN ('28')  THEN D.COL1 END)) AS COL32,
  NVAL(SUM(CASE WHEN D.RIND IN ('29')  THEN D.COL1 END)) AS COL33,
  NVAL(SUM(CASE WHEN D.RIND IN ('30')  THEN D.COL1 END)) AS COL34
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

  INNER JOIN VW_CL_CUATM CC ON (D.CUATM = CC.CODUL)
  INNER JOIN VW_CL_CUATM CCC ON (CC.FULL_CODE  LIKE '%'||CCC.CODUL||';%' )
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)   
--  AND D.CUIIO = 4496570   
  AND CCC.PRGS IN ('2','5')     
  
GROUP BY 
CCC.DENUMIRE,
CCC.CODUL,
CCC.FULL_CODE



ORDER BY 
 CCC.FULL_CODE