-- INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11,COL12,COL13,COL14,COL15,COL16,COL17,COL18,COL19,COL20,COL21,COL22,COL23,COL24,COL25,COL26,COL27,COL28,COL29,COL30,COL31,COL32,COL33
--)
--
SELECT
--  :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
--         
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
  ROUND(COL1,0)||'~'||NR_ROW AS NR_ROW,
  ROWNUM ORDINE,
  '000000000000000000000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL2,0) AS COL1,
  ROUND(COL3,0) AS COL2,
  ROUND(COL4,0) AS COL3,
  ROUND(COL5,0) AS COL4,
  ROUND(COL6,0) AS COL5,
  ROUND(COL7,0) AS COL6,
  ROUND(COL8,0) AS COL7,
  ROUND(COL9,0) AS COL8,
  ROUND(COL10,0) AS COL9,
  ROUND(COL11,0) AS COL10,
  ROUND(COL12,0) AS COL11,
  ROUND(COL13,0) AS COL12,
  ROUND(COL14,0) AS COL13,
  ROUND(COL15,0) AS COL14,
  ROUND(COL16,0) AS COL15,
  ROUND(COL17,0) AS COL16,
  ROUND(COL18,0) AS COL17,
  ROUND(COL19,0) AS COL18,
  ROUND(COL20,0) AS COL19,
  ROUND(COL21,0) AS COL20,
  ROUND(COL22,0) AS COL21,
  ROUND(COL23,0) AS COL22,
  ROUND(COL24,0) AS COL23,
  ROUND(COL25,0) AS COL24,
  ROUND(COL26,0) AS COL25,
  ROUND(COL27,0) AS COL26,
  ROUND(COL28,0) AS COL27,
  ROUND(COL29,0) AS COL28,
  ROUND(COL30,0) AS COL29,
  ROUND(COL31,0) AS COL30,
  ROUND(COL32,0) AS COL31,
  ROUND(COL33,0) AS COL32,
  ROUND(COL34,0) AS COL33
FROM
(
SELECT 
  D.CUIIO, 
  R.NR_ROW,
  R.NUME_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
--  D.CFOJ,
--  CCF.CODUL,
--  CCF.DENUMIRE,
  NVAL(SUM(CASE WHEN D.RIND IN ('A') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('B') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('2') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('3') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('4') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('5') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('6') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('7') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('8') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('9') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL12,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL13,
  NVAL(SUM(CASE WHEN D.RIND IN ('10') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.RIND IN ('11') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL15,
  NVAL(SUM(CASE WHEN D.RIND IN ('12') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL16,
  NVAL(SUM(CASE WHEN D.RIND IN ('13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.RIND IN ('14') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.RIND IN ('15') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL19,
  NVAL(SUM(CASE WHEN D.RIND IN ('16') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL20,
  NVAL(SUM(CASE WHEN D.RIND IN ('17') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.RIND IN ('18') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.RIND IN ('19') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL23,
  NVAL(SUM(CASE WHEN D.RIND IN ('20') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL24,
  NVAL(SUM(CASE WHEN D.RIND IN ('21') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL25,
  NVAL(SUM(CASE WHEN D.RIND IN ('22') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL26,
  NVAL(SUM(CASE WHEN D.RIND IN ('23') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL27,
  NVAL(SUM(CASE WHEN D.RIND IN ('24') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL28,
  NVAL(SUM(CASE WHEN D.RIND IN ('25') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL29,
  NVAL(SUM(CASE WHEN D.RIND IN ('26') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL30,
  NVAL(SUM(CASE WHEN D.RIND IN ('27') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL31,
  NVAL(SUM(CASE WHEN D.RIND IN ('28') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL32,
  NVAL(SUM(CASE WHEN D.RIND IN ('29') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL33,
  NVAL(SUM(CASE WHEN D.RIND IN ('30') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL34
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT
      CS.CODUL AS NR_ROW,
      CS.DENUMIRE AS NUME_ROW,
      CS.CODUL AS CS_CUATM,
      CS.FULL_CODE
    FROM
      VW_CL_CUATM CS
    
  ) R 
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)           
  AND D.CUIIO = 3001555
GROUP BY 
  R.NR_ROW,
  R.NUME_ROW,
  R.FULL_CODE,
  D.CUIIO
  --  CCF.CODUL,
--  CCF.DENUMIRE

ORDER BY 
 R.FULL_CODE
 
 )