SELECT 
  R.NR_ROW,
  R.NUME_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
--  D.CFOJ,
--  CCF.CODUL,
--  CCF.DENUMIRE,
  NVAL(SUM(CASE WHEN D.RIND IN ('A') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('B') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('2') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('3') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('4') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('5') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('6') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('7') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('8') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('9') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL12,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL13,
  NVAL(SUM(CASE WHEN D.RIND IN ('10') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.RIND IN ('11') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL15,
  NVAL(SUM(CASE WHEN D.RIND IN ('12') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL16,
  NVAL(SUM(CASE WHEN D.RIND IN ('13') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.RIND IN ('14') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.RIND IN ('15') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL19,
  NVAL(SUM(CASE WHEN D.RIND IN ('16') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL20,
  NVAL(SUM(CASE WHEN D.RIND IN ('17') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.RIND IN ('18') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.RIND IN ('19') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL23,
  NVAL(SUM(CASE WHEN D.RIND IN ('20') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL24,
  NVAL(SUM(CASE WHEN D.RIND IN ('21') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL25,
  NVAL(SUM(CASE WHEN D.RIND IN ('22') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL26,
  NVAL(SUM(CASE WHEN D.RIND IN ('23') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL27,
  NVAL(SUM(CASE WHEN D.RIND IN ('24') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL28,
  NVAL(SUM(CASE WHEN D.RIND IN ('25') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL29,
  NVAL(SUM(CASE WHEN D.RIND IN ('26') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL30,
  NVAL(SUM(CASE WHEN D.RIND IN ('27') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL31,
  NVAL(SUM(CASE WHEN D.RIND IN ('28') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL32,
  NVAL(SUM(CASE WHEN D.RIND IN ('29') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL33,
  NVAL(SUM(CASE WHEN D.RIND IN ('30') AND CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' THEN D.COL1 END)) AS COL34
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT
      CS.CODUL AS NR_ROW,
      CS.DENUMIRE AS NUME_ROW,
      CS.CODUL AS CS_CUATM,
      CS.FULL_CODE
    FROM
      VW_CL_CUATM CS
    
  ) R 
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)           
  
GROUP BY 
  R.NR_ROW,
  R.NUME_ROW,
  R.FULL_CODE
--  CCF.CODUL,
--  CCF.DENUMIRE

ORDER BY 
 R.FULL_CODE