SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CODUL||'~'||ROWNUM AS NR_ROW,
   ROWNUM ORDINE,
  '0000000000000000000000000000000000' AS DECIMAL_POS,
  NUME_ROW,
  ROUND(COL1,0) AS COL1,
  ROUND(COL2,0) AS COL2,
  ROUND(COL3,0) AS COL3,
  ROUND(COL4,0) AS COL4,
  ROUND(COL5,0) AS COL5,
  ROUND(COL6,0) AS COL6,
  ROUND(COL7,0) AS COL7,
  ROUND(COL8,0) AS COL8,
  ROUND(COL9,0) AS COL9,
  ROUND(COL10,0) AS COL10,
  ROUND(COL11,0) AS COL11,
  ROUND(COL12,0) AS COL12,
  ROUND(COL13,0) AS COL13,
  ROUND(COL14,0) AS COL14,
  ROUND(COL15,0) AS COL15,
  ROUND(COL16,0) AS COL16,
  ROUND(COL17,0) AS COL17,
  ROUND(COL18,0) AS COL18,
  ROUND(COL19,0) AS COL19,
  ROUND(COL20,0) AS COL20,
  ROUND(COL21,0) AS COL21,
  ROUND(COL22,0) AS COL22,
  ROUND(COL23,0) AS COL23,
  ROUND(COL24,0) AS COL24,
  ROUND(COL25,0) AS COL25,
  ROUND(COL26,0) AS COL26,
  ROUND(COL27,0) AS COL27,
  ROUND(COL28,0) AS COL28,
  ROUND(COL29,0) AS COL29,
  ROUND(COL30,0) AS COL30,
  ROUND(COL31,0) AS COL31,
  ROUND(COL32,0) AS COL32,
  ROUND(COL33,0) AS COL33,
  ROUND(COL34,0) AS COL34
FROM
(
SELECT 
  CCC.CODUL,
  CCC.DENUMIRE NUME_ROW,
  CCC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('A')  THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('B')  THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1')  THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('2')  THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('3')  THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('4')  THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('5')  THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('6')  THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('7')  THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('8')  THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('9')  THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13')  THEN D.COL1 END)) AS COL12,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14')  THEN D.COL1 END)) AS COL13,
  NVAL(SUM(CASE WHEN D.RIND IN ('10')  THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.RIND IN ('11')  THEN D.COL1 END)) AS COL15,
  NVAL(SUM(CASE WHEN D.RIND IN ('12')  THEN D.COL1 END)) AS COL16,
  NVAL(SUM(CASE WHEN D.RIND IN ('13')  THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.RIND IN ('14')  THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.RIND IN ('15')  THEN D.COL1 END)) AS COL19,
  NVAL(SUM(CASE WHEN D.RIND IN ('16') THEN D.COL1 END)) AS COL20,
  NVAL(SUM(CASE WHEN D.RIND IN ('17')  THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.RIND IN ('18')  THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.RIND IN ('19')  THEN D.COL1 END)) AS COL23,
  NVAL(SUM(CASE WHEN D.RIND IN ('20')  THEN D.COL1 END)) AS COL24,
  NVAL(SUM(CASE WHEN D.RIND IN ('21')  THEN D.COL1 END)) AS COL25,
  NVAL(SUM(CASE WHEN D.RIND IN ('22') THEN D.COL1 END)) AS COL26,
  NVAL(SUM(CASE WHEN D.RIND IN ('23')  THEN D.COL1 END)) AS COL27,
  NVAL(SUM(CASE WHEN D.RIND IN ('24')  THEN D.COL1 END)) AS COL28,
  NVAL(SUM(CASE WHEN D.RIND IN ('25')  THEN D.COL1 END)) AS COL29,
  NVAL(SUM(CASE WHEN D.RIND IN ('26')  THEN D.COL1 END)) AS COL30,
  NVAL(SUM(CASE WHEN D.RIND IN ('27')  THEN D.COL1 END)) AS COL31,
  NVAL(SUM(CASE WHEN D.RIND IN ('28')  THEN D.COL1 END)) AS COL32,
  NVAL(SUM(CASE WHEN D.RIND IN ('29')  THEN D.COL1 END)) AS COL33,
  NVAL(SUM(CASE WHEN D.RIND IN ('30')  THEN D.COL1 END)) AS COL34
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

  INNER JOIN VW_CL_CUATM CC ON (D.CUATM = CC.CODUL)
  INNER JOIN VW_CL_CUATM CCC ON (CC.FULL_CODE  LIKE '%'||CCC.CODUL||';%' )
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)   
--  AND D.CUIIO = 4496570   
  AND CCC.PRGS IN ('2','5')     
  
GROUP BY 
CCC.DENUMIRE,
CCC.CODUL,
CCC.FULL_CODE


UNION 

SELECT 
  CC.CODUL,
  D.CUIIO||'-'||CC.DENUMIRE NUME_ROW,
  CC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('A')  THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('B')  THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('1')  THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('2')  THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('3')  THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('4')  THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('5')  THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('6')  THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('7')  THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('8')  THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('9')  THEN D.COL1 END)) AS COL11,
  NVAL(SUM(CASE WHEN D.RIND IN ('10','13')  THEN D.COL1 END)) AS COL12,
  NVAL(SUM(CASE WHEN D.RIND IN ('11','14')  THEN D.COL1 END)) AS COL13,
  NVAL(SUM(CASE WHEN D.RIND IN ('10')  THEN D.COL1 END)) AS COL14,
  NVAL(SUM(CASE WHEN D.RIND IN ('11')  THEN D.COL1 END)) AS COL15,
  NVAL(SUM(CASE WHEN D.RIND IN ('12')  THEN D.COL1 END)) AS COL16,
  NVAL(SUM(CASE WHEN D.RIND IN ('13')  THEN D.COL1 END)) AS COL17,
  NVAL(SUM(CASE WHEN D.RIND IN ('14')  THEN D.COL1 END)) AS COL18,
  NVAL(SUM(CASE WHEN D.RIND IN ('15')  THEN D.COL1 END)) AS COL19,
  NVAL(SUM(CASE WHEN D.RIND IN ('16') THEN D.COL1 END)) AS COL20,
  NVAL(SUM(CASE WHEN D.RIND IN ('17')  THEN D.COL1 END)) AS COL21,
  NVAL(SUM(CASE WHEN D.RIND IN ('18')  THEN D.COL1 END)) AS COL22,
  NVAL(SUM(CASE WHEN D.RIND IN ('19')  THEN D.COL1 END)) AS COL23,
  NVAL(SUM(CASE WHEN D.RIND IN ('20')  THEN D.COL1 END)) AS COL24,
  NVAL(SUM(CASE WHEN D.RIND IN ('21')  THEN D.COL1 END)) AS COL25,
  NVAL(SUM(CASE WHEN D.RIND IN ('22') THEN D.COL1 END)) AS COL26,
  NVAL(SUM(CASE WHEN D.RIND IN ('23')  THEN D.COL1 END)) AS COL27,
  NVAL(SUM(CASE WHEN D.RIND IN ('24')  THEN D.COL1 END)) AS COL28,
  NVAL(SUM(CASE WHEN D.RIND IN ('25')  THEN D.COL1 END)) AS COL29,
  NVAL(SUM(CASE WHEN D.RIND IN ('26')  THEN D.COL1 END)) AS COL30,
  NVAL(SUM(CASE WHEN D.RIND IN ('27')  THEN D.COL1 END)) AS COL31,
  NVAL(SUM(CASE WHEN D.RIND IN ('28')  THEN D.COL1 END)) AS COL32,
  NVAL(SUM(CASE WHEN D.RIND IN ('29')  THEN D.COL1 END)) AS COL33,
  NVAL(SUM(CASE WHEN D.RIND IN ('30')  THEN D.COL1 END)) AS COL34
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS)

  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (30)                 AND 
  D.CAPITOL IN (376)   
--  AND D.CUIIO = 4496570        
  
GROUP BY 
D.CUIIO||'-'||CC.DENUMIRE,
CC.CODUL,
CC.FULL_CODE





ORDER BY 
 FULL_CODE
 )