SELECT
  DISTINCT
       NVAL(MAX(CASE WHEN D.PERIOADA IN (:PERIOADA-1) AND D.CUIIO IS NOT NULL THEN  1 ELSE NULL END)) +
    NVAL(MAX(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.CUIIO IS NOT NULL THEN  1 ELSE NULL END)) AS COL1
    
FROM
  CIS2.DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO  ) AND
   D.FORM  IN(67)