SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL  END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('1') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8 ) ELSE NULL END) || ' : Rind 1 '
     
      
       
      
      
  
  AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL  END)  <

SUM(CASE WHEN D.RIND IN ('1') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL  END)




UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('2') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 2 '
     
AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('2') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)


UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('3') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 3 '
     
      
       
      
 AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('3') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)

UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('4') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 4 '
     
      
       
      
 AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('4') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)

UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('5') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 5 '
     
      
       
      
 AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('5') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)


UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('6') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 6 '
     
      
       
      
 AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('6') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)

UNION 


SELECT   
'FILIALA:'||D.FILIAL||' Rind 8 : '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 : ', '2', 'COL2 : ', '3', 'COL3 :', '4', 'COL4 : ', '5', 'COL5 : ', '6', 'COL6 : ', '7', 'COL7 : ', '8', 'COL8 : ')||
  SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) ||' < '||
  SUM(CASE WHEN D.RIND IN ('7') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END) || ' : Rind 7 '
     
      
       
      
 AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION 
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION 
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL                                     
       ) CC     
 
WHERE
  (D.PERIOADA =:PERIOADA       ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM              ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (16)  AND
  D.CAPITOL IN (353) AND
  D.RIND IN ('8','1','2','3','4','5','6','7')
  
--  AND D.CUIIO IN (9202)
 
GROUP BY 
CC.NR_COLUMN, 
D.FILIAL


 HAVING
SUM(CASE WHEN D.RIND IN ('8') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)  <

SUM(CASE WHEN D.RIND IN ('7') THEN  DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '7', D.COL7, '8', D.COL8) ELSE NULL END)