SELECT
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE,
 COUNT (DISTINCT D.CUIIO) AS CNT,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('10') THEN  D.CUIIO ELSE NULL END) AS CFP_10,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('11') THEN  D.CUIIO ELSE NULL END) AS CFP_11,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('12') THEN  D.CUIIO ELSE NULL END) AS CFP_12,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('13') THEN  D.CUIIO ELSE NULL END) AS CFP_13,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('14') THEN  D.CUIIO ELSE NULL END) AS CFP_14,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('15') THEN  D.CUIIO ELSE NULL END) AS CFP_15,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('16') THEN  D.CUIIO ELSE NULL END) AS CFP_16,    
 COUNT (DISTINCT CASE WHEN D.CFP IN ('17') THEN  D.CUIIO ELSE NULL END) AS CFP_17,    
 COUNT (DISTINCT CASE WHEN D.CFP IN ('18') THEN  D.CUIIO ELSE NULL END) AS CFP_18, 
 COUNT (DISTINCT CASE WHEN D.CFP IN ('19') THEN  D.CUIIO ELSE NULL END) AS CFP_19,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('20') THEN  D.CUIIO ELSE NULL END) AS CFP_20,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('21') THEN  D.CUIIO ELSE NULL END) AS CFP_21,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('22') THEN  D.CUIIO ELSE NULL END) AS CFP_22,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('23') THEN  D.CUIIO ELSE NULL END) AS CFP_23,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('24') THEN  D.CUIIO ELSE NULL END) AS CFP_24,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('25') THEN  D.CUIIO ELSE NULL END) AS CFP_25,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('26') THEN  D.CUIIO ELSE NULL END) AS CFP_26,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('27') THEN  D.CUIIO ELSE NULL END) AS CFP_27,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('28') THEN  D.CUIIO ELSE NULL END) AS CFP_28,
 COUNT (DISTINCT CASE WHEN D.CFP IN ('29') THEN  D.CUIIO ELSE NULL END) AS CFP_29                 
     
    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (365)
    AND D.RIND IN ('0000000')
    AND CC.PRGS IN ('2')

GROUP BY 
  CC.CODUL,
  CC.FULL_CODE,
  CC.DENUMIRE
  
  ORDER BY
  CC.FULL_CODE
  
 