SELECT
 D.CUIIO,
 R.IDNO
     
  FROM CIS2.VW_DATA_ALL D 
       INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (365)
    AND D.RIND IN ('0000000')
   
    
GROUP BY 
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO