INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,   
  COL1, COL2, COL3,COL4,COL5
)


  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        

  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,  
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW,  
   ROWNUM AS ORDINE,
  '00000' AS DECIMAL_POS,
   NUME_ROW,
   COL1, COL2, COL3,COL4,COL5
   FROM
(
SELECT 
L.NR_ROW,
L.NUME_ROW,
L.COL1 AS COL1,
MAX(L.COL2) AS COL2,
MAX(L.COL3) AS COL3,
MAX(L.COL4) AS COL4,
MAX(R.COL5) AS COL5

FROM
(
SELECT
   R.CUIIO AS NR_ROW,
   R.DENUMIRE AS NUME_ROW, 
   R.CUATM AS COL1,
   SUBSTR (D.CAEM2,2,4) AS COL2,
   D.PACHET AS COL3,  
  TO_NUMBER(CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1195)   THEN D.RIND END))) AS COL4, 
  NULL  AS COL5 

 FROM
      CIS2.VW_DATA_ALL D        
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA ) AND
       D.FORM_VERS IN (:pFORM_VERS) AND 
     
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1195)
       
       --AND D.CUIIO = 15789743 
  
GROUP BY  
   R.CUIIO,
   R.CUATM,
   R.DENUMIRE,
   D.CAEM2, 
   D.PACHET ) L LEFT JOIN (
   SELECT
   R.CUIIO AS NR_ROW,
   R.DENUMIRE AS NUME_ROW, 
   R.CUATM AS COL1,
   SUBSTR (D.CAEM2,2,4) AS COL2,
   D.PACHET AS COL3,  
  TO_NUMBER(CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1195)   THEN D.RIND END))) AS COL4, 
   TO_NUMBER(CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1195)   THEN D.RIND END)))  AS COL5 

 FROM
      CIS2.VW_DATA_ALL D        
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA ) AND
       D.FORM_VERS IN (:pFORM_VERS) AND 
     
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1195)
       
       --AND D.CUIIO = 15789743 
  
GROUP BY  
   R.CUIIO,
   R.CUATM,
   R.DENUMIRE,
   D.CAEM2, 
   D.PACHET
   
   ) R ON L.NR_ROW = R.NR_ROW
   
   
    INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = L.COL1
   
   
   GROUP BY
   L.COL1,
   L.NR_ROW,
   L.NUME_ROW,
   C.FULL_CODE
   
   ORDER BY
   C.FULL_CODE 
   
   )
   