--BEGIN
--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,   
--  COL1, COL2, COL3
--)

  SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
   '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW||'~'||ROWNUM AS NR_ROW,
  ROWNUM AS ORDINE,
  '000' AS DECIMAL_POS,
   DENUMIRE||'-'||NUME_ROW AS NUME_ROW,
   CUIIO AS COL1, 
   COL1 AS COL2,
   COL2 AS COL3
   FROM
(
  SELECT
   CUIIO,
   MAX(DENUMIRE)  DENUMIRE,
   NR_ROW AS NR_ROW, 
   MAX(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NUME_ROW,'emsp'),'1'),'&'),'3'),'.'),';'),'-'),'2'),'4')) AS NUME_ROW, 
   ORDINE AS ORDINE, 
   
   SUM(COL1) AS COL1, 
   SUM(COL2) AS COL2 

  FROM 
  (
  SELECT
   R.CUIIO ,
   R.DENUMIRE,
   D.RIND AS NR_ROW,  
   RD.ORDINE AS ORDINE,
  '00' AS DECIMAL_POS,
   RD.DENUMIRE AS NUME_ROW, 
  CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1185) AND D.PERIOADA IN (:pPERIOADA)  THEN D.COL1 ELSE NULL END)) AS COL1, 
NULL AS COL2 

 FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN CIS2.MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS AND D.ID_MD=RD.ID_MD
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
    
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1185) 
       --AND D.RIND IN ('221','222','223','224')       
     --  AND D.CUIIO = 1000545
         
GROUP BY  
   R.CUIIO ,
   R.DENUMIRE,
   D.RIND,  
   RD.ORDINE,
   RD.DENUMIRE  
   
   
   
   UNION 
   
   
   SELECT
   R.CUIIO ,
   R.DENUMIRE,
   D.RIND AS NR_ROW,  
   RD.ORDINE AS ORDINE,
  '00' AS DECIMAL_POS,
   RD.DENUMIRE AS NUME_ROW, 
  NULL AS COL1, 
  CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1185) AND D.PERIOADA IN (:pPERIOADA-1)THEN D.COL1 ELSE NULL END)) AS COL2 

 FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN CIS2.MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS AND D.ID_MD=RD.ID_MD
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA-1 ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = 2000  AND  
  
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1185) 
       --AND D.RIND IN ('221','222','223','224')       
--AND D.CUIIO = 1000545
         
GROUP BY  
   R.CUIIO ,
   R.DENUMIRE,
   D.RIND,  
   RD.ORDINE,
   RD.DENUMIRE 
     

   ORDER BY ORDINE
   )
   
   GROUP BY
   CUIIO, 
  -- DENUMIRE,
   NR_ROW,
   ORDINE
   
--   HAVING 
--   
--   SUM(COL1) > 0 OR   
--   SUM(COL2)  > 0 
   
   ORDER BY 
   CUIIO,
   ORDINE
      )
      
--         ;
--END;
--   