--
--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,   
--  COL1, COL2, COL3,COL4
--)

  SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
   '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
     CUIIO||'~'||ROWNUM NR_ROW,  
  ROWNUM AS ORDINE,
  '0000' AS DECIMAL_POS,
   DENUMIRE NUME_ROW,
   COL1 AS COL1, 
   COL2 AS COL2,
   COL3 AS COL3,
   COL4 AS COL4
   FROM
(
  SELECT
   CUIIO,
   MAX(DENUMIRE)  DENUMIRE,
  
   COL1,
   COL2,
   SUM(COL1) AS COL3, 
   SUM(COL2) AS COL4 

  FROM 
  (
  SELECT
   R.CUIIO ,
   R.DENUMIRE,
    SUBSTR (D.CAEM2,2,4) AS COL1,
   D.PACHET AS COL2,
   
  TO_NUMBER(CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1195) AND D.COL1 IS NOT NULL AND D.PERIOADA IN (:pPERIOADA)  THEN D.RIND END))) AS COL3, 
  NULL AS COL4 

 FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN CIS2.MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS AND D.ID_MD=RD.ID_MD
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
    
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1195) 
              
      AND D.CUIIO = 15789743 
         
GROUP BY  
    R.CUIIO ,
   R.DENUMIRE,
   D.CAEM2, D.PACHET
   
   
   UNION 
   
   SELECT
   R.CUIIO ,
   R.DENUMIRE,
    SUBSTR (D.CAEM2,2,4) AS COL1,
   D.PACHET AS COL2,
    NULL AS COL3, 
  TO_NUMBER(CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1195) AND D.COL1 IS NOT NULL AND D.PERIOADA IN (:pPERIOADA-1)  THEN D.RIND END))) AS COL4 
 

 FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN CIS2.MD_RIND RD ON D.RIND=RD.RIND AND D.RIND_VERS=RD.RIND_VERS AND D.ID_MD=RD.ID_MD
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA-1 ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = 2000  AND  
    
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1195) 
              
       AND D.CUIIO = 15789743 
         
GROUP BY  
    R.CUIIO ,
   R.DENUMIRE,
   D.CAEM2, D.PACHET
   
    ORDER BY 
   CUIIO

     )
   
GROUP BY
CUIIO,
COL1, COL2

)