  SELECT 
   R.CUIIO,
   R.DENUMIRE,
   SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) THEN D.COL1  ELSE NULL  END) AS COL1,
   NULL AS COL2
   

 FROM
      CIS2.VW_DATA_ALL D  
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS
      


WHERE  D.PERIOADA IN (:pPERIOADA-1) AND
       D.FORM = :pFORM AND
       D.FORM_VERS IN (2000)  AND  

       D.CAPITOL IN (1181) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
       AND D.CAPITOL = 1181
       AND D.RIND IN ('110','111','112','113','120')
       AND D.CUIIO=2245786
     
  

GROUP BY  
   R.CUIIO,
   R.DENUMIRE


