SELECT 
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE,
ROUND(SUM(D.COL1),0) AS COL1,
ROUND(SUM(D.COL2),0) AS COL2,
ROUND(SUM(D.COL3),0) AS COL3,
SUM(D.COL4) AS COL4,
ROUND(SUM(D.COL5),1) AS COL5,
ROUND(SUM(D.COL6),1) AS COL6,
ROUND(SUM(D.COL7),1) AS COL7

FROM 
(
SELECT
CUIIO,
CUATM,
SUM(COL1) AS COL1,
SUM(COL2) AS COL2,
SUM(COL3) AS COL3,
SUM(COL4) AS COL4,
SUM(R_520 / 1000) AS COL5, 
SUM((R_520 / 1000) * (R_531 / 100)) AS COL6,
SUM((R_520 / 1000) * (R_532 / 100)) AS COL7
   FROM

(
SELECT
D.CUIIO,
D.CUATM,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('511','512') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS COL1,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('511')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL2,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('512')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL3,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('513')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL4,
SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE NULL  END) AS R_520,
SUM (CASE WHEN D.RIND  IN ('531') THEN  D.COL1 ELSE NULL  END) AS R_531,
SUM (CASE WHEN D.RIND  IN ('532') THEN  D.COL1 ELSE NULL  END) AS R_532

 FROM
      CIS2.VW_DATA_ALL D        
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1185) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
     -- AND D.CUIIO = 40211764
  
  GROUP BY
  D.CUIIO,
  D.CUATM
     
)         


GROUP BY
CUIIO,
CUATM 

) D

      INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
      INNER JOIN CIS2.VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||'%' 
      
      WHERE
      CC.PRGS IN ('2')
      GROUP BY
      CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE


ORDER BY
CC.FULL_CODE