INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,   
  COL1, COL2, COL3
)

  SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW AS NR_ROW,
   ROWNUM AS ORDINE,
  '000' AS DECIMAL_POS,
   NUME_ROW AS NUME_ROW,
   COL1,COL2, 
   COL3
  
   
  

FROM
(

SELECT 
   CC.CODUL AS NR_ROW,  
   CC.FULL_CODE AS ORDINE,
  '000' AS DECIMAL_POS,
   CC.DENUMIRE AS NUME_ROW,
ROUND(SUM(D.COL1),1) AS COL1,
ROUND(SUM(D.COL2),1) AS COL2,
ROUND(SUM(D.COL3),1) AS COL3


FROM 
(

SELECT
CUIIO,
CAEM2,
SUM(R_930) AS COL1,
SUM(R_940) AS COL2,
SUM(R_999 / NULLIF(CAP_SR1,0)) AS COL3
   
FROM

(
SELECT
D.CUIIO,
D.CAEM2,
COUNT (DISTINCT(CASE WHEN D.Capitol= 1206 AND D.RIND  IN ('930') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS R_930,
COUNT (DISTINCT(CASE WHEN D.Capitol= 1206 AND D.RIND  IN ('940') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS R_940,
SUM (CASE WHEN D.Capitol= 1206 AND D.RIND  IN ('999') THEN  D.COL1 ELSE NULL  END) AS R_999,
COUNT (DISTINCT(CASE WHEN D.Capitol= 1195 AND D.RIND  IN ('1') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS CAP_SR1

  
 FROM
      CIS2.VW_DATA_ALL D        
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 
       AND
       D.CAPITOL IN (1195,1206) --AND
      -- D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
    --  AND D.CUIIO = 40211764
  
  GROUP BY
  D.CUIIO,
  D.CAEM2
     
)         


GROUP BY
CUIIO,
CAEM2 


) D

      INNER JOIN CIS2.VW_CL_CAEM2 C  ON(D.CAEM2=C.CODUL)
      INNER JOIN CIS2.VW_CL_CAEM2 CC ON(C.FULL_CODE LIKE '%'||CC.CODUL||';%')   
      
 
      GROUP BY
      CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE


ORDER BY
CC.FULL_CODE

)