SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW AS NR_ROW,
   ROWNUM AS ORDINE,
  '0000111' AS DECIMAL_POS,
   NUME_ROW AS NUME_ROW,
   CASE WHEN  COL1 = 0 THEN NULL ELSE COL1 END COL1, 
   CASE WHEN  COL2 = 0 THEN NULL ELSE COL2 END COL2,  
   CASE WHEN  COL3 = 0 THEN NULL ELSE COL3 END COL3, 
   CASE WHEN  COL4 = 0 THEN NULL ELSE COL4 END COL4, 
   COL5,
   COL6,
   COL7
   
  

FROM
(

SELECT 
   CC.CODUL AS NR_ROW,  
   CC.FULL_CODE AS ORDINE,
  '11101' AS DECIMAL_POS,
   CC.DENUMIRE AS NUME_ROW,
ROUND(SUM(D.COL1),0) AS COL1,
ROUND(SUM(D.COL2),0) AS COL2,
ROUND(SUM(D.COL3),0) AS COL3,
SUM(D.COL4) AS COL4,
ROUND(SUM(D.COL5),1) AS COL5,
ROUND(SUM(D.COL6),1) AS COL6,
ROUND(SUM(D.COL7),1) AS COL7

FROM 
(
SELECT
CUIIO,
CAEM2,
SUM(COL1) AS COL1,
SUM(COL2) AS COL2,
SUM(COL3) AS COL3,
SUM(COL4) AS COL4,
SUM(R_520 / 1000) AS COL5, 
SUM((R_520 / 1000) * (R_531 / 100)) AS COL6,
SUM((R_520 / 1000) * (R_532 / 100)) AS COL7   
FROM

(
SELECT
D.CUIIO,
D.CAEM2,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('511','512') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS COL1,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('511')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL2,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('512')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL3,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('513')    AND   CIS2.NVAL(D.COL1)=1 THEN D.CUIIO END)) AS COL4,
SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE NULL  END) AS R_520,
SUM (CASE WHEN D.RIND  IN ('531') THEN  D.COL1 ELSE NULL  END) AS R_531,
SUM (CASE WHEN D.RIND  IN ('532') THEN  D.COL1 ELSE NULL  END) AS R_532
  
 FROM
      CIS2.VW_DATA_ALL D        
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1185) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
    --  AND D.CUIIO = 40211764
  
  GROUP BY
  D.CUIIO,
  D.CAEM2
     
)         


GROUP BY
CUIIO,
CAEM2 ) D

      INNER JOIN CIS2.VW_CL_CAEM2 C  ON(D.CAEM2=C.CODUL)
      INNER JOIN CIS2.VW_CL_CAEM2 CC ON(C.FULL_CODE LIKE '%'||CC.CODUL||';%')   
      
 
      GROUP BY
      CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE


ORDER BY
CC.FULL_CODE

)