SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   NR_ROW AS NR_ROW,
   ROWNUM AS ORDINE,
  '011101' AS DECIMAL_POS,
   NUME_ROW AS NUME_ROW,
   COL1,COL2, 
   COL3, 
   CASE WHEN  COL4 = 0 THEN NULL ELSE COL4 END COL4, 
   COL5
   
  

FROM
(

SELECT 
   CC.CODUL AS NR_ROW,  
   CC.FULL_CODE AS ORDINE,
  '11101' AS DECIMAL_POS,
   CC.DENUMIRE AS NUME_ROW,
ROUND(SUM(D.COL1),1) AS COL1,
ROUND(SUM(D.COL2),1) AS COL2,
ROUND(SUM(D.COL3),1) AS COL3,
SUM(D.COL4) AS COL4,
ROUND(SUM(D.COL5),1) AS COL5

FROM 
(
SELECT
CUIIO,
CAEM2,
SUM(R_520 / 1000) AS COL1,
SUM((R_520 / 1000) * (R_541 / 100)) AS COL2,
SUM((R_520 / 1000) * (R_542 / 100)) AS COL3,
SUM(COL4) AS COL4,
SUM(R_570 / 1000) AS COL5    
FROM

(
SELECT
D.CUIIO,
D.CAEM2,
SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE NULL  END) AS R_520,
SUM (CASE WHEN D.RIND  IN ('541') THEN  D.COL1 ELSE NULL  END) AS R_541,
SUM (CASE WHEN D.RIND  IN ('542') THEN  D.COL1 ELSE NULL  END) AS R_542,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('560') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS COL4,
SUM (CASE WHEN D.RIND  IN ('570') THEN  D.COL1 ELSE NULL  END) AS R_570
  
 FROM
      CIS2.VW_DATA_ALL D        
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1185) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
    --  AND D.CUIIO = 40211764
  
  GROUP BY
  D.CUIIO,
  D.CAEM2
     
)         


GROUP BY
CUIIO,
CAEM2 ) D

      INNER JOIN CIS2.VW_CL_CAEM2 C  ON(D.CAEM2=C.CODUL)
      INNER JOIN CIS2.VW_CL_CAEM2 CC ON(C.FULL_CODE LIKE '%'||CC.CODUL||';%')   
      
 
      GROUP BY
      CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE


ORDER BY
CC.FULL_CODE

)