SELECT
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE,

  ROUND(SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE 0   END) / 1000,1) AS COL1,
  
  
  ROUND((SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE 0   END) / 1000)  *
  SUM (CASE WHEN D.RIND  IN ('541')  THEN  D.COL1 ELSE 0   END) / 100,1) AS COL2,
  
  ROUND((SUM (CASE WHEN D.RIND  IN ('520')   THEN  D.COL1 ELSE 0   END) / 1000)  *
  SUM (CASE WHEN D.RIND  IN ('542')   THEN  D.COL1 ELSE 0   END) / 100,1) AS COL3,
  
   CIS2.NVAL(COUNT (DISTINCT(CASE WHEN D.RIND  IN ('560') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END))) AS COL4,
  ROUND(SUM (CASE WHEN D.RIND  IN ('570') AND D.CAPITOL IN (1185)     THEN  D.COL1 ELSE 0   END) / 1000,1) AS COL5

FROM
      CIS2.VW_DATA_ALL D        
      INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
      INNER JOIN CIS2.VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||'%' 
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1185) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
       AND CC.PRGS IN ('2')
       
 --   AND D.CUIIO = 40460355
     
        
 GROUP BY
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE       

ORDER BY

CC.FULL_CODE