SELECT 
CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE,
ROUND(SUM(D.COL1),1) AS COL1,
ROUND(SUM(D.COL2),1) AS COL2,
ROUND(SUM(D.COL3),1) AS COL3,
SUM(D.COL4) AS COL4,
ROUND(SUM(D.COL5),1) AS COL5

FROM 
(
SELECT
CUIIO,
CUATM,
SUM(R_520 / 1000) AS COL1,
SUM((R_520 / 1000) * (R_541 / 100)) AS COL2,
SUM((R_520 / 1000) * (R_542 / 100)) AS COL3,
SUM(COL4) AS COL4,
SUM(R_570 / 1000) AS COL5    
FROM

(
SELECT
D.CUIIO,
D.CUATM,
SUM (CASE WHEN D.RIND  IN ('520') THEN  D.COL1 ELSE NULL  END) AS R_520,
SUM (CASE WHEN D.RIND  IN ('541') THEN  D.COL1 ELSE NULL  END) AS R_541,
SUM (CASE WHEN D.RIND  IN ('542') THEN  D.COL1 ELSE NULL  END) AS R_542,
COUNT (DISTINCT(CASE WHEN D.RIND  IN ('560') AND   CIS2.NVAL(D.COL1)=1  THEN D.CUIIO END)) AS COL4,
SUM (CASE WHEN D.RIND  IN ('570') THEN  D.COL1 ELSE NULL  END) AS R_570
  
 FROM
      CIS2.VW_DATA_ALL D        
      
      WHERE  
       D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
       D.CAPITOL IN (1185) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||'%'
    --  AND D.CUIIO = 40211764
  
  GROUP BY
  D.CUIIO,
  D.CUATM
     
)         


GROUP BY
CUIIO,
CUATM ) D

      INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
      INNER JOIN CIS2.VW_CL_CUATM CC ON C.FULL_CODE LIKE '%'||CC.CODUL||'%' 
      
      WHERE
      CC.PRGS IN ('2')
      GROUP BY
      CC.CODUL,
CC.DENUMIRE,
CC.FULL_CODE


ORDER BY
CC.FULL_CODE