BEGIN
INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,   
COL1, COL2, COL3,COL4, COL5
)

  SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,        
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW||'~'||ROWNUM AS NR_ROW,
  ROWNUM AS ORDINE,
  '00000' AS DECIMAL_POS,
   DENUMIRE||'-'||NUME_ROW AS NUME_ROW,
   CUIIO AS COL1, 
   CUATM AS COL2,
   PACHET AS COL3,
   COL1 AS COL4,
   COL2 AS COL5

   FROM
(
SELECT 
L.CUIIO,
L.DENUMIRE,
L.CUATM,
L.NR_ROW,
L.ORDINE,
 MAX(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(L.NUME_ROW,'emsp'),'1'),'&'),'3'),'.'),';'),'-'),'2'),'4')) AS NUME_ROW, 
L.PACHET,
SUM(L.COL1) AS COL1,
SUM(R.COL2) AS COL2
FROM 
(
SELECT
   R.CUIIO,
   MAX(R.DENUMIRE) DENUMIRE,
   R.CUATM,
   RD.RIND AS NR_ROW,  
   RD.ORDINE AS ORDINE,
   RD.DENUMIRE AS NUME_ROW, 
   D.PACHET,
   CIS2.NVAL(MAX (CASE WHEN D.CAPITOL IN (1185) AND RD.RIND LIKE '%'||D.RIND||'%'  THEN D.COL1 ELSE NULL END)) AS COL1, 
NULL AS COL2 

 FROM
      CIS2.VW_DATA_ALL D 
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS 
      CROSS JOIN (
      SELECT 

      D.RIND,
      D.DENUMIRE,
      D.RIND_VERS,
      D.ORDINE  
     FROM     CIS2.MD_RIND D
     
     WHERE 
     
     D.CAPITOL  IN (1185)
     AND D.CAPITOL_VERS = 2014 
     AND D.RIND IN ('511','512','520','531','532','533','541','542','543','560','570')   
     
     AND STATUT IN ('1')
      AND D.FORM_VERS = 2011
GROUP BY 
      D.RIND,
      D.RIND_VERS,
      D.DENUMIRE,
      D.ORDINE          
      
      ORDER BY 
      D.ORDINE
      
      
      ) RD
      
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1185) 
           
      -- AND D.CUIIO = 37720723
         
GROUP BY  
   R.CUIIO,
   R.CUATM,
   RD.RIND,  
   RD.ORDINE,
   RD.DENUMIRE,
   D.PACHET  
   
   ORDER BY
   R.CUIIO,
   RD.ORDINE
    ) L   LEFT JOIN (
    
    SELECT
   R.CUIIO,
   MAX(R.DENUMIRE) DENUMIRE,
   R.CUATM,
   CASE 
   WHEN RD.RIND IN '611' THEN '511'
   WHEN RD.RIND IN '612' THEN '512'
   WHEN RD.RIND IN '620' THEN '520'
   WHEN RD.RIND IN '631' THEN '531' 
   WHEN RD.RIND IN '632' THEN '532'
   WHEN RD.RIND IN '633' THEN '533'
   WHEN RD.RIND IN '641' THEN '541'
   WHEN RD.RIND IN '642' THEN '542'
   WHEN RD.RIND IN '643' THEN '543'
   WHEN RD.RIND IN '660' THEN '560'
   WHEN RD.RIND IN '670' THEN '570'              
   
   ELSE RD.RIND END  AS NR_ROW,  
   RD.ORDINE AS ORDINE,
   RD.DENUMIRE AS NUME_ROW, 
   D.PACHET,
   NULL AS COL1, 
   CIS2.NVAL(SUM (CASE WHEN D.CAPITOL IN (1186) AND RD.RIND LIKE '%'||D.RIND||'%'  THEN D.COL1 ELSE NULL END))  AS COL2 

 FROM
      CIS2.VW_DATA_ALL D 
      INNER JOIN CIS2.RENIM R ON R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS 
      CROSS JOIN (
      SELECT 

      D.RIND,
      D.DENUMIRE,
      D.RIND_VERS,
      D.ORDINE  
     FROM     CIS2.MD_RIND D
     
     WHERE 
     
     D.CAPITOL  IN (1186)
     AND D.CAPITOL_VERS = 2012 
     AND D.RIND IN ('611','612','620','631','632','633','641','642','643','660','670')  
     AND D.FORM_VERS IN (2011) 
GROUP BY 
      D.RIND,
      D.DENUMIRE,
      D.RIND_VERS,
      D.ORDINE          
      
      ORDER BY 
      D.ORDINE
      
      
      ) RD
      
     
WHERE  
       D.FORM IN (71)             AND  
       D.PERIOADA IN (:pPERIOADA -2 ) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
       D.CAPITOL IN (1186) 
           
     --  AND D.CUIIO = 37720723
         
GROUP BY  
   R.CUIIO,
   R.CUATM,
   RD.RIND,  
   RD.ORDINE,
   RD.DENUMIRE,
   D.PACHET  
  
   ORDER BY
   R.CUIIO,
   RD.ORDINE
   
    )  R ON R.CUIIO = L.CUIIO AND L.NR_ROW = R.NR_ROW
    
    
    
    
    GROUP BY
    L.CUIIO,
L.DENUMIRE,
L.CUATM,
L.NR_ROW,
L.ORDINE,
L.NUME_ROW,
L.PACHET


) 
 ;
END; 
