SELECT
  'Rind. '||MR.RIND||': '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) AND (D.PERIOADA IN (:PERIOADA-1)) THEN CIS2.NVAL(D.COL13) ELSE 0 END))||' <> '||
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) AND (D.PERIOADA IN (:PERIOADA)) THEN CIS2.NVAL(D.COL1) ELSE 0 END)) 
  
  AS REZULTAT


FROM CIS2.VW_DATA_ALL_GC D

                                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD

WHERE
  (D.PERIOADA IN (:PERIOADA, :PERIOADA-1)   ) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS     OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (62)  AND
  D.CAPITOL IN (1117)  
   
 
  
GROUP BY 
MR.RIND
  
HAVING 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) AND (D.PERIOADA IN (:PERIOADA-1)) THEN CIS2.NVAL(D.COL13) ELSE 0 END)) <> 
  CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1117) AND (D.PERIOADA IN (:PERIOADA)) THEN CIS2.NVAL(D.COL1) ELSE 0 END)) 
  

ORDER BY MR.RIND