SELECT 

    D.RIND, 
    SUM(D.COL1) AS COL1
   
   FROM  CIS2.VW_DATA_ALL_GC  D
    INNER JOIN CIS2.MD_RIND R ON D.RIND=R.RIND AND D.ID_MD = R.ID_MD
WHERE
  (D.PERIOADA IN  (:pPERIOADA))  AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (62)  AND
  D.CAPITOL IN (1116) --AND D.UNIT_CODE=835349
  AND D.RIND IN ('5200')
  
  
  GROUP BY 
  D.RIND
  
  

  
  