--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2
--)

SELECT
-- :pPERIOADA AS PERIOADA,
--  :pFORM AS FORM,
--  :pFORM_VERS AS FORM_VERS,
--  :pID_MDTABLE AS ID_MDTABLE,
--  :pCOD_CUATM AS COD_CUATM,
  
--  '0' AS NR_SECTIE,
--  '0' AS NUME_SECTIE,
--  '0' AS NR_SECTIE1,
--  '0' AS NUME_SECTIE1,
--  '0' AS NR_SECTIE2,
--  '0' AS NUME_SECTIE2,
  A.NR_ROW,
  A.ORDINE,
  '01' AS DECIMAL_POS,
  A.NUME_ROW,
  ROUND(A.COL1,0) AS COL1,
  ROUND(B.COL2,1) AS COL2
FROM
(SELECT 
  
  MR.RIND||'~'||MR.ORDINE AS NR_ROW,
  MR.ORDINE AS ORDINE,
  REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'<br>'),'nbsp'),'&;') AS NUME_ROW,
  SUM(D.COL1) AS COL1
FROM 
  MD_RIND MR
  LEFT JOIN VW_DATA_ALL D ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
--  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS) 
WHERE
--  D.PERIOADA IN (:pPERIOADA) AND 
--  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  MR.FORM IN (34)                 AND 
  MR.CAPITOL IN (384) 
  
  AND D.CUIIO IN (

SELECT 
CUIIO 
FROM 

(
SELECT

    D.CUIIO,
    R.DENUMIRE,
    D.RIND,
    SUM(D.COL1) AS COL1
    
    
     FROM CIS2.VW_DATA_ALL D    
                INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS  = D.CUIIO_VERS   
     
     WHERE 
     
     D.FORM  =  34
     AND D.PERIOADA = 2010
     AND D.CAPITOL = 383
     AND D.RIND IN ('90')
     
     GROUP BY 
     D.CUIIO,
     R.DENUMIRE,
     D.RIND      
       
      
      HAVING 
      SUM(D.COL1) < 50000
     
     ORDER BY 
     SUM(D.COL1) DESC 
    

)

)

GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE) A
LEFT JOIN
(SELECT 
  R.NR_ROW||'~'||R.ORDINE AS NR_ROW,
  R.ORDINE AS ORDINE,
  R.NUME_ROW AS NUME_ROW,
  CASE 
    WHEN R.ORDINE IN (3) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0689') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0688') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (5) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0691') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0690') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (7) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0693') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0692') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (9) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0695') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0694') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (12) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0697') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0696') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (14) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0699') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0698') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (16) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0701') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0700') THEN D.COL1 END)))*1000
    WHEN R.ORDINE IN (18) THEN
    NVAL(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0703') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN R.NR_ROW LIKE '%'||D.RIND||'%' AND D.RIND IN ('0702') THEN D.COL1 END)))*1000
    END
  AS COL2
FROM 
  MD_RIND MR
  LEFT JOIN VW_DATA_ALL D ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
  CROSS JOIN (
    SELECT '0689/0688' AS NR_ROW, 'livezi, mii lei' AS NUME_ROW, 3 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0691/0690' AS NR_ROW, 'vii, mii lei' AS NUME_ROW, 5 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0693/0692' AS NR_ROW, 'arbusti fructiferi, mii lei' AS NUME_ROW, 7 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0695/0694' AS NR_ROW, 'alte plantatii perene, mii lei' AS NUME_ROW, 9 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0697/0696' AS NR_ROW, ' livezi, mii lei' AS NUME_ROW, 12 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0699/0698' AS NR_ROW, ' vii, mii lei' AS NUME_ROW, 14 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0701/0700' AS NR_ROW, ' arbusti fructiferi, mii lei' AS NUME_ROW, 16 AS ORDINE, '34' AS FORM FROM DUAL UNION
    SELECT '0703/0702' AS NR_ROW, ' alte plantatii perene, mii lei' AS NUME_ROW, 18 AS ORDINE, '34' AS FORM FROM DUAL
  ) R 
WHERE
  MR.FORM IN (34)                 AND 
  MR.CAPITOL IN (384) 
  
  

GROUP BY
  R.NR_ROW,
  R.ORDINE,
  R.NUME_ROW) B ON A.ORDINE=B.ORDINE