--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2,COL3,COL4,COL5
--)

SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  MR.RIND AS NR_ROW,
  MR.ORDINE AS ORDINE,
  '00000' AS DECIMAL_POS,
  REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MR.DENUMIRE,'</b>'),'<b>'),'<br>'),'nbsp'),'&;') AS NUME_ROW,
  SUM(D.COL1) AS COL1,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  SUM(D.COL5) AS COL5
FROM 
  MD_RIND MR
  LEFT JOIN VW_DATA_ALL D ON (D.FORM=MR.FORM AND D.ID_MD=MR.ID_MD AND D.CAPITOL=MR.CAPITOL AND D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%')
--  INNER JOIN RENIM RE ON (D.CUIIO=RE.CUIIO AND D.CUIIO_VERS=RE.CUIIO_VERS) 
WHERE
--  D.PERIOADA IN (:pPERIOADA) AND 
--  D.FORM_VERS = :pFORM_VERS     AND    
--  (:pID_MDTABLE=:pID_MDTABLE) AND
--  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  MR.FORM IN (34)                 AND 
  MR.CAPITOL IN (383) 
  
  
  AND D.CUIIO IN (
  

SELECT 
DISTINCT 
CUIIO 

FROM 

(
SELECT

    D.CUIIO,
    R.DENUMIRE,
    D.RIND,
    SUM(D.COL1) AS COL1
    
    
     FROM CIS2.VW_DATA_ALL D    
                INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS  = D.CUIIO_VERS   
     
     WHERE 
     
     D.FORM  =  34
     AND D.PERIOADA = 2011
     AND D.CAPITOL = 383
     AND D.RIND IN ('90')
     
     GROUP BY 
     D.CUIIO,
     R.DENUMIRE,
     D.RIND      
       
      
      HAVING 
      SUM(D.COL1) < 50000
     
     ) 
    

)
GROUP BY
  MR.RIND,
  MR.DENUMIRE,
  MR.ORDINE
  
  ORDER BY 
  
  MR.ORDINE