SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0'AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  ROUND(COL1,0)||'~'||ORDINE AS NR_ROW,
  ORDINE,
  '00011' AS DECIMAL_POS,
  ORDINE||' - '||DENUMIRE AS NUME_ROW,
  ROUND(COL2,0) AS COL1,
  ROUND(COL3,0) AS COL2,
  ROUND(COL4,1) AS COL3,
  ROUND(COL5,0) AS COL4,
  ROUND(COL6,0) AS COL5
FROM
(
SELECT
  R.DENUMIRE,
  TO_NUMBER(R.CUIIO) AS ORDINE,
  SUM(D.COL1) AS COL1,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  NVAL(SUM(D.COL3))/
  NOZERO(SUM(D.COL2)) AS COL5,
  NVAL(SUM(D.COL4))/
  NOZERO(SUM(D.COL2)) AS COL6
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) AND
  D.RIND IN ('1191')
GROUP BY
  R.DENUMIRE,
  R.CUIIO
UNION 
SELECT
  'TOTAL' AS DENUMIRE,
  0 AS ORDINE,
  SUM(D.COL1) AS COL1,
  SUM(D.COL2) AS COL2,
  SUM(D.COL3) AS COL3,
  SUM(D.COL4) AS COL4,
  NVAL(SUM(D.COL3))/
  NOZERO(SUM(D.COL2)) AS COL5,
  NVAL(SUM(D.COL4))/
  NOZERO(SUM(D.COL2)) AS COL6
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM R ON (D.CUIIO=R.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND

  D.FORM IN (45)AND   
  D.CAPITOL IN (399) AND
  D.RIND IN ('1191')
);