SELECT DISTINCT
  'Codul CUIIO='||D.CUIIO||' exista deja in sistemul BNS'
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL_TEMP D

WHERE
  (D.PERIOADA=:PERIOADA         ) AND
  (D.CUIIO=:CUIIO               ) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (:FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD) AND
  D.CAPITOL_DEN NOT IN ('TITLU')
  AND D.FORM NOT IN (7,12,33,45,26,6)
  
  
  
  AND (CASE WHEN D.FORM IN (21) AND D.CAPITOL IN (357,358) AND COL2 IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1)  
  AND (CASE WHEN D.FORM IN (8) AND D.CAPITOL IN (323) AND COL3 IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) 
  AND (CASE WHEN D.FORM IN (8) AND D.CAPITOL IN (323) AND COL4 IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) 
  AND (CASE WHEN D.FORM IN (8) AND D.CAPITOL IN (420) AND COL2 IS NOT NULL THEN 1 ELSE 0 END) NOT IN (1) 
