
SELECT 
   RR.NR_ROW,
  ROUND(SUM ( CASE WHEN  1=1 THEN DECODE(RR.NR_ROW, 
         '100', (DD.COL1),
         '110', (DD.COL2),
         '111', (DD.COL3),
         '112', (DD.COL4),
         '120', (DD.COL5) --here i added CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('120') THEN  CIS2.NVAL(D.COL1) END))  AS COL5
         
         )
       --Add next row (rind)  
         
         
         END),1)     AS COL1,
 
 SUM( CASE WHEN (DD.PERS BETWEEN 0 AND 9 OR DD.PERS IS NULL ) THEN  (DECODE(RR.NR_ROW, 
      
       
         '100',(DD.COL1),
         '110',(DD.COL2),
         '112',(DD.COL4),
         '120',(DD.COL5) --here i added CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('120') THEN  CIS2.NVAL(D.COL1) END))  AS COL5
       
         )) END)
       --Add next row (rind)   
         AS COL2
         
        
 

    FROM 
  (
-------------------------------------------------------------------------------
SELECT 
 --From here 
 DISTINCT D.CUIIO, 
   CASE WHEN MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) IS NULL THEN  MAX(SUBSTR(D.CAEM2,2,4)) 
   ELSE MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END )  END AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
 D.CUIIO_VERS, 
 D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD')  THEN  D.COL1 ELSE 0 END))  AS COL0,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('100') THEN  CIS2.NVAL(D.COL1) END))  AS COL1,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('110') THEN  CIS2.NVAL(D.COL1) END))  AS COL2,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('111') THEN  CIS2.NVAL(D.COL1) END))  AS COL3,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('112') THEN  CIS2.NVAL(D.COL1) END))  AS COL4,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('120') THEN  CIS2.NVAL(D.COL1) END))  AS COL5,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('121') THEN  CIS2.NVAL(D.COL1) END))  AS COL6,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('122') THEN  CIS2.NVAL(D.COL1) END))  AS COL7,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('130') THEN  CIS2.NVAL(D.COL1) END))  AS COL8,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('140') THEN  CIS2.NVAL(D.COL1) END))  AS COL9,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150') THEN  CIS2.NVAL(D.COL1) END))  AS COL10,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('151') THEN  CIS2.NVAL(D.COL1) END))  AS COL11,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('160') THEN  CIS2.NVAL(D.COL1) END))  AS COL12,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('170') THEN  CIS2.NVAL(D.COL1) END))  AS COL13,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN  CIS2.NVAL(D.COL1) END))  AS COL14,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN  CIS2.NVAL(D.COL1) END))  AS COL15,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('210') THEN  CIS2.NVAL(D.COL1) END))  AS COL16,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN  CIS2.NVAL(D.COL1) END))  AS COL17,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('221') THEN  CIS2.NVAL(D.COL1) END))  AS COL18,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('222') THEN  CIS2.NVAL(D.COL1) END))  AS COL19,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN  CIS2.NVAL(D.COL1) END))  AS COL20,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('241') THEN  CIS2.NVAL(D.COL1) END))  AS COL21,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('242') THEN  CIS2.NVAL(D.COL1) END))  AS COL22,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('243') THEN  CIS2.NVAL(D.COL1) END))  AS COL23,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('260') THEN  CIS2.NVAL(D.COL1) END))  AS COL24,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('270') THEN  CIS2.NVAL(D.COL1) END))  AS COL25,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('280') THEN  CIS2.NVAL(D.COL1) END))  AS COL26,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('281') THEN  CIS2.NVAL(D.COL1) END))  AS COL27,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('282') THEN  CIS2.NVAL(D.COL1) END))  AS COL28,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN  CIS2.NVAL(D.COL1) END))  AS COL29,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('291') THEN  CIS2.NVAL(D.COL1) END))  AS COL30,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2911') THEN  CIS2.NVAL(D.COL1) END))  AS COL31,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2912') THEN  CIS2.NVAL(D.COL1) END))  AS COL32,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('292') THEN  CIS2.NVAL(D.COL1) END))  AS COL33,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('293') THEN  CIS2.NVAL(D.COL1) END))  AS COL34,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2931') THEN  CIS2.NVAL(D.COL1) END))  AS COL35,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN  CIS2.NVAL(D.COL1) END))  AS COL36,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2941') THEN  CIS2.NVAL(D.COL1) END))  AS COL37,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2942') THEN  CIS2.NVAL(D.COL1) END))  AS COL38,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2943') THEN  CIS2.NVAL(D.COL1) END))  AS COL39,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2944') THEN  CIS2.NVAL(D.COL1) END))  AS COL40,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('295') THEN  CIS2.NVAL(D.COL1) END))  AS COL41,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('296') THEN  CIS2.NVAL(D.COL1) END))  AS COL42,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2961') THEN  CIS2.NVAL(D.COL1) END))  AS COL43,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('2962') THEN  CIS2.NVAL(D.COL1) END))  AS COL44,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('297') THEN  CIS2.NVAL(D.COL1) END))  AS COL45,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('300') THEN  CIS2.NVAL(D.COL1) END))  AS COL46,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('310') THEN  CIS2.NVAL(D.COL1) END))  AS COL47,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN  CIS2.NVAL(D.COL1) END))  AS COL48,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('320') THEN  CIS2.NVAL(D.COL2) END))  AS COL49,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN  CIS2.NVAL(D.COL1) END))   AS COL50,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN  CIS2.NVAL(D.COL2) END))  AS COL51,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN  CIS2.NVAL(D.COL1) END))  AS COL52,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN  CIS2.NVAL(D.COL2) END))  AS COL53,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN  CIS2.NVAL(D.COL1) END))  AS COL54,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN  CIS2.NVAL(D.COL2) END))  AS COL55,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL1) END))  AS COL56,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL2) END))  AS COL57,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL3) END))  AS COL58,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL1) END))  AS COL56,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL2) END))  AS COL57,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  CIS2.NVAL(D.COL3) END))  AS COL58,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN  CIS2.NVAL(D.COL1) END))  AS COL59,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN  CIS2.NVAL(D.COL2) END))  AS COL60,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1128) AND D.RIND IN ('500') THEN  CIS2.NVAL(D.COL3) END))  AS COL61,
 
 --Rindurile se incep de la 100 col1 pana la randul 500 col61- Asa sa-mi adaugi 
 --Utilizeaza nu mai decode 
 (SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 
 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS
 
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
  AND D.CUIIO IN (26844)


 GROUP BY D.CUIIO, D.CUIIO_VERS, D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA
 
HAVING
--  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) >0
  AND 
 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('1','5') THEN  D.COL1 ELSE 0 END)) > 0
 
 )DD

CROSS JOIN
(
    SELECT '100' AS NR_ROW, 'COL1' AS COL FROM DUAL UNION ALL 
    SELECT '110' AS NR_ROW, 'COL2' AS COL FROM DUAL UNION ALL 
    SELECT '120' AS NR_ROW, 'COL3' AS COL FROM DUAL UNION ALL 
    SELECT '130' AS NR_ROW, 'COL4' AS COL FROM DUAL UNION ALL 
    SELECT '140' AS NR_ROW, 'COL5' AS COL FROM DUAL UNION ALL 
    SELECT '150' AS NR_ROW, 'COL6' AS COL FROM DUAL UNION ALL 
    SELECT '160' AS NR_ROW, 'COL7' AS COL FROM DUAL UNION ALL 
    SELECT '170' AS NR_ROW, 'COL8' AS COL FROM DUAL UNION ALL 
    SELECT '180' AS NR_ROW, 'COL9' AS COL FROM DUAL UNION ALL 
    SELECT '190' AS NR_ROW, 'COL10' AS COL FROM DUAL UNION ALL 
    SELECT '200' AS NR_ROW, 'COL11' AS COL FROM DUAL UNION ALL 
    SELECT '210' AS NR_ROW, 'COL12' AS COL FROM DUAL UNION ALL 
    SELECT '220' AS NR_ROW, 'COL13' AS COL FROM DUAL UNION ALL 
    SELECT '230' AS NR_ROW, 'COL14' AS COL FROM DUAL UNION ALL 
    SELECT '240' AS NR_ROW, 'COL15' AS COL FROM DUAL UNION ALL 
    SELECT '250' AS NR_ROW, 'COL16' AS COL FROM DUAL UNION ALL 
    SELECT '260' AS NR_ROW, 'COL17' AS COL FROM DUAL UNION ALL 
    SELECT '270' AS NR_ROW, 'COL18' AS COL FROM DUAL UNION ALL 
    SELECT '280' AS NR_ROW, 'COL19' AS COL FROM DUAL UNION ALL 
    SELECT '290' AS NR_ROW, 'COL20' AS COL FROM DUAL UNION ALL 
    SELECT '300' AS NR_ROW, 'COL21' AS COL FROM DUAL UNION ALL 
    SELECT '310' AS NR_ROW, 'COL22' AS COL FROM DUAL UNION ALL 
    SELECT '320' AS NR_ROW, 'COL23' AS COL FROM DUAL UNION ALL 
    SELECT '330' AS NR_ROW, 'COL24' AS COL FROM DUAL UNION ALL 
    SELECT '340' AS NR_ROW, 'COL25' AS COL FROM DUAL UNION ALL 
    SELECT '350' AS NR_ROW, 'COL26' AS COL FROM DUAL UNION ALL 
    SELECT '360' AS NR_ROW, 'COL27' AS COL FROM DUAL UNION ALL 
    SELECT '370' AS NR_ROW, 'COL28' AS COL FROM DUAL UNION ALL 
    SELECT '380' AS NR_ROW, 'COL29' AS COL FROM DUAL UNION ALL 
    SELECT '390' AS NR_ROW, 'COL30' AS COL FROM DUAL UNION ALL 
    SELECT '400' AS NR_ROW, 'COL31' AS COL FROM DUAL UNION ALL 
    SELECT '410' AS NR_ROW, 'COL32' AS COL FROM DUAL UNION ALL 
    SELECT '420' AS NR_ROW, 'COL33' AS COL FROM DUAL UNION ALL 
    SELECT '430' AS NR_ROW, 'COL34' AS COL FROM DUAL UNION ALL 
    SELECT '440' AS NR_ROW, 'COL35' AS COL FROM DUAL UNION ALL 
    SELECT '450' AS NR_ROW, 'COL36' AS COL FROM DUAL UNION ALL 
    SELECT '460' AS NR_ROW, 'COL37' AS COL FROM DUAL UNION ALL 
    SELECT '470' AS NR_ROW, 'COL38' AS COL FROM DUAL UNION ALL 
    SELECT '480' AS NR_ROW, 'COL39' AS COL FROM DUAL UNION ALL 
    SELECT '490' AS NR_ROW, 'COL40' AS COL FROM DUAL UNION ALL 
    SELECT '500' AS NR_ROW, 'COL41' AS COL FROM DUAL UNION ALL 
    SELECT '510' AS NR_ROW, 'COL42' AS COL FROM DUAL UNION ALL 
    SELECT '520' AS NR_ROW, 'COL43' AS COL FROM DUAL UNION ALL 
    SELECT '530' AS NR_ROW, 'COL44' AS COL FROM DUAL UNION ALL 
    SELECT '540' AS NR_ROW, 'COL45' AS COL FROM DUAL UNION ALL 
    SELECT '550' AS NR_ROW, 'COL46' AS COL FROM DUAL UNION ALL 
    SELECT '560' AS NR_ROW, 'COL47' AS COL FROM DUAL UNION ALL SELECT '570' AS NR_ROW, 'COL48' AS COL FROM DUAL UNION ALL SELECT '580' AS NR_ROW, 'COL49' AS COL FROM DUAL UNION ALL SELECT '590' AS NR_ROW, 'COL50' AS COL FROM DUAL UNION ALL SELECT '600' AS NR_ROW, 'COL51' AS COL FROM DUAL UNION ALL SELECT '610' AS NR_ROW, 'COL52' AS COL FROM DUAL UNION ALL SELECT '620' AS NR_ROW, 'COL53' AS COL FROM DUAL UNION ALL SELECT '630' AS NR_ROW, 'COL54' AS COL FROM DUAL UNION ALL SELECT '640' AS NR_ROW, 'COL55' AS COL FROM DUAL UNION ALL SELECT '650' AS NR_ROW, 'COL56' AS COL FROM DUAL UNION ALL SELECT '660' AS NR_ROW, 'COL57' AS COL FROM DUAL UNION ALL SELECT '670' AS NR_ROW, 'COL58' AS COL FROM DUAL UNION ALL SELECT '680' AS NR_ROW, 'COL59' AS COL FROM DUAL UNION ALL SELECT '690' AS NR_ROW, 'COL60' AS COL FROM DUAL UNION ALL SELECT '700' AS NR_ROW, 'COL61' AS COL FROM DUAL
) RR


         
 WHERE 
  (DD.FORM=:pFORM) AND
  (DD.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) 
 AND  DD.CUIIO=26844
 
   GROUP BY
    RR.NR_ROW       
    
    
   ORDER BY 
   RR.NR_ROW
