SELECT
D.CUIIO,
SUM(CASE  WHEN  D.CAPITOL IN (1124)  AND D.RIND IN ('150') THEN  NVAL(D.COL1) ELSE 0 END ) AS COL1

   
    FROM
 CIS2.VW_DATA_ALL D 


WHERE
  (D.PERIOADA=:PERIOADA        ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (64) 

 

GROUP BY 
D.CUIIO


