SELECT

 'Ati selectat '|| CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('1','2','3','4','5','6','7') THEN D.COL1 ELSE 0 END )) ||' cauza(e)' AS REZULTAT 
        
FROM VW_DATA_ALL_TEMP D

WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
   D.FORM IN (64)
  
HAVING

CIS2.NVAL(SUM(CASE WHEN D.CAPITOL     IN (100)  AND D.RIND IN ('1','2','3','4','5','6','7') THEN D.COL1 ELSE 0 END ))=0 OR 
CIS2.NVAL(SUM(CASE WHEN D.CAPITOL     IN (100)  AND D.RIND IN ('1','2','3','4','5','6','7') THEN D.COL1 ELSE 0 END )) >= 2 --AND
--CIS2.NVAL(SUM(CASE WHEN D.CAPITOL NOT IN (1129) THEN CIS2.NVAL(COL1)+CIS2.NVAL(COL2)+CIS2.NVAL(COL3)+CIS2.NVAL(COL4) ELSE 0 END )) <>0
