--Cap.III [r.320c .2]= [RSF prescurtat, Anexa 1 r.060 col.5 ] sau [RSF1 complet, Anexa 1, r.290 col.5 ] 

SELECT 

     L.CUIIO,
     NVAL(L.COL1)||' <> '||NVAL(R.COL2)||' <> '||NVAL(R.COL1) 
     
     AS REZULTAT
FROM

(


SELECT
D.CUIIO,
SUM(CASE  WHEN  D.CAPITOL IN (1126)  AND D.RIND IN ('320') THEN  NVAL(D.COL2) ELSE 0 END ) AS COL1

   
    FROM
 CIS2.VW_DATA_ALL D 


WHERE
  (D.PERIOADA=:PERIOADA        ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (64) 

 

GROUP BY 
D.CUIIO





) L LEFT JOIN (

SELECT
D.CUIIO,
ROUND(SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1120.060') THEN  D.COL2 ELSE NULL END ) / 1000,1) AS COL1,
ROUND(SUM(CASE WHEN   D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('57.1090.290') THEN  D.COL2 ELSE NULL END ) /1000,1)AS COL2
    
    FROM
 CIS2.VW_DATA_ALL_FR D 


WHERE
  (D.PERIOADA=:PERIOADA ) AND
    (D.CUIIO=:CUIIO                ) AND
  (:CUIIO_VERS=:CUIIO_VERS      OR :CUIIO_VERS <> CUIIO_VERS) AND
  (:FORM = :FORM                OR :FORM <> :FORM) AND
  (:FORM_VERS=:FORM_VERS        OR :FORM_VERS <>:FORM_VERS) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (:ID_MD=:ID_MD                 OR :ID_MD<>:ID_MD) AND
  

   
    D.FORM||'.'||D.CAPITOL||'.'||D.RIND IN ('63.1120.060','57.1090.290')
    AND D.CUIIO  =  40070909
    
    GROUP BY
    D.CUIIO

) R ON R.CUIIO = L.CUIIO 



GROUP BY
L.CUIIO,
L.COL1,

R.COL1,
R.COL2



HAVING


NVAL(L.COL1) <> NVAL(R.COL1) + NVAL(R.COL2) 


 
 
 

