SELECT

 SUM(CASE WHEN D.RIND IN ('293')    THEN  NVAL(D.COL1)  ELSE 0 END) ||' < '||  
 SUM(CASE WHEN D.RIND IN ('2931')  THEN  NVAL(D.COL1)  ELSE 0 END)

  
  AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (64) AND 
  D.RIND IN ('293','2931') AND D.CAPITOL IN (1125)
  
  
  HAVING  
  
 SUM(CASE WHEN D.RIND IN ('293')    THEN  NVAL(D.COL1)  ELSE 0 END)  <   
 SUM(CASE WHEN D.RIND IN ('2931')  THEN  NVAL(D.COL1)  ELSE 0 END)