SELECT 
    TO_CHAR(SUM(L.COL1), '9999990') || ' <> ' || TO_CHAR(SUM(R.COL1), '9999990.00') AS REZULTAT
FROM (
    SELECT
        D.CUIIO,
        SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN NVAL(D.COL1) ELSE 0 END) AS COL1
        
    FROM CIS2.VW_DATA_ALL D
    WHERE
        (D.PERIOADA = :PERIOADA) AND
        (D.CUIIO = :CUIIO) AND
        (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1) AND
        (D.FORM = :FORM) AND
        (D.FORM_VERS = :FORM_VERS) AND
        (D.CAPITOL = :CAPITOL OR :CAPITOL = -1) AND
        (D.CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
        (D.ID_MD = :ID_MD OR :ID_MD = -1) AND
        D.FORM IN (64)
       -- AND D.CUIIO = 40039029
    GROUP BY D.CUIIO
) L 
LEFT JOIN (
    SELECT
        D.CUIIO,
        
        SUM(CASE WHEN D.FORM || '.' || D.CAPITOL || '.' || D.RIND IN ('57.1090.260') THEN D.COL1 ELSE NULL END) / 1000 AS COL1
    FROM CIS2.VW_DATA_ALL_FR D
    WHERE
        (D.PERIOADA = :PERIOADA) AND
        (D.CUIIO = :CUIIO) AND
        (:CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS <> CUIIO_VERS) AND
        (:FORM = :FORM OR :FORM <> :FORM) AND
        (:FORM_VERS = :FORM_VERS OR :FORM_VERS <> :FORM_VERS) AND
        (:CAPITOL = :CAPITOL OR :CAPITOL <> :CAPITOL) AND
        (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
        (:ID_MD = :ID_MD OR :ID_MD <> :ID_MD) AND
        D.FORM || '.' || D.CAPITOL || '.' || D.RIND IN ('57.1090.260')
       -- AND D.CUIIO = 40039029
    GROUP BY D.CUIIO
) R ON R.CUIIO = L.CUIIO
GROUP BY
    L.CUIIO
    
    
    HAVING

NVAL(ROUND(SUM(L.COL1), 2)) <> NVAL(ROUND(SUM(R.COL1), 2))