SELECT

'Rind 200 - '|| SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN CIS2.NVAL(D.COL1) ELSE 0 END) ||' Rind 110 - ' 
||SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('110')  THEN D.COL1 ELSE 0 END) 
 
  
  AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
   
   D.FORM IN (64)
   --AND D.CUIIO IN (38929313)
 HAVING  
 ( 
( SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN D.COL1 ELSE 0 END) > 0 
 AND 
 SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('110')  THEN D.COL1 ELSE 0 END)  = 0 )

OR 


( SUM( CASE WHEN D.CAPITOL IN (1125) AND  D.RIND IN ('200')  THEN D.COL1 ELSE 0 END) = 0 
 AND 
 SUM( CASE WHEN D.CAPITOL IN (1124) AND  D.RIND IN ('110')  THEN D.COL1 ELSE 0 END)  > 0 )
) 
  
 AND NVAL((
SELECT 
NVAL(TO_NUMBER(TO_CHAR(NVAL(MAX(CASE WHEN D.CAPITOL IN (1127) AND D.RIND NOT IN ('400','-') THEN D.COL31 ELSE NULL END))))) AS CAEM2


FROM CIS2.VW_DATA_ALL D
WHERE
        (D.PERIOADA = :PERIOADA) AND
        (D.CUIIO = :CUIIO) AND
        (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1) AND
        (D.FORM = :FORM) AND
        (D.FORM_VERS = :FORM_VERS) AND
        (:CAPITOL = :CAPITOL OR :CAPITOL <> :CAPITOL) AND
        (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
        (D.ID_MD = :ID_MD OR :ID_MD = -1) AND
        D.FORM = 64 AND
        D.CAPITOL IN (1127) AND
        D.RIND NOT IN ('400','-')
        
     --   AND D.CUIIO IN (38929313)
    


HAVING 
TO_CHAR(NVAL(MAX(CASE WHEN D.CAPITOL IN (1127) AND D.RIND NOT IN ('400','-') THEN D.COL31 ELSE NULL END)))  LIKE '56%'

GROUP BY
D.CUIIO,
D.RIND
)) = 0