SELECT

D.CUIIO,
 CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('220')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END)) ||' < '||  
(CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('221')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END))+
 CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('222')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END)))
  
  AS REZULTAT

FROM
 CIS2.VW_DATA_ALL D 
 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
 -- (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.RIND IN ('220','221','222') AND D.CAPITOL IN (1125)


GROUP BY 
D.CUIIO
  
  HAVING  
  
 CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('220')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END)) < 
(CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('221')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END))+
 CIS2.NVAL(MAX( CASE WHEN D.RIND IN ('222')  THEN CIS2.NVAL(D.COL1)  ELSE 0 END)))
  