SELECT PERIOADA, ANUL, NUM, CUIIO, CUIIO_VERS, 
 FILIAL, CUATM, CUATM_FULL, CFP, CFOJ, 
 COCM, CAEM, CAEM2, BUGET, TIP, 
 PACHET, FORM, FORM_VERS, FORM_DEN, T_XML_FORM_ID, 
 CAPITOL, CAPITOL_VERS, CAPITOL_DEN, TAB, ID_MD, 
 RIND, RIND_VERS, ID_USER, USER_NAME, DATA_REG, 
 ID_SCHEMA

FROM USER_EREPORTING.VW_DATA_ALL
WHERE
FORM IN  64

AND PERIOADA = 2012

-----------------------------------------
ORDER BY
DATA_REG DESC 

----------------------------------