SELECT 
--D.CUIIO,
--D.RIND,
TO_CHAR(NVAL(MAX(CASE WHEN D.CAPITOL IN (1127) AND D.RIND NOT IN ('400','-') THEN D.COL31 ELSE NULL END))) AS CAEM2


FROM CIS2.VW_DATA_ALL D
WHERE
        (D.PERIOADA = :PERIOADA) AND
        (D.CUIIO = :CUIIO) AND
        (D.CUIIO_VERS = :CUIIO_VERS OR :CUIIO_VERS = -1) AND
        (D.FORM = :FORM) AND
        (D.FORM_VERS = :FORM_VERS) AND
        (:CAPITOL = :CAPITOL OR :CAPITOL <> :CAPITOL) AND
        (:CAPITOL_VERS = :CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
        (D.ID_MD = :ID_MD OR :ID_MD = -1) AND
        D.FORM = 64 AND
        D.CAPITOL IN (1127) AND
        D.RIND NOT IN ('400','-')
        
        AND D.CUIIO IN (38929313)
    


HAVING 
TO_CHAR(NVAL(MAX(CASE WHEN D.CAPITOL IN (1127) AND D.RIND NOT IN ('400','-') THEN D.COL31 ELSE NULL END))) LIKE '56%'

GROUP BY
D.CUIIO,
D.RIND