SELECT  DISTINCT       

             D.CUIIO,  
             R.CAEM2,
             MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL  END) AS CAEM_CALCULAT,
             ROUND(SUM(CASE WHEN D.CAPITOL IN (1180) AND D.RIND IN ('800') THEN D.COL1 ELSE 0 END ),2) AS CAP_8_RIND_800_COL1
           
 
            FROM CIS2.VW_DATA_ALL_COEF D 
            
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
                    WHERE 
                    D.FORM IN (64)
                    AND D.PERIOADA IN (2010)
--                    AND D.CUIIO = 400053 

                    GROUP BY 
                    D.CUIIO,
                    R.CAEM2


HAVING 

SUM(CASE WHEN D.CAPITOL IN (1180) AND D.RIND IN ('800') THEN D.COL1 ELSE 0 END ) > 0 

AND 

(

MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL  END)   LIKE '45%' OR 
MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL  END)   LIKE '46%' OR 
MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31 ELSE NULL  END)   LIKE '47%'


)

