/* Formatted on 12/7/2022 10:00:48 AM (QP5 v5.326) */
  SELECT DISTINCT D.CUIIO, D.CUIIO_VERS
    FROM CIS2.VW_DATA_ALL D
   WHERE D.FORM IN (64) AND D.PERIOADA IN (2010)
GROUP BY D.CUIIO, D.CUIIO_VERS
  HAVING MAX (
             CASE
                 WHEN D.CAPITOL IN (1129) AND D.RIND IN ('8') THEN D.COL31
                 ELSE NULL
             END) LIKE
             '45%'