SELECT
CODUL_NEMOD,
DENUMIRE,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6

FROM
(
SELECT 
CODUL_NEMOD,
DENUMIRE,
FULL_CODE,
ROUND(SUM(COL1),1) AS COL1,
ROUND(SUM(COL2),1) AS COL2,
ROUND(SUM(COL3),1) AS COL3,
ROUND(SUM(COL4),1) AS COL4,
ROUND(SUM(COL5),1) AS COL5,
ROUND(SUM(COL6),1) AS COL6
FROM

(
SELECT 
CC.FULL_CODE,
CC.DENUMIRE,
CC.CODUL CODUL_NEMOD,
CC.GRUPA,
CC.PRIM,

CASE  WHEN SUBSTR(CC.CODUL, -4) = '0000' THEN SUBSTR(CC.CODUL, 1, 1)
    ELSE CC.CODUL END CODUL, 
SUM(DD.COL0) AS COL1,
SUM(CASE WHEN DD.CFP IN ('11','12','13') THEN DD.COL0 ELSE NULL  END) AS COL2,
SUM(CASE WHEN DD.CFP IN ('14','15','16','17','18','19') THEN DD.COL0 ELSE NULL  END) AS COL3,
SUM(CASE WHEN DD.CFP IN ('20','21')  THEN DD.COL0 ELSE NULL  END) AS COL4,
SUM(CASE WHEN DD.CFP IN ('22','23','24','25','26','27') THEN DD.COL0 ELSE NULL  END) AS COL5,
SUM(CASE WHEN DD.CFP IN ('28') THEN DD.COL0 ELSE NULL  END) AS COL6

  
FROM 
(
SELECT 
  
 DISTINCT D.CUIIO, 
 CASE WHEN MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) IS NULL 
 THEN    MAX(SUBSTR(D.CAEM2,2,4))  ELSE MAX(CASE WHEN  D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END ) END 
 
 AS CAEM2_ACTUALIZAT,
--
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
 D.CFP,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD')  THEN  D.COL1 ELSE 0 END))  AS COL0

 
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
  AND D.CUIIO IN (26844)


 GROUP BY D.CUIIO, D.CUIIO_VERS
 ,D.CUATM, D.FORM,D.FORM_VERS,D.CUATM_FULL,D.PERIOADA,D.CFP
 
HAVING
--  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)) >0
  AND 
 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('1','5') THEN  D.COL1 ELSE 0 END)) > 0 ) DD
 
  
 INNER JOIN (
 SELECT
CODUL, 
DENUMIRE, 
GRUPA, 
ORDINE, 
FULL_CODE, 
NUM_CODE, 
PRIM                
                FROM  CIS2.VW_CL_CAEM2
                
               
                
                WHERE 
                CODUL LIKE 'C%'
                OR CODUL LIKE 'B%'
                OR CODUL LIKE 'D%'
                OR CODUL LIKE 'E%'
                OR CODUL LIKE 'F%'
                OR CODUL LIKE 'G%'
                OR CODUL LIKE 'H%'
                OR CODUL LIKE 'I%'
                OR CODUL LIKE 'J%'
                OR CODUL LIKE 'L%'
                OR CODUL LIKE 'M%'
                OR CODUL LIKE 'N%'
                OR CODUL LIKE 'S%'
             
                
                
                ) C ON      SUBSTR( C.CODUL,2,4) = DD.CAEM2_ACTUALIZAT              
               INNER JOIN (
               
               SELECT 
CODUL, 
DENUMIRE, 
GRUPA, ORDINE,
FULL_CODE, 
NUM_CODE, PRIM

FROM CIS2.VW_CL_CAEM2

WHERE 


  CODUL IN ('B0000','B5000','B6000','B8000','B9000','C0000','D0000','E0000','F0000','G0000','H0000','I0000','J0000','L0000','M0000','N0000','S0000','00000')


               ) CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%') 
               
               
               GROUP BY
CC.FULL_CODE,
CC.DENUMIRE,
CC.CODUL,
CC.GRUPA,
CC.PRIM
   
   ORDER BY 

   
   FULL_CODE
               
)


GROUP BY 
CODUL_NEMOD,
DENUMIRE,
FULL_CODE

ORDER BY 
FULL_CODE
)