SELECT 
L.NR_ROW,
L.ORDINE,
L.NUME_ROW,
L.COL1,
L.COL2,
L.COL3,
L.COL4,
L.COL5,
L.COL6,
L.COL7,
L.COL8,
L.COL9,
SUBSTR(R.CAEM2,2) CAEM2_PROD,
SUBSTR(RR.CAEM2,2) CAEM2_VAL_PROD 



FROM
(
SELECT 
NR_ROW,
NR_ROW AS ORDINE,
NUME_ROW,
COL1,COL2, COL1-COL2 AS COL3,
(COL1-COL2)/CIS2.NOZERO(COL1)*100 COL4,COL5,COL6, COL7, COL8, CASE WHEN COL8 IS NULL THEN COL7 ELSE COL8 END AS COL9
FROM
(
SELECT 
 DISTINCT D.CUIIO AS NR_ROW,D.CUATM AS NUME_ROW,
 CIS2.NVAL(MAX(DD.COL1)) AS COL1,--RSF1, VV
 CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('150') AND D.CAPITOL IN (1124) THEN D.COL1 ELSE NULL END)) AS COL2,--CIFRA DE AFACERI ASA 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN D.COL4 ELSE NULL END)) AS COL5,--NR. SCRIPTIC SALARIATI ASA
 CIS2.NVAL(MAX(DD.COL2)) AS COL6,-- RSF1, SALARIATI
 CIS2.NVAL(MAX(DD.COL3)) AS COL7,
 CIS2.NVAL(MAX(CASE WHEN D.RIND IN '8' AND D.CAPITOL IN (1129) THEN D.COL31 ELSE NULL END)) AS COL8
-- CIS2.NVAL(MAX(CASE WHEN D.RIND IN '8' AND D.CAPITOL IN (1129) THEN D.COL31 ELSE SUBSTR(D.CAEM2,2,4) END)) AS COL9
 



FROM
 CIS2.VW_DATA_ALL D  
 LEFT JOIN 
 (
SELECT DISTINCT D.CUIIO,D.PERIOADA,
CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('010') AND D.CAPITOL IN (1092) THEN D.COL2 ELSE NULL END))/1000 AS COL1,--VENITUL DIN VINZARI
CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('4.5') AND D.CAPITOL IN (1095) THEN D.COL1 ELSE NULL END)) AS COL2,--SALARIATII
SUBSTR(MAX(CASE WHEN D.RIND IN ('CAEM') AND D.CAPITOL IN (1091) THEN D.COL1 ELSE D.CAEM2 END),2) AS COL3

FROM 
 CIS2.VW_DATA_ALL_FR D 
WHERE
  D.PERIOADA=:pPERIOADA AND 
  D.FORM = 57 AND  
  D.CAPITOL IN (1095,1092,1091) AND 
  D.RIND IN ('4.5','010','8','CAEM')
  
  GROUP BY D.CUIIO, D.PERIOADA

) DD ON DD.CUIIO=D.CUIIO AND D.PERIOADA=DD.PERIOADA
     
WHERE
  D.FORM IN (64)             AND   
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.FORM_VERS = :pFORM_VERS  AND 
--  D.FORM = :pFORM  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND  
  D.RIND IN ('400','150','8')  AND D.CAPITOL IN (1127,1124,1129)
  

GROUP BY D.CUIIO,D.CUATM 
ORDER BY D.CUATM,D.CUIIO
) ) L


           LEFT JOIN USER_BANCU.VW_KATALOG_PROD_MOLD_22 R ON R.CUIIO = L.NR_ROW
           
           
           LEFT JOIN USER_BANCU.FR RR ON RR.CUIIO = L.NR_ROW