BEGIN
INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  
  COL1, COL2, COL3, COL4, COL5, COL6
)

SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
   RR.NR_ROW AS NR_SECTIE,         
   RR.NUME_ROW AS NUME_SECTIE,
   
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  R.NR_ROW||'~'||RR.NR_ROW AS NR_ROW,
  TO_NUMBER(R.NR_ROW||'.'||RR.NR_ROW) AS ORDINE,
  '100000' AS DECIMAL_POS,
  
  R.NUME_ROW AS NUME_ROW,


  CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) THEN DECODE(R.NR_ROW, 
         '01', D.CD,
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  THEN D.CD END)) END),1)
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO) THEN (DECODE(R.NR_ROW, 
         '01', D.CD,
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  THEN D.CD END),
         '05',(CASE WHEN NVAL(D.COL1) BETWEEN 9 AND 12 THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0 THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0 THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0 THEN D.CD END))) END),1) END AS COL1,
         
         
           
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('11','12','13') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('11','12','13') THEN D.CD END)) END),0)
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('11','12','13') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) >0  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) >0  AND  D.CFP IN ('11','12','13') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) >0  AND  D.CFP IN ('11','12','13') THEN D.CD END)) END),0) END AS COL2,
--             
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN       
   ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END)) END),0)
   ELSE
   ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('14','15','16','17','18','19') THEN D.CD END)) END),0) END AS COL3,
--         
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN 
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL )  THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('20','21') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('20','21') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('20','21') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('20','21') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('20','21') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('20','21') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('20','21') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('20','21') THEN D.CD END)) END),0)
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)  THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('20','21') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('20','21') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('20','21') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('20','21') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('20','21') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('20','21') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('20','21') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('20','21') THEN D.CD END)) END),0) END AS COL4,
     
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN     
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END)) END),0)
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('22','23','24','25','26','27') THEN D.CD END)) END),0) END AS COL5,
         
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN  
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('28') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('28') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('28') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('28') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('28') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('28') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('28') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('28') THEN D.CD END)) END),0)
  ELSE
   ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)   THEN DECODE(R.NR_ROW, 
         '01',(CASE WHEN D.CFP IN ('28') THEN D.CD END),
         '02',(CASE WHEN D.COL1 BETWEEN 0 AND 3  AND  D.CFP IN ('28') THEN D.CD END),
         '03',(CASE WHEN D.COL1 BETWEEN 3 AND 6  AND  D.CFP IN ('28') THEN D.CD END),
         '04',(CASE WHEN D.COL1 BETWEEN 6 AND 9  AND  D.CFP IN ('28') THEN D.CD END),
         '05',(CASE WHEN D.COL1 BETWEEN 9 AND 12 AND  D.CFP IN ('28') THEN D.CD END),
         '06',(CASE WHEN NVAL(D.COL2) > 0  AND  D.CFP IN ('28') THEN D.CD END),
         '07',(CASE WHEN NVAL(D.COL3) > 0  AND  D.CFP IN ('28') THEN D.CD END),
         '08',(CASE WHEN NVAL(D.COL4) > 0  AND  D.CFP IN ('28') THEN D.CD END)) END),0) END AS COL6       
         

  
  FROM(

-------------------------------------------------------------------------------
SELECT 
 DISTINCT D.CUIIO,D. CUATM,D.CFP,
SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII') THEN  D.COL1 ELSE 0 END)  AS COL1 ,
SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('1') THEN  D.COL1 ELSE 0 END)  AS COL2, 
SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('2') THEN  D.COL1 ELSE 0 END)  AS COL3,  
SUM(CASE WHEN D.CAPITOL IN (1123) AND D.RIND IN ('3') THEN  D.COL1 ELSE 0 END)  AS COL4,
SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') THEN  D.COL4 ELSE 0 END)  AS COL5,
-------
SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)  AS CD,
(SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 

 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM = 64 AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS
                                                       

FROM   
    CIS2.VW_DATA_ALL_COEF D 
--      INNER JOIN CIS2.VW_CL_CFP VC ON (D.CFP = VC.CODUL)
 
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
   D.CAPITOL IN (100,1123,1127)
  AND D.RIND IN ('I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','1','CD','2','3','400')
-- AND D.CUIIO = 227548
 GROUP BY D.CUIIO,D.CUATM, D.CFP,D.PERIOADA,D.FORM
 
 HAVING
 SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  NVAL(D.COL1) ELSE 0 END)>0
)D
  CROSS JOIN
  ( 
    SELECT 'Numarul intreprinderilor total'              AS NUME_ROW, '01' AS NR_ROW, '01' AS ORDINE  FROM DUAL UNION
    SELECT 'au activat pina la 3 luni'                   AS NUME_ROW, '02' AS NR_ROW, '02' AS ORDINE  FROM DUAL UNION
    SELECT 'au activat de la 3 pina la 6 luni'           AS NUME_ROW, '03' AS NR_ROW, '03' AS ORDINE  FROM DUAL UNION
    SELECT 'au activat de la 6 pina la 9 luni'           AS NUME_ROW, '04' AS NR_ROW, '04' AS ORDINE  FROM DUAL UNION
    SELECT 'au activat de la 9 pina la 12 luni'          AS NUME_ROW, '05' AS NR_ROW, '05' AS ORDINE  FROM DUAL UNION
    SELECT 'Intreprinderea a fost inreg-ta, dar act. n-a fost inceputa'  AS NUME_ROW, '06' AS NR_ROW, '06' AS ORDINE  FROM DUAL UNION
    SELECT 'Activitatea a fost incetata temporar'        AS NUME_ROW, '07' AS NR_ROW, '07' AS ORDINE  FROM DUAL UNION
    SELECT 'Activitatea a fost incetata si nu va fi reluata'         AS NUME_ROW, '08' AS NR_ROW, '08' AS ORDINE  FROM DUAL     
    
  ) R
  
   CROSS JOIN
  ( 
    SELECT 'Întreprinderile cu numarul de salariati 0-9 persoane'              AS NUME_ROW, '01' AS NR_ROW, 0 AS PERS_FROM, 9 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-49 persoane'             AS NUME_ROW, '02' AS NR_ROW, 0 AS PERS_FROM, 49 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-249 persoane'            AS NUME_ROW, '03' AS NR_ROW, 0 AS PERS_FROM, 249 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 250 si mai mult persoane'  AS NUME_ROW, '04' AS NR_ROW, 250 AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Total republica Moldova'                                         AS NUME_ROW, '05' AS NR_ROW, 0 AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL
        
    
  ) RR  
  
  GROUP BY RR.NUME_ROW,RR.NR_ROW, R.NR_ROW,R.NUME_ROW,R.ORDINE
  
  
  
  
  
  UNION
  --------
SELECT
 PERIOADA,  FORM,   FORM_VERS,  ID_MDTABLE, COD_CUATM,  NR_SECTIE,  NUME_SECTIE, NR_SECTIE1,
 NUME_SECTIE1,  NR_SECTIE2,  NUME_SECTIE2, NR_ROW, ORDINE,  DECIMAL_POS, NUME_ROW, 
 ROUND(COL1,1) AS COL1, ROUND(COL2,0) AS COL2, ROUND(COL3,0) AS COL3, ROUND(COL4,0) AS COL4, ROUND(COL5,0) AS COL5, ROUND(COL6,0) AS COL6
FROM(
SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
   RR.NR_ROW AS NR_SECTIE,         
   RR.NUME_ROW AS NUME_SECTIE,
   
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  D.RIND ||', Col.'|| CC.NR_COLUMN||'~'||RR.NR_ROW||'.'|| CC.NR_COLUMN AS NR_ROW,

  TO_NUMBER(D.CAPITOL||'.'||D.RIND||CC.NR_COLUMN) AS ORDINE,
  '000000' AS DECIMAL_POS,
--CC.CLMN,

 REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RD.DENUMIRE,'<br>'),'nbsp'),'&;'),'</b>'),'<br />'),'<b>') AS NUME_ROW,

 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS)  THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1) 
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL1,

 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS)  AND D.CFP IN ('11','12','13') THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125) THEN DECODE(CC.NR_COLUMN, '1', D.COL1) 
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL2,
                   
                                                                                                        
 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS) AND  D.CFP IN ('14','15','16','17','18','19') THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1) 
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL3,
                   
                                                                                                                           
 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS) AND  D.CFP IN ('20','21') THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1) 
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL4,                   
                   
                                                                                                        
 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS) AND  D.CFP IN ('22','23','24','25','26','27') THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1)
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2) 
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL5,                   
                    
                                                                                                        
 SUM(CASE WHEN (DD.COL4 BETWEEN RR.PERS_FROM AND RR.PERS_TO OR DD.COL4 = RR.PERS) AND  D.CFP IN ('28') THEN 
             CASE WHEN  D.CAPITOL IN (1124, 1125)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1) 
                   WHEN  D.CAPITOL IN (1126)              THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2)
                   WHEN  D.CAPITOL IN (1127)              THEN DECODE(CC.NR_COLUMN, '1', D.COL3, '2', D.COL4, '3', D.COL5)
                   WHEN  D.CAPITOL IN (1128)              THEN DECODE(CC.NR_COLUMN, '1', D.COL8, '2', D.COL9, '3', D.COL10) END END)  AS COL6
   
FROM  
 CIS2.VW_DATA_ALL_COEF D  
INNER JOIN CIS2.VW_CL_CFP VC ON (D.CFP = VC.CODUL)
INNER JOIN CIS2.MD_RIND RD ON D.RIND=RD.RIND AND D.ID_MD=RD.ID_MD
INNER JOIN

  (
-------------------------------------------------------------------------------
SELECT 

 DISTINCT D.CUIIO,D.CUIIO_VERS, D. CUATM,
SUM(CASE WHEN D.CAPITOL IN (1127) AND D.RIND IN ('400') AND D.COL4 IS NOT NULL THEN D.COL4 ELSE 0  END)  AS COL4,
SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') AND D.COL1 IS NOT NULL THEN D.COL1 ELSE 0  END)  AS CD 
FROM   
    CIS2.VW_DATA_ALL D       
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1127,100) AND
  D.RIND IN ('400', 'CD')
 --AND  D.CUIIO=41234282
 GROUP BY D.CUIIO,D.CUATM, D.CUIIO_VERS
  HAVING
 SUM(CASE WHEN D.CAPITOL IN (100) AND D.RIND IN ('CD') AND D.COL1 IS NOT NULL THEN D.COL1 ELSE 0  END) >0

)DD ON D.CUIIO=DD.CUIIO AND D.CUIIO_VERS=DD.CUIIO_VERS
    
 
   CROSS JOIN
  ( 
    SELECT 'Întreprinderile cu numarul de salariati 0-9 persoane'              AS NUME_ROW, '01' AS NR_ROW, 0 AS PERS_FROM, 9 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-49 persoane'             AS NUME_ROW, '02' AS NR_ROW, 0 AS PERS_FROM, 49 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-249 persoane'            AS NUME_ROW, '03' AS NR_ROW, 0 AS PERS_FROM, 249 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 250 si mai mult persoane'  AS NUME_ROW, '04' AS NR_ROW, 250 AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Total republica Moldova'                                         AS NUME_ROW, '05' AS NR_ROW, 0 AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL
        
    
  ) RR
  
  CROSS JOIN               
       (                                                                        
       SELECT '1' AS NR_COLUMN FROM DUAL UNION                                  
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL                             
       ) CC           
  WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
  D.CAPITOL IN (1123,1124,1125,1126,1127,1128,1129) AND((D.ID_MD BETWEEN 58733 AND 58785) OR D.ID_MD IN (58791,59030,59032))
-- AND D.CUIIO = 227548
  
 GROUP BY RR.NUME_ROW,RR.NR_ROW, D.RIND,RD.DENUMIRE,D.CAPITOL, CC.NR_COLUMN
 

ORDER BY D.RIND||'~'||RR.NR_ROW||'.'||CC.NR_COLUMN)

UNION
------
SELECT
 PERIOADA,  FORM,   FORM_VERS,  ID_MDTABLE, COD_CUATM,  NR_SECTIE,  NUME_SECTIE, NR_SECTIE1,
 NUME_SECTIE1,  NR_SECTIE2,  NUME_SECTIE2, NR_ROW, ORDINE,  DECIMAL_POS, NUME_ROW, 
 ROUND(COL1,1) AS COL1, ROUND(COL2,1) AS COL2, ROUND(COL3,1) AS COL3, ROUND(COL4,1) AS COL4, ROUND(COL5,1) AS COL5, ROUND(COL6,1) AS COL6
FROM(
SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
   RR.NR_ROW AS NR_SECTIE,         
   RR.NUME_ROW AS NUME_SECTIE,
   
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  
  R.NR_ROW||'.'||RR.NR_ROW AS NR_ROW,
  TO_NUMBER(R.NR_ROW||'.'||RR.NR_ROW) AS ORDINE,
  '100000' AS DECIMAL_POS,
  R.NUME_ROW,
 CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL)  THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO) THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL1,
  
  CASE WHEN RR.NR_ROW NOT IN ('04')THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) AND D.CFP IN ('11','12','13') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO) AND D.CFP IN ('11','12','13') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL2,
   
   
     CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) AND D.CFP IN  ('14','15','16','17','18','19') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)AND D.CFP IN  ('14','15','16','17','18','19') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL3,
   
   
 CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) AND D.CFP IN  ('20','21') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)AND D.CFP IN  ('20','21') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL4,
   
   
 CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) AND D.CFP IN  ('22','23','24','25','26','27') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)AND D.CFP IN  ('22','23','24','25','26','27') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL5,
   
   
  CASE WHEN RR.NR_ROW NOT IN ('04') THEN
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO OR D.PERS IS NULL) AND D.CFP IN  ('28') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1)   
  ELSE
  ROUND(SUM( CASE WHEN (D.PERS BETWEEN RR.PERS_FROM AND RR.PERS_TO)AND D.CFP IN ('28') THEN DECODE(R.NR_ROW, 
   '600',D.COL1,
   '700',D.COL2) END),1) END AS COL6  

   
FROM  (

SELECT 
DISTINCT D.CUIIO,D. CUATM, 

--CASE WHEN D.CFP_AJUSTAT IS NULL THEN D.CFP ELSE D.CFP_AJUSTAT END AS CFP,
D.CFP,
D.COL1, D.COL2,D.PERS
 FROM (
SELECT 
 DISTINCT D.CUIIO,D.CUATM,
 D.CFP AS CFP,
 --MAX(CASE WHEN D.CAPITOL IN (1129) AND D.RIND IN ('5') THEN D.COL31 ELSE NULL END) AS CFP_AJUSTAT,
 
CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))  AS COL1,
  
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('150','160','170') THEN  CIS2.NVAL(D.COL1) END))- 
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('200') THEN CIS2.NVAL(D.COL1) END))+
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('330') THEN CIS2.NVAL(D.COL1) END)))+
 
(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL2) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1126) AND D.RIND IN ('340') THEN CIS2.NVAL(D.COL1) END)))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('220') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('240') THEN CIS2.NVAL(D.COL1) END))-
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('290') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1125) AND D.RIND IN ('294') THEN CIS2.NVAL(D.COL1) END))+
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('180') THEN CIS2.NVAL(D.COL1) END))   AS COL2,

SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)  AS CD,
(SELECT  CASE WHEN DD.COL4 IS NOT NULL THEN DD.COL4 ELSE 0 END 

 FROM
   CIS2.DATA_ALL DD
 WHERE
   DD.PERIOADA IN (D.PERIOADA) AND
   DD.FORM=D.FORM AND
   DD.ID_MD IN (69986) AND
   DD.CUIIO IN (D.CUIIO)) AS PERS                                                       

FROM   
    CIS2.VW_DATA_ALL_COEF D  
    INNER JOIN CIS2.VW_CL_CFP VC ON (D.CFP = VC.CODUL)
WHERE
  D.FORM IN (64)             AND 
  D.FORM_VERS = :PFORM_VERS  AND      
  D.PERIOADA =:pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   AND
   D.CAPITOL IN (100,1123,1124,1125,1126,1127,128,1129)
--    AND D.CUIIO = 227548
 
 GROUP BY D.CUIIO,D.CUATM, D.CFP,D.PERIOADA,D.FORM
 
 HAVING
 SUM(CASE WHEN D.CAPITOL IN (100)  AND D.RIND IN ('CD') THEN  D.COL1 ELSE 0 END)>0)D
 
 
 
 
 )D
 
   CROSS JOIN
  ( 
    SELECT 'Întreprinderile cu numarul de salariati 0-9 persoane'              AS NUME_ROW, '01' AS NR_ROW, 0  AS PERS_FROM, 9   AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-49 persoane'             AS NUME_ROW, '02' AS NR_ROW, 0  AS PERS_FROM, 49  AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 0-249 persoane'            AS NUME_ROW, '03' AS NR_ROW, 0  AS PERS_FROM, 249 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Întreprinderile cu numarul de salariati 250 si mai mult persoane'  AS NUME_ROW, '04' AS NR_ROW, 250 AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL UNION
    SELECT 'Total republica Moldova'                                         AS NUME_ROW, '05' AS NR_ROW, 0   AS PERS_FROM, 99999999 AS PERS_TO, NULL AS PERS FROM DUAL

        
  ) RR
  
   CROSS JOIN
  ( 
    SELECT 'Valoarea productiei: VP'  AS NUME_ROW, '600' AS NR_ROW FROM DUAL UNION     
    SELECT 'Valoarea adaugata bruta la costul factorilor: VAFC'  AS NUME_ROW, '700' AS NR_ROW FROM DUAL 
 ) R
  
  GROUP BY 
   R.NR_ROW, R.NUME_ROW, RR.NR_ROW, RR.NUME_ROW
  
  ORDER BY RR.NR_ROW||'.'||R.NR_ROW
  
  
  
   )

WHERE NVAL(COL1)>0 OR NVAL( COL2)>0 OR  NVAL(COL3)>0 OR  NVAL(COL4)>0 OR NVAL(COL5)>0 OR  NVAL(COL6)>0



--ORDER BY
--NR_ROW, 
--ORDINE 

;END;
