
SELECT 
   RR.NR_ROW,
  ROUND(SUM ( CASE WHEN 1=1 THEN DECODE(RR.NR_ROW, 
         '100', (DD.COL1),
         '110', (DD.COL2),
         '111', (DD.COL3),
         '112', (DD.COL4),
         '120', (DD.COL5),
         '130', (DD.COL6)
         END),1) AS COL1,

SUM( CASE WHEN (DD.PERS BETWEEN 0 AND 9 OR DD.PERS IS NULL) THEN (DECODE(RR.NR_ROW, 
         '100', (DD.COL1),
         '110', (DD.COL2),
         '112', (DD.COL4),
         '120', (DD.COL5),
         '130', (DD.COL6)
         )) END) AS COL2

FROM 
(
SELECT 
 DISTINCT D.CUIIO, 
 CASE WHEN MAX(CASE WHEN D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END) IS NULL THEN MAX(SUBSTR(D.CAEM2,2,4)) 
 ELSE MAX(CASE WHEN D.RIND IN ('8') AND D.CAPITOL IN (1129) THEN D.COL31 END) END AS CAEM2_ACTUALIZAT,
 MAX(SUBSTR(D.CAEM2,2,4))  AS CAEM2,
 D.CUIIO_VERS, 
 D.CUATM, D.FORM, D.FORM_VERS, D.CUATM_FULL, D.PERIOADA,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('100') THEN CIS2.NVAL(D.COL1) END)) AS COL1,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('110') THEN CIS2.NVAL(D.COL1) END)) AS COL2,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('111') THEN CIS2.NVAL(D.COL1) END)) AS COL3,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('112') THEN CIS2.NVAL(D.COL1) END)) AS COL4,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('120') THEN CIS2.NVAL(D.COL1) END)) AS COL5,
 CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1124) AND D.RIND IN ('130') THEN CIS2.NVAL(D.COL1) END)) AS COL6
FROM   
    CIS2.VW_DATA_ALL_COEF D       
WHERE
  D.FORM IN (64) AND 
  D.FORM_VERS = :PFORM_VERS AND      
  D.PERIOADA = :pPERIOADA AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.CAPITOL IN (100,1123,1124,1125,1126,1127,1128,1129) 
  AND D.CUIIO IN (26844)
GROUP BY D.CUIIO, D.CUIIO_VERS, D.CUATM, D.FORM, D.FORM_VERS, D.CUATM_FULL, D.PERIOADA
) DD

CROSS JOIN
( 
     SELECT '100' AS NR_ROW, 'Col1' AS COL FROM DUAL UNION   
     SELECT '110' AS NR_ROW, 'Col2' AS COL FROM DUAL UNION
     SELECT '111' AS NR_ROW, 'Col3' AS COL FROM DUAL UNION 
     SELECT '112' AS NR_ROW, 'Col4' AS COL FROM DUAL UNION 
     SELECT '120' AS NR_ROW, 'Col5' AS COL FROM DUAL UNION
     SELECT '130' AS NR_ROW, 'Col6' AS COL FROM DUAL
) RR

WHERE 
  (DD.FORM = :pFORM) AND
  (DD.FORM_VERS = :pFORM_VERS) AND
  (:pID_MDTABLE = :pID_MDTABLE) AND
  (DD.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND   
  DD.PERIOADA IN (:pPERIOADA) AND
  DD.CUIIO = 26844

GROUP BY
  RR.NR_ROW       

ORDER BY 
  RR.NR_ROW;
