SELECT
D.CUIIO,
--D.RIND,
COUNT (DISTINCT D.CUIIO) AS CNT 
--  TO_NUMBER(D.CUIIO||SUBSTR(D.RIND,0,1)||D.COL1) AS COL1,
--  SUBSTR(D.RIND,0,1) as rind,
--  COUNT(DISTINCT TO_NUMBER(D.CUIIO||SUBSTR(D.RIND,0,1)||D.COL1)) AS CNT

FROM
VW_DATA_ALL  D
WHERE
  (D.PERIOADA=:PERIOADA) AND
--  (D.CUIIO=:CUIIO) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM = 74
  AND D.CAPITOL IN (1197)
  --AND D.CAPITOL_VERS IN (1004)
  AND D.RIND IN ('2.1','2.3','2.2')
  AND D.CAEM2 NOT LIKE 'A%'
 -- AND D.CUIIO = 458963
  GROUP BY
  D.CUIIO
  --D.RIND
--TO_NUMBER(D.CUIIO||SUBSTR(D.RIND,0,1)||D.COL1),
--SUBSTR(D.RIND,0,1) 

----
--HAVING
--COUNT (DISTINCT D.CUIIO)  = 1


ORDER BY
CUIIO