SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('2.1','2.2','2.3')--AND D.CUIIO=40988116---------------------
  AND D.CAEM2 NOT LIKE 'A%'