SELECT    
SUM(CASE WHEN CIS2.D.RIND IN ('05') THEN CIS2.NVAL(D.COL2)  ELSE 0 END) ||' != '|| 
SUM(CASE WHEN CIS2.D.RIND IN ('06','07','08','09','10','11','12') THEN CIS2.NVAL(D.COL2) ELSE 0 END)
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
 
WHERE
  (D.PERIOADA =:PERIOADA        OR :PERIOADA=  -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  CIS2.D.FORM IN (15)  AND
  CIS2.D.CAPITOL in (1000)AND
  CIS2.D.RIND IN ('05','06','07','08','09','10','11','12')
HAVING
  SUM(CASE WHEN CIS2.D.RIND IN ('05') THEN CIS2.NVAL(D.COL2) ELSE 0 END) <> 
  SUM(CASE WHEN CIS2.D.RIND IN ('06','07','08','09','10','11','12') THEN CIS2.NVAL(D.COL2) ELSE 0 END)
