SELECT DISTINCT 

  SUM(CASE WHEN D.RIND IN  ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)||' <> '||
  SUM(CASE WHEN D.RIND NOT IN ('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)
  
  
  AS REZULTAT
FROM
  CIS2.VW_DATA_ALL_TEMP D 
WHERE
  (D.PERIOADA=:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS  ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (44)  AND
  D.CAPITOL IN (405)

 HAVING
  SUM(CASE WHEN D.RIND IN('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)  <> 
  SUM(CASE WHEN D.RIND NOT IN('1') THEN CIS2.NVAL(D.COL4) ELSE 0 END)
