SELECT 
1 ORDINE,
CUIIO,
PACHET,
'9999999' SERV_CODUL,
SERV_CODUL_OLD,
NULL DENUMIRE,
     SUM(COL1)  COL1,
     COL2 COL2,
      NVAL(SUM(COL1)) - NVAL(COL2) AS COL3
    
     FROM 
     (
SELECT
  D.CUIIO,
  MAX(D.PACHET) PACHET,
  CI.ITEM_CODE SERV_CODUL,
  CI.NAME||' - '||MAX(R.DENUMIRE) DENUMIRE,
  CI.A01 SERV_CODUL_OLD,
  SUM(CASE WHEN D.PERIOADA IN (1052,1053,1054,1055) AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050,1051) AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050,1051) AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (1051) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (1051) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  --(D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND    
 ((D.PERIOADA IN (1052,1053,1054,1055,1048,1049,1050,1051)))  AND
  (D.FORM =:pFORM) AND
 -- (D.FORM_VERS =:pFORM_VERS) AND 
  --(D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
   AND D.CUIIO = 20282383 
  
-- 5:35

GROUP BY
  D.CUIIO, 
  CI.ITEM_CODE,
  CI.NAME,
  CI.A01
  
  
HAVING

SUM(CASE WHEN D.PERIOADA IN (1052,1053,1054,1055)  AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) <> 0

UNION
SELECT DISTINCT
  CUIIO,
  MAX(PACHET) PACHET,
  MAX(ITEM_CODE) SERV_CODUL,
  MAX(NAME) DENUMIRE,
  A01 SERV_CODUL_OLD,
  SUM(COL1) AS COL1,
  COL2 
FROM
(SELECT
  D.CUIIO,
   MAX(D.PACHET) PACHET,
  CI.ITEM_CODE,
   CI.NAME||' - '||MAX(R.DENUMIRE)  NAME,
  CI.A01,
  SUM(CASE WHEN D.PERIOADA IN (1052,1053,1054,1055) AND  D.CAPITOL IN (405) AND D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1,
  (SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050,1051) AND D.CAPITOL IN (405) AND D.RIND NOT IN ('1','2','-') THEN NVAL(D.COL4) ELSE 0 END ) +
   SUM(CASE WHEN D.PERIOADA IN (1048,1049,1050,1051) AND D.CAPITOL IN (406) AND D.RIND NOT IN ('1','-') THEN  NVAL(D.COL4) ELSE 0 END ))AS COL2
FROM
  CIS2.VW_DATA_ALL D 
   INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND (CASE WHEN D.PERIOADA IN (1051) THEN TRIM(D.COL1) ELSE TRIM(D.COL31) END) = 
                                                                       (CASE WHEN D.PERIOADA IN (1051) THEN TRIM(CI.A01) ELSE TRIM(CI.ITEM_CODE) END))
WHERE 
  --(D.PERIOADA IN(:pPERIOADA, :pPERIOADA-4)) AND
   ((D.PERIOADA IN (1052,1053,1054,1055,1048,1049,1050,1051)))  AND    
  (D.FORM =:pFORM) AND
 -- (D.FORM_VERS =:pFORM_VERS) AND 
 -- (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (44)
  AND  D.CAPITOL IN (405,406) 
  
   AND D.CUIIO = 20282383 
  



GROUP BY
  CI.ITEM_CODE,
  D.CUIIO,
  CI.NAME,
  CI.A01

ORDER BY
  D.CUIIO,
  CI.A01,
  CI.ITEM_CODE
)
GROUP BY
  CUIIO,
  A01,
  COL2
HAVING
  SUM(COL1) = 0

  

  
   ORDER BY

    CUIIO,
    SERV_CODUL
    
   )



GROUP BY 
CUIIO,
PACHET,

SERV_CODUL_OLD,
COL2

HAVING 
(
NVAL(SUM(COL1)) - NVAL(COL2) > 500000
OR 
NVAL(COL2) - NVAL(SUM(COL1)) > 500000
 )

