SELECT
              :vPERIOADA,
              :vFORM,
              :vFORM_VERS,
              :vCUIIO,
              :vCUIIO_VERS,
              RR.ID_MD,
              SYSDATE AS DATA_REG,
              9999 AS ID_USER,
              D.COL1,D.COL2,D.COL3,D.COL4,D.COL5,D.COL6,D.COL7,D.COL8,D.COL9,D.COL10,D.COL11,D.COL12,D.COL13,D.COL14,D.COL15,D.COL16,
              D.COL31,D.COL32,D.COL33,D.COL34,D.COL35,D.COL36,D.COL37,D.COL38,D.COL39,D.COL40,R.FORMID,--T_XML_FORM_ID from F_XML_FORMS
              SYSDATE AS CREATED_DATE,
              :vID_SCHEMA
            FROM
            (
            SELECT
              REPLACE(REPLACE(REPLACE(REPLACE(
                SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1),
                'CAPITOL6_R612','CAPITOL6_R611'),
                'CAPITOL3_R331','CAPITOL3_R33'),
                'CAPITOL3_R332','CAPITOL3_R33'),
                'CAPITOL3_R333','CAPITOL3_R33') AS NR_ROW,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C1' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE 
                CASE 
                  WHEN SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1) IN ('CAPITOL6_R611') AND D.XML_NODE_VALUE IN (1) THEN '1' 
                  WHEN SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1) IN ('CAPITOL6_R612') AND D.XML_NODE_VALUE IN (1) THEN '2'  
                  WHEN SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1) IN ('CAPITOL3_R331') AND D.XML_NODE_VALUE IN (1) THEN '1' 
                  WHEN SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1) IN ('CAPITOL3_R332') AND D.XML_NODE_VALUE IN (1) THEN '2'  
                  WHEN SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1) IN ('CAPITOL3_R333') AND D.XML_NODE_VALUE IN (1) THEN '3'               
                ELSE D.XML_NODE_VALUE END 
              END END) AS COL1,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C2' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL2,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C3' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL3,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C4' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL4,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C5' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL5,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C6' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL6,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C7' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL7,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C8' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL8,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C9' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL9,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C10' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL10,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C11' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL11,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C12' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL12,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C13' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL13,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C14' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL14,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C15' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL15,
              SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C16' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL16,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C31' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL31,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C32' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL32,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C33' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL33,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C34' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL34,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C35' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL35,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C36' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL36,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C37' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL37,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C38' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL38,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C39' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL39,
              MAX(CASE WHEN D.XML_NODE_NAME LIKE '%_C40' THEN CASE WHEN D.XML_NODE_NAME LIKE '%_RCAEM_%' THEN SUBSTR(D.XML_NODE_VALUE,2,4) ELSE D.XML_NODE_VALUE END END) AS COL40
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C13' THEN D.XML_NODE_VALUE END) AS COL13,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C14' THEN D.XML_NODE_VALUE END) AS COL14,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C15' THEN D.XML_NODE_VALUE END) AS COL15,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C16' THEN D.XML_NODE_VALUE END) AS COL16,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C17' THEN D.XML_NODE_VALUE END) AS COL17,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C18' THEN D.XML_NODE_VALUE END) AS COL18,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C19' THEN D.XML_NODE_VALUE END) AS COL19,
            --  SUM(CASE WHEN D.XML_NODE_NAME LIKE '%_C20' THEN D.XML_NODE_VALUE END) AS COL20,
            FROM
            (
            SELECT 
              XML_NODE_NAME,
              XML_NODE_VALUE
            FROM 
              XMLTABLE('//dec/DataSet/Data/*' PASSING   
                (SELECT  xmltype(XML) FROM F_XML_FORMS WHERE FORMID IN (24374011))
                 COLUMNS 
                 XML_NODE_NAME VARCHAR2(100) PATH 'name()',
                 XML_NODE_VALUE VARCHAR2(100) PATH 'text()' 
            )
            ) D
            GROUP BY
              REPLACE(REPLACE(REPLACE(REPLACE(
                SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1),
                'CAPITOL6_R612','CAPITOL6_R611'),
                'CAPITOL3_R331','CAPITOL3_R33'),
                'CAPITOL3_R332','CAPITOL3_R33'),
                'CAPITOL3_R333','CAPITOL3_R33')
            ORDER BY
              REPLACE(REPLACE(REPLACE(REPLACE(
                SUBSTR(D.XML_NODE_NAME,0, INSTR(D.XML_NODE_NAME,'_C')-1),
                'CAPITOL6_R612','CAPITOL6_R611'),
                'CAPITOL3_R331','CAPITOL3_R33'),
                'CAPITOL3_R332','CAPITOL3_R33'),
                'CAPITOL3_R333','CAPITOL3_R33')
            ) D
            INNER JOIN
              (
                SELECT
                  R.FORM,
                  R.FORM_VERS,
                  C.DEN_SHORT,
                  R.CAPITOL,
                  R.CAPITOL_VERS,
                  R.RIND,
                  R.RIND_VERS,
                  R.ID_MD
                FROM
                  CIS2.MD_RIND R
                  INNER JOIN CIS2.MD_CAPITOL C ON (R.CAPITOL=C.CAPITOL AND R.CAPITOL_VERS=C.CAPITOL_VERS)
                  INNER JOIN (
                    SELECT
                      R.CAPITOL,
                      R.RIND,
                      MAX(R.RIND_VERS) AS RIND_VERS
                    FROM
                      CIS2.MD_RIND R
                    WHERE
                      R.FORM IN (36) AND
                    --  R.ID_SCHEMA IN (2) AND
                      R.RIND_VERS <= (2013)
                    GROUP BY
                      R.CAPITOL,
                      R.RIND
                  ) RR ON (R.RIND=RR.RIND AND R.RIND_VERS=RR.RIND_VERS AND R.CAPITOL=RR.CAPITOL)
                WHERE
                  R.FORM IN (36) AND
                  --R.ID_SCHEMA IN (2) AND
                  R.STATUT <> '3'
                ORDER BY
                  R.RIND) RR ON (D.NR_ROW = CASE WHEN RR.FORM IN (39) THEN DECODE(RR.DEN_SHORT,'Cap.I','CAP1')||'_R'||RR.RIND 
                                                 WHEN RR.FORM IN (5) THEN DECODE(RR.DEN_SHORT,'Cap. I','CAP1','Cap. II','CAP2','Cap. III','CAP3')||'_R'||RR.RIND 
                                                 WHEN RR.FORM IN (1) THEN DECODE(RR.DEN_SHORT,'Cap. Stocuri','CAP1','Cap. COSTURI','CAP2','Subcap. AGR','CAP3')||'_R'||RR.RIND 
                                                 WHEN RR.FORM IN (44) THEN DECODE(RR.DEN_SHORT,'Export de servicii','CAP1','Import de servicii','CAP2') ||'_R'||RR.RIND 
                                                 WHEN RR.FORM IN (74) THEN REPLACE(UPPER(RR.DEN_SHORT),'.','')||'_R'||REPLACE(RR.RIND,'.','_')
                                                 WHEN RR.FORM IN (45,33) THEN DECODE(RR.DEN_SHORT,'Cap.I','CAP1','Cap.I-a','CAP1A','Cap.II','CAP2','Cap.III','CAP3')||'_R'||RR.RIND
                                                 WHEN RR.FORM IN (7) THEN DECODE(RR.DEN_SHORT,'CAPITOLUL I','CAP1')||'_R'||RR.RIND
                                                 WHEN RR.FORM IN (34,35,29) THEN DECODE(RR.DEN_SHORT,'Cap.I','CAP1','Informativ','CAP2')||'_R'||RR.RIND
                                                 WHEN RR.FORM IN (18,36) THEN DECODE(RR.DEN_SHORT,'Cap.I','CAP1')||'_R'||RR.RIND 
                                                 WHEN RR.FORM IN (48) THEN DECODE(RR.DEN_SHORT,'Cap.1','CAPITOL1','Cap.2','CAPITOL2','Cap.3','CAPITOL3','Cap.4','CAPITOL4','Cap.5','CAPITOL5',
                                                                                               'Cap.6','CAPITOL6','Cap.7','CAPITOL7','Cap.8','CAPITOL8','Cap.9','CAPITOL9')||'_R'||REPLACE(RR.RIND,'.','')
                                            ELSE REPLACE(UPPER(REPLACE((RR.DEN_SHORT),'TITLUL','TITLU')),'.','')||'_R'||RR.RIND END)