SELECT TO_NUMBER(EXTRACT(XMLTYPE(XML), '/dec/DataSet/Header/YEAR/text()')) YEAR,
TO_NUMBER(EXTRACT(XMLTYPE(XML), '/dec/DataSet/Header/CUIIO/text()')) CUIIO  
FROM F_XML_FORMS 

WHERE 
FORMID IN (20584567)