SELECT 
    CASE WHEN CII.ITEM_CODE = '98' THEN '99' ELSE CII.ITEM_CODE END  AS NR_ROW,  
     CII.SHOW_ORDER   AS ORDINE,  
     CII.NAME NUME_ROW,
     SUM(CASE WHEN  D.CAPITOL IN (405)  AND D.RIND NOT IN ('1','-')  THEN CIS2.NVAL(D.COL4) ELSE 0 END) AS COL1
     

     FROM VW_DATA_ALL D
         INNER JOIN VW_CLS_CLASS_ITEM CI ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))         
         INNER JOIN VW_CLS_CLASS_ITEM CII ON (CII.CLASS_CODE IN ('CSPM2')
         AND REPLACE(' '||CI.ITEM_PATH,';','; ') LIKE '% '||TRIM(CII.ITEM_CODE)||';%')
   WHERE 
  (D.PERIOADA =:pPERIOADA) AND 
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  
  D.FORM IN (44)
  AND D.CAPITOL IN (405) 
  and CII.ITEM_CODE in ('9.2.2')
  GROUP BY 
  CII.ITEM_CODE,
  CII.SHOW_ORDER,  
  CII.NAME

  

ORDER BY
CII.SHOW_ORDER


  

  




  
