SELECT 
  'Rind. '||D.RIND||': '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 ', '2', 'COL2 ', '3', 'COL3 ')||': '||
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1)   THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3)  ELSE NULL END)) ||'<>'|| 
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA)      THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3)  ELSE NULL END)) 
  
   AS REZULTAT

   

FROM
  CIS2.VW_DATA_ALL_GC D,             
       (                               
       SELECT '1' AS NR_COLUMN FROM DUAL UNION 
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL                                    
       ) CC   
WHERE
 (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)          ) AND
  (D.NR_GOSP=:NR_GOSP               OR :NR_GOSP = -1) AND
  (:UNIT_CODE_VERS = :UNIT_CODE_VERS    OR :UNIT_CODE_VERS <>  :UNIT_CODE_VERS ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
--  
  D.FORM IN (61)  AND
  D.CAPITOL IN (1110)   AND D.RIND  not IN ('008')
  
GROUP BY
  CC.NR_COLUMN, 
  D.RIND
--  ,
--  D.NUM
----  
HAVING
  (CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1)    THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3)  ELSE NULL END)) <>
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA)      THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3)  ELSE NULL END)) )
 
   -- AND D.NUM NOT IN (1,2)



ORDER BY D.RIND,  CC.NR_COLUMN