SELECT 

 'Rind. '||D.RIND||': '||
  DECODE(CC.NR_COLUMN, '1', 'COL1 ', '2', 'COL2 ','3', 'COL3 ', '4', 'COL4 ','5', 'COL5 ', '6', 'COL6 ')||': '||
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-1)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6)  ELSE NULL END)) ||'<>'|| 
  NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA)    THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6)  ELSE NULL END)) 
   AS REZULTAT

   

FROM
  CIS2.VW_DATA_ALL_GC D,             
       (                               
       SELECT '1' AS NR_COLUMN FROM DUAL UNION 
       SELECT '2' AS NR_COLUMN FROM DUAL UNION    
       SELECT '3' AS NR_COLUMN FROM DUAL UNION
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL                               
       ) CC   
WHERE
 (D.PERIOADA IN (:PERIOADA,:PERIOADA-1)          ) AND
  (D.NR_GOSP=:NR_GOSP          ) AND
  (D.UNIT_CODE_VERS=:UNIT_CODE_VERS    OR :UNIT_CODE_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL            OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
--  
  D.FORM IN (61)  AND
  D.CAPITOL IN (1113)  
  
GROUP BY
  CC.NR_COLUMN, 
  D.RIND
  

  
HAVING
 ( 
NVAL((SUM(CASE WHEN D.CAPITOL IN (1113) AND D.PERIOADA IN (:PERIOADA-1)  THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6)  ELSE NULL END))) <>
   NVAL(SUM(CASE WHEN D.CAPITOL IN (1113) AND  D.PERIOADA IN (:PERIOADA)    THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '2', D.COL2, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6)  ELSE NULL END))) 

AND (
SELECT MAX(D.RIND) AS RIND 
            
             FROM VW_DATA_ALL_GC D

WHERE
  (D.PERIOADA IN  (:PERIOADA)) AND
  (D.NR_GOSP=:NR_GOSP  ) AND 
  D.FORM IN (61) AND  D.CAPITOL IN (1113)  

) IS NOT NULL 








ORDER BY 
D.RIND,  
CC.NR_COLUMN
