SELECT 
    'TRIM_3' AS TRIM,  -- Static value for the TRIM column
    D.UNIT_CODE,
    D.CUATM,
    CASE 
        WHEN D.CAPITOL = 1110 THEN 'Cap I'
        WHEN D.CAPITOL = 1111 THEN 'Cap II'
        WHEN D.CAPITOL = 1112 THEN 'Cap III'
        WHEN D.CAPITOL = 1113 THEN 'Cap IV'
        WHEN D.CAPITOL = 1114 THEN 'Cap SR'
    END AS CAPITOL,
    D.RIND,
    CASE 
        WHEN COALESCE(SUM(D.COL1), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL1), 0)
    END AS COL1,
    CASE 
        WHEN COALESCE(SUM(D.COL2), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL2), 0)
    END AS COL2,
    CASE 
        WHEN COALESCE(SUM(D.COL3), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL3), 0)
    END AS COL3,
    CASE 
        WHEN COALESCE(SUM(D.COL4), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL4), 0)
    END AS COL4,
    CASE 
        WHEN COALESCE(SUM(D.COL5), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL5), 0)
    END AS COL5,
    CASE 
        WHEN COALESCE(SUM(D.COL6), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL6), 0)
    END AS COL6,
    CASE 
        WHEN COALESCE(SUM(D.COL7), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL7), 0)
    END AS COL7,
    CASE 
        WHEN COALESCE(SUM(D.COL8), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL8), 0)
    END AS COL8,
    CASE 
        WHEN COALESCE(SUM(D.COL9), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL9), 0)
    END AS COL9,
    CASE 
        WHEN COALESCE(SUM(D.COL10), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL10), 0)
    END AS COL10,
    CASE 
        WHEN COALESCE(SUM(D.COL11), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL11), 0)
    END AS COL11,
    CASE 
        WHEN COALESCE(SUM(D.COL12), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL12), 0)
    END AS COL12,
    CASE 
        WHEN COALESCE(SUM(D.COL13), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL13), 0)
    END AS COL13,
    CASE 
        WHEN COALESCE(SUM(D.COL14), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL14), 0)
    END AS COL14,
    CASE 
        WHEN COALESCE(SUM(D.COL15), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL15), 0)
    END AS COL15,
    CASE 
        WHEN COALESCE(SUM(D.COL16), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL16), 0)
    END AS COL16,
    CASE 
        WHEN COALESCE(SUM(D.COL17), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL17), 0)
    END AS COL17,
    CASE 
        WHEN COALESCE(SUM(D.COL18), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL18), 0)
    END AS COL18,
    CASE 
        WHEN COALESCE(SUM(D.COL19), 0) = 0 THEN NULL
        ELSE COALESCE(SUM(D.COL19), 0)
    END AS COL19
FROM
    CIS2.VW_DATA_ALL_GC D
WHERE
    D.PERIOADA IN (1062)  
    AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
    AND D.FORM IN (61) 
    AND D.CAPITOL IN (1114, 1113, 1112, 1111, 1110)
GROUP BY 
    D.PERIOADA,
    D.UNIT_CODE,
    D.CUATM,
    D.CAPITOL,
    D.RIND  
ORDER BY 
    D.CUATM,
    D.UNIT_CODE,
    D.CAPITOL,
    D.RIND;
