--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4
--)


SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '1313' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    ROUND(COL1,1) AS COL1, ROUND(COL2,3) AS COL2, ROUND(COL3,1) AS COL3, ROUND(COL4,3) AS COL4
FROM
(
    SELECT 
         RR.ORDINE, 
         RR.RIND,
         RR.DENUMIRE , 
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111')  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111')  THEN D.COL2 ELSE NULL END)) AS COL2,
         
         ROUND((CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111')  THEN D.COL1 ELSE NULL END))/ 
         CIS2.NOZERO(MAX(DD.COL3)))*100,1) AS COL3,
         
         ROUND((CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111')  THEN D.COL2 ELSE NULL END))/ 
          CIS2.NOZERO(MAX(DD.COL4)))*100,3) AS COL4
FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1111')
  
  CROSS JOIN
  (  SELECT 
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('100') THEN D.COL1 ELSE NULL END)) AS COL3,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN ('100') THEN D.COL2 ELSE NULL END)) AS COL4
FROM
  CIS2.VW_DATA_ALL_GC  D
  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1111')  
 
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA ) AND
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND

  D.FORM IN (61)-- D.UNIT_CODE IN (836437)
  AND D.RIND IN ('100')  
  ) DD
  
 
WHERE
  (D.PERIOADA IN (:pPERIOADA))  AND   
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND

  D.FORM IN (61)
 AND D.UNIT_CODE = 822223
  
  GROUP BY 
  RR.RIND,
  RR.ORDINE,
  RR.DENUMIRE
  ORDER BY RR.RIND
  
  )