--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8
--)


SELECT
--    :pPERIOADA AS PERIOADA,
--    :pFORM AS FORM,
--    :pFORM_VERS AS FORM_VERS,
--    :pID_MDTABLE AS ID_MDTABLE,
--    :pCOD_CUATM AS COD_CUATM,
--    '0' AS NR_SECTIE,
--    '0' AS NUME_SECTIE,
--    '0' AS NR_SECTIE1,
--    '0' AS NUME_SECTIE1,
--    '0' AS NR_SECTIE2,
--    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '33333333' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    COL1, COL2, COL3, COL4, COL5,COL6,COL7,COL8
FROM
(

SELECT 
         RR.ORDINE AS ORDINE, 
         RR.RIND AS RIND,
         RR.DENUMIRE  DENUMIRE, 
         
        -- cap.II col1 rind.010 /10000

         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||1111111||';%'  AND  (D.PERIOADA = :pPERIOADA - 2)  THEN D.COL2 ELSE NULL END))/10000 AS COL1,
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||2222222||';%') OR (D.CUATM_FULL LIKE '%0100000;%')) 
         AND  (D.PERIOADA = :pPERIOADA - 2) THEN D.COL2 ELSE NULL END))/10000 AS COL2,
         
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||3333333||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%')) 
         AND  (D.PERIOADA = :pPERIOADA - 2)
         THEN D.COL2 ELSE NULL END))/10000 AS COL3,
         
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
         AND  (D.PERIOADA = :pPERIOADA - 2)
         
         
         THEN D.COL2 ELSE NULL END))/10000 AS COL4,

   -- (cap.II col.2 rind.010/ cap.II col 2 rind.100 ) *100

   


 ROUND(
 
 ((CIS2.NVAL(SUM(CASE WHEN    (D.PERIOADA = :pPERIOADA - 2)    AND  D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND D.CUATM_FULL LIKE '%'||1111111||';%' THEN D.COL2 ELSE NULL END))/10000)/
 
 
 
       ((CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA = :pPERIOADA - 2)     AND   D.CAPITOL IN ('1111') AND D.RIND IN ('100')    AND D.CUATM_FULL LIKE '%'||1111111||';%' THEN D.COL2 ELSE NULL END))/10000))
       
     +
     
      ((CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND  D.CAPITOL IN ('1110') AND D.RIND IN ('006')  AND D.CUATM_FULL LIKE '%'||1111111||';%' THEN D.COL1 ELSE NULL END))/3) 
      
      + 
       CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN(D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND   D.CAPITOL IN ('1110') AND D.RIND IN ('007')    AND D.CUATM_FULL LIKE '%'||1111111||';%' THEN D.COL1 ELSE NULL END))/3))))  
       
       *100,3) 
       
       
       
       
       
       AS COL5,
       
       ROUND(
 
 ((CIS2.NVAL(SUM(CASE WHEN    (D.PERIOADA = :pPERIOADA - 2)    AND  D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||2222222||';%') OR (D.CUATM_FULL LIKE '%0100000;%'))   THEN D.COL2 ELSE NULL END))/10000)/
 
 
 
       ((CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA = :pPERIOADA - 2)     AND   D.CAPITOL IN ('1111') AND D.RIND IN ('100')    AND ((D.CUATM_FULL LIKE '%'||2222222||';%') OR (D.CUATM_FULL LIKE '%0100000;%'))   THEN D.COL2 ELSE NULL END))/10000))
       
     +
     
      ((CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND  D.CAPITOL IN ('1110') AND D.RIND IN ('006')  AND ((D.CUATM_FULL LIKE '%'||2222222||';%') OR (D.CUATM_FULL LIKE '%0100000;%'))  THEN D.COL1 ELSE NULL END))/3) 
      
      + 
       CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN(D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND   D.CAPITOL IN ('1110') AND D.RIND IN ('007')    AND ((D.CUATM_FULL LIKE '%'||2222222||';%') OR (D.CUATM_FULL LIKE '%0100000;%'))  THEN D.COL1 ELSE NULL END))/3))))  
       
       *100,3) 
     
       AS COL6,
       
       ROUND(
 
 ((CIS2.NVAL(SUM(CASE WHEN    (D.PERIOADA = :pPERIOADA - 2)    AND  D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND ((D.CUATM_FULL LIKE '%'||3333333||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%'))   THEN D.COL2 ELSE NULL END))/10000)/
 
 
 
       ((CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA = :pPERIOADA - 2)     AND   D.CAPITOL IN ('1111') AND D.RIND IN ('100')    AND ((D.CUATM_FULL LIKE '%'||3333333||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%'))   THEN D.COL2 ELSE NULL END))/10000))
       
     +
     
      ((CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND  D.CAPITOL IN ('1110') AND D.RIND IN ('006')  AND ((D.CUATM_FULL LIKE '%'||3333333||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%'))  THEN D.COL1 ELSE NULL END))/3) 
      
      + 
       CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN(D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND   D.CAPITOL IN ('1110') AND D.RIND IN ('007')    AND ((D.CUATM_FULL LIKE '%'||3333333||';%') OR (D.CUATM_FULL LIKE '%'||9600000||';%'))   THEN D.COL1 ELSE NULL END))/3))))  
       
       *100,3) 
     
       AS COL7,
       
ROUND(
 
 ((CIS2.NVAL(SUM(CASE WHEN    (D.PERIOADA = :pPERIOADA - 2)    AND  D.CAPITOL IN ('1111') AND D.RIND IN (RR.RIND)  AND  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'   THEN D.COL2 ELSE NULL END))/10000)/
 
 
 
       ((CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA = :pPERIOADA - 2)     AND   D.CAPITOL IN ('1111') AND D.RIND IN ('100')    AND  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  THEN D.COL2 ELSE NULL END))/10000))
       
     +
     
      ((CIS2.NVAL(SUM(CASE WHEN  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND  D.CAPITOL IN ('1110') AND D.RIND IN ('006')  AND  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'  THEN D.COL1 ELSE NULL END))/3) 
      
      + 
       CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN(D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)   AND   D.CAPITOL IN ('1110') AND D.RIND IN ('007')    AND  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'    THEN D.COL1 ELSE NULL END))/3))))  
       
       *100,3) 
     
       AS COL8
   
          
    
   FROM
  CIS2.VW_DATA_ALL_GC   D
 
  CROSS JOIN ( 
  
  
  SELECT  RIND, DENUMIRE,ORDINE 
               FROM    CIS2.MD_RIND       
               WHERE   FORM= 61 AND CAPITOL = 1111 AND RIND NOT IN ('-','101','110') 
             --    AND CAPITOL_VERS = 1050
               
               ORDER BY ORDINE
               
               
               ) RR
               
         
    
WHERE
 (
 
 (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  
 OR   (D.PERIOADA = :pPERIOADA- 2) 
 
 )
 
 AND     
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 

 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61) AND D.CAPITOL IN ('1110','1111')  --AND D.NR_GOSP=802977
  
  GROUP BY 
  RR.ORDINE, 
  RR.RIND,
  RR.DENUMIRE 
 ORDER BY RR.ORDINE)
  
  
 