--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4
--)


SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
     RIND AS  NR_ROW,   
     ORDINE,
    '0022' AS DECIMAL_POS,
    DENUMIRE AS NUME_ROW, 
    ROUND(COL1,0), ROUND(COL2,0), ROUND(COL3,2), ROUND(COL4,2)
FROM
(
  SELECT 
         RR.ORDINE AS ORDINE, 
         RR.RIND AS RIND,
         RR.DENUMIRE  DENUMIRE, 
         
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '500' AND '580' AND D.RIND IN (RR.RIND)  THEN D.COL1 ELSE NULL END)) AS COL1,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '500' AND '580' AND D.RIND IN (RR.RIND)  THEN D.COL4 ELSE NULL END)) AS COL2,
         CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '500' AND '580' AND D.RIND IN (RR.RIND)  THEN D.COL7 ELSE NULL END)) AS COL3,
         ROUND(( CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '500' AND '580' AND D.RIND IN (RR.RIND)  THEN D.COL7 ELSE NULL END))/
         CIS2.NOZERO(CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN ('1113') AND D.RIND BETWEEN '500' AND '580' AND D.RIND IN (RR.RIND)  THEN D.COL4 ELSE NULL END))))*100,2) AS COL4
     
  
   FROM
  CIS2.VW_DATA_ALL_GC  D
--  INNER JOIN CIS2.MD_RIND RR ON D.ID_MD = RR.ID_MD AND D.CAPITOL IN ('1113')  
  CROSS JOIN ( SELECT  RIND, DENUMIRE,ORDINE 
               FROM    CIS2.MD_RIND       
               WHERE   FORM= 61 AND CAPITOL = 1113 /*AND RIND NOT IN ('-')*/ ORDER BY ORDINE) RR
    
WHERE
  (D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA)  AND  
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (:pID_MDTABLE =:pID_MDTABLE) AND
 (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  D.FORM IN (61)AND  D.RIND BETWEEN '500' AND '580' AND D.CAPITOL IN ('1113')  
  
  GROUP BY 
  RR.ORDINE, 
  RR.RIND,
  RR.DENUMIRE 
  ORDER BY RR.ORDINE
  
)