--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
--  COL1, COL2, COL3, COL4, COL5
--)

SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
NR_TABLE AS NR_SECTIE,
TABLE_DENUMIRE AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
ORDINE  NR_ROW,
ORDINE AS ORDINE,
'22202' AS DECIMAL_POS, 
RIND_DENUMIRE AS NUME_ROW,
ROUND(COL1,2) AS COL1, 
ROUND(COL2,2) AS COL2, 
ROUND(COL3,2) AS COL3, 
ROUND(COL1 + COL2 + COL3,0) AS COL4, 
ROUND(COL1 - COL3,2) AS COL5
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL1 *100 / (A.COL1 + A.COL2 + A.COL3),1) AS COL1,
  ROUND(A.COL2 *100 / (A.COL1 + A.COL2 + A.COL3),1) AS COL2,
  ROUND(A.COL3 *100 / (A.COL1 + A.COL2 + A.COL3),1) AS COL3,
  NULL AS COL4,
  NULL AS COL5
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
--  SUBSTR(A.CAEM2,1,1),


  SUM(CASE WHEN A.RIND IN ('4.1') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL1,
  SUM(CASE WHEN A.RIND IN ('4.2') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL2,
  SUM(CASE WHEN A.RIND IN ('4.3') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL3
FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL_COEF D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('4.1','4.2','4.3')--AND D.CUIIO=40988116
) A LEFT JOIN
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2024)                             --'B+C+D+E+F+G+H+I+J+L+M+N+R+S'
  CROSS JOIN 
  (
  
 SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, 'Total salariati' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 0 AS PERS_INIT, 9 AS PERS_FINAL, NULL AS RIND, '0-9 salariati' AS RIND_DENUMIRE, '2' AS ORDINE FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 10 AS PERS_INIT, 49 AS PERS_FINAL, NULL AS RIND, '10-49 salariati' AS RIND_DENUMIRE, '3' AS ORDINE FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 50 AS PERS_INIT, 249 AS PERS_FINAL, NULL AS RIND, '50-249 salariati' AS RIND_DENUMIRE, '4' AS ORDINE FROM DUAL UNION
    SELECT 2 AS NR_TABLE, 'Clasa de marime' AS TABLE_DENUMIRE, 250 AS PERS_INIT, 999999 AS PERS_FINAL, NULL AS RIND, '250 si peste salariati' AS RIND_DENUMIRE, '5' AS ORDINE FROM DUAL
     ) TR
     
       
     WHERE 
  A.CAEM2 NOT LIKE 'A%' 
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND
--  A.CAEM2
--ORDER BY
--  TR.NR_TABLE,
--  TR.ORDINE

) A
ORDER BY
  A.NR_TABLE,
  A.ORDINE
  
) 