INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, COL9
)

SELECT 
:pPERIOADA AS PERIOADA,
:pFORM AS FORM,
:pFORM_VERS AS FORM_VERS,
:pID_MDTABLE AS ID_MDTABLE,
:pCOD_CUATM AS COD_CUATM,    
NR_TABLE AS NR_SECTIE,
TABLE_DENUMIRE AS NUME_SECTIE,
'0' AS NR_SECTIE1,
'0' AS NUME_SECTIE1,
'0' AS NR_SECTIE2,
'0' AS NUME_SECTIE2, 
ORDINE  NR_ROW,
ORDINE AS ORDINE,
'222222222' AS DECIMAL_POS, 
RIND_DENUMIRE AS NUME_ROW,
COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8, ROUND(COL9,0) AS COL9
FROM
(
SELECT
  A.NR_TABLE,
  A.TABLE_DENUMIRE,
  A.RIND_DENUMIRE,
  A.ORDINE,
  A.RIND,
  ROUND(A.COL1 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL1,
  ROUND(A.COL2 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL2,
  ROUND(A.COL3 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL3,
  ROUND(A.COL4 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL4,
  ROUND(A.COL5 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL5,
  ROUND(A.COL6 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL6,
  ROUND(A.COL7 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL7,
  ROUND(A.COL8 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL8,
    ROUND(A.COL1 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) + 
    ROUND(A.COL2 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) +
    ROUND(A.COL3 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) + 
    ROUND(A.COL4 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) +
    ROUND(A.COL5 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) +
    ROUND(A.COL6 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) + 
    ROUND(A.COL7 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) + 
    ROUND(A.COL8 *100 / (A.COL1 + A.COL2 + A.COL3 + A.COL4 + A.COL5 + A.COL6 + A.COL7 + A.COL8),1) AS COL9  
  
FROM
(
SELECT
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND,
--  SUBSTR(A.CAEM2,1,1),


   SUM(CASE WHEN A.RIND IN ('9.01') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL1,
  SUM(CASE WHEN A.RIND IN ('9.02') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL2,
  SUM(CASE WHEN A.RIND IN ('9.03') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL3,
  SUM(CASE WHEN A.RIND IN ('9.04') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL4,
  SUM(CASE WHEN A.RIND IN ('9.05') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL5,
  SUM(CASE WHEN A.RIND IN ('9.06') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL6,

SUM(CASE WHEN A.RIND IN ('9.07') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL7,
  SUM(CASE WHEN A.RIND IN ('9.08') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL8,
  SUM(CASE WHEN A.RIND IN ('9.09') AND (TR.RIND LIKE '%'|| SUBSTR(A.CAEM2,1,1) ||'%' OR (ROUND(BS.PERS_IT) >= TR.PERS_INIT AND ROUND(BS.PERS_IT) <= TR.PERS_FINAL)) THEN A.COL1 END) AS COL9

FROM
(SELECT
  D.ANUL,
  D.CUIIO,
  D.CUATM,
  D.CAEM2,
  D.CAPITOL,
  D.RIND,
  D.COL1, 
  D.COL2
FROM 
  CIS2.VW_DATA_ALL_COEF D
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.CAPITOL IN (1197) AND
  D.RIND IN ('9.01','9.02','9.03','9.04','9.05','9.06','9.07','9.08')--AND D.CUIIO=40988116
) A LEFT JOIN
  CIS2.X_BAZA_SONDAJ BS ON (A.CUIIO=BS.CUIIO AND BS.ANUL=2024)
  CROSS JOIN 
  (
    SELECT 1 AS NR_TABLE, 'CAEM2' AS TABLE_DENUMIRE, NULL AS PERS_INIT, NULL AS PERS_FINAL, 'B+C+D+E+F+G+H+I+J+L+M+N+R+S' AS RIND, 'Total activitati' AS RIND_DENUMIRE, '1' AS ORDINE FROM DUAL 
     ) TR
     
       
     WHERE 
  A.CAEM2 NOT LIKE 'A%' 
GROUP BY
  TR.NR_TABLE,
  TR.TABLE_DENUMIRE,
  TR.RIND_DENUMIRE,
  TR.ORDINE,
  TR.RIND

) A
ORDER BY
  A.NR_TABLE,
  A.ORDINE
) 