SELECT
D.CUIIO,

  CIS2.NVAL(SUM(CASE WHEN CAPITOL IN (1034) AND D.RIND  NOT  IN '0000000' THEN COL1 ELSE 0 END)) AS COL1

  
FROM
  CIS2.VW_DATA_ALL D
 INNER JOIN CIS2.VW_CL_CUATM C ON (D.RIND=C.CODUL )
  
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
   D.FORM = 47 AND
  -- D.CUIIO=3399698 AND
   D.CAPITOL IN (1034,1035) 
   
   --AND CC.PRGS NOT IN 4  AND
   AND C.FULL_CODE LIKE '%'||:pCOD_CUATM||'%'
   
GROUP BY 

--  C.CODUL, C.FULL_CODE,C.PRGS,
  D.CUIIO
--   ORDER BY 
--   C.FULL_CODE