SELECT MR.RIND,
       MR.ORDINE,
       SUM(D.COL1) AS COL1,
       SUM(D.COL2) AS COL2,
       SUM(D.COL3) AS COL3,
       SUM(D.COL4) AS COL4,
       SUM(D.COL5) AS COL5,
       SUM(D.COL6) AS COL6,
       SUM(D.COL7) AS COL7,
       SUM(D.COL8) AS COL8,
       SUM(D.COL9) AS COL9,
       SUM(D.COL10) AS COL10 

FROM CIS2.DATA_ALL_LOG D 

                        INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD
                        INNER JOIN CIS2.MD_CAPITOL  MC ON MR.CAPITOL = MC.CAPITOL  
WHERE 
D.FORM = 47
AND D.PERIOADA = 2005
AND MC.capitol=1034 AND MC.capitol_vers=2000
AND CUIIO = 3399698

 AND D.DATA_REG >= TO_DATE('05/13/2025 00:00:00', 'MM/DD/YYYY HH24:MI:SS')



GROUP BY
MR.RIND,
MR.ORDINE


ORDER BY
MR.ORDINE
