SELECT
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  
  R.IDNO,
  R.DENUMIRE DENUMIRE_CUIIO,
  R.CFP, 
  D.RIND,
  SUM(CASE WHEN D.CAPITOL IN (1034) THEN D.COL4 ELSE 0 END) AS COL1,
  SUM(CASE WHEN D.CAPITOL IN (1034) THEN D.COL10 ELSE 0 END) AS COL2,
  NULL AS COL3,
  NULL AS COL4,
  NULL AS COL5,
  NULL AS COL6,
  NULL AS COL7,
  NULL AS COL8,
  NULL AS COL9,
  NULL AS COL10         
 
  

    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (1034)
    AND D.RIND IN ('0000000')
   
    
GROUP BY 
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO