SELECT
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  
  R.IDNO,
  R.DENUMIRE DENUMIRE_CUIIO,
  R.CFP, 
  D.RIND,
  NULL  AS COL1,
  NULL  AS COL2,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL1 ELSE 0 END) AS COL3,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL2 ELSE 0 END) AS COL4,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL3 ELSE 0 END) AS COL5,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL4 ELSE 0 END) AS COL6,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL5 ELSE 0 END) AS COL7,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL6 ELSE 0 END) AS COL8,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL7 ELSE 0 END) AS COL9,
  SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL8 ELSE 0 END) AS COL10
    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (1036)
    AND D.RIND IN ('0000000')
   
    
GROUP BY 
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO