SELECT 
RIND,
SUM(COL1) AS COL1,
SUM(COL2) AS COL2
FROM 
(

SELECT 
  D.CODUL,
  D.FULL_CODE,
  D.DENUMIRE,
  D.CUIIO,
  R.IDNO IDNO,
  
--  D.IDNO,
  D.DENUMIRE_CUIIO,
  D.CFP, 
  D.RIND,
  D.COL1,
  D.COL2,
  D.COL3,
  D.COL4,
  D.COL5,
  D.COL6,
  D.COL7,
  D.COL8,
  D.COL9,
  D.COL10

FROM

(

SELECT

  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  NULL CUIIO,
  NULL IDNO,
  NULL DENUMIRE_CUIIO,
  NULL AS CFP,
  NULL RIND,
  NULL AS COL1,
  NULL AS COL2,
  NULL AS COL3,
  NULL AS COL4,
  NULL AS COL5,
  NULL AS COL6,
  NULL AS COL7,
  NULL AS COL8,         
  NULL AS COL9,
  NULL AS COL10

    

        FROM  CIS2.VW_CL_CUATM C
        
        
            WHERE 
            
            C.PRGS IN ('2')
                
            
            GROUP BY 
              C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE
  


UNION 

SELECT 

  CODUL,
  FULL_CODE,
  DENUMIRE,
  CUIIO,
  
  IDNO,
  DENUMIRE_CUIIO,
  CFP, 
  RIND,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2,
  SUM(COL3) AS COL3,
  SUM(COL4) AS COL4,
  SUM(COL5) AS COL5,
  SUM(COL6) AS COL6,
  SUM(COL7) AS COL7,
  SUM(COL8) AS COL8,
  SUM(COL9) AS COL9,
  SUM(COL10) AS COL10

FROM 



(

SELECT
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  
  R.IDNO,
  R.DENUMIRE DENUMIRE_CUIIO,
  R.CFP, 
  D.RIND,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1034) THEN D.COL4 ELSE 0 END),1) AS COL1,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1034) THEN D.COL10 ELSE 0 END),1) AS COL2,
  NULL AS COL3,
  NULL AS COL4,
  NULL AS COL5,
  NULL AS COL6,
  NULL AS COL7,
  NULL AS COL8,
  NULL AS COL9,
  NULL AS COL10         
 
  

    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (1034)
    AND D.RIND IN ('0000000')
   --  AND
 --  D.CUIIO= 38923807 
   
    
GROUP BY 
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO
  
  UNION 
  
  SELECT
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  
  R.IDNO,
  R.DENUMIRE  ENUMIRE_CUIIO,
  R.CFP, 
  D.RIND,
  NULL  AS COL1,
  NULL  AS COL2,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL1 ELSE 0 END),1) AS COL3,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL2 ELSE 0 END),1) AS COL4,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL3 ELSE 0 END),1) AS COL5,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL4 ELSE 0 END),1) AS COL6,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL5 ELSE 0 END),1) AS COL7,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL6 ELSE 0 END),1) AS COL8,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL7 ELSE 0 END),1) AS COL9,
  ROUND(SUM(CASE WHEN D.CAPITOL IN (1036) THEN D.COL8 ELSE 0 END),1) AS COL10
    FROM CIS2.VW_DATA_ALL D 
    
            INNER JOIN CIS2.VW_CL_CUATM C ON C.CODUL = D.CUATM
            INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 
    
    WHERE 
    
    D.PERIOADA IN (:pPERIOADA)
    AND D.FORM IN (:pFORM)    
    AND D.CAPITOL IN (1036)
    AND D.RIND IN ('0000000')
  --   AND
 --  D.CUIIO= 38923807 
   
    
GROUP BY 
  C.CODUL,
  C.FULL_CODE,
  C.DENUMIRE,
  D.CUIIO,
  R.DENUMIRE,
  R.CFP,
  D.RIND,
  R.IDNO
  
  
  ORDER BY CUIIO  
  
  
  )
  
  GROUP BY 
    CODUL,
  FULL_CODE,
  DENUMIRE,
  CUIIO,
  
  IDNO,
  DENUMIRE,
  CFP, 
  RIND,
   DENUMIRE_CUIIO
  


ORDER BY 
FULL_CODE


) D  LEFT JOIN (

SELECT 
    CUIIO,
    IDNO

                    FROM  USER_BANCU.VW_MAX_RENIM_CIS2
) R ON D.CUIIO = R.CUIIO  


ORDER BY 
FULL_CODE

        

--WHERE 
--R.IDNO  IS NULL 
)

GROUP BY 
RIND