SELECT
CODUL,
FULL_CODE,
COL1,
COL2,
COL3,
SUM(COL4) AS COL4,
SUM(COL5) AS COL5,
  NULL AS COL6 

FROM
(
SELECT 
CUATM CODUL,
NULL FULL_CODE,
NULL AS COL1, 
NULL AS COL2,
NULL AS COL3,
SUM(CNT) AS COL4,
NULL AS COL5

FROM
(
SELECT
RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
---DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11,
COL12,
COL13,
COL14,
COL15,
COL16,
COL17,
COL18,
COL19,
COL20,
COL21,
COL22,
CASE WHEN  COL1 > 0 AND  COL1 IS NOT NULL THEN 1 ELSE 0  END 
+ CASE WHEN  COL2 > 0 AND  COL2 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL3 > 0 AND  COL3 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL4 > 0 AND  COL4 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL5 > 0 AND  COL5 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL6 > 0 AND  COL6 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL7 > 0 AND  COL7 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL8 > 0 AND  COL8 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL9 > 0 AND  COL9 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL10 > 0 AND  COL10 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL11 > 0 AND  COL11 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL12 > 0 AND  COL1 IS NOT NULL THEN 1 ELSE 0  END 
+ CASE WHEN  COL13 > 0 AND  COL2 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL14 > 0 AND  COL3 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL15 > 0 AND  COL4 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL16 > 0 AND  COL5 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL17 > 0 AND  COL6 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL18 > 0 AND  COL7 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL19 > 0 AND  COL8 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL20 > 0 AND  COL9 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL21 > 0 AND  COL10 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL22 > 0 AND  COL11 IS NOT NULL THEN 1 ELSE 0  END


 CNT
FROM

(
SELECT
ROWNUM RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
--DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11,
COL12,
COL13,
COL14,
COL15,
COL16,
COL17,
COL18,
COL19,
COL20,
COL21,
COL22
 
 
FROM
(


SELECT
DISTINCT
NULL DEN_SHORT,
D.CUIIO,
D.CUATM,
--R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
 NULL  AS DATA_PRIMIRII,
NULL  AS DATA_PROCESARII,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10,
SUM(D.COL11) AS COL11,


SUM(D.COL12) AS COL12,
SUM(D.COL13) AS COL13,
SUM(D.COL14) AS COL14,
SUM(D.COL15) AS COL15,
SUM(D.COL16) AS COL16,
SUM(D.COL17) AS COL17,
SUM(D.COL18) AS COL18,
SUM(D.COL19) AS COL19,
SUM(D.COL20) AS COL20,
SUM(D.COL21) AS COL21,
SUM(D.COL22) AS COL22

FROM
CIS2.VW_DATA_ALL D 
INNER JOIN USER_EREPORTING.VW_DATA_ALL_PRIMIT PR ON PR.CUIIO = D.CUIIO AND PR.CUIIO_VERS = D.CUIIO_VERS AND D.PERIOADA=PR.PERIOADA AND D.FORM=PR.FORM AND PR.ID_SCHEMA IN (2)
WHERE
D.PERIOADA = :pPERIOADA_LUNA AND
--D.CUATM LIKE '01%' AND
D.FORM IN (:pFORM)
 AND D.FORM_VERS IN (:pFORM_VERS)   
 
 AND D.CUIIO IN (
              SELECT DISTINCT D.CUIIO
                         
                          
            FROM CIS2.DATA_ALL D
            
                 
           WHERE D.PERIOADA = :pPERIOADA AND D.FORM IN (:pFORM)
              )
              
               AND D.DATA_REG  > TO_DATE('01/01/2025 00:00:00', 'MM/DD/YYYY HH24:MI:SS') 


GROUP BY
--F.DEN_SHORT,
D.CUIIO,
D.CUATM,
--R.DENUMIRE,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND

ORDER BY
DEN_SHORT,
CUIIO,
CAPITOL,
RIND

)

)



)

GROUP BY 
CUATM





union 


SELECT 
CUATM CODUL,
NULL FULL_CODE,
NULL AS COL1, 
NULL AS COL2,
NULL AS COL3,
NULL AS COL4,
SUM(CNT) AS COL5

FROM
(
SELECT
RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
--DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11,
COL12,
COL13,
COL14,
COL15,
COL16,
COL17,
COL18,
COL19,
COL20,
COL21,
COL22,
CASE WHEN  COL1 > 0 AND  COL1 IS NOT NULL THEN 1 ELSE 0  END 
+ CASE WHEN  COL2 > 0 AND  COL2 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL3 > 0 AND  COL3 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL4 > 0 AND  COL4 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL5 > 0 AND  COL5 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL6 > 0 AND  COL6 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL7 > 0 AND  COL7 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL8 > 0 AND  COL8 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL9 > 0 AND  COL9 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL10 > 0 AND  COL10 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL11 > 0 AND  COL11 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL12 > 0 AND  COL1 IS NOT NULL THEN 1 ELSE 0  END 
+ CASE WHEN  COL13 > 0 AND  COL2 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL14 > 0 AND  COL3 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL15 > 0 AND  COL4 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL16 > 0 AND  COL5 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL17 > 0 AND  COL6 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL18 > 0 AND  COL7 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL19 > 0 AND  COL8 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL20 > 0 AND  COL9 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL21 > 0 AND  COL10 IS NOT NULL THEN 1 ELSE 0  END
+ CASE WHEN  COL22 > 0 AND  COL11 IS NOT NULL THEN 1 ELSE 0  END


 CNT
FROM

(
SELECT
ROWNUM RIND_ID,
DEN_SHORT,
CUIIO,
CUATM,
--DENUMIRE,
PACHET,
DATA_PRIMIRII,
DATA_PROCESARII,
CAPITOL_DEN,
CAPITOL,
RIND,
COL1,
COL2,
COL3,
COL4,
COL5,
COL6,
COL7,
COL8,
COL9,
COL10,
COL11,
COL12,
COL13,
COL14,
COL15,
COL16,
COL17,
COL18,
COL19,
COL20,
COL21,
COL22
 
 
FROM
(


SELECT
DISTINCT
NULL DEN_SHORT,
D.CUIIO,
D.CUATM,
--R.DENUMIRE,
MAX(D.PACHET) AS PACHET,
NULL AS DATA_PRIMIRII,
NULL  AS DATA_PROCESARII,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND,
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL7) AS COL7,
SUM(D.COL8) AS COL8,
SUM(D.COL9) AS COL9,
SUM(D.COL10) AS COL10,
SUM(D.COL11) AS COL11,


SUM(D.COL12) AS COL12,
SUM(D.COL13) AS COL13,
SUM(D.COL14) AS COL14,
SUM(D.COL15) AS COL15,
SUM(D.COL16) AS COL16,
SUM(D.COL17) AS COL17,
SUM(D.COL18) AS COL18,
SUM(D.COL19) AS COL19,
SUM(D.COL20) AS COL20,
SUM(D.COL21) AS COL21,
SUM(D.COL22) AS COL22

FROM
CIS2.VW_DATA_ALL D --M1, CONS.TS, 5CI,65 AUTO, 2 INVEST

WHERE
D.PERIOADA = :pPERIOADA_LUNA AND



D.FORM IN (:pFORM)
 AND D.FORM_VERS IN (:pFORM_VERS)   
 
  AND D.DATA_REG  > TO_DATE('01/01/2025 00:00:00', 'MM/DD/YYYY HH24:MI:SS') 

GROUP BY
--F.DEN_SHORT,
D.CUIIO,
D.CUATM,
--R.DENUMIRE,
D.CAPITOL_DEN,
D.CAPITOL,
D.RIND

ORDER BY
DEN_SHORT,
CUIIO,
CAPITOL,
RIND

)

)
)

GROUP BY 
CUATM

)


group by 

CODUL,
FULL_CODE,
COL1,
COL2,
COL3



