 
 
SELECT
D.ITEM_CODE CODE,
D.A01 AS PRGS,
D.NAME DEN_CUATM,
D. ITEM_PATH AS FULL_CODE
 FROM CIS2.VW_CLS_CLASS_ITEM D INNER JOIN (
 SELECT 
ITEM_CODE,
MAX(ITEM_CODE_VERS) ITEM_CODE_VERS

FROM CIS2.VW_CLS_CLASS_ITEM

WHERE 
CLASS_CODE IN ('CUATM') 
GROUP BY 
ITEM_CODE
 ) DD ON D.ITEM_CODE = DD.ITEM_CODE AND D.ITEM_CODE_VERS = DD.ITEM_CODE_VERS  AND D.CLASS_CODE IN ('CUATM')
WHERE 
D. ITEM_PATH LIKE '%'||:pCOD_CUATM||';%'

ORDER BY
D. ITEM_PATH
 
