


   SELECT  
   L.CUIIO,
   L.CUIIO_VERS
   FROM USER_BANCU.ADD_NEW_SU_M3_2024 L 
   LEFT JOIN USER_EREPORTING.RENIM_EXTRA R ON R.CUIIO = L.CUIIO AND R.CUIIO_VERS = L.CUIIO_VERS
   
   WHERE 
   R.CUIIO IS NULL; 