SELECT DISTINCT
  'Col.'||C.COL||': RIND 10 = '||
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.RIND IN('10') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)||' < RIND 30 = '||
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.RIND IN('30') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)
  ||'  Trimestru precedent  : RIND 10 = '|| SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-3) AND D.RIND IN('10') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)
  ||'  : RIND 30 = '|| SUM(CASE WHEN D.PERIOADA IN (:PERIOADA-3) AND D.RIND IN('30') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)
  
  
  
  
  AS REZULTAT

FROM
  VW_DATA_ALL D,
  (
    SELECT 1 AS COL FROM DUAL 
  ) C
WHERE
  (D.PERIOADA IN (:PERIOADA, :PERIOADA- 3 )) AND 
  (D.CUIIO=:CUIIO               ) AND
  (:CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS <> :CUIIO_VERS) AND
  (D.FORM=:FORM                 ) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL            OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS  OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM    IN(5) AND     -- Forma: IND TS
  D.CAPITOL IN(27) AND    -- Cap. VS
  D.RIND    IN('10','30')
GROUP BY
  C.COL
HAVING
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.RIND IN('10') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)<
  SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.RIND IN('30') THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3) ELSE 0 END)