INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  
  COL1, COL2, COL3, COL4
)

SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
    R.CUIIO||'-'||R.FORM_DEN AS NR_ROW,
    ROWNUM AS ORDINE,
    '00000' AS DECIMAL_POS,
    R.DENUMIRE AS NUME_ROW,
    TO_NUMBER(R.CUATM) AS COL1,
    TO_NUMBER(SUBSTR(R.CAEM2,2,5)) AS COL2,
    R.BUGET AS COL3,
    R.CAUZA AS COL4

FROM
    (
    SELECT 
        DISTINCT
        R.DENUMIRE,
        D.CUIIO,
        MAX(D.CAEM2) AS CAEM2,
        D.CUATM,
        D.BUGET,
        D.FORM_DEN,
        MAX(TO_NUMBER(CASE WHEN D.CAPITOL IN (0) AND D.RIND NOT IN ('ER','CD','CM','DIH','01','I','-','10','11','12') AND D.PERIOADA IN (:pPERIOADA) THEN D.RIND ELSE NULL END)) AS CAUZA,
        MR.DENUMIRE AS DENUMIRE_CAUZA
    
    FROM
        VW_DATA_ALL_CALC D
        INNER JOIN RENIM R ON (D.CUIIO = R.CUIIO AND D.CUIIO_VERS = R.CUIIO_VERS)
        INNER JOIN MD_RIND MR ON (D.RIND = MR.RIND AND D.RIND_VERS = MR.RIND_VERS AND MR.CAPITOL IN ('0'))     
    
    WHERE
        D.CAPITOL IN (0) AND
        D.FORM IN (5) AND
        D.PERIOADA IN (:pPERIOADA) AND
        D.CUATM_FULL LIKE '%'|| :pCOD_CUATM||'%'
        
        --AND D.DIH='1'
    
    GROUP BY
        D.CUIIO,
--        D.CAEM,
        D.CUATM,
        D.BUGET,
        D.FORM_DEN,
        R.DENUMIRE,
        MR.DENUMIRE
        
     HAVING
         SUM(TO_NUMBER(CASE WHEN D.CAPITOL IN (0) AND D.RIND NOT IN ('ER','CD','CM','DIH','01','I','-','10','11','12') AND D.PERIOADA IN (:pPERIOADA) THEN TO_NUMBER(D.RIND) ELSE NULL END)) >0
       
    ORDER BY
        D.CUATM,
        D.CUIIO
    ) R