--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5
--)

SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0' AS NR_SECTIE,
    '0' AS NUME_SECTIE,
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2,
    D.CUIIO||'-'||D.FORM_DEN AS NR_ROW,
    ROWNUM AS ORDINE,
    '00000' AS DECIMAL_POS,
    D.DENUMIRE AS NUME_ROW,
    TO_NUMBER(D.CUATM) AS COL1,
    TO_NUMBER(SUBSTR(D.CAEM2,2,5)) AS COL2,
    D.FORM AS COL3,
     COL4,
     COL5
     
FROM
(

SELECT DISTINCT
  D.DENUMIRE,
  D.CUIIO,
  D.FORM_DEN,
  D.CUATM,
  D.CAEM2,
  D.FORM,
  TO_NUMBER(R.RIND) AS COL4,
  TO_NUMBER(D.RIND) AS COL5



FROM
 (
SELECT DISTINCT
  R.DENUMIRE,
  R.CUIIO,
  D.FORM_DEN,
  R.CUATM,
  R.CAEM2,
  D.FORM,
  D.RIND
  
FROM
  CIS.VW_DATA_ALL D
  INNER JOIN CIS.RENIM R ON (D.CUIIO = R.CUIIO AND D.CUIIO_VERS = R.CUIIO_VERS)
  
WHERE
  D.FORM IN (5) AND
  D.CUATM_FULL LIKE '%'|| :pCOD_CUATM||'%' AND
  D.CAPITOL = 0 AND
  D.PERIOADA IN :pPERIOADA AND
  D.RIND NOT IN ('CD','CM','DIH','ER','-','I') AND
  (R.CUIIO, R.CUIIO_VERS) IN (
  
  
SELECT
  DISTINCT
  R.CUIIO,
  R.CUIIO_VERS
  
FROM
  CIS.RENIM R
  INNER JOIN CIS.FORM_CUIIO F ON (R.CUIIO=F.CUIIO AND R.CUIIO_VERS=F.CUIIO_VERS)
  INNER JOIN 
  (
      SELECT
      R.CUIIO,
      MAX(R.CUIIO_VERS) AS CUIIO_VERS
    FROM
      CIS.RENIM R
    WHERE
      R.CUIIO_VERS <= :pPERIOADA
    GROUP BY
      R.CUIIO
  ) D ON (R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
WHERE
  F.FORM IN (5) AND
  F.STATUT <> '3' )) D
  
INNER JOIN (
  SELECT DISTINCT
  R.DENUMIRE,
  R.CUIIO,
  D.FORM_DEN,
  R.CUATM,
  R.CAEM2,
  D.FORM,
  D.RIND
  
FROM
  CIS.VW_DATA_ALL D
  INNER JOIN CIS.RENIM R ON (D.CUIIO = R.CUIIO AND D.CUIIO_VERS = R.CUIIO_VERS)
  
WHERE
  D.FORM IN (5) AND
  D.CUATM_FULL LIKE '%'|| :pCOD_CUATM||'%' AND
  D.CAPITOL = 0 AND
  D.PERIOADA IN :pPERIOADA-3 AND
  D.RIND NOT IN ('CD','CM','DIH','ER','-','I') AND
  (R.CUIIO, R.CUIIO_VERS) IN (
  
  
SELECT
  DISTINCT
  R.CUIIO,
  R.CUIIO_VERS
  
FROM
  CIS.RENIM R
  INNER JOIN CIS.FORM_CUIIO F ON (R.CUIIO=F.CUIIO AND R.CUIIO_VERS=F.CUIIO_VERS)
  INNER JOIN 
  (
      SELECT
      R.CUIIO,
      MAX(R.CUIIO_VERS) AS CUIIO_VERS
    FROM
      CIS.RENIM R
    WHERE
      R.CUIIO_VERS <= :pPERIOADA-3
    GROUP BY
      R.CUIIO
  ) D ON (R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
WHERE
  F.FORM IN (5) AND
  F.STATUT <> '3' )) R ON R.CUIIO = D.CUIIO

GROUP BY
  D.DENUMIRE,
  D.CUIIO,
  D.FORM_DEN,
  D.CUATM,
  D.CAEM2,
  D.FORM,
  D.RIND,  R.RIND
 
HAVING
  D.RIND <> R.RIND

) D