-- Tab.3 --
INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,
 COL2,
 COL3, COL4, COL5, COL6, COL7,COL8
)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  A.NR_ROW AS NR_ROW,
  ROWNUM AS ORDINE,
  '00000000' AS DECIMAL_POS,
  A.NUME_ROW,
  A.COL1,
  A.COL2,
  A.COL3,
  A.COL4,
  A.COL5,
  A.COL6,
  A.COL7,
  A.COL8
FROM
( SELECT
  CIS2.CC.CODUL AS NR_ROW,
  CIS2.CC.CODUL AS ORDINE,
  CIS2.CC.DENUMIRE AS NUME_ROW,
  
  SUM(CASE WHEN CIS2.D.RIND IN ('01') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('03') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('04') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('05') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('06') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('07') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL1,
  SUM(CASE WHEN CIS2.D.RIND IN ('01') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL2,
  SUM(CASE WHEN CIS2.D.RIND IN ('02') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL3,
  SUM(CASE WHEN CIS2.D.RIND IN ('03') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL4,
  SUM(CASE WHEN CIS2.D.RIND IN ('04') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL5,
  SUM(CASE WHEN CIS2.D.RIND IN ('05') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL6,
  SUM(CASE WHEN CIS2.D.RIND IN ('06') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL7, 
  SUM(CASE WHEN CIS2.D.RIND IN ('07') THEN CIS2.NVAL(CIS2.D.COL1) ELSE 0 END) AS COL8
 
           
          
      
      
  
FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.VW_CL_CUATM C ON (CIS2.D.CUATM=CIS2.C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (CIS2.C.FULL_CODE LIKE '%'||CIS2.CC.CODUL ||';%' )
WHERE
  (CIS2.D.FORM=:pFORM) AND
  (CIS2.D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (CIS2.D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  CIS2.D.FORM = 15 AND
  CIS2.D.CAPITOL IN (1000) AND
  CIS2.CC.PRGS IN (2) AND
  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
  
GROUP BY
   
   CIS2.CC.DENUMIRE,
   CIS2.CC.CODUL,
   CC.FULL_CODE
ORDER BY 
  CC.FULL_CODE
) A