INSERT INTO CIS2.TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1, COL2, COL3, COL4, COL5, COL6, COL7,COL8, COL9, COL10, COL11, COL12, COL13, COL14, COL15, COL16, COL17, COL18, COL19, COL20, COL21,
 COL22,COL23, COL24, COL25, COL26, COL27, COL28, COL29, COL30
)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
    A.NR_ROW,
  ROWNUM AS ORDINE,
  '111111111111111111111111111111' AS DECIMAL_POS,
  A.NUME_ROW,
  ROUND(A.COL1,1) AS COL1,
  ROUND(A.COL2,1) AS COL2,
  ROUND(A.COL3,1) AS COL3,
  ROUND(A.COL4,1) AS COL4,
  ROUND(A.COL5,1) AS COL5,
  ROUND(A.COL6,1) AS COL6,
  ROUND(A.COL7,1) AS COL7,
  ROUND(A.COL8,1) AS COL8,
  ROUND(A.COL9,1) AS COL9,
  ROUND(A.COL10,1) AS COL10,
  ROUND(A.COL11,1) AS COL11,
  ROUND(A.COL12,1) AS COL12,
  ROUND(A.COL13,1) AS COL13,
  ROUND(A.COL14,1) AS COL14,
  ROUND(A.COL15,1) AS COL15,
  ROUND(A.COL16,1) AS COL16,
  ROUND(A.COL17,1) AS COL17,
  ROUND(A.COL18,1) AS COL18,
  ROUND(A.COL19,1) AS COL19,
  ROUND(A.COL20,1) AS COL20,
  ROUND(A.COL21,1) AS COL21,
  ROUND(A.COL22,1) AS COL22,
  ROUND(A.COL23,1) AS COL23,
  ROUND(A.COL24,1) AS COL24,
  ROUND(A.COL25,1) AS COL25,
  ROUND(A.COL26,1) AS COL26,
  ROUND(A.COL27,1) AS COL27,
  ROUND(A.COL28,1) AS COL28,
  ROUND(A.COL29,1) AS COL29,
  ROUND(A.COL30,1) AS COL30
  
 
 FROM 
(
SELECT
  CC.CODUL AS NR_ROW,
  CC.CODUL AS ORDINE,
  CC.DENUMIRE AS NUME_ROW,
  
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL1 ELSE 0 END))  AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN D.COL2 ELSE 0 END))  AS COL2,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('02') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL3,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('03') THEN D.COL1 ELSE 0 END))  AS COL4,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('03') THEN D.COL2 ELSE 0 END))  AS COL5,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('03') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL6,
      
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('04') THEN D.COL1 ELSE 0 END))  AS COL7,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('04') THEN D.COL2 ELSE 0 END))  AS COL8,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('04') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL9,
  
    
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL1 ELSE 0 END))  AS COL10,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN D.COL2 ELSE 0 END))  AS COL11,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('06') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL12,
  
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('07') THEN D.COL1 ELSE 0 END))  AS COL13,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('07') THEN D.COL2 ELSE 0 END))  AS COL14,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('07') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL15,
  
    CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('08') THEN D.COL1 ELSE 0 END))  AS COL16,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('08') THEN D.COL2 ELSE 0 END))  AS COL17,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('08') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL18,
  
  
      CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('09') THEN D.COL1 ELSE 0 END))  AS COL19,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('09') THEN D.COL2 ELSE 0 END))  AS COL20,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('09') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL21,
  
        CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL1 ELSE 0 END))  AS COL22,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN D.COL2 ELSE 0 END))  AS COL23,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('10') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL24,
  
  
          CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('11') THEN D.COL1 ELSE 0 END))  AS COL25,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('11') THEN D.COL2 ELSE 0 END))  AS COL26,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('11') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL27,
  
    
          CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('12') THEN D.COL1 ELSE 0 END))  AS COL28,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('12') THEN D.COL2 ELSE 0 END))  AS COL29,
  CIS2.NVAL(SUM(CASE WHEN D.RIND IN ('12') THEN NVAL(D.COL2)/NOZERO(NVAL(D.COL1)) ELSE 0 END))  AS COL30                                      

FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.VW_CL_CUATM C ON (D.CUATM=C.CODUL)
  INNER JOIN CIS2.VW_CL_CUATM CC ON (C.FULL_CODE LIKE '%'||CC.CODUL ||';%' )  
  INNER JOIN CIS2.RENIM RR ON (D.CUIIO = RR.CUIIO AND D.CUIIO_VERS = RR.CUIIO_VERS)
 
     
WHERE
  (D.FORM=:pFORM) AND
  (D.FORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
  
  
  D.FORM = 15 AND
  D.CAPITOL IN (1000) AND
  CC.PRGS IN (2) AND
  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/4)*4 AND :pPERIOADA
  
GROUP BY
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
ORDER BY 
  CC.FULL_CODE


) A 