--INSERT INTO CIS.RENIM (
--
--   CUIIO, CUIIO_VERS, DENUMIRE, EDIT_USER, STATUT, 
-- CUATM, CFP, CFOJ, COCM, CAEM, 
-- BUGET, TIP, PROD, FOR_CUB, ETAPA_PROD, 
-- RENIM_PERS, CAEM2
--
--)
--

SELECT 
  R.CUIIO,
  R.CUIIO_VERS,
  R.DENUMIRE,
  R.EDIT_USER,
  R.STATUT,
  R.CUATM,
  R.CFP,
  R.CFOJ,
  R.COCM,
  R.CAEM,
  R.BUGET,
  R.TIP,
  R.PROD,
  R.FOR_CUB,
  R.ETAPA_PROD,
  R.RENIM_PERS, 
  R.CAEM2  
 
  
    
    FROM
    USER_BANCU.VW_MAX_RENIM_TRIM_CIS R 
     --USER_BANCU.VW_MAX_RENIM_299_CIS  R
     --USER_BANCU.VW_MAX_RENIM_CIS2
    -- USER_BANCU.VW_MAX_RENIM_TRIM_CIS2

   WHERE 
   
   R.CUIIO IN (
    SELECT CUIIO
            FROM USER_BANCU.UNICA_1056
   )    
    
   
 --  AND R.CUIIO_VERS <> 1058