INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,  
 COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8,COL9,COL10,COL11
)

SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  CODUL AS NR_ROW,
  ROWNUM AS ORDINE,
  '00000000000' AS DECIMAL_POS,
  DENUMIRE AS NUME_ROW,
  ROUND(COL1,0) AS COL1,
  ROUND(COL2,0) AS COL2,
  ROUND(COL3,0) AS COL3,
  ROUND(COL4,0) AS COL4,
  ROUND(COL5,0) AS COL5,
  ROUND(COL6,0) AS COL6,
  ROUND(COL7,0) AS COL7,
  ROUND(COL8,0) AS COL8,
  ROUND(COL9,0) AS COL9,
  ROUND(COL10,0) AS COL10,
  ROUND(COL11,0) AS COL11
FROM
(
SELECT
  CODUL,
  FULL_CODE,
  DENUMIRE,
  SUM(COL1) AS COL1,
  SUM(COL2) AS COL2,
  SUM(COL3) AS COL3,
  SUM(COL4) AS COL4,
  SUM(COL5) AS COL5,
  SUM(COL6) AS COL6,
  SUM(COL7) AS COL7,
  SUM(COL8) AS COL8,
  SUM(COL9) AS COL9,
  SUM(COL10) AS COL10,
  SUM(COL11) AS COL11
FROM
(
SELECT 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('32') THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('33') THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('34') THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('35') THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('36') THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('37') THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('38') THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('39') THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('40') THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('41') THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('42') THEN D.COL1 END)) AS COL11
FROM 
  VW_DATA_ALL D
  INNER JOIN VW_CL_CAEM2 C ON (D.CAEM2=C.CODUL)
  INNER JOIN VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (42)                 AND 
  D.CAPITOL IN (396) AND
  D.FILIAL IN ('0') AND
  CC.CODUL LIKE '%00'
GROUP BY
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
UNION
SELECT 
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE,
  NVAL(SUM(CASE WHEN D.RIND IN ('32') THEN D.COL1 END)) AS COL1,
  NVAL(SUM(CASE WHEN D.RIND IN ('33') THEN D.COL1 END)) AS COL2,
  NVAL(SUM(CASE WHEN D.RIND IN ('34') THEN D.COL1 END)) AS COL3,
  NVAL(SUM(CASE WHEN D.RIND IN ('35') THEN D.COL1 END)) AS COL4,
  NVAL(SUM(CASE WHEN D.RIND IN ('36') THEN D.COL1 END)) AS COL5,
  NVAL(SUM(CASE WHEN D.RIND IN ('37') THEN D.COL1 END)) AS COL6,
  NVAL(SUM(CASE WHEN D.RIND IN ('38') THEN D.COL1 END)) AS COL7,
  NVAL(SUM(CASE WHEN D.RIND IN ('39') THEN D.COL1 END)) AS COL8,
  NVAL(SUM(CASE WHEN D.RIND IN ('40') THEN D.COL1 END)) AS COL9,
  NVAL(SUM(CASE WHEN D.RIND IN ('41') THEN D.COL1 END)) AS COL10,
  NVAL(SUM(CASE WHEN D.RIND IN ('42') THEN D.COL1 END)) AS COL11
FROM 
  VW_DATA_ALL D
  INNER JOIN VW_CL_CAEM2 C ON (D.FILIAL=SUBSTR(C.CODUL,2,4))
  INNER JOIN VW_CL_CAEM2 CC ON (C.FULL_CODE LIKE '%'||CC.CODUL||';%')
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (42)                 AND 
  D.CAPITOL IN (396) AND
  CC.CODUL LIKE '%00'
GROUP BY
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
)
GROUP BY
  CODUL,
  DENUMIRE,
  FULL_CODE
ORDER BY
  FULL_CODE
)