INSERT INTO TABLE_OUT 
(
  PERIOADA,
  FORM,
  FORM_VERS,
  ID_MDTABLE,
  COD_CUATM,
  NR_SECTIE,
  NUME_SECTIE,
  NR_SECTIE1,
  NUME_SECTIE1,
  NR_SECTIE2,
  NUME_SECTIE2,
  NR_ROW,
  ORDINE,
  DECIMAL_POS,
  NUME_ROW,
  
  COL1, COL2, COL3,  COL4, COL5, COL6, COL7, COL8, COL9, COL10, COL11, COL12, COL13


)
----------------------------------------------------------------
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
  
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   CAEM2 AS NR_ROW,
   ROWNUM AS ORDINE,
  '0111111111100' AS DECIMAL_POS,
   DENUMIRE AS NUME_ROW,  
    ROUND(COL1,0) AS COL1,
    ROUND(COL2,1) AS COL2,
    ROUND(COL3,1) AS COL3,
    ROUND(COL4,1) AS COL4,
    ROUND(COL5,1) AS COL5,
    ROUND(COL6,1) AS COL6,
    ROUND(COL7,1) AS COL7,
    ROUND(COL8,1) AS COL8,
    ROUND(COL9,1) AS COL9,
    ROUND(COL10,1) AS COL10,
    ROUND(COL11,1) AS COL11,
    ROUND(COL12,0) AS COL12,
    ROUND(COL13,0) AS COL13
    

FROM
(SELECT 
  CR.CODUL AS CAEM2,
  CR.DENUMIRE,
  SUM(CASE WHEN COL=1 THEN VAL ELSE NULL END) COL1,
  SUM(NVAL(CASE WHEN COL=3 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=5 THEN VAL ELSE NULL END)) COL2,
  SUM(CASE WHEN COL=3 THEN VAL ELSE NULL END) COL3,
  SUM(CASE WHEN COL=4 THEN VAL ELSE NULL END) COL4,
  SUM(CASE WHEN COL=5 THEN VAL ELSE NULL END) COL5,
  SUM(NVAL(CASE WHEN COL=6 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=7 THEN VAL ELSE NULL END)) COL6,
  SUM(CASE WHEN COL=6 THEN VAL ELSE NULL END) COL7,
  SUM(CASE WHEN COL=7 THEN VAL ELSE NULL END) COL8,
  SUM(NVAL(CASE WHEN COL=8 THEN VAL ELSE NULL END)+NVAL(CASE WHEN COL=9 THEN VAL ELSE NULL END)) COL9,
  SUM(CASE WHEN COL=8 THEN VAL ELSE NULL END) COL10,
  SUM(CASE WHEN COL=9 THEN VAL ELSE NULL END) COL11,
  SUM(CASE WHEN COL=10 THEN VAL ELSE NULL END) COL12,
  SUM(CASE WHEN RIND='01' AND VAL='1' THEN VAL ELSE NULL END) COL13
  

FROM
(
-------------------------------------------------------------------------------
SELECT DISTINCT
  D.CUIIO,
  D.FILIAL,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.CUATM_FULL,
  D.CFP,
  C.COL-1 AS COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END AS RIND, 
  MAX(CASE WHEN D.RIND LIKE '00%' THEN 0 WHEN D.RIND LIKE '01%' THEN TO_NUMBER(SUBSTR(D.CAEM2,2,5)) ELSE D.COL1 END) AS CAEM2,
  SUM(CASE WHEN D.RIND LIKE '%'||S.SEX THEN DECODE(C.COL, 1,D.COL1, 2,D.COL2, 3,D.COL3, 4,D.COL4, 5,D.COL5, 6,D.COL6, 7,D.COL7, 8,D.COL8, 9,D.COL9, 10,D.COL10, 11,D.COL11, NULL) ELSE NULL END) AS VAL
FROM 
  VW_DATA_ALL_COEF D,
  (
    SELECT  2 AS COL FROM DUAL UNION
    SELECT  3 AS COL FROM DUAL UNION
    SELECT  4 AS COL FROM DUAL UNION
    SELECT  5 AS COL FROM DUAL UNION
    SELECT  6 AS COL FROM DUAL UNION
    SELECT  7 AS COL FROM DUAL UNION
    SELECT  8 AS COL FROM DUAL UNION
    SELECT  9 AS COL FROM DUAL UNION
    SELECT 10 AS COL FROM DUAL UNION
    SELECT 11 AS COL FROM DUAL
  ) C,
  (
    SELECT 'T' AS SEX FROM DUAL UNION
    SELECT 'F' AS SEX FROM DUAL
  ) S
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(301)
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CUATM_FULL,
  D.CFP,
  D.CAPITOL,
  D.CAPITOL_DEN,
  C.COL,
  CASE WHEN D.RIND LIKE '%T' AND S.SEX LIKE 'F' THEN SUBSTR(D.RIND,1,3)||'F' ELSE D.RIND END
  
UNION
    
   
SELECT DISTINCT
    D.CUIIO,
    D.FILIAL,
    D.CAPITOL,
    D.CAPITOL_DEN,
    D.CUATM_FULL,
    D.CFP,
    NULL AS COL,
    D.RIND AS RIND,
    TO_NUMBER(SUBSTR(D.CAEM2,2,5)) AS CAEM2,
    SUM(DECODE(D.RIND, 1,D.COL1, 2,D.COL1, 3,D.COL1, 4,D.COL1, NULL)) AS VAL
FROM
    VW_DATA_ALL_COEF D
WHERE
  (D.PERIOADA=:pPERIOADA) AND
  (:pFORM_VERS=:pFORM_VERS) AND
  (:pID_MDTABLE=:pID_MDTABLE) AND
  
  D.FORM = 3 AND
  D.CAPITOL IN(302,100) AND
  D.RIND IN ('1','2','3','4','01')
GROUP BY
  D.CUIIO,
  D.FILIAL,
  D.CUATM_FULL,
  D.CFP,
  D.CAEM2,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.RIND
-------------------------------------------------------------------------------
) D 
  INNER JOIN VW_CL_CAEM2 C  ON(D.CAEM2=C.NUM_CODE)
  INNER JOIN VW_CL_CAEM2 CR ON(C.FULL_CODE LIKE '%'||CR.CODUL||';%') 
WHERE 
  D.CAEM2 <> '0' AND FILIAL = '0' AND (RIND LIKE '%T' OR RIND IN ('1','2','3','4','01'))  AND D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  (CR.CODUL LIKE '%00' OR (SUBSTR(C.CODUL,1,3) IN('C11') OR (SUBSTR(C.CODUL,1,3) IN('A01','C10','O84','P85','Q86') AND CR.CODUL LIKE '%0'))) AND CFP  IN ('28','29')
GROUP BY
  CR.DENUMIRE,
  CR.CODUL
ORDER BY
  CR.CODUL
)