--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,
--  
--  COL1, COL2, COL3, COL4, COL5, COL6, COL7, COL8
--)

-------------------------------------------------------------------------------
SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  DECODE (R.NR_ROW,'01','0','1') AS NR_SECTIE2,
  DECODE (R.NR_ROW,'02','din care:','0') as NUME_SECTIE2,
  
  R.NR_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
  '11111111' AS DECIMAL_POS,
  
  R.NUME_ROW AS NUME_ROW,
  
  DECODE(
        R.NR_ROW,
        '01',SUM(CASE WHEN D.RIND IN ('100') THEN D.COL1 END),
        '02',SUM(CASE WHEN D.RIND IN ('200') THEN D.COL1 END),
        '03',SUM(CASE WHEN D.RIND IN ('240') THEN D.COL1 END),
        '04',SUM(CASE WHEN D.RIND IN ('300') THEN D.COL1 END),
        '05',SUM(CASE WHEN D.RIND IN ('400') THEN D.COL1 END),
        '06',SUM(CASE WHEN D.RIND IN ('500') THEN D.COL1 END)
        ) AS COL1,
  
  DECODE(
        R.NR_ROW,
        '01',100*SUM(CASE WHEN D.RIND IN ('100') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('100') THEN D.COL2 END)),
        '02',100*SUM(CASE WHEN D.RIND IN ('200') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('200') THEN D.COL2 END)),
        '03',100*SUM(CASE WHEN D.RIND IN ('240') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('240') THEN D.COL2 END)),
        '04',100*SUM(CASE WHEN D.RIND IN ('300') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('300') THEN D.COL2 END)),
        '05',100*SUM(CASE WHEN D.RIND IN ('400') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('400') THEN D.COL2 END)),
        '06',100*SUM(CASE WHEN D.RIND IN ('500') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('500') THEN D.COL2 END))
        ) AS COL2,
        
  DECODE(
        R.NR_ROW,
        '01',SUM(CASE WHEN D.RIND IN ('210','310','410') THEN D.COL1 END),
        '02',SUM(CASE WHEN D.RIND IN ('210') THEN D.COL1 END),
        '03',NULL,
        '04',SUM(CASE WHEN D.RIND IN ('310') THEN D.COL1 END),
        '05',SUM(CASE WHEN D.RIND IN ('410') THEN D.COL1 END),
        '06',NULL
        ) AS COL3,
        
  DECODE(
        R.NR_ROW,
        '01',100*SUM(CASE WHEN D.RIND IN ('210','310','410') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('210','310','410') THEN D.COL2 END)),
        '02',100*SUM(CASE WHEN D.RIND IN ('210') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('210') THEN D.COL2 END)),
        '03',NULL,
        '04',100*SUM(CASE WHEN D.RIND IN ('310') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('310') THEN D.COL2 END)),
        '05',100*SUM(CASE WHEN D.RIND IN ('410') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('410') THEN D.COL2 END)),
        '06',NULL
        ) AS COL4,    
  
  DECODE(
        R.NR_ROW,
        '01',SUM(CASE WHEN D.RIND IN ('220','320','420') THEN D.COL1 END),
        '02',SUM(CASE WHEN D.RIND IN ('220') THEN D.COL1 END),
        '03',NULL,
        '04',SUM(CASE WHEN D.RIND IN ('320') THEN D.COL1 END),
        '05',SUM(CASE WHEN D.RIND IN ('420') THEN D.COL1 END),
        '06',NULL
        ) AS COL5,
        
  DECODE(
        R.NR_ROW,
        '01',100*SUM(CASE WHEN D.RIND IN ('220','320','420') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('220','320','420') THEN D.COL2 END)),
        '02',100*SUM(CASE WHEN D.RIND IN ('220') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('220') THEN D.COL2 END)),
        '03',NULL,
        '04',100*SUM(CASE WHEN D.RIND IN ('320') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('320') THEN D.COL2 END)),
        '05',100*SUM(CASE WHEN D.RIND IN ('420') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('420') THEN D.COL2 END)),
        '06',NULL
        ) AS COL6,    
        
   DECODE(
        R.NR_ROW,
        '01',SUM(CASE WHEN D.RIND IN ('230','330','430') THEN D.COL1 END),
        '02',SUM(CASE WHEN D.RIND IN ('230') THEN D.COL1 END),
        '03',NULL,
        '04',SUM(CASE WHEN D.RIND IN ('330') THEN D.COL1 END),
        '05',SUM(CASE WHEN D.RIND IN ('430') THEN D.COL1 END),
        '06',NULL
        ) AS COL7,
        
  DECODE(
        R.NR_ROW,
        '01',100*SUM(CASE WHEN D.RIND IN ('230','330','430') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('230','330','430') THEN D.COL2 END)),
        '02',100*SUM(CASE WHEN D.RIND IN ('230') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('230') THEN D.COL2 END)),
        '03',NULL,
        '04',100*SUM(CASE WHEN D.RIND IN ('330') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('330') THEN D.COL2 END)),
        '05',100*SUM(CASE WHEN D.RIND IN ('430') THEN D.COL1 END)/NOZERO(SUM(CASE WHEN D.RIND IN ('430') THEN D.COL2 END)),
        '06',NULL
        ) AS COL8              
                                                                    
                      
FROM 
    --VW_DATA_ALL_COEF D
    VW_DATA_ALL D
  INNER JOIN RENIM RN ON (D.CUIIO = RN.CUIIO AND D.CUIIO_VERS = RN.CUIIO_VERS)
  INNER JOIN VW_CL_CUATM CC ON(RN.CUATM = CC.CODUL)
  CROSS JOIN
  ( 
    SELECT 'Total'                                                   AS NUME_ROW, '01' AS NR_ROW FROM DUAL UNION
    SELECT 'Valoarea lucrarilor de constructii noi'                  AS NUME_ROW, '02' AS NR_ROW FROM DUAL UNION
    SELECT 'din care executate pentru populatie'                     AS NUME_ROW, '03' AS NR_ROW FROM DUAL UNION
    SELECT 'Valoarea lucrarilor de reparatii capitale'               AS NUME_ROW, '04' AS NR_ROW FROM DUAL UNION
    SELECT 'Valoarea lucrarilor de intretineri si reparatii curente' AS NUME_ROW, '05' AS NR_ROW FROM DUAL UNION
    SELECT 'Alte lucrari'                                            AS NUME_ROW, '06' AS NR_ROW FROM DUAL
  ) R

WHERE
  D.FORM IN (2)              AND --CONS TS
  D.FORM_VERS = :PFORM_VERS  AND    
  D.CAPITOL IN (6)           AND --CAP VLC   
  D.PERIOADA BETWEEN FLOOR(:pPERIOADA/12)*12 AND :pPERIOADA AND
  --D.PERIOADA =:pPERIOADA AND
  CC.FULL_CODE LIKE '%'||:pCOD_CUATM||';%'
  
GROUP BY
  R.NR_ROW, R.NUME_ROW