--INSERT INTO CIS2.TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,   
--  COL1
--)


SELECT 
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
   '900' AS NR_ROW,
   '1'  AS ORDINE,
  '00000' AS DECIMAL_POS,
   'Timpul utilizat pentru completarea formularului, minute '  AS NUME_ROW,
   SUM(COL2) AS COL1



FROM
(
SELECT

D.CUIIO,  
SUM(CASE WHEN D.CAPITOL = 1195 AND D.RIND IN ('1') THEN D.COL1 ELSE 0 END ) AS COL1,
SUM(CASE WHEN D.CAPITOL = 1206 AND D.RIND IN ('900') THEN D.COL1 ELSE 0 END ) AS COL2
      
 
 
 
  FROM
      CIS2.VW_DATA_ALL D        
    


WHERE  D.PERIOADA IN (:pPERIOADA) AND
       D.FORM = :pFORM AND
       D.FORM_VERS = :pFORM_VERS  AND  
      (:pID_MDTABLE=:pID_MDTABLE) AND
       D.FORM = 71 AND
--       D.CAPITOL IN (1206) AND
       D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%'
  
      
GROUP BY  
D.CUIIO


HAVING 
SUM(CASE WHEN D.CAPITOL = 1195 AND D.RIND IN ('1') THEN D.COL1 ELSE 0 END ) = 1 
)