SELECT 
                DISTINCT D.CUIIO,
                MAX(D.DATA_REG)  DATA_REG


                FROM USER_EREPORTING.VW_DATA_ALL_PRIMIT D

                WHERE    
                D.FORM IN  (7)

AND D.PERIOADA = 464
AND ID_SCHEMA = 1
GROUP BY 
D.CUIIO

ORDER BY 
DATA_REG DESC