







SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  '0' AS NR_SECTIE,
  '0' AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NUME_ROW||'~'||NR_ROW,
  ORDINE,
  '02002' AS DECIMAL_POS,
  NR_ROW,
  COL1,
  COL1/NOZERO(NUME_ROW) AS COL2,
  COL3,
  COL4,
  COL4/NOZERO(COL3) AS COL5
FROM
(
SELECT 
  
  RN.CUIIO||'-'||RN.DENUMIRE AS NR_ROW,
  TO_NUMBER(RN.CUIIO) AS ORDINE,
  SUM(CASE WHEN D.RIND IN ('36') THEN D.COL1 END) AS NUME_ROW,
  SUM(CASE WHEN D.RIND IN ('36') THEN D.COL2 END) AS COL1,
  SUM(CASE WHEN D.RIND IN ('36') THEN D.COL4 END) AS COL3,
  SUM(CASE WHEN D.RIND IN ('36') THEN D.COL5 END) AS COL4
FROM 
  VW_DATA_ALL D
  INNER JOIN RENIM RN ON (D.CUIIO = RN.CUIIO AND D.CUIIO_VERS = RN.CUIIO_VERS)
WHERE
  D.FORM IN (26)                 AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  D.CAPITOL IN (367)            AND 
  D.PERIOADA=:pPERIOADA AND 
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY 
  RN.CUIIO,
  RN.DENUMIRE )



                    