--INSERT INTO TABLE_OUT 
--(
--  PERIOADA,
--  FORM,
--  FORM_VERS,
--  ID_MDTABLE,
--  COD_CUATM,
--  NR_SECTIE,
--  NUME_SECTIE,
--  NR_SECTIE1,
--  NUME_SECTIE1,
--  NR_SECTIE2,
--  NUME_SECTIE2,
--  NR_ROW,
--  ORDINE,
--  DECIMAL_POS,
--  NUME_ROW,  
-- COL1,COL2,COL3,COL4,COL5
--)
SELECT
  :pPERIOADA AS PERIOADA,
  :pFORM AS FORM,
  :pFORM_VERS AS FORM_VERS,
  :pID_MDTABLE AS ID_MDTABLE,
  :pCOD_CUATM AS COD_CUATM,
         
  TO_NUMBER(ORDINE_SECTIE) AS NR_SECTIE,
  NUME_SECTIE AS NUME_SECTIE,
  '0' AS NR_SECTIE1,
  '0' AS NUME_SECTIE1,
  '0' AS NR_SECTIE2,
  '0' AS NUME_SECTIE2,
  NR_ROW||'~'||NUME_ROW,
  ORDINE,
  '02002' AS DECIMAL_POS,
  NUME_ROW,
  COL1,
  COL1/NOZERO(NR_ROW) AS COL2,
  COL3,
  COL4,
  COL4/NOZERO(COL3) AS COL5
FROM
(
SELECT
  TR.NR_ROW AS NR_SECTIE,
  TR.NUME_ROW AS NUME_SECTIE,
  TR.ORDINE AS ORDINE_SECTIE,
  R.NUME_ROW AS NUME_ROW,
  TO_NUMBER(R.NR_ROW) AS ORDINE,
  SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND TR.NR_ROW LIKE '%'|| D.RIND ||'%' AND TR.LENGTH_ROW=LENGTH(D.RIND) THEN D.COL1 END) AS NR_ROW,
  SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND TR.NR_ROW LIKE '%'|| D.RIND ||'%' AND TR.LENGTH_ROW=LENGTH(D.RIND) THEN D.COL2 END) AS COL1,
  SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND TR.NR_ROW LIKE '%'|| D.RIND ||'%' AND TR.LENGTH_ROW=LENGTH(D.RIND) THEN D.COL4 END) AS COL3,
  SUM(CASE WHEN CC.FULL_CODE LIKE '%'||R.CS_CUATM||'%' AND TR.NR_ROW LIKE '%'|| D.RIND ||'%' AND TR.LENGTH_ROW=LENGTH(D.RIND) THEN D.COL5 END) AS COL4
FROM 
  VW_DATA_ALL D
  INNER JOIN MD_RIND MR ON (D.RIND=MR.RIND AND D.RIND_VERS=MR.RIND_VERS AND D.CAPITOL=MR.CAPITOL AND D.CAPITOL_VERS=MR.CAPITOL_VERS AND D.FORM=MR.FORM)
  INNER JOIN VW_CL_CUATM CC ON(D.CUATM = CC.CODUL)
  CROSS JOIN 
  (
    SELECT
      DECODE(CS.CODUL, 
      '0000000','01','0100000','02','1111111','03','0300000','04',
      '1400000','05','3400000','06','3600000','07','4100000','08','4300000','09',
      '4500000','10','4800000','11','6200000','12','7100000','13','7400000','14',
      '7800000','15','2222222','16','1000000','17','2500000','18','3100000','19',
      '3800000','20','5300000','21','5500000','22','6000000','23','6400000','24',
      '6700000','25','8000000','26','8300000','27','8900000','28','9200000','29',
      '3333333','30','1200000','31','1700000','32','2100000','33','2700000','34',
      '2900000','35','5700000','36','8500000','37','8700000','38','9600000','39')
      AS NR_ROW,
      CS.DENUMIRE AS NUME_ROW,
      CS.CODUL AS CS_CUATM
    FROM
      VW_CL_CUATM CS
    WHERE
      CS.CODUL 
      IN(
         '0000000','0100000','1111111','0300000','1400000','3400000','3600000','4100000','4300000','4500000',
         '4800000','6200000','7100000','7400000','7800000','2222222','1000000','2500000','3100000','3800000',
         '5300000','5500000','6000000','6400000','6700000','8000000','8300000','8900000','9200000','3333333',
         '1200000','1700000','2100000','2700000','2900000','5700000','8500000','8700000','9600000'
        )
  ) R 
  CROSS JOIN 
  (
SELECT '11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26' AS NR_ROW,'Culturi cereale si leguminoase boabe - total' AS NUME_ROW, 2 AS LENGTH_ROW, 1 AS ORDINE FROM DUAL UNION
SELECT '11+12' AS NR_ROW, 'Griu - total' AS NUME_ROW, 2 AS LENGTH_ROW, 2 AS ORDINE FROM DUAL UNION
SELECT '11' AS NR_ROW, 'Griu exclusiv seminte de soi' AS NUME_ROW, 2 AS LENGTH_ROW, 3 AS ORDINE FROM DUAL UNION
SELECT '12' AS NR_ROW, 'Seminte de soi de griu' AS NUME_ROW, 2 AS LENGTH_ROW, 4 AS ORDINE FROM DUAL UNION
SELECT '13' AS NR_ROW, 'Secara' AS NUME_ROW, 2 AS LENGTH_ROW, 5 AS ORDINE FROM DUAL UNION
SELECT '14' AS NR_ROW, 'Orz' AS NUME_ROW, 2 AS LENGTH_ROW, 6 AS ORDINE FROM DUAL UNION
SELECT '15' AS NR_ROW, 'Ovaz' AS NUME_ROW, 2 AS LENGTH_ROW, 7 AS ORDINE FROM DUAL UNION
SELECT '16' AS NR_ROW, 'Mei' AS NUME_ROW, 2 AS LENGTH_ROW, 8 AS ORDINE FROM DUAL UNION
SELECT '17' AS NR_ROW, 'Hrisca' AS NUME_ROW, 2 AS LENGTH_ROW, 9 AS ORDINE FROM DUAL UNION
SELECT '18+19+20+21+22' AS NR_ROW, 'Leguminoase boabe - total' AS NUME_ROW, 2 AS LENGTH_ROW, 10 AS ORDINE FROM DUAL UNION
SELECT '18' AS NR_ROW, 'Mazare (boabe uscate)' AS NUME_ROW, 2 AS LENGTH_ROW, 11 AS ORDINE FROM DUAL UNION
SELECT '19' AS NR_ROW, 'Fasole' AS NUME_ROW, 2 AS LENGTH_ROW, 12 AS ORDINE FROM DUAL UNION
SELECT '20' AS NR_ROW, 'Linte' AS NUME_ROW, 2 AS LENGTH_ROW, 13 AS ORDINE FROM DUAL UNION
SELECT '21' AS NR_ROW, 'Mazariche si borceag de mazariche(cu predominarea mazarichii) pentru boabe' AS NUME_ROW, 2 AS LENGTH_ROW, 14 AS ORDINE FROM DUAL UNION
SELECT '22' AS NR_ROW, 'Alte leguminoase pentru boabe' AS NUME_ROW, 2 AS LENGTH_ROW, 15 AS ORDINE FROM DUAL UNION
SELECT '23+24' AS NR_ROW, 'Porumb - total' AS NUME_ROW, 2 AS LENGTH_ROW, 16 AS ORDINE FROM DUAL UNION
SELECT '23' AS NR_ROW, 'Porumb (exclusiv seminte de soi)' AS NUME_ROW, 2 AS LENGTH_ROW, 17 AS ORDINE FROM DUAL UNION
SELECT '24' AS NR_ROW, 'Seminte de soi de porumb' AS NUME_ROW, 2 AS LENGTH_ROW, 18 AS ORDINE FROM DUAL UNION
SELECT '25' AS NR_ROW, 'Sorg pentru boabe' AS NUME_ROW, 2 AS LENGTH_ROW, 19 AS ORDINE FROM DUAL UNION
SELECT '26' AS NR_ROW, 'Alte culturi cerealiere' AS NUME_ROW, 2 AS LENGTH_ROW, 20 AS ORDINE FROM DUAL UNION
SELECT '27' AS NR_ROW, 'Sfecla de zahar ' AS NUME_ROW, 2 AS LENGTH_ROW, 21 AS ORDINE FROM DUAL UNION
SELECT '28' AS NR_ROW, 'Tutun uscat' AS NUME_ROW, 2 AS LENGTH_ROW, 22 AS ORDINE FROM DUAL UNION
SELECT '29+30' AS NR_ROW, 'Floarea soarelui -total' AS NUME_ROW, 2 AS LENGTH_ROW, 23 AS ORDINE FROM DUAL UNION
SELECT '29' AS NR_ROW, 'Floarea soarelui (exclusiv  seminte de soi)' AS NUME_ROW, 2 AS LENGTH_ROW, 24 AS ORDINE FROM DUAL UNION
SELECT '30' AS NR_ROW, 'Seminte de soi de floarea soarelui' AS NUME_ROW, 2 AS LENGTH_ROW, 25 AS ORDINE FROM DUAL UNION
SELECT '31' AS NR_ROW, 'Soia' AS NUME_ROW, 2 AS LENGTH_ROW, 26 AS ORDINE FROM DUAL UNION
SELECT '32+33' AS NR_ROW, 'Rapita - total' AS NUME_ROW, 2 AS LENGTH_ROW, 27 AS ORDINE FROM DUAL UNION
SELECT '32' AS NR_ROW, 'Rapita de toamna pentru boabe' AS NUME_ROW, 2 AS LENGTH_ROW, 28 AS ORDINE FROM DUAL UNION
SELECT '33' AS NR_ROW, 'Rapita de primavara pentru boabe ' AS NUME_ROW, 2 AS LENGTH_ROW, 29 AS ORDINE FROM DUAL UNION
SELECT '35+36+37+38+39+40' AS NR_ROW, 'Culturi etero-oleaginoase – total' AS NUME_ROW, 2 AS LENGTH_ROW, 30 AS ORDINE FROM DUAL UNION
SELECT '35' AS NR_ROW, 'Trandafir' AS NUME_ROW, 2 AS LENGTH_ROW, 31 AS ORDINE FROM DUAL UNION
SELECT '36' AS NR_ROW, 'Salvie' AS NUME_ROW, 2 AS LENGTH_ROW, 32 AS ORDINE FROM DUAL UNION
SELECT '37' AS NR_ROW, 'Levantica' AS NUME_ROW, 2 AS LENGTH_ROW, 33 AS ORDINE FROM DUAL UNION
SELECT '38' AS NR_ROW, 'Marar' AS NUME_ROW, 2 AS LENGTH_ROW, 34 AS ORDINE FROM DUAL UNION
SELECT '39' AS NR_ROW, 'Minta' AS NUME_ROW, 2 AS LENGTH_ROW, 35 AS ORDINE FROM DUAL UNION
SELECT '40' AS NR_ROW, 'Alte culturi etero-oleaginoase' AS NUME_ROW, 2 AS LENGTH_ROW, 36 AS ORDINE FROM DUAL UNION
SELECT '41' AS NR_ROW, 'Plante medicinale' AS NUME_ROW, 2 AS LENGTH_ROW, 37 AS ORDINE FROM DUAL UNION
SELECT '42' AS NR_ROW, 'Seminte de sfecla de zahar' AS NUME_ROW, 2 AS LENGTH_ROW, 38 AS ORDINE FROM DUAL UNION
SELECT '43' AS NR_ROW, 'Rasada de tutun, mii bucati' AS NUME_ROW, 2 AS LENGTH_ROW, 39 AS ORDINE FROM DUAL UNION
SELECT '44' AS NR_ROW, 'Rasada de legume, mii bucati' AS NUME_ROW, 2 AS LENGTH_ROW, 40 AS ORDINE FROM DUAL UNION
SELECT '45' AS NR_ROW, 'Alte culturi tehnice, inclusiv sorg pentru maturi' AS NUME_ROW, 2 AS LENGTH_ROW, 41 AS ORDINE FROM DUAL UNION
SELECT '47+48' AS NR_ROW, 'Material saditor (butasi), mii bucati – total' AS NUME_ROW, 2 AS LENGTH_ROW, 42 AS ORDINE FROM DUAL UNION
SELECT '47' AS NR_ROW, 'De trandafir' AS NUME_ROW, 2 AS LENGTH_ROW, 43 AS ORDINE FROM DUAL UNION
SELECT '48' AS NR_ROW, 'De levan?ica' AS NUME_ROW, 2 AS LENGTH_ROW, 44 AS ORDINE FROM DUAL UNION
SELECT '49' AS NR_ROW, 'Cartofi' AS NUME_ROW, 2 AS LENGTH_ROW, 45 AS ORDINE FROM DUAL UNION
SELECT '51+52+53+54+55+56+57+58+59+60+61+62+63+64+65' AS NR_ROW, 'Legume de cîmp – total' AS NUME_ROW, 2 AS LENGTH_ROW, 46 AS ORDINE FROM DUAL UNION
SELECT '51' AS NR_ROW, 'Varza (toate varietatile)' AS NUME_ROW, 2 AS LENGTH_ROW, 47 AS ORDINE FROM DUAL UNION
SELECT '52' AS NR_ROW, 'Castraveti' AS NUME_ROW, 2 AS LENGTH_ROW, 48 AS ORDINE FROM DUAL UNION
SELECT '53' AS NR_ROW, 'Tomate' AS NUME_ROW, 2 AS LENGTH_ROW, 49 AS ORDINE FROM DUAL UNION
SELECT '54' AS NR_ROW, 'Sfecla de masa' AS NUME_ROW, 2 AS LENGTH_ROW, 50 AS ORDINE FROM DUAL UNION
SELECT '55' AS NR_ROW, 'Morcov' AS NUME_ROW, 2 AS LENGTH_ROW, 51 AS ORDINE FROM DUAL UNION
SELECT '56' AS NR_ROW, 'Ceapa uscata' AS NUME_ROW, 2 AS LENGTH_ROW, 52 AS ORDINE FROM DUAL UNION
SELECT '57' AS NR_ROW, 'Usturoi uscat' AS NUME_ROW, 2 AS LENGTH_ROW, 53 AS ORDINE FROM DUAL UNION
SELECT '58' AS NR_ROW, 'Mazare verde' AS NUME_ROW, 2 AS LENGTH_ROW, 54 AS ORDINE FROM DUAL UNION
SELECT '59' AS NR_ROW, 'Bostani' AS NUME_ROW, 2 AS LENGTH_ROW, 55 AS ORDINE FROM DUAL UNION
SELECT '60' AS NR_ROW, 'Dovlecei' AS NUME_ROW, 2 AS LENGTH_ROW, 56 AS ORDINE FROM DUAL UNION
SELECT '61' AS NR_ROW, 'Ardei grasi' AS NUME_ROW, 2 AS LENGTH_ROW, 57 AS ORDINE FROM DUAL UNION
SELECT '62' AS NR_ROW, 'Vinete' AS NUME_ROW, 2 AS LENGTH_ROW, 58 AS ORDINE FROM DUAL UNION
SELECT '63' AS NR_ROW, 'Gogosari' AS NUME_ROW, 2 AS LENGTH_ROW, 59 AS ORDINE FROM DUAL UNION
SELECT '64' AS NR_ROW, 'Verzaturi' AS NUME_ROW, 2 AS LENGTH_ROW, 60 AS ORDINE FROM DUAL UNION
SELECT '65' AS NR_ROW, 'Alte legume' AS NUME_ROW, 2 AS LENGTH_ROW, 61 AS ORDINE FROM DUAL UNION
SELECT '67+68+69' AS NR_ROW, 'Legume de pe teren acoperit – total' AS NUME_ROW, 2 AS LENGTH_ROW, 62 AS ORDINE FROM DUAL UNION
SELECT '67' AS NR_ROW, 'Tomate' AS NUME_ROW, 2 AS LENGTH_ROW, 63 AS ORDINE FROM DUAL UNION
SELECT '68' AS NR_ROW, 'Castraveti' AS NUME_ROW, 2 AS LENGTH_ROW, 64 AS ORDINE FROM DUAL UNION
SELECT '69' AS NR_ROW, 'Alte legume' AS NUME_ROW, 2 AS LENGTH_ROW, 65 AS ORDINE FROM DUAL UNION
SELECT '71+72' AS NR_ROW, 'Culturi bostanoase alimentare – total' AS NUME_ROW, 2 AS LENGTH_ROW, 66 AS ORDINE FROM DUAL UNION
SELECT '71' AS NR_ROW, 'Pepeni verzi' AS NUME_ROW, 2 AS LENGTH_ROW, 67 AS ORDINE FROM DUAL UNION
SELECT '72' AS NR_ROW, 'Pepeni galbeni' AS NUME_ROW, 2 AS LENGTH_ROW, 68 AS ORDINE FROM DUAL UNION
SELECT '73' AS NR_ROW, 'Seminte de culturi bostanoase' AS NUME_ROW, 2 AS LENGTH_ROW, 69 AS ORDINE FROM DUAL UNION
SELECT '74' AS NR_ROW, 'Seminte de culturi legumicole' AS NUME_ROW, 2 AS LENGTH_ROW, 70 AS ORDINE FROM DUAL UNION
SELECT '75' AS NR_ROW, 'Seminte de mazare verde' AS NUME_ROW, 2 AS LENGTH_ROW, 71 AS ORDINE FROM DUAL UNION
SELECT '130' AS NR_ROW, 'Seminte de ierburi de un an' AS NUME_ROW, 3 AS LENGTH_ROW, 72 AS ORDINE FROM DUAL UNION
SELECT '131' AS NR_ROW, 'Seminte de ierburi perene' AS NUME_ROW, 3 AS LENGTH_ROW, 73 AS ORDINE FROM DUAL UNION
SELECT '76' AS NR_ROW, 'Ceapa - arpagic' AS NUME_ROW, 2 AS LENGTH_ROW, 74 AS ORDINE FROM DUAL UNION
SELECT '77+78+79+80+81+82+83+84+85' AS NR_ROW, 'Plantele de nutret - total' AS NUME_ROW, 2 AS LENGTH_ROW, 75 AS ORDINE FROM DUAL UNION
SELECT '77' AS NR_ROW, 'Plante radacinoase pentru nutret' AS NUME_ROW, 2 AS LENGTH_ROW, 76 AS ORDINE FROM DUAL UNION
SELECT '78' AS NR_ROW, 'Sfecla de zahar pentru nutret' AS NUME_ROW, 2 AS LENGTH_ROW, 77 AS ORDINE FROM DUAL UNION
SELECT '79' AS NR_ROW, 'Culturi pentru siloz' AS NUME_ROW, 2 AS LENGTH_ROW, 78 AS ORDINE FROM DUAL UNION
SELECT '80' AS NR_ROW, 'Porumb pentru siloz, masa verde' AS NUME_ROW, 2 AS LENGTH_ROW, 79 AS ORDINE FROM DUAL UNION
SELECT '81' AS NR_ROW, 'Fin' AS NUME_ROW, 2 AS LENGTH_ROW, 80 AS ORDINE FROM DUAL UNION
SELECT '82' AS NR_ROW, 'Masa verde din ierburi' AS NUME_ROW, 2 AS LENGTH_ROW, 81 AS ORDINE FROM DUAL UNION
SELECT '83' AS NR_ROW, 'Alte plante de nutre? ' AS NUME_ROW, 2 AS LENGTH_ROW, 82 AS ORDINE FROM DUAL UNION
SELECT '84' AS NR_ROW, 'Paie' AS NUME_ROW, 2 AS LENGTH_ROW, 83 AS ORDINE FROM DUAL UNION
SELECT '85' AS NR_ROW, 'Tulpini de porumb' AS NUME_ROW, 2 AS LENGTH_ROW, 84 AS ORDINE FROM DUAL UNION
SELECT '87+94+99' AS NR_ROW, 'Fructe si pomu?oare de cultura – total' AS NUME_ROW, 2 AS LENGTH_ROW, 85 AS ORDINE FROM DUAL UNION
SELECT '88+89+90+91+92+93' AS NR_ROW, 'Fructe sîmburoase - total' AS NUME_ROW, 2 AS LENGTH_ROW, 86 AS ORDINE FROM DUAL UNION
SELECT '88' AS NR_ROW, 'Prune' AS NUME_ROW, 2 AS LENGTH_ROW, 87 AS ORDINE FROM DUAL UNION
SELECT '89' AS NR_ROW, 'Visine' AS NUME_ROW, 2 AS LENGTH_ROW, 88 AS ORDINE FROM DUAL UNION
SELECT '90' AS NR_ROW, 'Cirese' AS NUME_ROW, 2 AS LENGTH_ROW, 89 AS ORDINE FROM DUAL UNION
SELECT '91' AS NR_ROW, 'Caise' AS NUME_ROW, 2 AS LENGTH_ROW, 90 AS ORDINE FROM DUAL UNION
SELECT '92' AS NR_ROW, 'Piersici' AS NUME_ROW, 2 AS LENGTH_ROW, 91 AS ORDINE FROM DUAL UNION
SELECT '93' AS NR_ROW, 'Alte' AS NUME_ROW, 2 AS LENGTH_ROW, 92 AS ORDINE FROM DUAL UNION
SELECT '95+96+97+98' AS NR_ROW, 'Fructe samintoase – total ' AS NUME_ROW, 2 AS LENGTH_ROW, 93 AS ORDINE FROM DUAL UNION
SELECT '95' AS NR_ROW, 'Mere' AS NUME_ROW, 2 AS LENGTH_ROW, 94 AS ORDINE FROM DUAL UNION
SELECT '96' AS NR_ROW, 'Pere' AS NUME_ROW, 2 AS LENGTH_ROW, 95 AS ORDINE FROM DUAL UNION
SELECT '97' AS NR_ROW, 'Gutui' AS NUME_ROW, 2 AS LENGTH_ROW, 96 AS ORDINE FROM DUAL UNION
SELECT '98' AS NR_ROW, 'Alte' AS NUME_ROW, 2 AS LENGTH_ROW, 97 AS ORDINE FROM DUAL UNION
SELECT '132+133+134' AS NR_ROW, 'Pomusoare de cultura – total' AS NUME_ROW, 3 AS LENGTH_ROW, 98 AS ORDINE FROM DUAL UNION
SELECT '132' AS NR_ROW, 'Zmeura, mure' AS NUME_ROW, 3 AS LENGTH_ROW, 99 AS ORDINE FROM DUAL UNION
SELECT '133' AS NR_ROW, 'Capsuna' AS NUME_ROW, 3 AS LENGTH_ROW, 990 AS ORDINE FROM DUAL UNION
SELECT '134' AS NR_ROW, 'Alte' AS NUME_ROW, 3 AS LENGTH_ROW, 9901 AS ORDINE FROM DUAL UNION
SELECT '101+102' AS NR_ROW, 'Struguri – total' AS NUME_ROW, 3 AS LENGTH_ROW, 9902 AS ORDINE FROM DUAL UNION
SELECT '101' AS NR_ROW, 'De soiuri de masa' AS NUME_ROW, 3 AS LENGTH_ROW, 9903 AS ORDINE FROM DUAL UNION
SELECT '102' AS NR_ROW, 'De soiuri tehnice' AS NUME_ROW, 3 AS LENGTH_ROW, 9904 AS ORDINE FROM DUAL UNION
SELECT '104+105+106+107+108' AS NR_ROW, 'Material saditor pentru livezi, vii si arbusti fructiferi, mii bucati:' AS NUME_ROW, 3 AS LENGTH_ROW, 9905 AS ORDINE FROM DUAL UNION
SELECT '104' AS NR_ROW, 'Pomi fructiferi' AS NUME_ROW, 3 AS LENGTH_ROW, 9906 AS ORDINE FROM DUAL UNION
SELECT '105' AS NR_ROW, 'Butasi de vita de vie' AS NUME_ROW, 3 AS LENGTH_ROW, 9907 AS ORDINE FROM DUAL UNION
SELECT '106' AS NR_ROW, 'Butasi de arbusti fructiferi' AS NUME_ROW, 3 AS LENGTH_ROW, 9908 AS ORDINE FROM DUAL UNION
SELECT '107' AS NR_ROW, 'Butasi portaltoi' AS NUME_ROW, 3 AS LENGTH_ROW, 9909 AS ORDINE FROM DUAL UNION
SELECT '108' AS NR_ROW, 'Butasi altoi' AS NUME_ROW, 3 AS LENGTH_ROW, 9910 AS ORDINE FROM DUAL UNION
SELECT '109' AS NR_ROW, 'Flori, mii bucati' AS NUME_ROW, 3 AS LENGTH_ROW, 9911 AS ORDINE FROM DUAL UNION
SELECT '110' AS NR_ROW, 'Nuci uscate in coaja' AS NUME_ROW, 3 AS LENGTH_ROW, 9912 AS ORDINE FROM DUAL UNION
SELECT '135' AS NR_ROW, 'Ciuperci' AS NUME_ROW, 3 AS LENGTH_ROW, 9913 AS ORDINE FROM DUAL UNION
SELECT '112+113+114+115+116' AS NR_ROW, 'Vite si pasari (in masa vie) – total' AS NUME_ROW, 3 AS LENGTH_ROW, 9914 AS ORDINE FROM DUAL UNION
SELECT '112' AS NR_ROW, 'Bovine' AS NUME_ROW, 3 AS LENGTH_ROW, 9915 AS ORDINE FROM DUAL UNION
SELECT '113' AS NR_ROW, 'Porcine' AS NUME_ROW, 3 AS LENGTH_ROW, 9916 AS ORDINE FROM DUAL UNION
SELECT '114' AS NR_ROW, 'Ovine si caprine' AS NUME_ROW, 3 AS LENGTH_ROW, 9917 AS ORDINE FROM DUAL UNION
SELECT '115' AS NR_ROW, 'Pasari' AS NUME_ROW, 3 AS LENGTH_ROW, 9918 AS ORDINE FROM DUAL UNION
SELECT '116' AS NR_ROW, 'Alte specii de animale' AS NUME_ROW, 3 AS LENGTH_ROW, 9919 AS ORDINE FROM DUAL UNION
SELECT '118+119' AS NR_ROW, 'Lapte (in echivalent lapte cu un continut de grasime stabilit)' AS NUME_ROW, 3 AS LENGTH_ROW, 9920 AS ORDINE FROM DUAL UNION
SELECT '118' AS NR_ROW, 'Lapte de vaca' AS NUME_ROW, 3 AS LENGTH_ROW, 9921 AS ORDINE FROM DUAL UNION
SELECT '119' AS NR_ROW, 'Lapte de oaie' AS NUME_ROW, 3 AS LENGTH_ROW, 9922 AS ORDINE FROM DUAL UNION
SELECT '121+122' AS NR_ROW, 'Oua-total, mii bucati' AS NUME_ROW, 3 AS LENGTH_ROW, 9923 AS ORDINE FROM DUAL UNION
SELECT '121' AS NR_ROW, 'Alimentare' AS NUME_ROW, 3 AS LENGTH_ROW, 9924 AS ORDINE FROM DUAL UNION
SELECT '122' AS NR_ROW, 'Pentru incubatie' AS NUME_ROW, 3 AS LENGTH_ROW, 9925 AS ORDINE FROM DUAL UNION
SELECT '123' AS NR_ROW, 'Lina (in masa fizica)' AS NUME_ROW, 3 AS LENGTH_ROW, 9926 AS ORDINE FROM DUAL UNION
SELECT '124' AS NR_ROW, 'Caracul si pielicele, bucati' AS NUME_ROW, 3 AS LENGTH_ROW, 9927 AS ORDINE FROM DUAL UNION
SELECT '125' AS NR_ROW, 'Miere de albine' AS NUME_ROW, 3 AS LENGTH_ROW, 9928 AS ORDINE FROM DUAL
  ) TR --ON (D.RIND LIKE '%'|| TR.NR_ROW ||'%')
WHERE
  D.FORM IN (26)                 AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  D.CAPITOL IN (367,368)            AND 
  D.PERIOADA=:pPERIOADA AND 
  CC.FULL_CODE LIKE '%'||:pCOD_CUATM||';%' 
GROUP BY 
  TR.NR_ROW,
  TR.NUME_ROW,
  TR.ORDINE,
  R.NR_ROW, 
  R.NUME_ROW, 
  R.CS_CUATM
ORDER BY
  TR.ORDINE
)