SELECT 

L.CUIIO,
L.DENUMIRE,
RR.PACHET,
L.ITEM_CODE, 
L.NAME,
SUM(L.COL1) AS COL1,
SUM(R.COL1) AS COL2,
SUM(L.COL1) - SUM(R.COL1) AS COL3

FROM 

(
SELECT
   D.CUIIO,
   R.DENUMIRE,
   MAX(D.PACHET) PACHET,
   CI.ITEM_CODE, 
   CI.NAME,
  SUM(CASE WHEN  D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1
 


FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))

WHERE 
  (D.PERIOADA IN(:pPERIOADA)) AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (44)
   AND  D.CAPITOL IN (405) 
  AND D.CUIIO = 40602223
  
GROUP BY
  D.CUIIO,
  
  R.DENUMIRE,
  CI.ITEM_CODE,
  CI.NAME ) L LEFT JOIN (
  
  
  SELECT
   D.CUIIO,
   R.DENUMIRE,
   MAX(D.PACHET) PACHET,
   CI.ITEM_CODE, 
   CI.NAME,
  SUM(CASE WHEN  D.RIND NOT IN ('1','-')  THEN NVAL(D.COL4) ELSE 0 END) AS COL1
 


FROM
  CIS2.VW_DATA_ALL D 
  INNER JOIN CIS2.RENIM R ON R.CUIIO =  D.CUIIO AND R.CUIIO_VERS =  D.CUIIO_VERS 
  INNER JOIN  CIS2.VW_CLS_CLASS_ITEM CI  ON (CI.CLASS_CODE IN ('CSPM2') AND TRIM(D.COL31)=TRIM(CI.ITEM_CODE))

WHERE 
  (D.PERIOADA IN(:pPERIOADA-1)) AND    
  (D.FORM =:pFORM) AND
  (D.FORM_VERS =:pFORM_VERS) AND 
--  (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND
   D.FORM IN (44)
   AND  D.CAPITOL IN (405) 
  AND D.CUIIO = 40602223
  
GROUP BY
  D.CUIIO,
  
  R.DENUMIRE,
  CI.ITEM_CODE,
  CI.NAME
  ) R ON R.CUIIO = L.CUIIO  AND L.ITEM_CODE = R.ITEM_CODE
  
  
  
  LEFT JOIN (
 
 
 SELECT
  DISTINCT  D.CUIIO,
                    MAX(D.PACHET) AS PACHET
                   FROM CIS2.VW_DATA_ALL D 
                                INNER JOIN MD_RIND  R ON R.ID_MD = D.ID_MD 
                    
                    WHERE 
                    D.FORM = 44
                    AND D.PERIOADA IN(:pPERIOADA)
                    AND (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') 
                   
                    
                    GROUP BY 
                    D.CUIIO
  
 ) RR ON RR.CUIIO = L.CUIIO
  
  GROUP BY
  L.CUIIO,
L.DENUMIRE,
RR.PACHET,
L.ITEM_CODE, 
L.NAME