SELECT 
            
        DISTINCT 
       -- D.PERIOADA,
        D.CUIIO,
        MAX(R.DENUMIRE) DENUMIRE,
        MAX(R.CAEM2) CAEM2,
        MAX(CASE WHEN  D.PERIOADA = 1052 THEN D.RIND ELSE NULL END)  AS COL1,
        MAX(CASE WHEN  D.PERIOADA = 1053 THEN D.RIND ELSE NULL END)  AS COL2,
        MAX(CASE WHEN  D.PERIOADA = 1054 THEN D.RIND ELSE NULL END)  AS COL3,
        MAX(CASE WHEN  D.PERIOADA = 1055 THEN D.RIND ELSE NULL END)  AS COL4,
        MAX(CASE WHEN  D.PERIOADA = 1056 THEN D.RIND ELSE NULL END)  AS COL5,
        MAX(CASE WHEN  D.PERIOADA = 1057 THEN D.RIND ELSE NULL END)  AS COL7,
        MAX(CASE WHEN  D.PERIOADA = 1058 THEN D.RIND ELSE NULL END)  AS COL8,
        MAX(CASE WHEN  D.PERIOADA = 1059 THEN D.RIND ELSE NULL END)  AS COL9,
        MAX(CASE WHEN  D.PERIOADA = 1060 THEN D.RIND ELSE NULL END)  AS COL10,
        MAX(CASE WHEN  D.PERIOADA = 1061 THEN D.RIND ELSE NULL END)  AS COL11,
        MAX(CASE WHEN  D.PERIOADA = 1062 THEN D.RIND ELSE NULL END)  AS COL12,
        MAX(CASE WHEN  D.PERIOADA = 1063 THEN D.RIND ELSE NULL END)  AS COL13
        
     
        
            FROM CIS2.VW_DATA_ALL D 
                    INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO  AND R.CUIIO_VERS = D.CUIIO_VERS
            
            WHERE
            D.FORM = 44
            AND D.ANUL IN  (2024,2023,2022)
         --   AND D.PERIOADA = 1063
            AND D.RIND NOT IN ('01','05')
            AND D.capitol=14 AND D.capitol_vers=1028
            
            
            GROUP BY
      --      D.PERIOADA,
            D.CUIIO
       -- R.DENUMIRE,
       -- R.CAEM2
        --D.RIND
        
        
        ORDER BY
        D.CUIIO
        
        ------------------------------------