SELECT

 COUNT(CIS.NVAL(D.COL1)) AS CNUM

FROM CIS.VW_DATA_ALL D
WHERE
  (D.PERIOADA=:PERIOADA         ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
 -- (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <> :CAPITOL_VERS ) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.CAPITOL IN (0,46) AND
  D.RIND IN('01','02','03','04','05','06','07','08','09','10','11','12') --AND
  
