SELECT DISTINCT
  SUM(CASE WHEN D.RIND IN('200') THEN D.COL6 ELSE 0 END)||' <> '||
  SUM(CASE WHEN D.RIND NOT IN('100','200') THEN D.COL6 ELSE 0 END)
  AS REZULTAT

FROM
  CIS.VW_DATA_ALL D   
   INNER JOIN CIS.RENIM R ON R.CUIIO=D.CUIIO AND D.CUIIO_VERS=R.CUIIO_VERS  
                                    
WHERE
  (D.PERIOADA=:PERIOADA         OR :PERIOADA = -1) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL=-1) AND
  (:FORM = :FORM) AND
  
  D.FORM    IN(3) AND     -- Forma: IND TS
  D.CAPITOL IN(94) -- Cap. PROD2
  --AND R.PROD=1
   
  
HAVING
  SUM(CASE WHEN D.RIND IN('200') THEN D.COL6 ELSE 0 END)<>
  SUM(CASE WHEN D.RIND NOT IN('100','200') THEN D.COL6 ELSE 0 END)