SELECT DISTINCT
'CUIIO: '||DD.CUIIO||'-'||TRIM(IC.IDNO)||' nu este in lista'   AS REZULTAT
FROM   
  USER_EREPORTING.DATA_ALL_FOR_VALIDATE DD   INNER JOIN  
  USER_EREPORTING.IDNO_CUIIO IC ON DD.CUIIO=IC.CUIIO
                                      
WHERE 
  (DD.PERIOADA=:PERIOADA        ) AND
  (DD.CUIIO=:CUIIO              OR :CUIIO = -1) AND
  ( :CUIIO=:CUIIO               OR :CUIIO = -1) AND
  ( :CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  ( :FORM = :FORM               OR :FORM = -1) AND
  ( :FORM_VERS=:FORM_VERS       OR :FORM_VERS = -1) AND
  ( :CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  ( :CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  ( :ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  DD.FORM =67
  GROUP BY DD.CUIIO, IC.IDNO

HAVING 

DD.CUIIO||'-'||TRIM(IC.IDNO) NOT IN (
SELECT
  DISTINCT
  R.CUIIO||'-'||TRIM(R.IDNO) AS IDENTIFICARE
  
FROM
  CIS2.RENIM R
  INNER JOIN CIS2.FORM_CUIIO FC ON (R.CUIIO=FC.CUIIO AND R.CUIIO_VERS=FC.CUIIO_VERS)
  INNER JOIN (
SELECT
  DISTINCT
      R.IDNO,
      R.CUIIO,
      MAX(R.CUIIO_VERS) AS CUIIO_VERS
    FROM
      CIS2.RENIM R
      INNER JOIN CIS2.FORM_CUIIO FC ON (R.CUIIO=FC.CUIIO AND R.CUIIO_VERS=FC.CUIIO_VERS)
    WHERE
      R.CUIIO_VERS <= :PERIOADA AND
      FC.FORM IN (:FORM)
    GROUP BY
      R.CUIIO, R.IDNO) D ON (R.IDNO=D.IDNO AND R.CUIIO=D.CUIIO AND R.CUIIO_VERS=D.CUIIO_VERS)
WHERE
  FC.FORM IN (:FORM) AND
  FC.STATUT <> '3')
  