SELECT 
D.CUIIO,
D.RIND,
SUM(D.COL5) AS COL5 
FROM

     CIS2.VW_DATA_ALL D 
      
WHERE
  (D.PERIOADA        =:PERIOADA          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (:CUIIO_VERS<>:CUIIO_VERS      OR :CUIIO_VERS=:CUIIO_VERS) AND
  (:FORM <> :FORM                OR :FORM =:FORM) AND
  (:FORM_VERS<>:FORM_VERS        OR :FORM_VERS=:FORM_VERS) AND
  (:CAPITOL <> :CAPITOL          OR :CAPITOL=:CAPITOL) AND
  (:CAPITOL_VERS<>:CAPITOL_VERS OR :CAPITOL_VERS=:CAPITOL_VERS) AND
  (:ID_MD=:ID_MD               OR :ID_MD = -1)
  AND D.FORM = 67 
  AND D.CAPITOL IN (1141)
  AND D.RIND IN ('500','560')    
 

  
  GROUP BY
  D.CUIIO, 
  D.RIND