INSERT INTO  TABLE_OUT B

    (
    B.PERIOADA,
    B.FORM,
    B.FORM_VERS,

    B.ID_MDTABLE,
    B.COD_CUATM,
    B.NR_SECTIE,
    B.NUME_SECTIE,
    B.NR_SECTIE1,
    B.NUME_SECTIE1,
    B.NR_SECTIE2,
    B.NUME_SECTIE2,
    B.NR_ROW,
    B.ORDINE,
    B.DECIMAL_POS,
    B.NUME_ROW, 
    B.COL1,
    B.COL2,
    B.COL3,
    B.COL4,
    B.COL5,
    B.COL6,
    B.COL7,
    B.COL8,
    B.COL9,
    B.COL10,
    B.COL11,
    B.COL12,
    B.COL13,
    B.COL14,
    B.COL15,
    B.COL16,
    B.COL17,
    B.COL18,
    B.COL19,
    B.COL20,
    B.COL21,
    B.COL22,
    B.COL23,
    B.COL24,
    B.COL25,
    B.COL26,
    B.COL27,
    B.COL28,
    B.COL29,
    B.COL30,
    B.COL31,
    B.COL32,
    B.COL33,
    B.COL34,
    B.COL35,
    B.COL36
    )


SELECT 

      B.PERIOADA,
      B.FORM,
      B.FORM_VERS,
      B.ID_MDTABLE,
      B.COD_CUATM,
      B.NR_SECTIE,
      B.NUME_SECTIE,
      B.NR_SECTIE1,
      B.NUME_SECTIE1,
      B.NR_SECTIE2,
      B.NUME_SECTIE2,
   L.ITEM_CODE||'~'||ROWNUM NR_ROW,
      B.ORDINE,
      B.DECIMAL_POS,
      B.NUME_ROW,   
        B.COL1,
    B.COL2,
    B.COL3,
    B.COL4,
    B.COL5,
    B.COL6,
    B.COL7,
    B.COL8,
    B.COL9,
    B.COL10,
    B.COL11,
    B.COL12,
    B.COL13,
    B.COL14,
    B.COL15,
    B.COL16,
    B.COL17,
    B.COL18,
    B.COL19,
    B.COL20,
    B.COL21,
    B.COL22,
    B.COL23,
    B.COL24,
    B.COL25,
    B.COL26,
    B.COL27,
    B.COL28,
    B.COL29,
    B.COL30,
    B.COL31,
    B.COL32,
    B.COL33,
    B.COL34,
    B.COL35,
    B.COL36
    

FROM 



(
SELECT
    :pPERIOADA AS PERIOADA,
    :pFORM AS FORM,
    :pFORM_VERS AS FORM_VERS,
    :pID_MDTABLE AS ID_MDTABLE,
    :pCOD_CUATM AS COD_CUATM,
    '0'  AS  NR_SECTIE,
    '0'  AS NUME_SECTIE, 
    '0' AS NR_SECTIE1,
    '0' AS NUME_SECTIE1,
    '0' AS NR_SECTIE2,
    '0' AS NUME_SECTIE2, 

     SUBSTR(((CASE WHEN (ltrim(TO_NUMBER(B.codul),'0')) IS  NULL   THEN '0'  WHEN (ltrim(TO_NUMBER(B.codul),'0')) = 1   THEN '10'  ELSE (ltrim(TO_NUMBER(B.codul),'0')) END)||'~'||ROWNUM/1.145), 1, INSTR(((CASE WHEN (ltrim(TO_NUMBER(B.codul),'0')) IS  NULL   THEN '0'  WHEN (ltrim(TO_NUMBER(B.codul),'0')) = 1   THEN '10'  ELSE (ltrim(TO_NUMBER(B.codul),'0')) END)||'~'||ROWNUM/1.145), '~') - 1) AS NR_ROW,
    
    ROWNUM  AS ORDINE,
   '000000000000000000000000000000000000' AS DECIMAL_POS,
    TRIM(B.DENUMIRE)    NUME_ROW,
    B.COL1,
    B.COL2,
    B.COL3,
    B.COL4,
    B.COL5,
    B.COL6,
    B.COL7,
    B.COL8,
    B.COL9,
    B.COL10,
    B.COL11,
    B.COL12,
    B.COL13,
    B.COL14,
    B.COL15,
    B.COL16,
    B.COL17,
    B.COL18,
    B.COL19,
    B.COL20,
    B.COL21,
    B.COL22,
    B.COL23,
    B.COL24,
    B.COL25,
    B.COL26,
    B.COL27,
    B.COL28,
    B.COL29,
    B.COL30,
    B.COL31,
    B.COL32,
    B.COL33,
    B.COL34,
    B.COL35,
    B.COL36
   

FROM 


(


SELECT 

   CC.CODUL,
   CC.DENUMIRE,
   CC.FULL_CODE,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL1,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL2,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL3,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL4,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL5,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0000000'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL6,
   -------------------------------------------------------------------------------------------------
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL7,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL8,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL9,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL10,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL11,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'0100000'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL12,
  --------------------------------------------------------------------------------------------------
  
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL13,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL14,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL15,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL16,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL17,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'1111111'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL18,
   --------------------------------------------------------------------------------------------------
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL19,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL20,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL21,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL22,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL23,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'2222222'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL24,
--------------------------------------------------------------------------------------------------------   
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL25,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL26,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL27,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL28,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL29,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'3333333'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL30,
   ------------------------------------------------------------------------------------------------
   
   
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL7) ELSE NULL END) COL31,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL8) ELSE NULL END) COL32,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL9) ELSE NULL END) COL33,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL10) ELSE NULL END) COL34,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL11) ELSE NULL END) COL35,
   SUM (CASE WHEN D.CUATM_FULL LIKE '%'||'9600000'||';%' THEN CIS2.NVAL(D.COL12) ELSE NULL END) COL36
   
   
   
   

   


FROM 
  CIS2.VW_DATA_ALL D
  
  INNER JOIN (

 
SELECT 
    D.CUIIO,
    D.CUIIO_VERS,
    D.RIND  RIND,
(CASE 
  WHEN TO_CHAR(SUBSTR(D.RIND, 2)) LIKE '0%' THEN REPLACE(LTRIM(TO_CHAR(SUBSTR(D.RIND, 2)), '0'), '.', '')
  ELSE REPLACE(TO_CHAR(SUBSTR(D.RIND, 2)), '.', '')
END) AS RIND_MOD,
    D.ID_MD,
    D.RIND_VERS,
    MR.ORDINE
 FROM 
  CIS2.VW_DATA_ALL D  
  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD 
  
WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049) AND     
( D.RIND NOT IN  ( SELECT  CODUL FROM CIS2.CL_TARI_CS ) AND  D.RIND NOT IN ('010','020','030','035','040','050','060','070'))   
 
  
   ) DD ON  (DD.ID_MD = D.ID_MD AND D.CUIIO = DD.CUIIO AND D.RIND = DD.RIND AND D.RIND_VERS = DD.RIND_VERS  AND D.CUIIO_VERS = DD.CUIIO_VERS)   
   
   
 INNER JOIN  (SELECT  
        
        RINDOUT CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13915) C  ON  (ltrim(TO_NUMBER(C.codul),'0') =  DD.RIND_MOD) 
     
    INNER  JOIN   (SELECT  
        
        TRIM(RINDOUT) CODUL,
        DENUMIRE DENUMIRE,
        
        ORDINE,
        
         RIND FULL_CODE

FROM CIS2.MD_RIND_OUT

WHERE
 ID_MDTABLE = 13915)   CC ON  C.FULL_CODE LIKE '%'||CC.CODUL||';%'
    
    

    
   
 WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
 -- D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (49)                 AND 
  D.CAPITOL IN (1049)
 
 
  
  GROUP  BY
  CC.CODUL,
  CC.DENUMIRE,
  CC.FULL_CODE
  
  ORDER BY 
  CC.FULL_CODE
  
   ) B ) B 
   
    
   LEFT JOIN (

SELECT 
C.ITEM_CODE,
REPLACE(C.ITEM_CODE, '.', '') AS COD_SPEC,
NAME
FROM CIS2.VW_CLS_CLASS_ITEM C

WHERE 
C.CLASS_CODE = 'SPEC_2EDU') L ON L.COD_SPEC = B.NR_ROW

