SELECT DISTINCT
'Rind.'||A.RIND||':   '||

MAX(CASE WHEN DD.CAPITOL IN (338)  AND DD.PERIOADA= :PERIOADA   AND DD.RIND IN (A.RIND)  THEN NVAL(DD.COL1) ELSE 0 END) ||'<> '||
MAX(CASE WHEN D.CAPITOL IN (338)   AND D.PERIOADA = :PERIOADA-1 AND D.RIND  IN (A.RIND)  THEN NVAL(D.COL1) ELSE 0 END)
AS REZULTAT 
FROM
(SELECT
  DISTINCT
  RIND
FROM
(
SELECT DISTINCT 
  D.RIND 
FROM 
  CIS2.VW_DATA_ALL D
WHERE   
  (D.PERIOADA IN(:PERIOADA-1))AND 
  (D.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS      = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (D.FORM            = :FORM           OR :FORM = -1)        AND 
  (D.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (D.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (D.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND D.FORM = 13 
  AND D.CAPITOL = 338
    --VERIFICARE  LIPSA CUIIO IN CIS PERIOADA -1  --
   AND
  (
 SELECT
  DISTINCT
  D.CUIIO
FROM
  CIS2.VW_DATA_ALL D
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  D.FORM  IN(13) AND     
  D.CAPITOL IN(338)) IS NOT NULL
UNION
SELECT DISTINCT 
  DD.RIND
  
 FROM 
     USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD 
WHERE
  (DD.PERIOADA IN(:PERIOADA))AND 
  (DD.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS      = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (DD.FORM            = :FORM           OR :FORM = -1)        AND 
  (DD.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (DD.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (DD.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND DD.FORM = 13 
  AND DD.CAPITOL = 338              
  AND  DD.ID_SCHEMA IN (2) 
)) A
INNER  JOIN CIS2.VW_DATA_ALL D ON (A.RIND=SUBSTR(D.RIND,1,3) AND (D.PERIOADA IN(:PERIOADA-1))AND 
  (D.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS      = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (D.FORM            = :FORM           OR :FORM = -1)        AND 
  (D.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (D.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (D.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND D.FORM = 13 
  AND D.CAPITOL = 338)
INNER  JOIN USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE DD ON (A.RIND=SUBSTR(DD.RIND,1,3) AND
  (DD.PERIOADA IN(:PERIOADA))AND 
  (DD.CUIIO           = :CUIIO          OR :CUIIO= -1)        AND 
  (:CUIIO_VERS      = :CUIIO_VERS     OR :CUIIO_VERS = -1)  AND 
  (DD.FORM            = :FORM           OR :FORM = -1)        AND 
  (DD.FORM_VERS       = :FORM_VERS      OR :FORM_VERS = -1)   AND 
  (DD.CAPITOL         = :CAPITOL        OR :CAPITOL = -1  )   AND 
  (DD.CAPITOL_VERS    = :CAPITOL_VERS   OR :CAPITOL_VERS = -1) 
  AND DD.FORM = 13 
  AND DD.CAPITOL = 338              
  AND  DD.ID_SCHEMA IN (2) )
GROUP BY
  A.RIND,
  DD.NUM
  
HAVING
 
MAX(CASE WHEN DD.CAPITOL IN (338)  AND DD.PERIOADA= :PERIOADA   AND DD.RIND IN (A.RIND)  THEN NVAL(DD.COL1) ELSE 0 END) <> 
MAX(CASE WHEN D.CAPITOL IN (338)   AND D.PERIOADA = :PERIOADA-1 AND D.RIND  IN (A.RIND)  THEN NVAL(D.COL1) ELSE 0 END)
  AND DD.NUM IN (2,3,4)
   AND
  (
  
 SELECT
  DISTINCT
  D.CUIIO
FROM
   CIS2.VW_DATA_ALL D
            
WHERE
  (D.PERIOADA IN (:PERIOADA-1)) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  D.FORM  IN(13) AND     
  D.CAPITOL IN(337)
  
  
  
  ) IS NOT NULL