SELECT
  CASE WHEN CUIIO_RSF IS NULL THEN CUIIO ELSE CUIIO_RSF END AS CUIIO,
  MAX(DENUMIRE) AS DENUMIRE,
  MAX(IDNO) AS IDNO,
  SUM(COL1) AS COL1
FROM
(
SELECT
  D.CUIIO,
  R1.DENUMIRE,
  R1.IDNO,
  D.COL1,
  (
    SELECT
      DISTINCT
      R.CUIIO
    FROM
      RENIM R
      INNER JOIN FORM_CUIIO F ON (R.CUIIO=F.CUIIO AND R.CUIIO_VERS=F.CUIIO_VERS)
      INNER JOIN 
      (
          SELECT
          R.CUIIO,
          MAX(R.CUIIO_VERS) AS CUIIO_VERS
        FROM
          RENIM R
          INNER JOIN FORM_CUIIO F ON (R.CUIIO=F.CUIIO AND R.CUIIO_VERS=F.CUIIO_VERS)
        WHERE
          F.FORM IN (57) AND
          R.CUIIO_VERS <= 2012
        GROUP BY
          R.CUIIO
      ) D1 ON (R.CUIIO=D1.CUIIO AND R.CUIIO_VERS=D1.CUIIO_VERS)
    WHERE
      F.FORM IN (57) AND
      F.STATUT <> '3'
      AND R.CUIIO IN TO_NUMBER(SUBSTR(CASE WHEN LENGTH(D.CUIIO) < 8 THEN TRIM(TO_CHAR(D.CUIIO,'00000000')) ELSE CASE WHEN LENGTH(D.CUIIO)>10 AND LENGTH(D.CUIIO)<13 THEN TRIM(TO_CHAR(SUBSTR(D.CUIIO,0,LENGTH(D.CUIIO)-4),'00000000')) ELSE TRIM(TO_CHAR(D.CUIIO)) END  END,0,8))
  ) AS CUIIO_RSF
FROM
  VW_DATA_ALL D
  INNER JOIN RENIM R1 ON (D.CUIIO=R1.CUIIO AND D.CUIIO_VERS=R1.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.RIND IN ('1440')
--  AND D.CUIIO IN (38670189602,3867018)
)
GROUP BY
  CASE WHEN CUIIO_RSF IS NULL THEN CUIIO ELSE CUIIO_RSF END