SELECT
--D.CUIIO,
  TR.ORDINE||'. '||
  CASE 
    WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) > TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci Rîndul.'||MAX(TR.RIND2)||' sa anuleze bifa'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) > TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci unul din Rîndurile.'||MAX(TR.RIND2)||' trebuie sa fie bifate'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) >= MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci Rîndul.'||MAX(TR.RIND2)||' se anuleaza bifa'
  WHEN
      MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IN ('CAEM2') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||SUBSTR(D.CAEM2,0,1)||'%') THEN 1 ELSE 0 END) = MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' A?i introdus Rîndul.'||MAX(TR.RIND1)||' care se completeaza doar de catre entita?ile cu genurile principale de activitate "Industrie" sau "Construc?ii"'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) <> MAX(TR.RESULT2))
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' A?i introdus Rîndul.'||MAX(TR.RIND1)||' dar nu a?i bifat rîndul ' ||MAX(TR.RIND2)
  WHEN
      MAX(TR.CONDITIE1) IN ('CAEM2') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||SUBSTR(D.CAEM2,0,1)||'%') THEN 1 ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Nu a?i introdus Rîndul.'||MAX(TR.RIND2)||' care se completeaza doar de catre entita?ile cu genurile principale de activitate "Industrie" sau "Construc?ii"'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<=') AND MAX(TR.BOTH_COL) IN ('1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) <= MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci Rîndul.'||MAX(TR.RIND2)||' trebuie sa fie bifate'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1) ELSE 0 END) > MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND2)||' a?i bifat mai multe variante de raspuns'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
      SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) < MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci unul din Rîndurile.'||MAX(TR.RIND2)||' trebuie sa fie bifate'
  WHEN
      MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('1') AND
      (SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1) ELSE 0 END) < MAX(TR.RESULT2)) 
    THEN
      MAX(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) THEN D.CAPITOL_DEN END)||' Rîndul.'||MAX(TR.RIND1)||' a?i selectat '||MAX(DECODE(NR_COLUMN1,'1','Da','2','Nu'))||' atunci unul din Rîndurile.'||MAX(TR.RIND2)||' trebuie sa fie bifate'  
  END
  AS REZULTAT
--AS REZULTAT,
  --SUM(LENGTH(D.RIND)) AS AAAA, SUM(TR.RIND_LENGTH) AS VVVVVV,
  --SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) AS JJJJJJ,
  --SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2,'32',D.COL32)) ELSE 0 END) AS KKKKKK
FROM 
 (
 SELECT
  D.CUIIO,
  D.CAPITOL,
  D.CAPITOL_DEN,
  D.RIND,
  D.CAEM2,
  D.COL1,D.COL2, D.COL32
FROM
 CIS2.VW_DATA_ALL_TEMP D 
 
WHERE
  (D.PERIOADA IN (:PERIOADA) ) AND
  (D.CUIIO=:CUIIO               OR :CUIIO = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS  OR :FORM_VERS = -1) AND
  (:CAPITOL=:CAPITOL           OR  :CAPITOL<>:CAPITOL) AND
  (:CAPITOL_VERS = :CAPITOL_VERS OR  :CAPITOL_VERS <> :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  D.FORM IN (74) AND
  D.CAPITOL IN (1197,1199) AND
  (SELECT
      DD.RIND
    FROM
      VW_DATA_ALL DD
    WHERE
      (DD.PERIOADA IN (:PERIOADA) ) AND
      DD.FORM IN (74) AND
      DD.CAPITOL IN (1199) AND
      DD.CUIIO=D.CUIIO AND
      DD.RIND NOT IN ('CD','PHONE')) IN (1)
 )D
CROSS JOIN
 (
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '1.1,1.2,1.3' AS RIND2, 1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '1.1,1.2,1.3' AS RIND2, 1 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '2.1,2.2,2.3' AS RIND2, 2 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '3.1,3.2,3.3' AS RIND2, 3 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '4.1,4.2,4.3' AS RIND2, 4 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '5.1,5.2,5.3' AS RIND2, 5 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '6.1,6.2,6.3' AS RIND2, 6 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '7.1,7.2,7.3' AS RIND2, 7 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '8.1,8.2,8.3' AS RIND2, 8 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '9' AS RIND1, '9.01,9.02,9.03,9.04,9.05,9.06,9.07,9.08' AS RIND2, 9.1 AS ORDINE, '2' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '9' AS RIND1, '9.01,9.02,9.03,9.04,9.05,9.06,9.07,9.08' AS RIND2, 9.2 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '9.08' AS RIND1, '9.08' AS RIND2, 9.3 AS ORDINE, '1' AS NR_COLUMN1, '32' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '9' AS RIND2, 9 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '10' AS RIND2, 10 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '11.1,11.2,11.3,11.4' AS RIND2, 11 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '11.4' AS RIND1, '12.1,12.4' AS RIND2, 11.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '12.1,12.2,12.3,12.4' AS RIND2, 12 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '13.1,13.2,13.3,13.4,13.5' AS RIND2, 13 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '11.4' AS RIND1, '13.1,13.2,13.3,13.4,13.5' AS RIND2, 13.11 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '12.4' AS RIND1, '13.1,13.2,13.3,13.4,13.5' AS RIND2, 13.12 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '14.1,14.2,14.3,14.4' AS RIND2, 14 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '15.1,15.2,15.3,15.4' AS RIND2, 15 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '16.1,16.2,16.3' AS RIND1, 'B,C,D,E,F' AS RIND2, 16 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '>' AS CONDITIE1, 'CAEM2' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '17.1,17.2,17.3' AS RIND1, 'B,C,D,E,F' AS RIND2, 17 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '>' AS CONDITIE1, 'CAEM2' AS CONDITIE2, '0' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, 'B,C,D,E,F' AS RIND1, '16.1,16.2,16.3' AS RIND2, 16.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, 'CAEM2' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, 'B,C,D,E,F' AS RIND1, '17.1,17.2,17.3' AS RIND2, 17.1 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, 'CAEM2' AS CONDITIE1, '=' AS CONDITIE2, '1' AS RESULT1, '0' AS RESULT2, 'ROWS1' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
SELECT 1199 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '18' AS RIND2, 18 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL

--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '8' AS RIND2, 18 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '2.1,2.2,2.3' AS RIND2, 19 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '3.1,3.2,3.3' AS RIND2, 20 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '4.1,4.2,4.3' AS RIND2, 21 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '5.1,5.2,5.3' AS RIND2, 22 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '6.1,6.2,6.3' AS RIND2, 23 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '7.1,7.2,7.3' AS RIND2, 24 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 2 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '8' AS RIND2, 25 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '9' AS RIND2, 26 AS ORDINE, '1' AS NR_COLUMN1, '1,2' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '10.1,10.2,10.3' AS RIND2, 27 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '11.1,11.2,11.3' AS RIND2, 28 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '13.1,13.2,13.3,13.4' AS RIND2, 29 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '1.1,1.2,1.3' AS RIND2, 32 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '2.1,2.2,2.3' AS RIND2, 33 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '3.1,3.2,3.3' AS RIND2, 34 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '4.1,4.2,4.3' AS RIND2, 35 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '5.1,5.2,5.3' AS RIND2, 36 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '6.1,6.2,6.3' AS RIND2, 37 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '7.1,7.2,7.3' AS RIND2, 38 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 3 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '10.1,10.2,10.3' AS RIND2, 39 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '11.1,11.2,11.3' AS RIND2, 40 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '13.1,13.2,13.3,13.4' AS RIND2, 41 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '15.1,15.2,15.3' AS RIND2, 42 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, 'ROWS2' AS BOTH_COL, 4 AS RIND_LENGTH FROM DUAL UNION
--SELECT 1197 AS CAPITOL1, 1197 AS CAPITOL2, '1' AS RIND1, '1' AS RIND2, 43 AS ORDINE, '1' AS NR_COLUMN1, '1' AS NR_COLUMN2, '=' AS CONDITIE1, '<>' AS CONDITIE2, '1' AS RESULT1, '1' AS RESULT2, '1' AS BOTH_COL, 1 AS RIND_LENGTH FROM DUAL

) TR
GROUP BY
--  D.CUIIO,
  TR.ORDINE
HAVING
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) > TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) > TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2)) ELSE 0 END) <> MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) >= MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('>') AND MAX(TR.CONDITIE2) IN ('CAEM2') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) > MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||SUBSTR(D.CAEM2,0,1)||'%') THEN 1 ELSE 0 END) = MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<>') AND MAX(TR.BOTH_COL) IN ('1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 IN (D.RIND) THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) <> MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('CAEM2') AND MAX(TR.CONDITIE2) IN ('=') AND MAX(TR.BOTH_COL) IN ('ROWS1') AND
  --SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND D.RIND IN ('1') THEN D.COL1 ELSE 0 END) = 1 AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||SUBSTR(D.CAEM2,0,1)||'%') THEN 1 ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<=') AND MAX(TR.BOTH_COL) IN ('1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') /*AND LENGTH(D.RIND) = TR.RIND_LENGTH*/ THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1)+NVAL(D.COL2) ELSE 0 END) <= MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('>') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1) ELSE 0 END) > MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('ROWS2') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') /*AND LENGTH(D.RIND) = TR.RIND_LENGTH*/ THEN NVAL(DECODE(NR_COLUMN2,'1',D.COL1,'2',D.COL2,'32',LENGTH(D.COL32))) ELSE 0 END) < MAX(TR.RESULT2)) OR
   -----------------------------------------------------------------------------
  (MAX(TR.CONDITIE1) IN ('=') AND MAX(TR.CONDITIE2) IN ('<') AND MAX(TR.BOTH_COL) IN ('1') AND
  SUM(DISTINCT CASE WHEN D.CAPITOL IN (TR.CAPITOL1) AND TR.RIND1 LIKE ('%'||D.RIND||'%') THEN NVAL(DECODE(NR_COLUMN1,'1',D.COL1,'2',D.COL2)) ELSE 0 END) = MAX(TR.RESULT1) AND
  SUM(CASE WHEN D.CAPITOL IN (TR.CAPITOL2) AND TR.RIND2 LIKE ('%'||D.RIND||'%') AND LENGTH(D.RIND) = TR.RIND_LENGTH THEN NVAL(D.COL1) + NVAL(D.COL2) ELSE 0 END) < MAX(TR.RESULT2))