SELECT 
      D.CUIIO,
      MAX(CASE WHEN  D.CAPITOL = 1127   THEN  D.COL31 ELSE NULL END ) AS COL_B,
      MAX(CASE WHEN  D.CAPITOL = 1127   THEN  D.COL32 ELSE NULL END ) AS COL_C,
      SUM(CASE WHEN  D.CAPITOL = 1124   AND   D.RIND IN ('150')  THEN NVAL(D.COL1) ELSE 0 END ) AS RIND_150,
      SUM(CASE WHEN  D.CAPITOL = 1180   AND   D.RIND IN ('800')  THEN NVAL(D.COL1) ELSE 0 END ) AS RIND_800
       FROM  CIS2.VW_DATA_ALL D
          WHERE
           D.FORM = 64
           AND D.PERIOADA = 2011


           GROUP BY
                D.CUIIO
           HAVING
           SUM(CASE WHEN  D.CAPITOL = 1180   THEN NVAL(D.COL1) ELSE 0 END ) > 0
             ORDER BY

               SUM(CASE WHEN  D.CAPITOL = 1124   THEN NVAL(D.COL1) ELSE 0 END )
               
               --4711