SELECT   

  DECODE(CC.NR_COLUMN,  '1', 'COL.1 ','2', 'COL.2 ','3', 'COL.3 ','4', 'COL.4', '5', 'COL.5','6', 'COL.6','7', 'COL.7','8', 'COL.8','9', 'COL.9','10', 'COL.10','11', 'COL.11','12', 'COL.12','13', 'COL.13')||':'||'['||
  SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END) ||' <> '||
  SUM(CASE WHEN CIS2.D.RIND IN ('041') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('042') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END )
     ||']'   
  
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D,             
       (                             
       SELECT '1' AS NR_COLUMN FROM DUAL UNION
       SELECT '2' AS NR_COLUMN FROM DUAL UNION
       SELECT '3' AS NR_COLUMN FROM DUAL UNION
       SELECT '4' AS NR_COLUMN FROM DUAL UNION
       SELECT '5' AS NR_COLUMN FROM DUAL UNION
       SELECT '6' AS NR_COLUMN FROM DUAL UNION
       SELECT '7' AS NR_COLUMN FROM DUAL UNION
       SELECT '8' AS NR_COLUMN FROM DUAL UNION
       SELECT '9' AS NR_COLUMN FROM DUAL UNION
       SELECT '10' AS NR_COLUMN FROM DUAL UNION  
       SELECT '11' AS NR_COLUMN FROM DUAL UNION
       SELECT '12' AS NR_COLUMN FROM DUAL UNION
       SELECT '13' AS NR_COLUMN FROM DUAL 
       ) CC     
 
WHERE
  (CIS2.D.PERIOADA =:PERIOADA        ) AND
  (CIS2.D.CUIIO=:CUIIO               ) AND
  (CIS2.D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (CIS2.D.FORM = :FORM               ) AND
  (CIS2.D.FORM_VERS=:FORM_VERS       ) AND
  (CIS2.D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (CIS2.D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (CIS2.D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  CIS2.D.FORM IN (17)  AND
  CIS2.D.CAPITOL IN (1004) 
  
 
 
GROUP BY CC.NR_COLUMN

HAVING

SUM(CASE WHEN CIS2.D.RIND IN ('040') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END)  <> 
  SUM(CASE WHEN CIS2.D.RIND IN ('041') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END +
      CASE WHEN CIS2.D.RIND IN ('042') THEN DECODE(CC.NR_COLUMN, '1', CIS2.NVAL(D.COL1), '2', CIS2.NVAL(D.COL2), '3', CIS2.NVAL(D.COL3), '4', CIS2.NVAL(D.COL4), '5', CIS2.NVAL(D.COL5), '6', CIS2.NVAL(D.COL6), '7', CIS2.NVAL(D.COL7), '8', CIS2.NVAL(D.COL8), '9', CIS2.NVAL(D.COL9), '10', CIS2.NVAL(D.COL10), '11', CIS2.NVAL(D.COL11), '12', CIS2.NVAL(D.COL12), '13', CIS2.NVAL(D.COL13)) ELSE 0 END 

      ) 
