SELECT   DISTINCT 
  '['|| 
  SUM(CASE WHEN D.CAPITOL IN (1004) AND D.RIND IN ('020') THEN CIS2.NVAL(D.COL1) ELSE 0 END) ||']'||' <> '||'['|| 
  SUM(CASE WHEN D.CAPITOL IN (1005) AND D.RIND IN ('010') THEN CIS2.NVAL(D.COL1) ELSE 0 END) ||']'
  ||' <> '||'['||
  SUM(CASE WHEN D.CAPITOL IN (1006) AND D.RIND IN ('010') THEN CIS2.NVAL(D.COL1) ELSE 0 END) 
  ||']'
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D
 
  
WHERE
  (D.PERIOADA =:PERIOADA        ) AND
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               OR :FORM = -1) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (17)  
  
  AND
  D.CAPITOL IN (1004,1005,1006)
 

HAVING
  
  SUM(CASE WHEN D.CAPITOL IN (1004) AND D.RIND IN ('020') THEN CIS2.NVAL(D.COL1) ELSE 0 END)  <>
  SUM(CASE WHEN D.CAPITOL IN (1005) AND D.RIND IN ('010') THEN CIS2.NVAL(D.COL1) ELSE 0 END)  OR
  
  SUM(CASE WHEN D.CAPITOL IN (1005) AND D.RIND IN ('010') THEN CIS2.NVAL(D.COL1) ELSE 0 END)  <>
  SUM(CASE WHEN D.CAPITOL IN (1006) AND D.RIND IN ('010') THEN CIS2.NVAL(D.COL1) ELSE 0 END) 
