SELECT
     :pID_MDTABLE -1,
     :pCOD_CUATM AS COD_CUATM,
     '01' AS NR_ROW,
      1  AS ORDINE,
     'Total' AS NUME_ROW,
     CIS2.NVAL(COUNT(DISTINCT CASE WHEN  D.CAPITOL IN (1004) AND RIND_VERS IN (2011)  AND  NT.CODUL <> 6 THEN D.CUIIO ELSE NULL END))  AS  COL1, 
     CIS2.NVAL(COUNT(DISTINCT CASE WHEN  D.CAPITOL IN (1004) AND RIND_VERS IN (2011) AND  NS.CODUL = '1' AND  NT.CODUL <> '6' THEN D.CUIIO ELSE NULL END))  AS  COL2,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1001) AND D.RIND IN ('010')  THEN D.COL2 ELSE NULL END))   AS   COL3,   
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1001) AND D.RIND IN ('010')  THEN D.COL1 ELSE NULL END)) AS  COL4,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL1 ELSE NULL END)) AS  COL5,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL2 ELSE NULL END)) AS  COL6,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL3 ELSE NULL END)) AS  COL7, 
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL4 ELSE NULL END)) AS  COL8,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL5 ELSE NULL END)) AS  COL9,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL6 ELSE NULL END)) AS  COL10,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL7 ELSE NULL END)) AS  COL11,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL8 ELSE NULL END)) AS  COL12,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('010')  THEN D.COL9 ELSE NULL END)) AS  COL13,
     CIS2.NVAL(SUM(CASE WHEN D.CAPITOL IN (1002) AND D.RIND IN ('020')  THEN D.COL1 ELSE NULL END)) AS  COL14
       
       FROM    
             CIS2.VW_DATA_ALL D    
                      
               INNER JOIN CIS2.RENIM RN ON (RN.CUIIO=D.CUIIO AND RN.CUIIO_VERS=D.CUIIO_VERS)  
               -------------------------------------------------------------------------------------                           
               INNER JOIN CIS2.CL_N85_NTIIP NT ON (RN.N85_NTIIP=NT.CODUL) --(NIÎP).(Col.6) <> 6 --- NT.CODUL <> 6 
               --------------------------------------------------------------------------------------------------
               INNER JOIN CIS2.CL_N85_NSIIP NS ON (RN.N85_NSIIP=NS.CODUL) -- care (NIÎP).(Col.10) = 1 
                
                WHERE  
               (D.PERIOADA =:pPERIOADA) AND
               (D.FORM =:pFORM) AND
               (D.FORM_VERS =:pFORM_VERS) AND
               (:pID_MDTABLE=:pID_MDTABLE) AND
               (D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%') AND 
               D.FORM = 17 AND
               D.CAPITOL IN (1001,1002,1004)