--SELECT MIN(ROWID)
--  FROM USER_BANCU.REG_UNIT_GC
--  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS;
  

--DELETE
SELECT *
  
  FROM USER_BANCU.REG_UNIT_GC_C2
WHERE ROWID NOT IN
(
  SELECT MIN(ROWID)
  FROM USER_BANCU.REG_UNIT_GC_C2
  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS
)