--SELECT MIN(ROWID)
--  FROM USER_BANCU.REG_UNIT_GC
--  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS;
  

--DELETE
SELECT *
  
  FROM USER_BANCU.REG_UNIT_GC3_2024
WHERE ROWID NOT IN
(
  SELECT MIN(ROWID)
  FROM USER_BANCU.REG_UNIT_GC3_2024
  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS
)

---------------------------------------------------

