--SELECT MIN(ROWID)
--  FROM USER_BANCU.REG_UNIT_GC
--  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS;
  
  SELECT * 
  
  FROM USER_BANCU.REG_UNIT_GC
WHERE ROWID NOT IN
(
  SELECT MIN(ROWID)
  FROM USER_BANCU.REG_UNIT_GC
  GROUP BY UNIT_CODE, UNIT_CODE_VERS, NR_GOSP, NR_MAPS
)