SELECT 
D.CUIIO,
R.IDNO,
R.DENUMIRE,
D.CUATM,
D.RIND,
SUM(D.COL1) AS COL1 

FROM CIS2.VW_DATA_ALL D 
        INNER JOIN CIS2.RENIM R ON R.CUIIO = D.CUIIO AND R.CUIIO_VERS = D.CUIIO_VERS 

        

WHERE
  D.PERIOADA IN (:pPERIOADA) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (45)                
  AND D.RIND IN ('1440')
  
   --- AND D.CUIIO  LIKE '%'||41070998||'%' 
  
GROUP BY 
D.CUIIO,
R.IDNO,
R.DENUMIRE,
D.CUATM,
D.RIND

  
  ORDER BY
  
   D.CUIIO   
